### ISSUE TITLE
Add Rake task for production deployment configuration

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#1003]
Production serves with a different config. Create a rake task to do this and then migrate the AWS deploy scripts to invoke this task so our deployment configuration can be atomically version controlled with the source.

The core of this is probably just running:
  `bundle exec jekyll serve --config _config.yml,_config_production.yml`

but we should probably also clean the environment to be certain. In bash, I would have done env -i and then imported the specific environment vars I needed. Not sure how best to do this in rake.

**Comment by joduinn** [comment]
Found in triage.

@awong-dev @mechaxl I know you've both been doing a bunch of ansible work on deployments in other tickets. Anything left to do here?
