### ISSUE TITLE
two Rates pages currently on vets.gov

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1005]
We need to kill one of them. We also need to decide if it makes sense to link to Rates from both locations. Here they are:
/disability-benefits/rates/ 
(Rates is a tile on the disability landing page--very prominent location)

/disability-benefits/claims-process/ratings/ 
(much less prominent as we link to it from a piano key at the bottom of the Claims Process page)

**Comment by dannychapman** [comment]
@bethpotts It would be great if we could just the /disability-benefits/rates/ one in my opinion.

**Comment by bethpotts** [comment]
Do I add Ric and Susan to this conversation in github by adding them as Assignees?

**Comment by dannychapman** [comment]
cc @sjb912 @rcarthur

**Comment by bethpotts** [comment]
Thanks, Danny!

**Comment by bethpotts** [comment]
@dannychapman @rcarthur @sjb912 Should we remove the piano key on the Claims Process page that links to one of the Rates pages and kill that Rates page? The piano key says: "How does VA assign disability ratings?" If we do this, we would be left with the very prominent Rates tile off the Disability landing page. I think that's sufficient. Opinions?

**Comment by bethpotts** [comment]
@dannychapman @sjb912 @rcarthur We addressed this in our content working call. Susan, Ric, and I agreed that we would like to remove the Rates tile from the disability landing page and kill the page it currently links to (/disability-benefits/rates/). We will keep the piano key link currently on the Claims Process page that goes to the other Rates page (/disability-benefits/claims-process/ratings/). Let me know if you need clarification on any of this, Danny.

**Comment by dannychapman** [comment]
@bethpotts Got it! I have a pull request in for review.

**Comment by dannychapman** [comment]
Fixed! Closing.
