### ISSUE TITLE
Facility Locator Pages not Rendering

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/vets-website#10070]
Chris Johnson reported the following facilitator locator bug, but unclear of root cause. 

**Steps to Reproduce**:
- Go to Facility Locator:  - Go to Facility Locator: https://www.va.gov/find-locations/
- Search for “Cleveland” and “VA Health”: https://www.va.gov/find-locations/?zoomLevel=9&page=1&address=cleveland&facilityType=health&serviceType&location=41.5052%2C-81.6934&context=Cleveland%2C%20Ohio%2C%20United%20States
- Scroll down to and click on “Louis Stokes Cleveland Dept of VAMC”
- You’ll get an incomplete rendered page at: https://www.va.gov/find-locations/facility/vha_541

I learned from a VHA stakeholder today that this is also true for all of the following as well (though not limited to just these):
-https://www.va.gov/find-locations/facility/vha_541GG
-https://www.va.gov/find-locations/facility/vha_541BY
-https://www.va.gov/find-locations/facility/vha_541GH
541GF
541GB
541
541GD
541GE
541GL
541GC
541GI
541BZ
538GA
538
538GD
538GC
538GB
538GF
539
539GB
539GF
539GE
552GA
437

**Comment by ncksllvn** [comment]
I'm looking at the response data in Prod for `vha_541GH`. I'm seeing empty values for the `access` property as well as `feedback`. The former is used for the `AppointmentInfo` component and the latter for `AccessToCare`.

I can easily add error-handling for that data being empty, but it seems like these components were built expecting that data to never be empty, so I'm wondering if this could be an API issue for these values. Still looking into it...

**Comment by ncksllvn** [comment]
Issue moved to [department-of-veterans-affairs/vets.gov-team #18569](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18569) via [**ZenHub**](https://www.zenhub.com/)
