### ISSUE TITLE
UserVoice Idea: Add C&P Exam explanation to Claim Process

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1014]
Add information regarding the C&P Examination process to the Claims Process page? This could explain what these are and set realistic expectations for the setup and process of these exams.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11351523-add-c-p-exam-explanation-to-claim-process

**Comment by ss0ss** [comment]
@sjb912 @rcarthur Please note.

**Comment by koconnor719** [comment]
posted response:

Thank you for your feedback. We agree with you that the C&P exam process is very important for Veterans! We'll be adding that content in the coming months as we build out vets.gov, using feedback from Veterans. In the meantime, we invite you to be part of our Veteran research to provide additional feedback on vets.gov.  If you would like to participate, please contact our team at vavetsgov-feedback@va.gov. We conduct the session over the phone/computer and it only takes 30 minutes.

vets.gov team

**Comment by J-Quag** [comment]
Thanks Kelly, this one was actually mine. I submitted it during the workshop we had last week re: C&P Exams.

**Comment by koconnor719** [comment]
thanks Josh!  did we answer your question?

**Comment by J-Quag** [comment]
It did, thanks. Looking forward to seeing the content.
