### ISSUE TITLE
UserVoice Idea: Impossible conclusion s

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1015]
Something I am having a hard time to understand is how my PTSD cannot be service connected when it says Combat directly above it how can I possibly be? I have already broken my code of silence once I don't care to do that ever again.so can you please do c some reconsideration of that.in fear sleeping what the soldier went throughllike myself went t the things that I saw things that I did the things that I saw on how can you not considered a service-connected I know I don't understand that what' exactly you we were going through at that time at that period of time in our lives I was only 24 years oldand my life was very fearful in my head fear of my lifeI seriously don't know if this is going to make any difference whatsoever in my claim that how can I be ti can I have P postmatic stress disorder without combat without what did I get a lot of fights before I join the military that you know I wear what I don't understand how you came up with that conclusion that PTSD was not service connected hand combat not there what can I get out cannot be can you please explain that to me? if you can explain that to me then I might be a little more understanding on why you came to that conclusion howwill you be able to seriously answer that question

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11355594-impossible-conclusion-s

**Comment by koconnor719** [comment]
@MarinaMartin is this response ok: 

Here is some information that might be helpful if you need immediate assistance--the Veterans Chat will able to help you find the right person to ask your question--this feedback page is just for the vets.gov website:
- Call the Veterans Crisis Line 1-800-273-8255 and press 1 to talk to someone now.
- Get online support with the confidential Veterans Chat https://www.veteranscrisisline.net/ChatTermsOfService.aspx?account=Veterans%20Chat/ 
- Text 838255 to get help right away.
- Call 911.
- Go to the nearest emergency room.

I think you are asking about PTSD being service connected and benefits eligibility, so here are some additional sources of information for you:
- VA benefits 1-800-827-1000
-VA health benefits 1-800-222-8387 
- National Center for PTSD http://www.ptsd.va.gov 

vets.gov team

**Comment by MarinaMartin** [comment]
@koconnor719 I think that's a good response. We might also want to ask Debi's team for feedback.

**Comment by koconnor719** [comment]
verified response; closing item. will follow up w/ Debi's team for guidance on future comments like this.
