### ISSUE TITLE
Why do user voice issue responses not go to the submitters email?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1020]
Kelly and I made a test, and I did not receive the response she sent. This might explain why no one has ever  responded.

**Comment by koconnor719** [comment]
I am also doing a test on this

**Comment by emilyville** [comment]
I think I figured some thing out here. I clicked around until I got a response. If you look at this screenshot - adding a comment _did not_ send me an email. However, adding a message did. 

![screen shot 2016-01-10 at 2 33 50 pm](https://cloud.githubusercontent.com/assets/1307774/12224497/71745b78-b7a7-11e5-9d27-140d616ecf81.png)

It looks like since we've been doing it the other way (with comments) most are showing that we have not responded. I think maybe going through and sending those as messages even if it's super delayed would be good. We can tag team this since it's going to be kind of lame. 

Let me know what you think @koconnor719 or @MarinaMartin !

**Comment by emilyville** [comment]
ping! let's make a plan to send these responses out. If the screenshot is unclear I can explain IRL.

**Comment by koconnor719** [comment]
I will need help doing this? Not sure who has bandwidth to do



Sent with Good (www.good.com)


-----Original Message-----

**Comment by koconnor719** [comment]
i resent all of our vets.gov responses as "messages" and tested on 2 of my own test messages and did received a response.  closing this issue.

**Comment by MarinaMartin** [comment]
Thank you @koconnor719 ! I am so sorry we should have split that up. Next repetitive task is on me :)
