### ISSUE TITLE
UserVoice Idea: Veteran research and feedback

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1021]
Veterans can participate in vets.gov user research activities throughout 2016. They are conducted online and take only 30 minutes. Please contact the vets.gov team at vavetsgov-feedback@va.gov.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11374035-veteran-research-and-feedback

**Comment by koconnor719** [comment]
this was my posting; closing issue no response needed
