### ISSUE TITLE
Make a colophon

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1022]
I like this Colophon idea from gov.uk and think we should also do it. Perhaps it is part of Roadrunner?

https://gds.blog.gov.uk/colophon-alpha/

Assigning to @plusjeff but feel free to delegate to someone else.

cc @emilyville

**Comment by emilyville** [comment]
I like this, we have a couple similar things that could be modified or merged(?) to go for this idea more specifically:
 
https://www.vets.gov/playbook/design/code/
https://www.vets.gov/playbook/platform/

I realize you all might already be familiar with these, but adding anyway for issue robustness!

**Comment by dannychapman** [comment]
Love this idea!
