### ISSUE TITLE
UserVoice Idea: Multiple MOS's Selection for Skills Translator

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1027]
Would be nice to be able to use the MOS skills translator to add multiple MOS's to the resume.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11388633-multiple-mos-s-selection-for-skills-translator

**Comment by koconnor719** [comment]
Checking with Veteran user to see if this is possible if a Veteran is logged in and has a saved profile.

**Comment by MarinaMartin** [comment]
This is not possible because the skills translator only operates off one MOC. The Veteran can add however many MOCs they want directly within their resume.

**Comment by koconnor719** [comment]
posted and closed:

Thank you for your feedback. Our skills translator only operates off of one MOC, but you can add multiple MOCs directly within your resume. This should enable you to have multiple MOCs on your resume.

vets.gov team
