### ISSUE TITLE
User Voice -not sending responses

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1030]
User voice is not sending vets.gov admin posted responses to feedback back to original posters; i believe it is supposed to do this??? so people who submit feedback aren't getting our responses--unless they come back to the site. @emilyville

**Comment by MarinaMartin** [comment]
@emilyville was researching this, I am assigning it to her (Emily, assign back to me if you need to!)

**Comment by emilyville** [comment]
@koconnor719 this is a duplicate of #1020 and that issue has how we can fix it. Closing this issue - I will assign that one to you.
