### ISSUE TITLE
C-123 page doesn't match the other pages linked to off Agent Orange landing page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1040]
cc @sjb912 @rcarthur The text block at the top of the C-123 Aircraft page doesn't match all the other pages linked to off of the Agent Orange landing page. All except C-123 have the text block at the top in larger font and blue rather than black. Is there a way to get this page consistent with the others?

**Comment by dannychapman** [comment]
@bethpotts I have a pull request in to fix this.
