### ISSUE TITLE
UserVoice Idea: Add log in button at the top of the screen

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1042]
Identify to users that logging in is needed. Many users are linked to this website through ebenifits and will assume they are logged in. It was very frustrating to fill out all this information just to find out that it all disappears when you hit the log in button.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11450529-add-log-in-button-at-the-top-of-the-screen

**Comment by koconnor719** [comment]
Posted response:

Thank you for your feedback. Can you tell us which website you are logging into? Currently vets.gov does not have a login. 

We plan to have a vets.gov login in the future so Veterans can access the VA services and benefits they have earned quickly and easily. If you would like to provide us additional feedback about vets.gov and how we can make it better for Veterans, please contact us at vavetsgov-feedback@va.gov to participate in our user research activities.

vets.gov team

**Comment by koconnor719** [comment]
closed issue; no additional information. if user provides another comment a new user voice issue will be opened.
