### ISSUE TITLE
GIDS Generate Preview button not working when a new CSV type is added

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/vets-website#10450]
Generate Preview button was disabled even though a new CSV had been uploaded.

Issue was due the fact the GIDS database table Uploads was missing a row for Sec109SchoolClosure

Reproduce by
- Checking out SHA Hash below
```
git fetch origin
git checkout 7e8c75bc9d17754f236f3e5d267823f53f738088
```
- Go to localhost:4000
- Upload a CSV
- Notice "Generate Preview" button is still disabled

Fix by
- In pgadmin do
```
Insert into uploads values (2, 1, 'sec109_closed_school.csv', 'Sec109ClosedSchool', 'Seeding', true, '2019-07-17 18:36:12.378059', '2019-07-17 18:36:12.415584')
```
- Upload a CSV
- Notice "Generate Preview" button is now enabled

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/399

**Comment by sonntag-adam** [comment]
<img width="1676" alt="Screen Shot 2019-07-22 at 1 45 03 PM" src="https://user-images.githubusercontent.com/48804582/61652973-31592900-ac87-11e9-8874-0c43e0917abb.png">

**Comment by sonntag-adam** [comment]
"Not enough uploads" appears when hovering to let user know the issue.

**Comment by jholton** [comment]
Was this issue created in the wrong repository?  I don't think this has anything to do with `vets-website`.
There's a "Move Issue" button at the bottom of the right hand column if you need it.

**Comment by zurbergram** [comment]
Issue moved to [department-of-veterans-affairs/vets.gov-team #19344](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19344) via [**ZenHub**](https://www.zenhub.com/)
