### ISSUE TITLE
UserVoice Idea: Blog the progress of vets.gov

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1057]
Post regularly (at least once per week) about design choices, new apps transitioned, team working on vets.gov, "how we work" posts about tools & culture, website performance, etc.

1 post in 2.5 months isn't really a blog.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11489268-blog-the-progress-of-vets-gov

**Comment by koconnor719** [comment]
team has three(3) blogs in process. 

closed and posted response:
Thank you for your feedback. We agree with you and will be posting more blogs.  We are working on several right now and plan to post blogs more regularly on the progress of vets.gov--and other topics!  Thank you.

vets.gov team

**Comment by koconnor719** [comment]
@dannychapman @emilyville @rcarthur team, pls. send me your blogs so i can get approved by martin and posted:)

**Comment by koconnor719** [comment]
@EmilyTav emily will facilitate review and publish of blogs from team.

**Comment by dannychapman** [comment]
@koconnor719 Sounds good. PR'd mine and Richard's posts.

**Comment by koconnor719** [comment]
closed and  posted response: 

Thank you for your feedback.  We've added a new blog "Designing Vets.gov"  https://www.vets.gov/2016/03/02/designing-for-veterans.html, and have several more in the queue! 

vets.gov team
