### ISSUE TITLE
UserVoice Idea: i goit the same email saying good fit   i contacted the company found he does not wok for how are these scamers abl to get our info and who

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1059]
another scam

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11490255-i-goit-the-same-email-saying-good-fit-i-contacte

**Comment by koconnor719** [comment]
posted and closed:

Thank you for your feedback. It is unfortunate that anyone would try to take advantage of a Veteran. We have a blog post to help warn Veterans about protecting themselves from scams and phishing attacks "Veterans Employment Center Website: False Claim of Breach" at http://www.blogs.va.gov/VAntage/23299/veterans-employment-center-website-false-claim-of-breach/ . 

vets.gov team
