### ISSUE TITLE
UserVoice Idea: Allow entry of Job Title and MOS

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1075]
Allow the entry of the job title as well as MOS to bring up the job descriptions for the military jobs.  This will assist recruiters/employment coordinators to find the job description when unable to get MOS  

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11517027-allow-entry-of-job-title-and-mos

**Comment by koconnor719** [comment]
@maryannbrody  can you add this to your user research for VEC?  @ayaleloehr fyi 

closed and posted response:
Thank you for your feedback.  We'll add this to our user research and usability testing for the Veterans Employment Center to see what Veterans think! Our team uses a Human Centered Design approach as we design and build vets.gov. We ask Veterans what they want and need on an ongoing basis, and we’ve designed in response to that. We’ve tested and made adjustments based on their feedback, and will continue to do so as we add new features and information to the site. 

vets.gov team

**Comment by maryannbrody** [comment]
Closing this issue -- I have it tracked for user research.
