### ISSUE TITLE
UserVoice Idea: MOS translator

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1078]
E-benifits had a great MOS translator, now I get redirected to vets.gov and the translator does not even work.  Please go back to using the ebenifits translator if this site is not going to have it.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11532324-mos-translator

**Comment by ayaleloehr** [comment]
The skills translator is working for me currently. Can we maybe find out what MOS he or she is using?

**Comment by koconnor719** [comment]
posted response:

Thank you for your feedback. Our team has tested the Veterans Employment Center skills translator and it works.  Can you give us some additional information and we can re-test--what MOS codes are you using?  

vets.gov team

**Comment by koconnor719** [comment]
closed; no response from users in more than 2 weeks; if new information comes in a new issue will be opened.
