### ISSUE TITLE
VEC Job Seekers page has an extra word (typo)

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1081]
https://www.vets.gov/veterans-employment-center/for_job_seekers
The second gray box, called "Free Coursera Certificates" needs the word "chose" removed. Please delete "chose" but keep "choose."

**Comment by ayaleloehr** [comment]
Closed via commit 2f2a1cc8d018593ac7162608fa076e0a883886a9 in VEC repo.
