### ISSUE TITLE
Feedback Forum error: "This page can't be displayed error" on VA computer using Explorer 11

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1082]
@MarinaMartin @emilyville 

this issue was referred by Sec. Bob fyi: a VA employee using VA machine and Explorer v9 browser is not able to access the feedback forum page (https://veterans.uservoice.com).  she's getting error message "this page cannot be displayed."

**Comment by koconnor719** [comment]
i confirmed w/ paulette (she works at a VA research facility in Boston and is using a VA computer) that she does in fact have Explorer 11 (initially she thought it was v9); while she can access the vets.gov page, she can not access the feedback forum (user voice) and is getting that error message.

**Comment by koconnor719** [comment]
christine going to take lead on this

**Comment by koconnor719** [comment]
user has confirmed that another co-worker is also having the same problem when trying to access user voice.

**Comment by koconnor719** [comment]
@MarinaMartin can you help w/ this one?  @cfeeney-va  has done some good due diligence on this but it's still an issue.

**Comment by joduinn** [comment]
Found in triage.

Pushing to @cfeeney-va - can you see if there is anything still to do here or if you can just close?

**Comment by koconnor719** [comment]
this was closed months ago; christine left multiple message for user; we retested on pc in office and it worked. we believe it's a browser setting issue w/ user--emailed and phoned w/ instructions to adjust settings.
