### ISSUE TITLE
Implement the Life Insurance Benefit next

### ISSUE THREAD

**Issue by killiandown** [department-of-veterans-affairs/vets-website#1083]
This benefit is not very well advertised and the Prudential interface is completely separate so you could use the same SSO code for your DS Login to Resume Bank.

**Comment by joduinn** [comment]
Found in triage.

Pushing to @staceylanger. Where does this "next feature" request fit in given our other prioritized new feature work?

**Comment by koconnor719** [comment]
Thank you for the feedback.  This is on our 2017 roadmap.
