### ISSUE TITLE
UserVoice Idea: Incorrect Job Description

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1085]
The Skills Translator lists the correct job title for USMC MOS 2676 (2676 : Central Asian Cryptologic Linguist), but when you import into the resume builder, the job description is completely wrong. It seems to be the job description for CH-54 helicopters. 

Perhaps this could reference the VMET database and import job descriptions from there. Or, if it already does that, maybe this particular MOS is buggy. 

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11581104-incorrect-job-description

**Comment by koconnor719** [comment]
pls. advise on response @ayaleloehr

**Comment by ayaleloehr** [comment]
I checked the data files that this came from and this issue exists in there as well (meaning this is not an issue with the VEC application logic, but with the input data).  That doesn't help the user, but is important for our team to know.

The data file says the source is "mosdb", which I do not know what is in reference to.  For reference, the other two sources in that file are Mil2Fed and O*NET.  VMET looks like a good database to use, unfortunately you need to be a service member or have DS_Login to use it, which I am unable to get an account for. Do we have a contact there maybe to see if they want to give us a data dump?

We appreciate the feedback and will work to make this better!  Issue 506 in the VEC repo containing this bug has been created, so @koconnor719 can close this issue in vets-website once she responds.

**Comment by ss0ss** [comment]
A note - several of us on the content team have DS log ins, not sure if that helps db access though.

**Comment by koconnor719** [comment]
posted and closed: Thank you for your feedback. Our team is testing this issue and working to update the source data for this job title.

vets.gov team
