### ISSUE TITLE
Optimize Tagging and Search Result

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1086]
- User searched for “post 9/11” and said “all URLs look the same, this is not helpful, not sure what to select or how to scan”
- Optimize tagging & search results page to facilitate scanning (more descriptive titles, definitions, and links)

**Comment by gnakm** [comment]
This is on-going for search results.

**Comment by ayaleloehr** [comment]
Who is in charge of this? I feel like this is something we should do!
