### ISSUE TITLE
GIBCT Button

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1087]
Make GI Bill link look more actionable so that it doesn't get lost on the GI Bill page. 

Suggestion: A button that is a different color from the green "Apply for Benefits" button (as per discussion) with an icon that will be easy to spot on the page. 
Pros: 
- Helps break content on the page so that intro (text) is not exceeding 75 characters
- Helps find tools better throughout the site 
- If we decide on using icons for resources and tools, it can be added to best practices. 

![screen shot 2016-01-26 at 3 49 34 pm](https://cloud.githubusercontent.com/assets/13420618/12594477/4b98188c-c444-11e5-8816-8b0625e8d61c.png)

**Comment by emilyville** [comment]
Let's revive this! I think the layout is perfect, but a stock button would be best - maybe green like this page?

https://www.vets.gov/disability-benefits/apply-for-benefits/

**Comment by koconnor719** [comment]
should this go in GI tool repo?  we've combined VEC and Careers and Employment (using VEC repo); should we include all things GI in that repo?

**Comment by emilyville** [comment]
So, to summarize, on this page:
https://www.vets.gov/education/gi-bill/

- Move the top green button to apply for education benefits down off the top bar
- put it next to a link to the GI Bill Comparison Tool Page (there will be two buttons there next to the text)

Kind of like this page:
https://www.vets.gov/disability-benefits/apply-for-benefits/

**Comment by gnakm** [comment]
We will need two buttons -- one green and one blue, under the body copy. 

<img width="816" alt="screen shot 2016-03-17 at 4 01 35 pm" src="https://cloud.githubusercontent.com/assets/13420618/13859383/90ab3d68-ec59-11e5-8ba3-da51fc3e596d.png">


<img width="532" alt="screen shot 2016-03-17 at 3 59 40 pm" src="https://cloud.githubusercontent.com/assets/13420618/13859339/651d2b8e-ec59-11e5-9fc8-ce7e1bd123f1.png">
