### ISSUE TITLE
Update getting started documentation to include CMS.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/vets-website#11018]
GIven that a large part of the content is now coming from the CMS it would be nice to have the getting started documentation include cloning the cms and any connections that need to be made in order to make vets-website pull from the local clone.
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/pages/getting-started/index.mdx

**Comment by mchelen-gov** [comment]
resolved by https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/45b0344ad8c1f1ef24c87894bf779d6e7138e2de#diff-c537222c07ce280da4900bdd4ecbc3fa
