### ISSUE TITLE
Pittsburgh hero image broken on IE11 and Edge

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/vets-website#11023]
Hello,

The hero image on va.gov/pittsburgh-health-care is broken on IE11 and Edge. The root cause is due to a class we have on the image that uses "duo tone" When removed, the image is fine. Is there a way to make an alt class just for IE11 and Edge? 

Actual Result
1- Visit  va.gov/pittsburgh-health-care on IE11 or Edge
2- Notice the hero image is a blue box
![unnamed](https://user-images.githubusercontent.com/8558266/68243145-e10c9980-ffdf-11e9-989c-e7b3e751074a.png)

Expected Result
1- Visit  va.gov/pittsburgh-health-care on IE11 or Edge
2- See hero image 
![image](https://user-images.githubusercontent.com/8558266/68243261-1d3ffa00-ffe0-11e9-8b5e-9d6b8b802aa2.png)

Notice on Chrome - the duo tone works fine:
![image](https://user-images.githubusercontent.com/8558266/68243304-3a74c880-ffe0-11e9-8af4-364c5667610f.png)

cc @andrewlewandowski

**Comment by swirtSJW** [comment]
This issue has been resolved with the merge of #11042
