### ISSUE TITLE
Search terms not being recorded in Google Analytics

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#1110]
There are no results for search terms in the vets.gov Google Analytics account (but there are for the VEC Google Analytics account): 

https://analytics.google.com/analytics/web/#report/content-site-search-search-terms/a50123418w107014820p111433053/%3F_u.date00%3D20160101%26_u.date01%3D20160131/

**Comment by joduinn** [comment]
Found in triage. 

Assigning to myself to investigate...

**Comment by ayaleloehr** [comment]
Search terms are recorded via DigitalGov Search here: https://search.usa.gov/sites/6277/queries/new

If there is a reason to also want them in Google Analytics, someone will need to set that up.

**Comment by koconnor719** [comment]
low priority per jeff and stacey

**Comment by jcmeloni** [comment]
@robertfairhead I know you've been doing GA stuff -- is this still an issue and/or something you want tracked? cc @akainic @ayaleloehr

**Comment by robertfairhead** [comment]
@jcmeloni per alex's comment we already have them in digitalgov search so i don't see a need for them in GA. We used the digitalgov data for search team analysis and it worked fine. I'd suggest closing this out and we can open a new ticket if there's ever a reason to put them into google analytics.

**Comment by jcmeloni** [comment]
Perfect!
