### ISSUE TITLE
Add Content-Security-Policy header to nginx config

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#1111]
Been thinking about forcibly reducing XSS attack surface across a federated vets.gov.

If we don't go with an origin sandbox, another option is to reduce the XSS surface area via Content-Security-Policy. http://www.html5rocks.com/en/tutorials/security/content-security-policy/

Ideally, I would disable all inline javascript and restrict all script domains to localhost and a few whitelisted CDNs. We might also turn off flash content.

Lastly, we'd want to put in a post-back handler to detect CSP violations and match our site when they show up.

This will make development a bit more bumpy perhaps (cause no inline javascript) and it only forces compliance on modern browsers (eg Chrome), but that's still a large percentage of our users and the CSP post-back capability turns all users into what's effectively a large-scale vulnerability scan so it can improve overall site security (assuming we respond to the alerts) even if not all browsers actually enforce the policy yet.

**Comment by awong-dev** [comment]
@ShawnArnwine @ayaleloehr @plusjeff

**Comment by plusjeff** [comment]
Cool - just seeing this now. I need to read up about CSP since I don't know anything about it at the moment. Want to understand the scope/impact of inhibiting inline JS, esp on the currently deployed apps.

I trust your judgement though and it sounds like we should do this.

**Comment by awong-dev** [comment]
I think it's a worthwhile experiment. It's easy to turn off later, but it's hard to turn on once there's a mass of inlined javascript and bad cross-origin assumptions.

Happy to discuss more in person. This is one of those thing were me giving an intro might be easier than everyone reading about it separately.

**Comment by ayaleloehr** [comment]
+1 to @awong-dev giving an intro.

**Comment by plusjeff** [comment]
Another +1 for the mix. @awong-dev Could you schedule this?

**Comment by plusjeff** [comment]
@ShawnArnwine @jkassemi : Do you know if we ever did this?

**Comment by awong-dev** [comment]
nope. You need to move the google analytics code from a <script> tag to its
own js file before you can do this. It's easy, but no one's done it.

**Comment by carlmjohnson** [comment]
I think that before we add a CSP we should add a "report" directive that would only send us a message if a user encountered a CSP violation but still let the page render. That way we won't get surprised and accidentally break, e.g., web fonts or something.

**Comment by carlmjohnson** [comment]
https://hacks.mozilla.org/2016/02/implementing-content-security-policy/ is a good overview.

**Comment by awong-dev** [comment]
Yes. The rollout should be de-inline js and CSS. Add a report URL. Add csp
in staging. Crawl sitemap and see if you get any 400s. And if not, move
forward.

Then add csp into nightwatch and fail tests on 400s or something to get CI
coverage.  What you gain is huge protection from xss on modern browsers.

**Comment by plusjeff** [comment]
Thanks for the info @awong-dev and @carlmjohnson !

Assigning to @crwallace for to add to Vanguard's backlog for future work.

**Comment by crwallace** [comment]
@jkassemi -- Can you look at this when you have some time?

**Comment by jcmeloni** [comment]
@jkassemi LMK if you want a different tag on this. Thanks!

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
