### ISSUE TITLE
Re-design UserVoice icon to provide users with more context about what it is. 

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/vets-website#1122]
See issue #1058 

I posted this to @dannychapman as a concept: 
![image](https://cloud.githubusercontent.com/assets/12674895/12787698/8a982b78-ca64-11e5-9e56-00ac6f56cec6.png)

He responded, 

> For the feedback button, we'll have to see what options there in terms of styling  / adding content with Uservoice for the feedback title. Only negative I see with that approach is how much it will cover the content as you scroll. We could consider something fancy, like having the additional feedback text appear after a few seconds of no scroll / interaction. 

@dannychapman @emilyville Can we look into something "fancy"? We could also consider the additional feedback text sliding out on mouseover.

**Comment by dannychapman** [comment]
Working on a fix for this that also tackles an accessibility issue with the widget.

**Comment by Drakenhart** [comment]
Have you considered doing it "tool tip" style, by using javascript to expose the title tag and style it?

**Comment by koconnor719** [comment]
team something happened to the feedback forum that needs to be reverted back to the way it was; see issue #1305  @awong-dev albert thanks for offering to look into this.  it is NOT urgent at all, but we should change it back to the way it was before this last product push on 3/3--because that format was based on user feedback.  @emilyville

**Comment by emilyville** [comment]
I think this can be closed. We've tackled the above issued and the only remaining on is that it's inconsistent across repos - which is already reflected in https://github.com/department-of-veterans-affairs/va_common/issues/25

**Comment by koconnor719** [comment]
Agreed!



Sent with Good (www.good.com)


-----Original Message-----
