### ISSUE TITLE
breadcrumb fix for former Legacy page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1140]
/education/legacy-programs/ 
should be changed to 
/education/other-educational-assistance-programs/

These are the pages affected:
/education/legacy-programs/reap/
/education/legacy-programs/call-to-service/
/education/legacy-programs/veap/

**Comment by webinista** [comment]
Looks like this is fixed. Closing. Might make sense to also redirect old `/education/legacy-programs/ ` URLs to `/education/other-educational-assistance-programs/`.
