### ISSUE TITLE
VOA: things to do for demo

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#1144]
- [X] Missing images (e.g., dropdown arrows)
- [X] Merge PR #1138 (close enough)
- [x] Make inputs correct size (check 18f)
- [X] Remove or comment out PRA content
- [X] Fix breadcrumbs on form.html ("Health Care > Apply for Health Care")
- [X] Remove blue bar above form
- [X] Break questions into sections
- [X] Add "Continue" and "Next" buttons to each section
- [X] Fix Checkboxes
- [X] Comment out commentary with TODOs
- [X] Designate optional form fields (refer to 18f, `span` on label)
- [X] Hardcode an error field for an example (for SSN)
- [x] Javascript to make continue and next functionality work

PUNTING
- [ ] Add copy to "Review and Submit" page
- [ ] Fix tabs so they look like progress bar mockups

@emilyville @awong-dev @EmilyTav

**Comment by emilyville** [comment]
We'll make PRs off of voa-progress-form.

**Comment by awong-dev** [comment]
Is there a reason not to merge voa-progress-form now?

**Comment by emilyville** [comment]
@akainic checked some more boxes with  PR #1146 1146!
