### ISSUE TITLE
js tooltip library?

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#1145]
I'm noticing that we have 3 different tooltip libraries checked in to vets website's vendor folder with jquery-accessible-simple-tooltip-aria.js being the only used that.

However, even there, jquery-accessible-simple-tooltip-aria.js looks to be used in the playbook and on the facility-locator/index.html only.

What is this for? Do we really need it? If not, can I remove it to simplify?

**Comment by awong-dev** [comment]
@dannychapman

**Comment by dannychapman** [comment]
I'd advocate for removing entirely, since those are the only two places we use them. If you want to assign this to either me or @emilyville, I can retool those pages and we can just remove it.

**Comment by emilyville** [comment]
Assigning this to you @webinista - I think this is likely addressed in other issues so it's likely just closing this out.

**Comment by webinista** [comment]
Blocked by #2083.

I'd like to remove all of the tool tip libraries, but before we do that, we should decide whether/how to display the data contained within the tooltip.

It's also used on these pages in the playbook. 

https://www.vets.gov/playbook/product-methodology/definition/
https://www.vets.gov/playbook/product-methodology/discovery/
https://www.vets.gov/playbook/product-methodology/kickoff/

There's already a pull request to remove this tooltip from the Facility Locator.

In the meantime, I'll remove the tooltip scripts that aren't `jquery-accessible-simple-tooltip-aria.js`.

**Comment by crwallace** [comment]
@webinista -- are we good to close this out?

**Comment by webinista** [comment]
Yeah.
