### ISSUE TITLE
Add Patient Wait Times Page

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1170]
There is a new page launching (elsewhere) on Nov 29th, and we've been asked to include information that would send people to it. 

This is the link from the email from Jack Bates:
http://vapwtdev.azurewebsites.net/

Should put it somehow like this until we have more of a "health section" or could somehow incoporate with facility locator - though both of those are out of scope for Feb 29th.
![screen shot 2016-02-11 at 11 34 48 am](https://cloud.githubusercontent.com/assets/1307774/12982621/7e3c70dc-d0b3-11e5-9608-fbe714bc0243.png)

Assigning to @rcarthur for a pass at content (feel free to reassign appropriately) - I don't think we need to treat 2/29 as a hard deadline, but since it's a small amount of work it's a "nice to have."

@rcarthur once you have content please reassign to me or @koconnor719

**Comment by emilyville** [comment]
Also if anyone disagrees with adding a one-off page please chime in - I know this kind of process could get unruly. I'm inclined to think the value of this (I <3 this similar feature for my local DMV!) outweighs the possibly that there is insanity after we do a million more like it.  

cc/ @dannychapman @maryannbrody

**Comment by rickleegit** [comment]
Not sure if we will be doing this post March 31, but we have spoken about incorporating this data into the Facilities Locator as a second phase enhancement.

**Comment by koconnor719** [comment]
let's plan to include in FL; but agree let's get up on site prior to March 31 as long as everyone ok w/ that.

**Comment by emilyville** [comment]
Yes, this issue should remain independent from facility locator.

**Comment by koconnor719** [comment]
closing this issue per call w/ Jack Bates 2/17; this is a post May 1 task.  patient wait times team still has internal testing to do on this tool in march and april; no actions for our team at this time.
