### ISSUE TITLE
something up with "new window" icon

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1182]
We are having to remove some CSS that puts this icon at the end of links
![exit-icon](https://cloud.githubusercontent.com/assets/1307774/12994368/090f9286-d0ee-11e5-96e2-63a01507fb3a.png)

It wasn't working - but then with some bourbon updates it was working in a way that broke things, so it's removed completely!

I believe this is the intended behavior:
![screen shot 2016-02-11 at 6 37 28 pm](https://cloud.githubusercontent.com/assets/1307774/12994433/a7062090-d0ee-11e5-813e-ac523ffcbbad.png)

**Comment by emilyville** [comment]
@webinista I think we're missing these everywhere now, take a look and assess!

**Comment by webinista** [comment]
Yes, it was a global change. I'm working on it, but it's blocked by #1663.
