### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/vets-website#11948]
test

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/95f62874-f2f6-45f1-ba9a-dda02d85d45f)

**Comment by ncksllvn** [comment]
@kelsonic I don't understand this issue. What's the acceptance criteria?

**Comment by kelsonic** [comment]
@ncksllvn Good question, we may want to open a new ticket to discuss that.

**Comment by ncksllvn** [comment]
Okay, let's schedule a meeting for our teams to sync on this issue
