### ISSUE TITLE
Set up sprints for vets.gov website work

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1201]
set up sprint cycle for main vets.gov site once new vets.gov product manager starts 2/22.

@emilyville @plusjeff

**Comment by emilyville** [comment]
Sure, but we'd also need to identify a project team...

**Comment by emilyville** [comment]
I'd also advocate to move this issue to vets-team repo since that's where we'd need to specify the team, and the project. We'd need to clarify what would be owned by this team.

i.e. would they also be responsible for global changes filtering out to apps?

**Comment by koconnor719** [comment]
I thought the opposite:) it�s the �website� repo that needs the sprints.  :)


Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by koconnor719** [comment]
assigning to stacey to decide repo (per emdash suggestion) and next step.

**Comment by koconnor719** [comment]
closing this since it seems obsolete
