### ISSUE TITLE
Instrument performance telemetry

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#1211]
https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings

We should have metrics and telemetry for performance of our site. That way we can have more insight into if we're messing up mobile users or users with older browsers, etc.

In particular, if we are going to target mobile links (rural areas) which are characterized as "long fat pipes) we need to 
  (a) reduce payload size [cost, not necessarily speed...but maybe speed on 2g]
  (b) avoid round-trips [latency is much higher on mobile links], especially serialized round-trips on APIs
  (c) expect older browsers on low-powered devices meaning careful about assuming JS is fast and that large DOMs are okay because JS on ARM phones can be abysmally slow (esp on old versions of browsers) and memory is obviously smaller.

**Comment by awong-dev** [comment]
Tagging @MarinaMartin

**Comment by carlmjohnson** [comment]
Our performance on first load is not very good at the moment: http://www.webpagetest.org/result/160628_D0_Z6P/

**Comment by carlmjohnson** [comment]
Here's our performance from my home network (FiOS) according to [boom](https://github.com/rakyll/boom):

```shell
$ boom https://vets.gov
200 / 200 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 %

Summary:
  Total:        9.2354 secs.
  Slowest:      5.7514 secs.
  Fastest:      1.1435 secs.
  Average:      2.0935 secs.
  Requests/sec: 21.6557
  Total Data Received:  2675000 bytes.
  Response Size per Request:    13375 bytes.

Status code distribution:
  [200] 200 responses

Response time histogram:
  1.144 [1]     |
  1.604 [80]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  2.065 [49]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  2.526 [4]     |∎∎
  2.987 [18]    |∎∎∎∎∎∎∎∎∎
  3.447 [38]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  3.908 [2]     |∎
  4.369 [6]     |∎∎∎
  4.830 [1]     |
  5.291 [0]     |
  5.751 [1]     |

Latency distribution:
  10% in 1.2692 secs.
  25% in 1.3459 secs.
  50% in 1.7437 secs.
  75% in 2.9476 secs.
  90% in 3.2507 secs.
  95% in 3.4619 secs.
  99% in 4.7970 secs.
```

**Comment by carlmjohnson** [comment]
For comparison, here's my personal website (low traffic, static HTML, hosted on a single private virtual server):

```
$ boom https://carlmjohnson.net

Summary:
  Total:        0.8751 secs.
  Slowest:      0.3842 secs.
  Fastest:      0.1017 secs.
  Average:      0.2044 secs.
  Requests/sec: 228.5513

Status code distribution:
  [200] 200 responses

Response time histogram:
  0.102 [1]     |
  0.130 [28]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.158 [50]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.186 [40]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.215 [22]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.243 [9]     |∎∎∎∎∎∎∎
  0.271 [0]     |
  0.299 [7]     |∎∎∎∎∎
  0.328 [20]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.356 [7]     |∎∎∎∎∎
  0.384 [16]    |∎∎∎∎∎∎∎∎∎∎∎∎

Latency distribution:
  10% in 0.1194 secs.
  25% in 0.1445 secs.
  50% in 0.1753 secs.
  75% in 0.2871 secs.
  90% in 0.3474 secs.
  95% in 0.3689 secs.
  99% in 0.3841 secs.
```

**Comment by awong-dev** [comment]
Part of this is due to TIC requirements.  What is the meat of this test? Is
it just a short packet or is there a large payload.

Also... YOU HAVE PERCENTILES!!! YAY!

**Comment by awong-dev** [comment]
Due to our current network topology, things entering through the east coast
gateway will be the slowest since we for a transcontinental hop into
govcloud.

I notice the locale for your page's test is Dulles VA. The other gateway is
in Austin. I'm curious what you get if you try austin.

Also, our DNS is even RR, not geolocated.  Thus, we can actually incur a 2
trans-continental hit per load. <3 TIC. Not.

**Comment by carlmjohnson** [comment]
Yeah, I think the topology is the most likely culprit, because the actual download after first byte is very fast. Once we move everything to govcloud, it should be considerably less latent.

Boom works by just downloading the raw page (no images or other associated files). It's mostly good as a way of getting a sense of how long it takes to get a connection. webpagetest.org on the other hand renders the whole page in a virtual browser, so it's better for getting a sense how long it will take for users to see the page.

In terms of setting up telemetry, it would be good to have these scripts run regularly and then dump the output somewhere (S3?), so that we can make graphs of speed over time and check it every few weeks. At my old company we did a "tech huddle" every Monday to go over the numbers: how many 500s, how long is the longest DB transaction, etc. and then make tickets if anything got worse.

Making a script for webpagetest.org shouldn't be too hard. Once you have a key you can run `curl "http://www.webpagetest.org/runtest.php?url=https://www.vets.gov&f=json&k=KEY"` and you'll get a response like

```json
{
        "data": {
                "detailCSV": "http://www.webpagetest.org/result/160628_33_10RF/requests.csv",
                "jsonUrl": "http://www.webpagetest.org/jsonResult.php?test=160628_33_10RF",
                "ownerKey": "747ffe160351d5dfb49a8d5fb75776c81827eaba",
                "summaryCSV": "http://www.webpagetest.org/result/160628_33_10RF/page_data.csv",
                "testId": "160628_33_10RF",
                "userUrl": "http://www.webpagetest.org/result/160628_33_10RF/",
                "xmlUrl": "http://www.webpagetest.org/xmlResult/160628_33_10RF/"
        },
        "statusCode": 200,
        "statusText": "Ok"
}
```

Then if you grab data.jsonUrl, you get the full data trace with all the timing info we'd need.

**Comment by koconnor719** [comment]
james pls. move to dev ops repo:)

**Comment by jkassemi** [comment]
@koconnor719, dev ops is working on collecting information on time to first byte and response latency, but I think this is still relevant for the google analytics integration and collecting timing information (DOM load, first paint) from the client's perspective.

Can you point me to who's got details on the GA integration?

**Comment by koconnor719** [comment]
For GA integration we have been waiting on an ad hoc person . You should check w Bob .



Sent with Good (www.good.com)


-----Original Message-----

**Comment by jkassemi** [comment]
Spoke with @robertfairhead regarding our current GA integration. We're already collecting some useful performance information there. I've opened an issue in devops to cover further metrics collection for prometheus.
