### ISSUE TITLE
standardize the presentation of addresses

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1231]
For example, on this page:
https://staging.vets.gov/education/apply-for-education-benefits/regional-office/

The elements of addresses (and the phone numbers) appear all on one line:
1700 Clairmont Rd. Decatur, GA 30033 (800) 827-1000

We would like it to be like this instead:
1700 Clairmont Rd. 
Decatur, GA 30033 
(800) 827-1000

**Comment by emilyville** [comment]
![screen shot 2016-03-09 at 2 54 57 pm](https://cloud.githubusercontent.com/assets/1307774/13653496/ef0c5df0-e606-11e5-923e-ff57d01d1a6d.png)

**Comment by gnakm** [comment]
changed and merged #1463
