### ISSUE TITLE
quick links - Veteran feedback

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1248]
can we review the quick links? there are links for all of the "resources" except VEC?  we are getting Veteran user feedback is that users can't find employment information. can we consider making a quick link for employment? (not "vec" but something relevant to employment--like "create a civilian resume" or something? 

  also, can we revisit the yellow bar on "how can i find VA locations" why does that one have a yellow bar?  that seems confusing--or at least unclear? 

@gnakm @maryannbrody

**Comment by emilyville** [comment]
OK, sure. I think having a careers and employment section should solve
this, so i propose we visit after.

The yellow bar and facility location sound like separate issue...

**Comment by koconnor719** [comment]
sure i can break out to 2 issue, but was thinking this issues was just to review all the quick links based on on our user research to date and in anticipation of launching new careers and employment.  for the yellow bar,  "what education benefits are available by school" is also a link to the GI tool, but that doesn't have a yellow bar. (i thought maybe b/c they went to one of our services that was the yellow bar?)

![screen shot 2016-02-26 at 7 54 20 pm](https://cloud.githubusercontent.com/assets/13770771/13369450/fd33aa0c-dcc2-11e5-9fb4-0de48fda4524.png)

**Comment by emilyville** [comment]
I am not really sure what to do to address this issue. If you can point me towards the user research you're referencing I might have more insight, but as it is I'm not sure what the next steps are for this. 

The yellow bar is for "tools" or "apps" 
No yellow bar is for content pages.

**Comment by koconnor719** [comment]
research-of-one just me:)  that makes sense about the yellow bar--but  "what eduction benefits are available by school" is also a too-- but no yellow bar?  you can close this if no action but just wanted to point out potential inconsistency.

**Comment by emilyville** [comment]
I think we should
- remove the yellow bar unless we can justify when and why we're using it clearly (but I can't seem to!)
- close this for quick links and implement the change in https://github.com/department-of-veterans-affairs/vets-website/issues/2054

**Comment by gnakm** [comment]
I agree to get rid of the yellow bars. If we find a use case where we need a quick link to tools, then we could maybe 1. add a 3rd column (to #2054) with something like Quick Tools as a header or 2. put them all in the footer and potentially make changes discussed in (#2218).

**Comment by maryannbrody** [comment]
fwiw, this sounds great to me too.
