### ISSUE TITLE
Blog page "experience" text box?

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1249]
is the blog page supposed to function this way--with the yellow experience box moving down the page as you scroll?  

![screen shot 2016-02-29 at 7 02 54 am](https://cloud.githubusercontent.com/assets/13770771/13393943/9b4b030c-deb2-11e5-8d15-bc8f4055b334.png)

the yellow box moves w/ the page as you scroll.  

![screen shot 2016-02-29 at 7 04 11 am](https://cloud.githubusercontent.com/assets/13770771/13393950/ab66f944-deb2-11e5-8eb0-d1b825b1e4bc.png)

@emilyville

**Comment by koconnor719** [comment]
@gnakm is this working as it should?  the experience box seems odd?  if this is how it is supposed to be working, then pls. close this issue.

**Comment by gnakm** [comment]
@koconnor719 That is most definitely not supposed to do that so I will try to fix it.

**Comment by emilyville** [comment]
I'm 90% sure this was intentional, but i don't mind if we want to change it to make it like the rest of the breadcrumbs. I don't feel like that's a super urgent fix though, since imho nothing is broken ;)

**Comment by emilyville** [comment]
Let's make this less surprising and have it scroll with the page. initial landing place it good!
