### ISSUE TITLE
Critical Vulnerabilities

### ISSUE THREAD

**Issue by JNHQ** [department-of-veterans-affairs/vets-website#12631]
Am submitting this issue on behalf of a company that analyzes critical infrastructure supply chain risk for the US government. Our analysis of the vets-website code has identified. Five critical vulnerabilities in the VA front end, including a malware package. Screenshot is attached. Please contact info@ionchannel.io if you  want the full analysis or wish to coordinate further. 
[Vets-website analysis screenshot.pdf](https://github.com/department-of-veterans-affairs/vets-website/files/4617244/Vets-website.analysis.screenshot.pdf)

**Comment by gunsch** [comment]
Duplicate of #12637
