### ISSUE TITLE
Local linting command does not match CircleCI linting rules

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/vets-website#12711]
When following https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/test and running `yarn lint` locally it does not seem to include all the linting rules, such as `va/use-resolved-path` which are used by CircleCI `lint:circle`.

This causes confusion, as the developer believes they are passing all lint checks, and then CircleCI throws a lint error. Can both linting commands be made to do the same thing, or the documentation updated to explain this?

**Comment by jhonnyoddball** [comment]
The ESLint rules in CircleCI is an experimental staging area as we explore new rules and ways to communicate any issues that are discovered.

Part of the process for CircleCI is to run tasks against the code. There are 2 tasks that include ESLint in the workflow. One of these tasks (test_and_build) runs the rules which are enforced and the other task (additional-linting) runs the rules which are experimental. additional-linting will display all the errors related with the ESLint rules being tested, but it won't block the PR from being merged.

For more information about this, [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/eslint/adding-new-rules.md).

**Comment by mchelen-gov** [comment]
Thanks for the additional context, that makes sense. When looking at the PR and seeing that a CircleCI task failed, and that merging is blocked, it can be a little confusing that the block is due to PR review and has nothing to do with the CircleCI task. Not sure if there is any way to make this clearer from dev ex side?

**Comment by jhonnyoddball** [comment]
Yes, absolutely! This is something new we are implementing. We just need to update the documentation.

**Comment by timwright12** [comment]
Closing out since we deprecated circleCI
