### ISSUE TITLE
GitHub / Waffle issue?

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1291]
potential bug in github or waffle with automatically unassigning, closing, and removing issues from current sprint.  
![screen shot 2016-03-02 at 11 19 55 pm](https://cloud.githubusercontent.com/assets/13770771/13484671/f5ee6192-e0cd-11e5-92a0-f177a893c423.png)

assigning jeff to review--and assign as appropriate:)

**Comment by plusjeff** [comment]
@koconnor719 : What's the link to the issue this happened with?

**Comment by koconnor719** [comment]
one of them was in employment center github issue #73

**Comment by plusjeff** [comment]
Not seeing the issue in VEC 73: https://github.com/department-of-veterans-affairs/veterans-employment-center/issues/73

**Comment by koconnor719** [comment]
i can't replicate this sorry; can i close this.

**Comment by emilyville** [comment]
We can reopen if this happens again.
