### ISSUE TITLE
Blind testing request from Sec

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1292]
Chris O'Connor is our assistant secretary for congressional affairs. This needs to go through him. There was a congressman Complaining about VA.gov not being accessible for blind veterans, would be good to show him vets.gov with a screen reader.

**Comment by maryannbrody** [comment]
Update -- I emailed Pat Sheehan to get his help. I do not have bandwidth to do a usability study with blind veterans in the next couple of weeks, so hoping he can help us make a quick video with a screen reader. If he can't, I will explore other options.

**Comment by koconnor719** [comment]
@maryannbrody did this get completed?

**Comment by maryannbrody** [comment]
No - I reached out to Pat Sheehan but never heard back. I will reach out again this week! Also trying to get to the Blind Veterans Association national conference in August...

**Comment by koconnor719** [comment]
thx.  can you pls. send me that email string w pat.  we are constantly getting dinged that we don't work with that office, so i want the email to show they are not responsive--just in case this comes up again.  :)  @MarinaMartin

**Comment by maryannbrody** [comment]
@crwallace and I are conducting testing at the Blind Veterans Association conference August 23+24 in Milwaukee, WI. Closing this.
