### ISSUE TITLE
Vets.gov header for tools - for discussion and consideration

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/vets-website#1308]
**Context**:
- On both the CT and the FL tools, certain interactions require page reloads.
- In certain situations, that reload returns to the user what appears to be the same page, with different data populated or refined. 
- The user is required to scroll down on the page to view results or reengage tool features or content. 

**Example: **
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Facilities_Locator/PM%20Docs/SFL_Scroll.mov

**Question:**
Should we create a tool specific header that condenses the header vertically and allows us to render key functionality closer to the top of the screen and reduce the necessity of repositioning, via scroll, for the user? 

@emilyville @maryannbrody @gnakm @dannychapman

**Comment by emilyville** [comment]
My gut reaction is no. We shouldn't make a tools specific header at this point. If we need to have a globally less  bulky header that's definitely a thing we could consider. 

More better - would be reloading the content without refreshing the page or scrolling to the top. In my experience this is way less hard than redesigning global elements.

**Comment by rickleegit** [comment]
"reloading the content without refreshing the page or scrolling to the top"

This would be the better way of handling this. Not sure what is possible in terms of passing variables through cookies instead of URLs. CCing @ayaleloehr

**Comment by emilyville** [comment]
Adding an anchor and reloading to that place on the page would be a pretty low-fi interim hack, not ideal long term but would be awesome for a prototype.

**Comment by rickleegit** [comment]
That might work. Worth a try. Thanks!

**Comment by ayaleloehr** [comment]
Adding to the conversation late, but "reloading the content without refreshing the page or scrolling to the top" is just an ajax call, so that's simple.  But that won't give you the nice URL that I think you're looking for @rickleegit , where the URL explains exactly what's on the page and you can send someone a link to it.  Whether it's more valuable to have that info in the URL or to have the UX of non-reloading becomes the tradeoff that needs to be considered.
