### ISSUE TITLE
IA comments

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1313]
summary of comments for Mary Ann and team to review for IA:)

- include homeless call center telephone and chat where appropriate in IA; this is a call center set up specifically for homeless issues: 

http://www.va.gov/homeless/
<img width="226" alt="screen shot 2016-03-04 at 4 24 41 pm" src="https://cloud.githubusercontent.com/assets/13770771/13540636/acd69246-e225-11e5-9fbb-7d5df40ed213.png">

- add crisis line content page in "are you struggling" section

**Comment by emilyville** [comment]
Assigning to Mariana as it seems relevant to #1312 

Might be worth consolidating.

**Comment by mariana-almeida** [comment]
Sounds good. This is already part of the Preventing Homelessness IA. It's good to know where it came from.

**Comment by emilyville** [comment]
I think this is part of a bigger effort and can be closed along with #1312 

for now we'll just do #1606
