### ISSUE TITLE
breadcrumb fix for Accredited Rep (Get Help Filing a Claim) page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1328]
On this page:
https://staging.vets.gov/disability-benefits/apply-for-benefits/help/index.html

In the breadcrumbs, the word "For" in "Apply For Benefits" needs to be lowercased.

**Comment by nsinai** [comment]
I can't see the staging site

**Comment by bethpotts** [comment]
Here it is!
https://vets-website-pr-1304.herokuapp.com/

**Comment by bethpotts** [comment]
Sorry, you don't need staging. It is just this:
vets.gov/disability-benefits/apply-for-benefits/help/index.html
