### ISSUE TITLE
Markdown links broken

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1329]
Under "Before enrolling at your foreign school" the links are funky and broken.

https://www.vets.gov/education/gi-bill/foreign-programs/

![screen shot 2016-03-07 at 12 53 45 pm](https://cloud.githubusercontent.com/assets/1307774/13582981/f83237c8-e463-11e5-9fa6-a106042f01e2.png)

**Comment by emilyville** [comment]
@bethpotts approved! and a new image with the bullets 
![screen shot 2016-03-07 at 5 37 04 pm](https://cloud.githubusercontent.com/assets/1307774/13589251/41315c66-e48b-11e5-8424-6cfae1c760f2.png)

**Comment by awong-dev** [comment]
LGTM
