### ISSUE TITLE
Stakeholder Interviews 

### ISSUE THREAD

**Issue by LEHigley** [department-of-veterans-affairs/vets-website#13340]
- [ ] VetLink Kiosk: Shawn Adams
- [ ] Lighthouse APIs: Dave Mazik 
- [ ] My HealtheVet: Kathy Frisbee, Dr. Evans
- [ ] Kellie Condon 
- [ ] VEO: Denise Kitts 
- [ ] Internal Medicine and Informatics physician: Dr. Byrne
- [x] eScreening: James Pittman 

Stakeholders to identify: 
- [ ] Clinical Informatics Lead for Nursing Intake forms: This stakeholder can assist in updated patient intake forms documentation being done with both Vista and Cerner to ensure we are leveraging the modernization of the EHR project for consolidated and consistent documentation across facilities and specialties.
- [ ] Connected Care- clinical tool VCM 
- [ ] Clinical/Admin/Intake staff who can speak to current state processes & documents

**Comment by abuckley3385** [comment]
@LEHigley  this ticket is in the vets-website instead of va.gov-team workspace.  Im not sure I know how to move it to our or we can cancel and recreate in our space??
