### ISSUE TITLE
Make a smarter way to link to veterans employment center (old) from vets-website

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1372]
For stuff like this we should be smarter, maybe set a variable somewhere so there's just the one spot this is set.
`<a href="https://www.vets.gov/veterans-employment-center/createresume/">THING</a>`

.... and then replace then all.

Tagging @ayaleloehr @awong-dev @plusjeff since I think it's possible whatever solution also works for other tools. 

(Maybe we already have a way and I just don't know what it is?)

**Comment by awong-dev** [comment]
Yeah...isn't this where Jekyll configs come into play?

**Comment by emilyville** [comment]
reviving this for some time-sensitive VEC stuff coming up @awong-dev @plusjeff @ayaleloehr @webinista 

I think we need a smarter way to set URL variables between repos. like VEC, GI tool, etc from vets-website.

Anyone have bandwidth to take this on? I don't think it's a huge task.

**Comment by ayaleloehr** [comment]
My hope is that we can just do this with relative links.  Right now, vets-website links to GI Bill Comparison tool like [this](https://github.com/department-of-veterans-affairs/vets-website/blob/94e9cf9a0a7258db5d25130cb562e701f31f8a37/404.html#L44) or [this](https://github.com/department-of-veterans-affairs/vets-website/blob/1296c641f696ba92792766e90bf6262e352b183f/_education/tools-programs/locate-a-school.md). So hopefully we can just match that and put `/employment/job-seekers/skills-translator`, for example, as the links in vets-website

**Comment by emilyville** [comment]
:+1: ! if this is not actually an issue we can close.
