### ISSUE TITLE
this page is linking to itself

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1375]
Is something else supposed to go in the last piano key?

https://vets-website-pr-1304.herokuapp.com/employment/job-seekers/start/register/

**Comment by rcarthur** [comment]
I agree - piano key should link to this document.  https://www.pivotaltracker.com/story/show/112172071 We should be able to finally resolve this in the next couple days - soon as we get the new IA in place.  Sorry for delay.

**Comment by emilyville** [comment]
no worries - this is fixed!
