### ISSUE TITLE
Resume Builder copy update

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1400]
Here is the resume builder page:
https://www.vets.gov/veterans-employment-center/createresume

This is from pivotal:

> The Veterans Employment Center™ (VEC) can help you build your profile so potential employers can find you on vets.gov. This profile can then be downloaded into a civilian or federal résumé. You can easily import your LinkedIn™ profile with a few simple clicks. Your public job-seeker profile will be stored on vets.gov, and you can update your information as often as needed.  
[Link to ebenefits]

@bethpotts @lanaduffy I don't understant you added a link to ebenefits before beginning the resume builder? This would not help someone complete their resume - ebenefits does not have this capability, however the page you would already be on does.

I'm also wondering if this completely replaces the existing copy - which I think is functionally helpful in navigating the form. i.e. I will assume we want to keep the Autofill from linkedin button?

> Build a Profile & Résumé
Use this form to create a public profile so employers committed to hiring Veterans can find you here on the Veterans Employment Center™.

> Manually enter your information into the form fields below, or use the Auto-fill from LinkedIn button to pre-populate some of the fields from your LinkedIn account. (Not all fields will be populated).

> Auto-fill from LinkedIn
LinkedIn is also providing a free 1-year Job Seeker Premium subscription ($360 value) to all U.S. Veterans and Servicemembers. Learn more here.

**Comment by rcarthur** [comment]
@emilyville The content in pivotal is meant to supplement the content that already surrounds the tool, which we thought was pretty good.  Sorry for confusion on this - this is one of the pages that we envisioned walking through hand in hand with Danny. The link to ebenefits is an old relic from our first draft when we used ebenefits as shorthand for the existing VEC tools.

**Comment by emilyville** [comment]
this is done and reflected going forward in #1546
