### ISSUE TITLE
Appeals User Voice Comments are going to vets.gov repo

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1421]
appeals team is now using user voice; appeals comments should be routed to separate repo; see issue #1398 

@gmorgana-va 

![screen shot 2016-03-14 at 10 31 16 pm](https://cloud.githubusercontent.com/assets/13770771/13765984/804889e8-ea34-11e5-94ea-9e3d6ca08fd3.png)

![screen shot 2016-03-14 at 10 30 59 pm](https://cloud.githubusercontent.com/assets/13770771/13765977/742201bc-ea34-11e5-9c19-0d00018c4727.png)

**Comment by MarinaMartin** [comment]
They actually are not, I am deleting this forum tomorrow.

**Comment by MarinaMartin** [comment]
Turned off the appeals forum, they are not using it.
