### ISSUE TITLE
GI Bill Page Prototype 75 characters

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1444]
<img width="816" alt="screen shot 2016-03-17 at 4 01 35 pm" src="https://cloud.githubusercontent.com/assets/13420618/13859484/0c1f8fe4-ec5a-11e5-8520-bf11cfb73e26.png">

Body copy should be 75 characters in length.
Text has to be left-aligned with the breadcrumb.

**Comment by webinista** [comment]
@gnakm Are these going to be a global changes? Should all body copy be a maximum of 75 characters or so wide?

**Comment by gnakm** [comment]
@webinista We were thinking this would just be a prototype for this issue. We're going to get the design community to pull the branch together and make a consensus for global change. Thanks for asking!

**Comment by gnakm** [comment]
@webinista I just checked out new buttons and they look great! Could you make the body copy shorter so that the width is max 75 characters in length?
