### ISSUE TITLE
Card Navigation Redesign

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1455]
We want to make a prototype of the cards with new sublinks
One example we've been playing with is the [education benefits](https://www.vets.gov/education/) landing page

1. Make card height shorter (140 px instead of 160)
2. Make GI Bill card clickable with an arrow
3. Have 2 square bullet point links when you click downward arrow
    - GI Bill Comparison Tool: https://www.vets.gov/gi-bill-comparison-tool/
    - Apply for Education Benefits: https://www.vets.gov/education/apply-for-education-benefits/

![closed](https://cloud.githubusercontent.com/assets/13420618/13886123/d4b1ecca-ed0b-11e5-81d1-d957b508f9b4.png)

![open](https://cloud.githubusercontent.com/assets/13420618/13886291/ab13a6aa-ed0c-11e5-8feb-d9eee6668b1c.png)

Mobile will have same interaction. This is the open version. 
![mobile](https://cloud.githubusercontent.com/assets/13420618/13886295/b090849a-ed0c-11e5-8f18-52fff41ebd4e.png)

**Comment by webinista** [comment]
@gnakm Can you send me SVG and PNG versions of the down arrow? (Attaching them to this ticket is fine.)

**Comment by gnakm** [comment]
@webinista 

![vetsdotgov_downarrow-01](https://cloud.githubusercontent.com/assets/13420618/13931852/a4d0cfcc-ef7b-11e5-9d83-c9a7a0235ceb.png)

**Comment by gnakm** [comment]
@webinista 
After chatting with the designers, an alternative to a drawer is having a fixed height for the cards. 

For the large screen version, we are thinking having the arrows clickable. For the 2nd image on the right, the GI BILL in blue won't be active but active again when you close the links again. Let me know if that makes sense
<img width="722" alt="screen shot 2016-03-21 at 6 39 45 pm" src="https://cloud.githubusercontent.com/assets/13420618/13936504/8da696ba-ef94-11e5-84a4-931adcaceff7.png">

For easier usability, the arrow for the mobile version will be on the side. 
<img width="524" alt="screen shot 2016-03-21 at 6 53 07 pm" src="https://cloud.githubusercontent.com/assets/13420618/13936745/39926fde-ef96-11e5-8b7d-8654bcc0b67e.png">

Here are the pngs of both blue and white arrows:

![blue down](https://cloud.githubusercontent.com/assets/13420618/13936926/93eaad24-ef97-11e5-8ee9-8fd330af5431.png)
![blue up](https://cloud.githubusercontent.com/assets/13420618/13936925/93e9c800-ef97-11e5-82f9-a51b2d7005b9.png)

![white down](https://cloud.githubusercontent.com/assets/13420618/13936931/992dc0d2-ef97-11e5-9b58-1d849ca48c3d.png)
![white up](https://cloud.githubusercontent.com/assets/13420618/13936932/992edaa8-ef97-11e5-8242-543124d32ab5.png)

**Comment by webinista** [comment]
@gnakm  
1. Can you add SVG arrows as well? This will keep us from having to use DPI queries and what-not.
2. Is the idea that this drawer would slide up from below? 
![](https://cloud.githubusercontent.com/assets/13420618/13936504/8da696ba-ef94-11e5-84a4-931adcaceff7.png)
3. This doesn't quite make sense to me.
> GI BILL in blue won't be active but active again when you close the links again.

What does "active" mean here?

**Comment by gnakm** [comment]
1.You can find SVG files [here](https://github.com/department-of-veterans-affairs/vets-website/tree/master/assets/images)
2. Yes. Draw slides up, card height does not change.
3.
![gi link](https://cloud.githubusercontent.com/assets/13420618/13954623/031cbb08-f018-11e5-9539-42721488509f.png)
