### ISSUE TITLE
Refactor and/or document breakpoints

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#1467]
There's a USWDS breakpoint of `600px` and a Foundation breakpoint of `640px`. Foundation breakpoints are mostly used in the grid layouts. USWDS is used in many other places. It's a bit of a mess to figure out when you step into the code. Let's either agree to use one breakpoint or document the mess.

**Comment by emilyville** [comment]
@webinista I defer to your best judgment on this! also tagging @akainic and @crwallace for opinions!

**Comment by akainic** [comment]
@emilyville Is the plan still to remove Foundation eventually and just use USWDS or Neat? If so, maybe for now we just change the Foundation breakpoint to match the USWDS one?

**Comment by webinista** [comment]
Assigning it to you @emilyville because we need an answer :-). Reassign as you wish.

**Comment by emilyville** [comment]
I think changing the foundation breakpoint to be consistent with USWDS (600) makes sense to me. It seems more likely that we let go of foundation than USWDS, I think.

**Comment by webinista** [comment]
Closing. We have a much bigger problem than breakpoints. Foundation is too entrenched in our markup for breakpoints to be considered separately.
