### ISSUE TITLE
New page for stubbing - 

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1483]
Emily  -  

This is a new page that needs to be stubbed out.  This page is the the "Job Seekers" blue box on the top left of the revised C&E IA below:
![careers employment sitemap v2 2](https://cloud.githubusercontent.com/assets/14881302/14003208/397e089a-f10e-11e5-820c-9a0a2479392c.png)

Here is the word document that lists all of the content that we will flow into the site.  (10 stops on subway map.)
[JobsV2_landingPage_draft04_20160323.docx](https://github.com/department-of-veterans-affairs/vets-website/files/186986/JobsV2_landingPage_draft04_20160323.docx)

Here is a sample vets.gov page that can be used for reference - except there are 10 stops on the subway map......
https://www.vets.gov/disability-benefits/apply-for-benefits/

**Comment by webinista** [comment]
Should replace the content at `/employment/job-seekers/`

**Comment by emilyville** [comment]
this is done!
