### ISSUE TITLE
Subway Map Mockup

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1488]
Subway map mockups for new job seekers page

**Comment by emilyville** [comment]
Just adding that I'm making this now re: https://github.com/department-of-veterans-affairs/vets-website/issues/1483

I will post a screenshot when it's done so you can start from there or critique.

**Comment by emilyville** [comment]
looks like this - we could give it some <3
![screencapture-0-0-0-0-4000-employment-job-seekers-1458884066411](https://cloud.githubusercontent.com/assets/1307774/14039091/ab92e772-f215-11e5-93d8-8ca8371c3185.png)

**Comment by emilyville** [comment]
@gnakm let's look at this d

**Comment by gnakm** [comment]
@emilyville How about breaking down the 10 steps into 2 sets of 5 steps? I'm more into the arrows than the tabs because I don't know what I would label the tabs unless @mariana-almeida is there a way to break down this list into two themes (i.e. Steps 1-5 = Your profile, Steps 6- 10 = Other resources...). It would be nice to see everything in 10 steps but page is getting long. Also, would it be okay to scrap the first paragraph before "Before you begin?.."

![job steps tabs](https://cloud.githubusercontent.com/assets/13420618/14084665/d960ddd6-f4e9-11e5-8789-9e2905e3e8ee.png)
![job steps arrow](https://cloud.githubusercontent.com/assets/13420618/14084670/dda57712-f4e9-11e5-9e7c-209dace2ab54.png)

**Comment by gnakm** [comment]
@mariana-almeida @mollyblake 
Thanks for the next steps.
Action Item: Condense to 6 steps and add related info in light blue box.

**Comment by mollyblake** [comment]
@gnakm @mariana-almeida I think we can make that "before you begin..." text smaller and bold the top lines of text. And I'd like to change those to ?'s. "Do you plan to leave active duty in less than 12 months?" etc.

**Comment by mariana-almeida** [comment]
@mollyblake That sounds fine. Give it a whirl!

**Comment by mollyblake** [comment]
@gnakm @mariana-almeida Another thought ... the top three questions -- (do you have less than a year, unemployment, alternative) can we put those in a box on the side?  I'm really struggling with their placement and the experience ... any thoughts on how we can treat those as sort of 'other' categories that some might fall into and set them aside on the page?

**Comment by emilyville** [comment]
this is done!
