### ISSUE TITLE
Need page stubbed out for Federal Employment 

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1508]
This page will be linked off of the Job Seekers Landing Page.   Once the page is visible in the repo, we can load in our content.  

Federal Employment
[Jobs_FedEmployment_20160211 (2).docx](https://github.com/department-of-veterans-affairs/vets-website/files/188881/Jobs_FedEmployment_20160211.2.docx)

**Comment by emilyville** [comment]
This one's been hanging out for a while, apologies for not sending it your way. 

It's possible it's out of date: https://github.com/department-of-veterans-affairs/vets-website/issues/1512

/employment/job-seekers/federal-employment/
