### ISSUE TITLE
global fix for piano keys on the job-seekers pages

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1509]
They all have pivotal IDs that need to be removed, as well as the preceding colon and #. 
    One-on-One Assistance: #110298554
    Skills Translator: #110298580
    Résumé Builder: #111659432
    Search the Veterans Job Bank: #110298570
    Interest and Aptitude Profiler: #110298582
    Military Transcripts: 110298578
Here's an example of a page that has these piano keys:
https://staging.vets.gov/employment/job-seekers/employment-support/

**Comment by emilyville** [comment]
This is done & in a pull request.
