### ISSUE TITLE
Need a page stubbed out for "Establish an Apprentice Position" 

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1520]
This is an update on this "pre-new-IA"  issue from 9 days ago.
https://github.com/department-of-veterans-affairs/vets-website/issues/1434

Right now, this page does not exist in the Employment v2 repo.  

It should be linked off from the  "Employers Landing Page"  

The content for this should this:
[Jobs_ApprenticeshipProgram_20160325 (1).docx](https://github.com/department-of-veterans-affairs/vets-website/files/190035/Jobs_ApprenticeshipProgram_20160325.1.docx)

**Comment by emilyville** [comment]
It exists. I moved it out of commitments because according to the new IA so now it's at:

employment/employers/apprenticeship/

Closing this
