### ISSUE TITLE
Wrong Content on Employer Facing - "Make a Hiring Commitment"

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1524]
If you click "Make a Hiring Commitment" on the "Employer Landing Page" (https://staging.vets.gov/employment/employers) you end up, incorrectly going to this page:  https://staging.vets.gov/employment/commitments 

Instead of this page:
https://staging.vets.gov/employment/employers/20/edit#hiring-commitments

....which should include this content somewhere on this page - preferably the top.  
[Jobs_EmployerCommitments_20160325 (1).docx](https://github.com/department-of-veterans-affairs/vets-website/files/190073/Jobs_EmployerCommitments_20160325.1.docx)

**Comment by emilyville** [comment]
Cool, we haven't made any changes to the employer landing page yet (since it's in VEC) but when we do it can link more correctly. 

I actually think there's no reason we _need_ login on this page, so we could move it over to vets-website. Is there a copy doc for the employer landing page @rcarthur? I don't see one in pivotal.

**Comment by emilyville** [comment]
Actually, now that I look at this more, I am not following.

This is the Make a Commitment Page, as far as I can tell nothing incorrect is happening to have us send you here when you click "make a commitment"
https://staging.vets.gov/employment/commitments

The link you're saying is correct does not work for me:
https://staging.vets.gov/employment/employers/20/edit#hiring-commitments

I will add this copy to the former page, the employer commitments page.

**Comment by emilyville** [comment]
Creating an issue to update copy on the commitments page and assigning this to @mariana-almeida  as an IA issue.

**Comment by rcarthur** [comment]
@emilyville @mariana-almeida  
The confusing thing is that this page:
https://staging.vets.gov/employment/commitments
....actually has two elements to it.  You can "edit your profile" or "make a hiring commitment".  IMO, it should either be one or the other.

It seems weird to me that the result of the users decision to heed a call to action ("Make a Hiring Commitment"!!) is a page that displays the hiring commitments that others have made (https://staging.vets.gov/employment/commitments) ---- and then makes you click AGAIN to third page (https://staging.vets.gov/employment/employers/20/edit#hiring-commitments) that labelled "Edit Your Profile", which does not match the language that you just clicked to arrive at that page.

**Comment by rcarthur** [comment]
Copy for the "Employers Landing Page"
[30 Jobs_ForEmployers_20160303_concurrence_edits_incorp.docx](https://github.com/department-of-veterans-affairs/vets-website/files/191848/30.Jobs_ForEmployers_20160303_concurrence_edits_incorp.docx)

**Comment by mariana-almeida** [comment]
User flow goes like this: 
Make a hiring commitment box on the Employer landing page > Learn about what it means to make an commitment > Log in > make the actual commitment (but **create profile first,** then make the commitment)
We need time with @emilyville to go over this page flow and be sure the pages exist in the best way.
