### ISSUE TITLE
Redirect banner for Debt Management Center

### ISSUE THREAD

**Issue by 3obryandogs** [department-of-veterans-affairs/vets-website#15303]
@peggygannon - would you please review the proposed banner for the Debt Management Center? They have requested one to promote that the new debt management will be coming. The wording has received an OK from DMC.  Thanks!

**New tool coming for Veteran debt management**
A new online tool will soon be available to view your debt letters, history, and repayment options online. It will be a quick and easy way to see everything about managing your VA debt in one convenient location. Check back here regularly to find out when it’s available.

**Comment by peggygannon** [comment]
thanks, @3obryandogs where will this banner go?

**Comment by leahkeeler** [comment]
@peggygannon This is the banner for Debtman to inform Veterans that there is a new application. Their admin will take care of posting, we were asked to assist in writing the verbiage.

**Comment by 3obryandogs** [comment]
Top of the current debtman site, I believe. Let me double-check with Leah.

**Comment by peggygannon** [comment]
OK, thank you. Here's my recommendation. I've edited the language to be more active voice. 

@3obryandogs @leahkeeler 



EDITED
**Coming soon: New Veteran debt management tool**

We’ll be launching a new online tool that will let you quickly and easily manage your VA debt. With this tool, you’ll be able to view your debt letters, payment history, and repayment options all in one place. 
Please check back regularly to find out when the tool will be available.

**Comment by leahkeeler** [comment]
So, when the the app is live - keep the same verbiage except change 'launching ' to 'launched' ?

**Comment by 3obryandogs** [comment]
There’s a separate ticket for the launched banner – Peggy is looking at it, too. https://github.com/department-of-veterans-affairs/va.gov-team/issues/16812
