### ISSUE TITLE
The apprenticeship page does not include on the job resources

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1539]
but the link leads you to believe it will. Assigning to you to follow up on, @mariana-almeida 
Should we change the link - or the page?

[Jobs_ApprenticeshipProgram_20160325.1 (1).docx](https://github.com/department-of-veterans-affairs/vets-website/files/190722/Jobs_ApprenticeshipProgram_20160325.1.1.docx)
![screen shot 2016-03-26 at 6 04 15 pm](https://cloud.githubusercontent.com/assets/1307774/14063244/d6b0dc48-f37d-11e5-9736-e1c720f2009b.png)

![screencapture-localhost-4000-employment-employers-apprenticeship-1459040901585](https://cloud.githubusercontent.com/assets/1307774/14063242/c6a15224-f37d-11e5-8616-8d699bc7665a.png)

**Comment by rcarthur** [comment]
The verbiage on the IA is slightly inaccurate.  It should only read, "Establish and Apprenticeship"  --- should not say anything about job resources.

**Comment by gnakm** [comment]
@rcarthur done!

![careers employment sitemap v2](https://cloud.githubusercontent.com/assets/13420618/14085314/2994d750-f4ed-11e5-8a9d-f0db37dc7ab0.png)

**Comment by mollyblake** [comment]
Done!

**Comment by emilyville** [comment]
If everyone is saying done, should this be closed @mollyblake @rcarthur @gnakm ?

**Comment by rcarthur** [comment]
Yes, we can close it....but it should say "Establish an Apprenticeship" -
"an" instead of "and"

**Comment by gnakm** [comment]
That's already been changed. I'm closing this.
