### ISSUE TITLE
rapid transition page in IA

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1541]
I can't find where the rapid transition page in the IA - or any links to it on the job-seeker landing page. 

this is likely an oversight - here is a link to the page:

https://staging.vets.gov/employment/job-seekers/rapid/

The page on staging (at the time of writing this) is broken, I think someone put the copy in the wrong place. I fixed it and here is a screenshot of it in case that's not out yet.

![screencapture-localhost-4000-employment-job-seekers-rapid-1459047982032](https://cloud.githubusercontent.com/assets/1307774/14063605/420845f2-f38e-11e5-8674-3c19efe4de4a.png)

**Comment by rcarthur** [comment]
The screenshot looks correct. Thanks, Emiliy!   

It should be linked from the Job Seekers Landing Page - probably either via some language in the first section "Before You Begin".....or one layer down linked out of the "you plan to leave the service in the next 12 months"

**Comment by rcarthur** [comment]
@mariana-almeida @emilyville @mollyblake @kellyskennedy 
As per conversation with Mariana, we are going to kill "Rapid Transition" page....while making sure that all relevant content is reflected in "Within 12 Months of Leaving Active Duty", which is the page that we are keeping.

**Comment by emilyville** [comment]
ok- sounds good! I will remove this page and close out the issue.
