### ISSUE TITLE
Fonts on non-retina displays aren't anti-aliased

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#1552]
![screen shot 2016-03-25 at 3 12 49 pm](https://cloud.githubusercontent.com/assets/144579/14085088/ba197be8-f4d2-11e5-8991-642e8ed01605.png)

This is on a Mac, running Chrome 49.0.2623.87 (Official Build) (64-bit) on an external (non-retina) monitor.

@webinista suggests 
```
adding `-webkit-font-smoothing: antialiased` helps for chrome/safari
```

which makes me think we need to use a bourbon 4.0 mixin or upgrade to bourbon 5.0 and use auto-prefixer to handle the vendor prefixes in our CSS.

**Comment by webinista** [comment]
We shouldn't apply it globally, because it's a [potential usability/readability problem](http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/)). It's something that happens with light text on dark backgrounds. See #1555 for more.
