### ISSUE TITLE
Spouses and Family Members - path incorrect

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1553]
@emilyville @mariana-almeida  In accordance with IA, this page should be linked via piano key on the landing page.  

https://github.com/department-of-veterans-affairs/vets-website/blob/jobs-employment-v2/_employment/job-seekers/family-members.md

**Comment by emilyville** [comment]
@rcarthur when you say the path is incorrect I am confused. There is no piano key on the landing page. do you mean there should be a piano key added to the landing page that sends you to the spouses and family members page?

**Comment by emilyville** [comment]
also it looks like this is a duplicate issue of #1554. @rcarthur please verify and close if that is the case.

**Comment by rcarthur** [comment]
Yes, that's correct. #1554 handles it.  

Thank you, Emily!
