### ISSUE TITLE
Landing page needs piano keys

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1554]
@emilyville 

The landing page....- https://staging.vets.gov/employment/
....should have piano keys for:
1)  Spouses and Family Job Seekers  
2)  Start or Grow Your Business

Do you concur @mariana-almeida?

**Comment by mariana-almeida** [comment]
Agreed. Thank you!

**Comment by emilyville** [comment]
Assigning to @kantrowitz !

There is a piano key for this on the job-seekers.md page 
https://staging.vets.gov/employment/job-seekers/

That should be moved to the main landing page (before you select job seeker or employer)
and then add another piano key link to start or grow your business.

ping me if you need help, and assign the PR to me to review!
