### ISSUE TITLE
Enable retries for Cypress on CI

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/vets-website#15688]
Cypress 6 supports retries of failing tests without having to use a plugin. In order to reduce the amount of false failures from flaky tests, we need to enable retries on Jenkins and CircleCI. This should reduce the number of failing builds we see on CircleCI and Jenkins, which will have a significant, positive effect on commits going through the CI pipeline.

[Cypress documentation for retries](https://docs.cypress.io/guides/guides/test-retries.html#Global-Configuration)

**Comment by pjhill** [comment]
Although it would be logical to create and work an issue related to Cypress in `vets-website` since this is where Cypress lives, all the project management activity takes place in `va.gov-team`. Please recreate this ticket with the same details in `va.gov-team`.
