### ISSUE TITLE
Entrepreneurship Counseling page needs to be stubbed

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#1580]
It appears that Entrepreneurship counseling page needs to be stubbed (or re-stubbed).  Pivotal number 
#112172071.

Thanks!

**Comment by kantrowitz** [comment]
@mollyblake Please take a look. If it needs further adjustment, just let me know.

**Comment by mollyblake** [comment]
Hi @kantrowitz . Is the page on heroku? I don't see it on staging. Thanks!

**Comment by kantrowitz** [comment]
Here's the link. Had to resolve a conflict. 

https://staging.vets.gov/employment/job-seekers/start/counseling/

**Comment by mollyblake** [comment]
Thanks @kantrowitz ... @rcarthur -- the breadcrumb might not need to include the "START" .. can you weigh in?  THANKS
<img width="975" alt="screen shot 2016-03-30 at 8 53 09 pm" src="https://cloud.githubusercontent.com/assets/16196072/14165018/84cdd5e0-f6b9-11e5-944a-4b1868aff357.png">

**Comment by rcarthur** [comment]
Yep - should be "Start or Grow a Business" - but now we are going way too
long.

I think one way to do it is have the bread crumbs show

Job Seekers - Entrepreneurship - Counseling

(This is slightly cheating I know - but it's better than what's there now).

**Comment by emilyville** [comment]
Breadcrumbs are automagical. Once you decide what to do check out @webinista awesome documentation of how they work in the read me to fix and send to her for review.

**Comment by rcarthur** [comment]
@kantrowitz @bethpotts @molly  Let's talk about this later this morning.

**Comment by mollyblake** [comment]
I love the word automagical @emilyville

**Comment by molly** [comment]
Pinging @mollyblake for you because I have no idea what this is :smiley:

**Comment by emilyville** [comment]
@mollyblake or @rcarthur can you clarify this or close it out? I am confused by what needs to happen.

**Comment by mollyblake** [comment]
@emilyville I will close it. No further work needed. Thanks!
