### ISSUE TITLE
Resume Builder Page

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1584]
The following content should go at the top of this page:https://staging.vets.gov/employment/job-seekers/create-resume

Build a Profile & Résumé
The Veterans Employment Center™ (VEC) can help you build your profile so potential employers can find you on vets.gov. This profile can then be downloaded into a civilian or federal résumé.Your public job-seeker profile will be stored on vets.gov, and you can update your information as often as needed. 

Manually enter your information into the form fields below, or use the Auto-fill from LinkedIn button to pre-populate some of the fields from your LinkedIn account. 

@bethpotts @mariana-almeida @mollyblake @kellyskennedy

**Comment by emilyville** [comment]
to be completed with https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/254

**Comment by emilyville** [comment]
This is merged, so calling it done!
