### ISSUE TITLE
Tables from CMS are all missing bottom row.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/vets-website#15910]
Currently tables generated from tablefields in the CMS are missing their bottom row.

Example:  CMS on left.  Prod on right.
![image](https://user-images.githubusercontent.com/5752113/106652490-8a379c00-6563-11eb-859a-8be6e68a690f.png)

It comes down to this logic in the template which blindly discards the last element in the array, assuming it is a caption.
https://github.com/department-of-veterans-affairs/vets-website/blob/07cf3654bd0e7fd59f261880b70252bc4cd9a04c/src/site/paragraphs/table.drupal.liquid#L45

This stems from what was a bug in the CMS where the contrib tablefield module  was incorrectly putting the caption value into the rows array.  This has been fixed upstream so the caption now lives as the same level as rows, not within the rows. 

Unfortunately this upstream fix has now made the logic in the template flawed.  The caption has to be grabbed one level up (might need an alteration to the GraphQL)  and the rows logic should no longer throw away that last row.

**Comment by kelsonic** [comment]
@brianalloyd, Nick's PR was merged so I think we can close this for now until it comes back up 👍
