### ISSUE TITLE
VR&E Coming Soon page needs stub

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#1599]
Please create stub for VR&E Coming soon page. Content is created and the page is loaded into pivotal. Content is also pasted here for convenience: 

Coming Soon: Information about VA's Vocational Rehabilitation and Employment Program (VR&E). If you have a service-connected disability that limits your ability to work or prevents you from working, VR&E can help you, and in some cases your family members, explore career options and receive additional training.

**Comment by mariana-almeida** [comment]
Hi Molly, I don't think we need this page. It was on the IA for informational purposes. 

I find these "coming soon" pages to be not very useful to users. Plus they create added pressure on the team to deliver something immediately. Thoughts?

**Comment by rcarthur** [comment]
That makes sense - especially since we're not taking C&E live this week.

**Comment by mollyblake** [comment]
The only problem @rcarthur and @mariana-almeida is that we need to send people somewhere that relates to VR&E - we have links to VR&E on a lot of pages so it's either a "coming soon" page or a VA.gov page.  I feel like we should pick one and go with it globally.

**Comment by mollyblake** [comment]
This page is not going to be created.
