### ISSUE TITLE
Make crisis line look like a button

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1606]
Use @gnakm mockups from this issue:

https://github.com/department-of-veterans-affairs/vets-website/issues/1312

and switch to the copy like the button as well!

tagging @mariana-almeida and @koconnor719 for awareness :)

**Comment by koconnor719** [comment]
@gnakm check w/ @mariana-almeida  on this--we have other crisis line changes in progress as well:)

**Comment by emilyville** [comment]
I'm closing this because it's been consolidated into #1617
