### ISSUE TITLE
Copy change to make this list less overhwhelming?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1618]
![screen shot 2016-03-29 at 7 35 49 pm](https://cloud.githubusercontent.com/assets/1307774/14130157/bbbf14ee-f5e5-11e5-96f9-62bf15cf34fc.png)

This block of text is kind of overwhelming. Could we parse it a little more for users? Thinking we could change to 

Yes if, 
You are the child or spouse of a Servicemember
- option
- option 
- option

You are the child or spouse of a Veteran
- option 
- option 
-option

- couple more options.

if you agree, feel free to assign to me!

**Comment by mollyblake** [comment]
@emilyville what page is this?  I'm happy to look over the content to see if we can combine some bullet points. @mariana-almeida

**Comment by emilyville** [comment]
Doh! forgot the link. https://www.vets.gov/education/survivors-dependent-assistance/

Thanks @mollyblake !! :dancer:

**Comment by mariana-almeida** [comment]
Good call out, @emilyville! We love ta chunk da text.

**Comment by emilyville** [comment]
Assigning to you, @kantrowitz

**Comment by kantrowitz** [comment]
Need the chunked text.
