### ISSUE TITLE
Escalation path for force-pushing changes to master

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/vets-website#16248]
Until we have app isolation, we need an escalation path for small, low-risk changes to be force-pushed to master without triggering the entire hour-long CI flow.

Examples of situations where this could be useful:

- disabling a flaky test that's blocking all teams
- pushing a hotfix to production
- fixing an issue with the build

**Comment by mpelzsherman** [comment]
@drorva @f1337 Any thoughts on this?

**Comment by f1337** [comment]
We cannot allow force pushes to master. The solution is to reduce the build time.

**Comment by mpelzsherman** [comment]
Thanks @f1337 . I'll close the ticket and inform the VSA team.
