### ISSUE TITLE
Hiring Commitment Mockup 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1624]
This will go with new copy from issue #1600 
![hiring commitment](https://cloud.githubusercontent.com/assets/13420618/14154306/bcce27e0-f689-11e5-8886-a233c768aefe.png)
Woohoo for numbers!
reference: https://vets-website-pr-1600.herokuapp.com/disability-benefits/apply-for-benefits/

**Comment by rcarthur** [comment]
Nice!

**Comment by emilyville** [comment]
should be done when this is merged pending some copy reviews, https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/256
