### ISSUE TITLE
sweep to make text width consistent in new careers and employment branch

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1634]
Let's use the new text widths here consistently!

also make sure to make a pr off of the jobs-employment-v2 branch

**Comment by webinista** [comment]
@emilyville I know that we have a maximum text width, but do they apply to all text? Do we have guidelines about which blocks of text they apply to? Am I making sense at all?

**Comment by emilyville** [comment]
yes! you are making sense. I am following the USWDS specification and honestly haven't implemented it myself and have just been hacking at setting column widths at medium-9, which isn't ideal. 

I think we can use usa-content - 

> Line length: Controlling the length of lines of text in extended copy makes reading more comfortable by helping readers’ eyes flow easily from one line to the next. Somewhere between 50 and 75 characters per line is broadly considered to be a readable line length, while 66 characters is considered the ideal. Other factors beyond line length also affect reading comfort. Text with more space between lines can have somewhat longer line length. Also, contexts in which users will not be reading long passages of text (such as footnotes or alerts) can safely be set with somewhat longer lines as well.

more here: https://playbook.cio.gov/designstandards/visual-style/

I'm happy if you want to make a call on the best way to standardize - or we @gnakm or I can make a more global decision.

**Comment by gnakm** [comment]
@webinista 
We prototyped to test the line length on this page https://vets-website-pr-1459.herokuapp.com/education/gi-bill/ , which was set to 53rem (approx. 75 character length) but after receiving feedback and talking about it, we think 70rem (approx. 100 character length) is a better decision. This will be for all blocks of texts. We are going add this to roadrunner. I, too am happy if there is a better way to standardize.

**Comment by emilyville** [comment]
This is done!
