### ISSUE TITLE
Landing Page should have a smaller box link for "Military Spouse and Family Job Seekers"

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1635]
https://vets-website-pr-1600.herokuapp.com/employment/

According to IA, this page should have a third option for "Military Spouse and Family Job Seekers"

Also, the VEC button is supposed to be gone, right?

**Comment by emilyville** [comment]
@rcarthur I think this was just not out yet:
https://staging.vets.gov/employment/

Verify this is what you meant and please if so go ahead and close!

**Comment by rcarthur** [comment]
Yes, it looks good!
