### ISSUE TITLE
The underscore should be a dash in this link: /employment/job_seekers/skills-translator

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1638]
The content team was given a list of 5 links to use for tools. This was one of them. Albert and I were looking at why tests failed on a recent PR, and he discovered this tiny error. Can a global fix be made for this since we have this link, incorrectly constructed, on other pages as well? So, from:
/employment/job_seekers/skills-translator

To:
/employment/job-seekers/skills-translator

Many thanks!!

**Comment by emilyville** [comment]
I believe I have already fixed this. Are there more?

**Comment by emilyville** [comment]
I do not have time to get to this tonight  - @ayaleloehr or @cfeeney-va if you have a chance tomorrow, might be good to double check I got all of these.

**Comment by ayaleloehr** [comment]
This was my fault initially on creating the typo where I put `_` instead of `-` in job-seekers. Sorry about that. At present, there are zero instances of the text `job_seekers` in the jobs-employment-v2 branch, so this is taken care of and I'm going to close this issue.
