### ISSUE TITLE
Add Blue Box Unemployment Support

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1654]
https://employment.vets.gov/employment/job-seekers/unemployment-support/

**Comment by emilyville** [comment]
Like this @kantrowitz 
![screen shot 2016-04-04 at 3 38 18 pm]

From here: (https://cloud.githubusercontent.com/assets/1307774/14260825/5c30b146-fa7b-11e5-9852-529ff0e030a6.png)

https://employment.vets.gov/disability-benefits/conditions/
