### ISSUE TITLE
Military Skills Translator Link Repeated

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1655]
https://employment.vets.gov/employment/job-seekers/

The link for #2 Civilian Occupation Translator and #3 Military Skills Translator both link to the military skills translator. Could we change the copy or just get rid of #2? Once the change is made, please assign it back to me! Thanks.

**Comment by rcarthur** [comment]
@mollyblake  - could you look at this?

**Comment by mollyblake** [comment]
@gnakm @rcarthur the current version employment/job-seekers/ is correct -- "interest profiler" goes to the employment/job-seekers/interest-profiler/ and "military skills translator" goes to employment/job-seekers/skills-translator

**Comment by rcarthur** [comment]
Thanks Molly!
