### ISSUE TITLE
Refactor body.home .navigation, body.fourohfour .navigation selector

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#1672]
This is a little bit of a design question. The [home page](https://www.vets.gov/) and the [404 error page](https://www.vets.gov/404) are very similar. The big differences are:

- the amount of padding above and below that row of navigation cards. 
- the missing rule line underneath "Quick Links" 

Making the designs more consistent would save a few bytes. Okay to proceed?

**Comment by webinista** [comment]
(@gnakm Assigning to you for design consideration. You can pass the task back to me once there's a yay or nay about that change.)

**Comment by gnakm** [comment]
@webinista Do you mean design considerations to make it better or for me check that it's consistent? It looks good to me.

**Comment by webinista** [comment]
@gnakm Design considerations to make it better. Screenshots to illustrate:

#### 404 page with current padding (3em) above and below the card navigation:

![vetsgov404](https://cloud.githubusercontent.com/assets/354277/14573003/058f53bc-0307-11e6-8e8d-dc1335bb8463.png)

#### 404 page with the 1.5em padding above and below the card navigation (consistent with the home page)

![vetsgov404-after](https://cloud.githubusercontent.com/assets/354277/14573009/2137d1fc-0307-11e6-8a47-e0d38d61af67.png)

**Comment by gnakm** [comment]
@webinista I like the 2nd one. (1.5em). Could we get the the missing rule line underneath "Quick Links?"

**Comment by webinista** [comment]
@gnakm Yep. On it! Thanks :-)
