### ISSUE TITLE
Change "Search for help near you" in jobs branch

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#1682]
Should read "Search Accredited Attorneys, Claims Agents, or Veterans Service Organizations (VSO) Representatives." see #605. Can probably `git cherry-pick` from a4fa61e14b199a5cec458426033833c517b37b0d

**Comment by ayaleloehr** [comment]
@webinista looks like this might be done already and just didn't get closed?

**Comment by mariana-almeida** [comment]
@ayaleloehr to follow up with @webinista
