### ISSUE TITLE
NOD: Add unit tests & cleanup

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-website#16869]
## Description

Finish up work on the Notice of Disagreement form.

## Tasks
- [ ] Code cleanup
- [ ] Add better code coverage (unit tests)
- [ ] Check accessibility
- [ ] Ensure form with mock data submits to endpoint after updates (see #16868)

## Acceptance criteria
- Tasks completed

**Comment by vhenry07** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #23526](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23526) via [**ZenHub**](https://www.zenhub.com/)
