### ISSUE TITLE
Commitments Number too big

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1690]
@emilyville I did not account for the actual growth of number. Would decreasing font size for all 3 boxes be the best way to go about this? Wonder if you have a better solution in mind.
<img width="1435" alt="screen shot 2016-04-01 at 9 52 39 am" src="https://cloud.githubusercontent.com/assets/13420618/14208890/a4dfbefc-f7ef-11e5-8a61-241e243a83b3.png">

**Comment by ayaleloehr** [comment]
FWIW, I assume we're not going to go past a 7 digit number, but it would be nice to be able to add in commas at some point without breaking it.

**Comment by ayaleloehr** [comment]
Also this is the same as https://github.com/department-of-veterans-affairs/veterans-employment-center/issues/259

**Comment by gnakm** [comment]
@ayaleloehr Jinx! Closing now. 
#259
