### ISSUE TITLE
something funny happening here

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1691]
https://www.vets.gov/playbook/product-methodology/

![screencapture-www-vets-gov-playbook-product-methodology-1459528652509](https://cloud.githubusercontent.com/assets/1307774/14213551/6df884f2-f7ed-11e5-8fc5-e59a74cb7aaa.png)

**Comment by emilyville** [comment]
I actually can't remember what the intended look was - I think the color may have only been along the side? @gnakm do you know?

**Comment by gnakm** [comment]
yowsa! I think there were 3 full color boxes with text inside, instead of color just along the sides.

**Comment by webinista** [comment]
😭

**Comment by emilyville** [comment]
FWIW I have no objections to making this page less of a snowflake, and removing things that aren't used elsewhere. Not because it isn't special - but because it might be soon brought into a new roadrunner land... whatever that might mean.

**Comment by webinista** [comment]
It can be fixed with a minimum of additional CSS. We can do that in the meantime, and then figure out how to make it less of a snowflake.
