### ISSUE TITLE
Error: Unknown option '--env.api'

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/vets-website#16915]
When trying to pass any --env.* flags, it will error with 
[webpack-cli] Error: Unknown option '--env.api'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Should we update the readme file to support the correct flag values?

**Comment by theodur** [comment]
Closing this ticket since the current README shows the correct option usage
