### ISSUE TITLE
Yellow Box -- VECI

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#1694]
@emilyville can we please write out **Veterans Economic Community Initiative** in the Yellow Box on the this page https://employment.vets.gov/employment/job-seekers/veci/

THANKS!!!

**Comment by emilyville** [comment]
Assigning to @webinista - if you want to also rope in @kantrowitz and show her the ropes on this sort of change go for it!

**Comment by emilyville** [comment]
Also, this will be a breadcrumb change off of the jobs-employment-v2 branch. (You probably know this, but just in case.)
