### ISSUE TITLE
Style Guidance on a landing page with external links.

### ISSUE THREAD

**Issue by Drakenhart** [department-of-veterans-affairs/vets-website#1707]
Issue: Site that requires a landing page to help users find information not within the site. 

Clarification: Due to the high levels of internal search queries for benefits (and specific forms) a landing page was devised to help guide users to what they were looking for specifically.

Rather then send them to the home page of a given site, certain of the most searched items were taken and made links. Some of them are links to specific home pages (ie Medline Plus).

I haven't found anything within the current Playbook that address this specific issue. Seeking Guidance on specific style or choice of navigational options so our project more closely matches with vets.gov styles.

**Comment by koconnor719** [comment]
Thank you for your feedback. Can you provide additional details on your question/suggestion?

**Comment by Drakenhart** [comment]
It was in regards as to what we could use. Should we use the definition lists, cards, or plain links, considering the page is a landing page to help direct people to where they need to go.


However, I think at this point it's a moot point, considering the changes that have been made to date to the vest.gov project. :) :+1:
