### ISSUE TITLE
Line Length Change in Careers and Employment Pages

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1739]
Change _all_  line lengths in Careers and Employment pages to fit 100 characters.

Here is an example of a current page that does this: https://employment.vets.gov/employment/job-seekers/

Context: Currently the text on all the pages are super long and isn't user friendly. We plan on making a global change but want to start off by standardizing the careers and employment section.

**Comment by emilyville** [comment]
My random 2 cents: You may want to break this into a few pull requests

Here is a PR @webinista did to make it correct on one page:
https://github.com/department-of-veterans-affairs/vets-website/pull/1700

And I would use this page as a guide: https://employment.vets.gov/employment/employers/support-veteran-employees/
