### ISSUE TITLE
Edits to the Resume Builder page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1742]
The following appears on multiple pages and we need to lowercase the word Federal in every occurrence:
(This section is required for federal job applications)

Orange stripe header needs accent marks in the word Résumé.

I get an error message when I click on "Sign in" here:
Already have a profile saved on vets.gov? Sign in to access it. 

In the below sentence, change the word "use" to "click"; add the word "blue" before the name of the button; and remove the hyphen from "pre-populate." This sentence should now look like this: Manually enter your information into the form fields below, or click the blue Auto-fill from LinkedIn button to prepopulate some of the fields from your LinkedIn account.

**Add the Basics** (capitalize the word Basics)
- Enter your name and email (add "and email")
- Your name (lowercase the n in name)
- Your email (lowercase the e in email)

**State Your Objectives**
Change the text to say this: Provide 1-2 sentences. 
(delete "about your qualifications and career objectives" since we've already said this in the text above.)

**When can you start work?** (change this header to say **Your Start Date**)
Change the text just below this header to say: Enter your available start date. 
(delete "When can you start work?")

**Your Civilian Skills**
Change the text just below this header to say: Provide your civilian skills. Add as many as necessary with the help of the autocomplete field. 
(replace the first "Add" with "Provide"; replace "by using" with "with the help of"; and add a period at the end)

**Education and Training** (replace the ampersand with "and")
Change the text just below this header to say: Provide your education information. Add as many credentials as necessary by clicking Add Education Experience below. 
(replace the first "Add" with "Provide"; add the word "credentials"; replace "using" with "clicking"; delete "the"; capitalize the name of the link--Add Education Experience; replace the word "link" with "below")

**Military Service**
Change the text just below this header to say: Provide your military information. Add as many occupations as necessary by clicking Add Military Experience below.
(replace the first "Add" with "Provide"; add the word "occupations"; replace "using" with "clicking"; delete "the"; capitalize the name of the link--Add Military Experience; replace the word "link" with "below")
Capitalize only the first word of the descriptors above the fields:
Military occupation code
Duty station
Branch of service
Describe your position responsibilities
Start date
End date

**Work Experience**
Change the text just below this header to say: Provide your employment information. Add as many positions as necessary by clicking Add Work Experience below.
(replace the first "Add" with "Provide"; add the word "positions"; replace "using" with "clicking"; delete "the"; capitalize the name of the link--Add Work Experience; replace the word "link" with "below")
Capitalize only the first word of the descriptors above the fields:
Describe your position responsibilities
Hours/week
Start date
End date

**Volunteer Experience**
Change the text just below this header to say: Provide your volunteer experience. Add as many positions as necessary by clicking Add Volunteer Experience below.
(replace the first "Add" with "Provide"; replace the word "work" with "volunteer"; add the word "positions"; replace "using" with "clicking"; delete "the"; capitalize the name of the link--Add Volunteer Experience; replace the word "link" with "below")
Capitalize only the first word of descriptors:
Start date
End date

**Awards**
Change the text just below this header to say: Enter your award information. Add as many awards as necessary by clicking Add Award below.
(add the word "awards"; replace "using" with "clicking"; delete "the"; capitalize the name of the link--Add Award; replace "link" with "below")
Capitalize only the first word of descriptors:
Name of award
Awarding organization
Date received

**Professional Affiliations**
Change the text just below this header to say: Enter your professional affiliations. Add as many affiliations as necessary by clicking Add Affiliation below. 
(replace "job title information" with "professional affiliations"; add "Add as many affiliations as necessary by clicking Add Affiliation below.")
Capitalize only the first word of descriptors:
Affiliated organization

**References**
Change the text just below this header to say: Provide your professional references. Add as many references as necessary by clicking Add Reference below.
(replace the first "Add" with "Provide"; add the word "references"; replace "using" with "clicking"; delete "the"; capitalize the name of the link--Add Reference; replace "link" with "below")

**Location Preference**
Change the text just below this header to say: Enter your location preferences below. Add as many locations as necessary by clicking Add Location below.
(add the word "locations"; replace "using" with "clicking"; delete "the"; delete "another"; capitalize "Location"; replace "link" with "below")
Capitalize only the first word of descriptors:
Desired location

**Other**
Change the text just below this header to say: Enter optional additional information to help potential employers find your profile.
(replace "assist" with "help"; delete "in"; replace "finding" with "find")

**Save as Draft** (lowercase "as")

**Comment by ayaleloehr** [comment]
Viewable at https://employment.vets.gov/employment/job-seekers/create-resume
