### ISSUE TITLE
List of links and descriptions

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1752]
Careers and Employment Pages:
https://employment.vets.gov/employment/job-seekers/alternative/
https://employment.vets.gov/employment/job-seekers/career-fairs/

The list can be in alphabetical order for easier findability 

This is pretty much like gov.uk but it's super easy to read. Downside is, it's not aesthetically pleasing.
![style 1](https://cloud.githubusercontent.com/assets/13420618/14304098/0608f234-fb7e-11e5-8a8b-b05be152388d.png)

This is the UI component that is already existing. Example:https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/
Downside is that we would have the edit all the description content to make the style consistent. 
![style 2](https://cloud.githubusercontent.com/assets/13420618/14304119/298bf17a-fb7e-11e5-8b26-03f8e2930556.png)

**Comment by gnakm** [comment]
@emilyville Would love feedback!

**Comment by mollyblake** [comment]
@rcarthur @bethpotts I really like the second one with the boxes. We will need to adjust content.

**Comment by gnakm** [comment]
Punting on this because of changes in the near future!
