### ISSUE TITLE
New Text Links

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1754]
https://employment.vets.gov/employment/job-seekers/

For the purpose of findability and scanability, we need to link the texts better.
Currently this page was designed for people who need help getting started but we also have to account for people who are looking for links hence, we need to make the text links more comprehendible. This page is already content heavy so the text links have to work more as highlights without context.

ex. My eyes automatically go to read "a few simple steps" and "new career" without knowing any context. Could we give the links more context at first glance so users can know exactly what to expect without having to read all the content?
<img width="451" alt="screen shot 2016-04-05 at 10 55 17 pm" src="https://cloud.githubusercontent.com/assets/13420618/14304526/839fabfe-fb81-11e5-973e-9f147c3e0e3b.png">
<img width="415" alt="screen shot 2016-04-05 at 10 55 24 pm" src="https://cloud.githubusercontent.com/assets/13420618/14304525/839f1d1a-fb81-11e5-9724-26256afdff28.png">

I would go ahead and change the text links but this actually requires edits in the sentences. Could somebody in the content team kindly review this page again? We're really getting there team!

**Comment by mollyblake** [comment]
@bethpotts let's you and I work on this today! @gnakm  we are on it. Standby!

**Comment by gnakm** [comment]
Thanks! Just saw this. Good example of this issue: https://www.healthcare.gov/health-coverage-exemptions/exemptions-from-the-fee/

**Comment by ayaleloehr** [comment]
@bethpotts @mollyblake does this need to be done before launch?

**Comment by mollyblake** [comment]
Thanks @gnakm we worked on this page and made some changes!
