### ISSUE TITLE
Less Than 1 Year Callout Box

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1756]
https://employment.vets.gov/employment/job-seekers/less-than-one-year/

- Could we put these in a callout box 

**Who should read this?**
Servicemembers, and their spouses, who are within one year of separating from the military.
**Why should you read this?**
You can take certain steps to improve your chances of moving smoothly and successfully into civilian life.

- For consistency purposes, could we have them styled just like issue #1753
<img width="754" alt="screen shot 2016-04-05 at 10 43 58 pm" src="https://cloud.githubusercontent.com/assets/13420618/14305019/4f9c4d4e-fb86-11e5-9c10-31fa3ea7d8b6.png">

- Take out line break between the top section and steps

**Comment by mollyblake** [comment]
@gnakm Yes!  Thanks
