### ISSUE TITLE
Tweaks to Job Search Page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1757]
I want to call this a love tap? Just want to make sure we don't over use our callout boxes. What about a line break instead of highlighting the featured jobs section?
![love bump](https://cloud.githubusercontent.com/assets/13420618/14305109/23927c2c-fb87-11e5-947a-6395ac752ab0.png)

@emilyville

**Comment by mollyblake** [comment]
@gnakm yes, the line break looks great!  Much easier than the boxes.  THANKS!!!

**Comment by emilyville** [comment]
approved! I don't know why this has been blue.

**Comment by ayaleloehr** [comment]
@gnakm If this still needs to be done, can you add it on the VEC repo?

**Comment by gnakm** [comment]
Switched to VEC repo. New issue #279
