### ISSUE TITLE
Add Lynda link and details

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#1759]
Lynda is a new no-cost partnership for us (similar to LinkedIn and Coursera, which we already had).  The link for Veterans to get one year of free courses is: https://specialedition.linkedin.com/veteran-lynda-access/

I believe this belongs on the job seekers landing page (/employment/job-seekers) probably right next to the Coursera link, but will leave it up to @mariana-almeida and @rcarthur to make that call and get it in there. 

I assume we'll need some content surrounding it, so here is a first attempt: "Free Lynda Subscription: Lynda.com offers thousands of online courses to help individuals learn business, software, technology, and creative skills. Veterans can sign up for a free, one-year subscription." But will definitely leave that to the content team to decide on.

**Comment by ayaleloehr** [comment]
Update: the link is actually going to be https://veterans.linkedin.com which sends you to a link to get both LinkedIn and Lynda memberships.  Can this be added to the "Consider furthering your education" section of the Job Seekers landing page?  @rcarthur @mollyblake

**Comment by rcarthur** [comment]
@ayaleloehr  - added "Learn transition techniques plus business, software, technology, and creative skills with a free one-year subscription to online courses with [Linked-In's Lynda](https://veterans.linkedin.com/)."  Sound good?

**Comment by rcarthur** [comment]
Content is live on staging.  Closing issue.
