### ISSUE TITLE
Edits to the Careers and Employment: Commitments page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1761]
https://employment.vets.gov/employment/commitments
I can't find this in the repo--please point me there if I'm mistaken! Or if I'm right to pass along my edits, here you go:
1) Replace intro text with the following:
Veterans and military family members have consistently proven themselves to be reliable, independent, and hardworking team members. Veterans also have soft skills such as problem solving and creativity that can benefit a company’s bottom line. By signing up and making a commitment, your company will stand out to candidates eager to enter the civilian workforce.

2) Can you add commas for "total positions committed to hire" that currently is 1056972, so that it looks like this?: 1,056,972

3) In the table, please replace "By date" with "Target hire date"?

4) Please add the word "a" before "spreadsheet": Download all commitments as spreadsheet

**Comment by emilyville** [comment]
Sure thing. It's in the VEC repo.

@ayaleloehr - don't know how hard it would be to add a comma.

**Comment by ayaleloehr** [comment]
Fixed in PR 269 in the VEC repo.
