### ISSUE TITLE
Remove or redirect disability-benefits/rates/ to disability-benefits/ratings/ [Was: Page title link is the wrong color/size]

### ISSUE THREAD

**Issue by kantrowitz** [department-of-veterans-affairs/vets-website#1762]
https://www.vets.gov/disability-benefits/rates/

Appears like this:
![image](https://cloud.githubusercontent.com/assets/17709320/14330623/5c718d2a-fc0f-11e5-9337-0c067cdb24da.png)

Should appear like this?

![image](https://cloud.githubusercontent.com/assets/17709320/14330644/704c0fd2-fc0f-11e5-91b7-9813016d82d9.png)

Sending to you @gnakm for design confirmation. Reassign to me if this does in fact require fixing.

**Comment by webinista** [comment]
It's a simple fix to make. Requires adding a class name. _However_ the template is hard to find. If you know where it is, please tell me.

**Comment by webinista** [comment]
@kantrowitz How did you get to this page?

**Comment by kantrowitz** [comment]
1. Go into the search bar. 
2. Type in "Are you service disabled?"
3. It's the 4th one down.

**Comment by webinista** [comment]
Ah... Ok. I think that's a page that should be deleted from S3. It's not linked from anywhere and shouldn't exist.

**Comment by emilyville** [comment]
I think @ayaleloehr or @awong-dev should be able to delete this one from S3, and hopefully we'll fix search soonish, especially to include Careers and Employment. Could either of you take that on?

**Comment by ayaleloehr** [comment]
Even if we delete this page from S3, until search is updated, I believe this will still exist in the search results. The question then becomes, in the mean time:
- Is it better to have search point to a page that doesn't exist, so it will return a 404?
OR
- is it better for this page to still exist and only have search point to it?

**Comment by emilyville** [comment]
Or... could we have it redirect?

Either way, not a huge deal.

**Comment by webinista** [comment]
Re-assigning, since this gets into search and areas that I do not understand.

**Comment by ayaleloehr** [comment]
Yea, this can be assigned to me. @plusjeff and I need to do something about search soon, so when we do I will make sure this gets resolved.

**Comment by ayaleloehr** [comment]
Page deleted. Will still show up in search for the time being (being tracked in another issue), but gives a 404 now instead of showing the broken page.
