### ISSUE TITLE
Further clarify breadcrumbs documentation

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#1770]
See the discussion in #1738 and #1694

**Comment by Drakenhart** [comment]
I had some questions about the use of h-tags in the breadcrumb. Having that clarity would help.

I think my perk of curiosity comes from 2 items specifically. The use of H tags in the breadcrumb trail (not a typical design pattern and not normally suggested as one) is one of them. As well as the large scale size of it so it dominates the page as if it were a main navigation, rather then a more common secondary and supplemental navigation.

It caught me off guard, and I was curious as to the thought behind it. I'm not against new design patterns. They happen and many times for the good. But I like to understand the mental process behind them (more so I can explain them to clients if/when the pattern is adopted). ^.^
