### ISSUE TITLE
Support Veteran Employees shouldn't have employer login button

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#1771]
Green button in the top right corner here: https://employment.vets.gov/employment/employers/support-veteran-employees/

This feels strange, especially because on this page in vets-website we don't know if the employer is actually logged in or not. I thought the decision was that from vets-website there shouldn't be any login links but they should instead link to `/employment/employers`, which would then allow employers to log in?  

Assigning to @emilyville for triage or rassignment.

**Comment by emilyville** [comment]
Agreed I meant to remove this! I'll do that now...
