### ISSUE TITLE
Edits for Military Skills Translator page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1777]
https://employment.vets.gov/employment/job-seekers/skills-translator
1) The bolded subhead for the bulleted list needs the word "Military" inserted, like this:
Tips for using the Military Skills Translator:

2) Replace the second bullet point with the following text:
You may add any missing skills by manually searching for skills or qualities not listed by the translator.

3) Replace the third bullet point with the following text:
The skills you select will be imported into the Résumé Builder. Carefully select skills that best fit either a specific job description or the employment sector that interests you.

4) Replace the fourth bullet point with the following text:
Once you have selected your skills, click the green Import into Résumé Builder button and continue to work on your Résumé.

5) Replace the fifth bullet point with the following text:
Know which skills you want to use on your résumé? Skip directly to the Résumé Builder to create a résumé and public profile that employers can search. They can also connect with you directly.

**Comment by ayaleloehr** [comment]
Will be closed via PR245 in the VEC repo.
