### ISSUE TITLE
piano key Skills Translator should be Military Skills Translator

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1780]
We need to add the word "Military." Is it possible to search for all instances of this piano key? Or do I need to click through all the pages to find each instance?

**Comment by emilyville** [comment]
@ayaleloehr just fixed this with this pr https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/275

**Comment by emilyville** [comment]
nevermind - this is fixed on VEC, but not in piano keys. reopening.
