### ISSUE TITLE
Simplify # content .main .section.one ul.plain selector

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#1781]

**Comment by JABiesterfeld** [comment]
Stop fucking sending me EVERYTHING. I WANT NOTHING FROM YOU EVER AGAIN

**Comment by jcmeloni** [comment]
@webinista Does it also address #2506?

**Comment by webinista** [comment]
Yes it does. In fact, I'll close that issue as a duplicate of this one.
