### ISSUE TITLE
Piano Key name change?

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#1789]
Can we do a global change to a piano key name @emilyville ? It currently reads "Interest and Aptitude Profiler" and it should just be "Interest Profiler" as it directs people to the Interest Profiler page?  Does that make sense?  Thanks so much! Everything is looking so great!

**Comment by mollyblake** [comment]
@kantrowitz can you help with this?  THANKS!!!

**Comment by emilyville** [comment]
I can go ahead and take this so it's out for tomorrow!
