### ISSUE TITLE
Production feedback forum link is wacky

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#1791]
It looks like the image below, with two separate links on top of each other:

![screen shot 2016-04-07 at 8 03 16 pm](https://cloud.githubusercontent.com/assets/4719765/14370425/edc7a416-fcfb-11e5-8948-bf91b595c056.png)

**Comment by emilyville** [comment]
This is happening on large screens, looks like the secondary forum link is landing on top of the primary feedback "popup" link.

**Comment by webinista** [comment]
I think updating the CSS to remove that extra-large break point is the best fix. It's odd that it changes after 1600px or whatever.
