### ISSUE TITLE
Remove Text and Link

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/vets-website#1799]
- On this page https://www.vets.gov/education/tools-programs/education-career-counseling/ > under How it works, there is the following text and link: "Apply for free counseling services."

- This link directs to the old PDF method for applying for chapter 36 benefits. 

- Bettye Hodge has provided guidance (concurred by Mike Carr - Robert.Carr@va.gov) that this text and link was to have been supplanted by the green “Apply for Education Benefits” and that this link should be removed. Applicants will apply for chapter 36 benefits via eBenefits/VonApp. 

**Note: 
Mike Carr asks: "Will the vets.gov content have messaging about using the electronic application for Chapter 36 in eBenefits?"**

@koconnor719: Please advise on assignment and labeling of this issue.

cc; @mariana-almeida

**Comment by emilyville** [comment]
I made an issue to remove the link. Apply for education benefits is already on the page, so this issuee should be good to go for everything, other than Mike Carr's question - assigning to Kelly.

**Comment by koconnor719** [comment]
@mariana-almeida if this is not urgent, i suggest just working this through jennifer r when she returns.

**Comment by rickleegit** [comment]
VBA is asking for a timeline for the completion of this copy addition that they can provide to GAO. Possible to provide?

cc; @mariana-almeida @koconnor719

**Comment by koconnor719** [comment]
@rickleegit what is status of this? i'm not sure how i would have any idea about the answer to this question.

**Comment by koconnor719** [comment]
@mariana-almeida can you pls update or close this issue?

**Comment by mariana-almeida** [comment]
Closing. This page was corrected. This page was also reviewed recently by Jennifer Rudisill who made further edits.
