### ISSUE TITLE
Remove old link in education career counseling page

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1800]
On this page:
https://www.vets.gov/education/tools-programs/education-career-counseling

Remove the text and link: "Apply for free counseling services."

It is old. More here: https://github.com/department-of-veterans-affairs/vets-website/issues/1799

**Comment by rickleegit** [comment]
VBA is asking for a timeline for the completion of this that they can provide to GAO. Possible to provide?

cc; @emilyville @koconnor719

**Comment by webinista** [comment]
@rickleegit Just opened PR #1844 to fix this.
