### ISSUE TITLE
Create VRE blank template pages

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1802]
Create blank templates for pages for content team to work for VR&E and beyond: 
- Topic-landing
- information
- detailed landing
- Process

![topic-landing](https://cloud.githubusercontent.com/assets/1307774/14385487/b524ffdc-fd55-11e5-8889-f0e081444cfe.png)
![information](https://cloud.githubusercontent.com/assets/1307774/14385495/bb4f7d88-fd55-11e5-8ea1-608b23fd9c35.png)
![detailed-landing](https://cloud.githubusercontent.com/assets/1307774/14385503/be8c147a-fd55-11e5-9def-6353e710a39a.png)
![process](https://cloud.githubusercontent.com/assets/1307774/14385504/c4f84c3e-fd55-11e5-8933-3f1b8a72fd39.png)

CC @gnakm @webinista @kantrowitz

**Comment by kantrowitz** [comment]
Added 1st drafts of these.

**Comment by emilyville** [comment]
closing because this is done for now!
