### ISSUE TITLE
Create structure for words

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1803]
word counts for common UI elements such as piano keys!

For now, we can dump it in this issue, then we can figure out where it should go later

:musical_keyboard:

**Comment by gnakm** [comment]
**Intro body copy**
(#content.interior.primary)
Max: 25-35 words
example: https://employment.vets.gov/employment/job-seekers/

<img width="744" alt="screen shot 2016-04-08 at 2 24 46 pm" src="https://cloud.githubusercontent.com/assets/13420618/14393573/afd37e1a-fd95-11e5-8cda-cd442afc69c6.png">


**Blue Cards**
- Max: 100 Characters
example: https://employment.vets.gov/disability-benefits/ 
Disclaimer: We are aware that a lot of our cards exceed 100 characters. it's just 100 characters look the best and we want to go that route and make some of our current things an exception

<img width="334" alt="screen shot 2016-04-08 at 2 12 38 pm" src="https://cloud.githubusercontent.com/assets/13420618/14393581/b58db870-fd95-11e5-9b60-d58107552812.png">
example: https://employment.vets.gov/employment/job-seekers/unemployment-support/

**Body Copy Headers**
- (h3)

<img width="613" alt="screen shot 2016-04-08 at 2 25 26 pm" src="https://cloud.githubusercontent.com/assets/13420618/14393592/c730a970-fd95-11e5-9698-4d08af47c591.png">


**Piano Keys**
- Title (h5)
- Description: 10-15 words/ 100 characters
Example: https://employment.vets.gov/disability-benefits/conditions/

<img width="948" alt="screen shot 2016-04-08 at 2 26 07 pm" src="https://cloud.githubusercontent.com/assets/13420618/14393626/e2cca3fa-fd95-11e5-843e-79c2a54e9515.png">

**Comment by gnakm** [comment]
@kantrowitz Since you've been making some changes, you'll probably know a lot of the front end consistencies at this point. Hope you find this somewhat useful!

@rcarthur @mollyblake @bethpotts This is our makeshift attempt before we put it on Roadrunner but we hope you find this helpful for VR&E!

**Comment by gnakm** [comment]
Closing because this has been added the the RR markdown https://github.com/department-of-veterans-affairs/roadrunner/edit/master/design/index.md with list of things we're compiling. Maybe found on playbook v2 in the near future!
