### ISSUE TITLE
Replace dummy link with real link

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1804]
https://employment.vets.gov/employment/job-seekers/one-year-left/

has a dummy link under 

Résumé Building > Basic tips > "Federal Job Application" (about 3/4 of the way down)

Please replace it with whatever the real link is that needs to go here.

**Comment by mollyblake** [comment]
@rcarthur @bethpotts I think we killed this page from the IA?

**Comment by kantrowitz** [comment]
Should I do this one?

**Comment by bethpotts** [comment]
@mollyblake @rcarthur Molly's right. We killed this page. @kantrowitz Can we remove this page from the repo--or does it not matter if we don't link to it?

**Comment by kantrowitz** [comment]
Yes, we can. It would most likely still be discoverable via search even if we do not link to it. I'll remove it.

**Comment by mollyblake** [comment]
Thanks @kantrowitz !!
