### ISSUE TITLE
Some structured data for new pages

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#1805]
@rcarthur and @mariana-almeida - 

I propose introducing this list of information to the creation/hand-off of the IA. It will speed things up and bypass a lot of messy finding and replacing later. (Even if it's wrong, because at least it will be consistently wrong, which makes it easier to make consistently right!) 

1. URL
2. Page title
3. Subtitle or tagline for that page (as would go in a piano key, under the page title, for example)
4. Page type (of the 4: process, detailed-landing, topic-landing, information, see playbook for reference)

One day, :rainbow: we will automate more things, and this will mean once we define this at the beginning, we'll input it once and only reference it later. That will be awesome, we're not there yet but this will be one step closer. 

so @rcarthur @mariana-almeida Does this sound reasonable?

@gnakm @webinista @kantrowitz let me know if I'm missing any thing.

**Comment by mollyblake** [comment]
Awesome!  What about a date? Or Pivotal #? Is that helpful or will this complicate it more?

**Comment by emilyville** [comment]
@mollyblake We don't need any of those to make the page work -  I imageing you need it for other parts of the process, and by all means keep on using it :) this isn't meant to replace anything you're already keeping track of.

**Comment by rcarthur** [comment]
Makes sense.  By URL do you mean our suggestion?  For example:  "/vocrehab/choosetrack/newskills"

**Comment by emilyville** [comment]
yeah - perfect!

I'm thinking this will us keep from losing pages! We can always change it, but then at least there will be a place to update it.

**Comment by rcarthur** [comment]
Great.  We'll make it happen.  Thanks Emily!!

**Comment by mollyblake** [comment]
Going forward, new stories will look like this:  
Title: Burials - What to do when a death has occurred
Tagline: Steps to take immediately after the death of a Veteran 
Pivotal #: XXXXXXXX
Template: Action Page
Suggested URL:  vets.gov/burials/plan-burial
VA SME:  TBD
Date last touched:  04/12/2016
Chain of Ownership:

**Comment by emilyville** [comment]
If this is documented somewhere else I will close - otherwise where is the best place to keep this?

**Comment by mariana-almeida** [comment]
Yes, it's documented, and it's already being used! Closing this item.
