### ISSUE TITLE
Remove data-alert from markup [WAS: What does the data-alert attribute do?]

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#1827]
I see it all over the markup, usually tied to an `alert-box` class, but what does it do? For example:

```
<div data-alert class="alert-box coda">
    <div class="row">
      <div class="small-12 columns">
        <a id="feedback-tool" class="feedback-widget" tabindex="0" href="http://veterans.uservoice.com" data-uv-trigger="smartvote">
          <span class="icon"></span>
          <span class="text">Provide feedback on vets.gov</span>
        </a>
        
        <a href="https://veterans.uservoice.com/" class="feedback-widget">Visit the feedback forum</a>
      </div>
    </div>
  </div>
```

I've searched the repo for instances of it in JavaScript and CSS, but don't see it. Am I missing something? 

@emilyville this is low priority, just in case you're checking your email on vacation.

**Comment by emilyville** [comment]
I have no idea. If you have searched and not found it - I think it's likely safe to remove. We certainly aren't going to use it correctly going forward if we can't figure out what it's for !
