### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1829]
Problem with the breadcrumb here- 

https://employment.vets.gov/employment/employers/

It is showing "Veteran Employment Center" instead of "Employment"

**Comment by kantrowitz** [comment]
An issue with the breadcrumbs plugin?

**Comment by webinista** [comment]
I think this is another VEC repo issue.

**Comment by ayaleloehr** [comment]
Yep, as a VEC issue. Fixed now.
