### ISSUE TITLE
Employer Landing Page - should have additional piano keys or blue boxes

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1831]
@ayaleloehr  
@mariana-almeida 

This page should have a blue box next "Find a Veteran Candidate" for "Post a Job"

Note:  We do not need a link for "Your Favorite Veterans" or "Employer Info" because those are covered under the "Log In and create/manage your account."

**Comment by ayaleloehr** [comment]
fixed.
