### ISSUE TITLE
Sign-In page edits

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1833]
https://employment.vets.gov/employment/users/sign_in

For the above page, we should delete the first sentence (above the sign-in buttons) and then move the sign-in buttons to the bottom (under the 2nd para). 

Thanks!

**Comment by kantrowitz** [comment]
Where is this page in the structure? I can't find it. Could you point me to it, and then I'll take care of it.

**Comment by webinista** [comment]
@kantrowitz I actually do not know where this is. It might not be in the repo. @awong-dev @plusjeff can you guide us here?

**Comment by ayaleloehr** [comment]
I can take this one. It's in the VEC repo.

**Comment by webinista** [comment]
@ayaleloehr Just created an issue in that repo and assigned it to ya. Going to close this one.
