### ISSUE TITLE
Edits for the Job Search page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1846]
https://employment.vets.gov/employment/job-seekers/search_jobs

1) Please add the word "Military" before "Skills Translator" (so it says "Military Skills Translator") for No. 3 in the blue box on the right:
Use the Military Skills Translator to translate your military skills into language hiring managers will understand.

2) Below that is the header "Featured Jobs" and the line of text under that needs the first word ("From") and last word ("Veterans") capitalized, like this:
From employers that have committed to hiring Veterans.

Thank you!

**Comment by ayaleloehr** [comment]
fixed in PR 284 in the VEC repo
