### ISSUE TITLE
Edits for Log in page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1854]
Please replace the paragraph of text under the header "First time here?" with the following:

It's free and easy to create an account. Simply log in with your LinkedIn or Google account by clicking on one of the buttons below. The first time you log in, we'll ask for your company name and EIN. You will be able to use all the employer features right away, but we have to approve you (by confirming your company name and EIN) before you will be able to view Veteran names or email addresses. This process usually takes less than a day.

**Comment by ayaleloehr** [comment]
Fixed in PR 284 in the VEC repo.
