### ISSUE TITLE
Employer Landing Page Copy Note

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1855]
https://employment.vets.gov/employment/employers/

1) In the middle tile, Find Veteran Candidates, please replace the description with the following:
They are leaders, technicians, and skilled workers with expertise in customer service, operations, and much more. View their profiles and save favorites.

2) Lowercase "m" "more" and delete the colon where we have "Learn More:" so that it looks like this: Learn more (and could you increase the size of Learn more?)

3) Start the first bullet like this (delete "Read" and change "showing" to "shows"): Research shows...

4) In the second bullet, replace the second sentence with this: Additional programs include Vocational Rehabilitation and Employment and apprenticeships.
--Retain the links for [Vocational Rehabilitation and Employment] and [apprenticeships].

5) Change the text in the third bullet to the following: Find out how the Compensated Work Therapy program can meet your company’s needs.
--Retain the link

4) Last bullet on this page should read:
Some cities have a [Veterans Economic Community Initiative (VECI)](/employment/job-seekers/veci/) liaison who can help you hire Veterans. 

5) Delete "Related info:" just above the piano keys. The piano keys can stand alone. It also seems like there is a huge blue box around the piano keys that could be removed??

**Comment by ayaleloehr** [comment]
fixed in VEC repo PR 284
