### ISSUE TITLE
Edits for the Employers after-log-in page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1859]
1) In the middle tile, Find Veteran Candidates, please replace the description with the following:
They are leaders, technicians, and skilled workers with expertise in customer service, operations, and much more. View their profiles and save favorites.

2) For the description in the Your Favorite Veterans tile, replace the text with this: You have not designated any Veterans as favorites yet.

3) Delete "Related info:" just above the piano keys. The piano keys can stand alone. It also seems like there is a huge blue box around the piano keys that could be removed??

**Comment by ayaleloehr** [comment]
fixed
