### ISSUE TITLE
Raise Right Call out Box

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1885]
https://employment.vets.gov/employment/job-seekers/search_jobs

Move up blue box so it’s aligned with Search the Veterans Job Bank to find the right position for you. height

**Comment by kantrowitz** [comment]
What branch is this on?

**Comment by gnakm** [comment]
This is not an issue anymore because this page received a completely new makeover https://www.vets.gov/employment/job-seekers/
