### ISSUE TITLE
Learn More line break (service disabled)

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1887]
Learn More (Line Break before learn more)
https://employment.vets.gov/employment/job-seekers/service-disabled/

**Comment by kantrowitz** [comment]
Another line break? Or a physical line? Do you have an example?

**Comment by gnakm** [comment]
Like this: https://www.vets.gov/employment/employers/

**Comment by gnakm** [comment]
Has been implemented. Add line break to service-disabled #1969
