### ISSUE TITLE
Bold Header for Career Fairs 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1890]
Visit the following sites to find a career fair near you: (have to be bolded header)
https://employment.vets.gov/employment/job-seekers/career-fairs/

**Comment by kantrowitz** [comment]
Done. Shouldn't this be bolded, too? "Your preparation for job fairs is critical to your success. Here are a few tips:"

**Comment by gnakm** [comment]
Yes! Thanks!

**Comment by gnakm** [comment]
Merged via #1926
