### ISSUE TITLE
Remove black line across screen above "How it works" on multiple VR&E pages

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1921]
Some examples (do you want me to list all here?):
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/apply-vre/
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/choose-your-track/existing-skills/
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/choose-your-track/existing-position/

**Comment by webinista** [comment]
@kantrowitz This is being caused by the long lines of `---------------------------`. Those compile to an `<hr>` tag when generated. Remove them and you'll remove the line.

**Comment by bethpotts** [comment]
@gnakm @webinista Just heard from Tiby that this line is a new design element. Sorry, I didn't realize this was intentional. If that's the case, I see one instance where the line goes right through the blue box. Here:
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/choose-your-track/existing-position/

**Comment by kantrowitz** [comment]
I'm not completely sure that this is so. It's up to @gnakm. It's just been requested to be added on other pages and awaits a decision there, too. I'll correct the one you point out, though.

**Comment by kantrowitz** [comment]
This is added per design @gnakm.
