### ISSUE TITLE
Implement search in Header v2

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/vets-website#19304]
# Description

**Related Slack thread:** https://dsva.slack.com/archives/C52CL1PKQ/p1635879088259200

Design spec:
![image](https://user-images.githubusercontent.com/12773166/140103763-774fa28b-9d98-4b30-876b-d18dc94bef99.png)

[Sketch files](https://www.sketch.com/s/63193c20-04fc-4d4f-8b54-abf698c48636/a/Vr8Zzrw)

As we have been working to develop the new header, we are running into a case where we cannot use the existing `SearchMenu` component _in its current form_. If we do use it in its current form, it looks like this:

![image](https://user-images.githubusercontent.com/12773166/140105264-c5d09e48-ab8c-48ed-b822-1ccd00d0024c.png)

We need to either modify the `SearchMenu` component to support this new design only for the new header v2 or create a new search component specifically for header v2.

## Acceptance Criteria

- [ ] Make search work within the new header v2 app
- [ ] Ensure the styling of search matches the [design spec](https://www.sketch.com/s/63193c20-04fc-4d4f-8b54-abf698c48636/a/Vr8Zzrw)

**Comment by srsuddath** [comment]
Hey @kelsonic Kelson, check out
src/applications/search/containers/SearchApp.jsx line 354

**Comment by brianalloyd** [comment]
Shifting to ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/32424 as I had issues adding this to our repo. Closing to avoid confusion.
