### ISSUE TITLE
Change path-name of page from "Existing Position" to "New Skills"

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1983]
@ayaleloehr  - don't know if you're the right person to help us with this one - but you're probably will know who this should go to. 

https://github.com/department-of-veterans-affairs/vets-website/pull/1981
The new title of this page is "New Skills".  Please change breadcrumbs to "new-skills"

**Comment by kantrowitz** [comment]
Existing Position page was removed. New Skills page was added.

See here: https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/new-skills/
