### ISSUE TITLE
Needs final proof.  

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1995]
Here is the website:
https://vets-website-pr-1801.herokuapp.com/disability-benefits/claims-process/claim-types/predischarge-claim/

Here is the github file to edit in case you see a problem. 
https://github.com/department-of-veterans-affairs/vets-website/blob/vre-master/_disability-benefits/claims-process/claim-types/predischarge-claim.md

**Comment by bethpotts** [comment]
Hi Tiby, the new text that Ric added looks good, but the piano keys seem to be messed up for some reason. I'm not able to see this latest file on the live site, just through heroku preview, FYI. The piano keys render as bullets...can you help?

**Comment by kantrowitz** [comment]
Fixed by the design updates.
