### ISSUE TITLE
Merged changes not showing up in 1801

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1997]
@kantrowitz  - Beth merged this about 10 am PST and the changes still are not reflected on 1801.  Can you look at this?

**Comment by kantrowitz** [comment]
Which PR did she merge? Was this addressed via Albert's conversation on Slack #content, 5;44PM, 4/19? Albert restarted Heroku, which was using his personal account which was overloaded.
