### ISSUE TITLE
Need help with failed checks

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1999]
https://github.com/department-of-veterans-affairs/vets-website/pull/1998

@kantrowitz - On our landing page:
https://vets-website-pr-1801.herokuapp.com/vre/

....the "Service Disabled" blue box should link to this page:
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/choose-track/

**Comment by kantrowitz** [comment]
Please close this issue, as it is addressed by #1998 ("choose-track" was removed, pages shifted)
