### ISSUE TITLE
Delete redundant page

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2000]
This page should be deleted - 
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/

because it is replaced by this page:
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/choose-track/

**Comment by rcarthur** [comment]
The piano keys below should have the taglines moved into the bolded positions

Existing Position
New Skills

**Comment by kantrowitz** [comment]
Check #1998
