### ISSUE TITLE
Pull Request did not correct problem on Choose your Track

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2002]
https://github.com/department-of-veterans-affairs/vets-website/issues/2000

PR was submitted
https://github.com/department-of-veterans-affairs/vets-website/pull/2001

And it removed the green box but didn't fix the language on the piano keys. 

I'm submitting this as an issue just for archival sake.

**Comment by kantrowitz** [comment]
Fixed by #1998
