### ISSUE TITLE
VR&E breadcrumb fix to remove hyphen from Service-Disabled

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#2016]
So, for instance, on this page:
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/independent-living/

The breadcrumbs should look like this:
Vocational Rehabilitation and Employment (VR&E) > Service Disabled > Independent Living

**Comment by ayaleloehr** [comment]
Thank you @webinista !!

**Comment by kantrowitz** [comment]
Removed the hypen.
