### ISSUE TITLE
Phantom page in Jobs V2

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#2034]
@ayaleloehr In the jobs V2 repo, there is a page called .employers.md ... and it seems to be a phantom page. It's not the pre-login page, nor the post-login page. Can you help solve this mystery? Thanks! 

https://github.com/department-of-veterans-affairs/vets-website/blob/jobs-employment-v2/_employment/employers.md

**Comment by kantrowitz** [comment]
@mollyblake Do you need this page for some reason?

**Comment by ayaleloehr** [comment]
@kantrowitz actually, on the live site, https://www.vets.gov/employment/employers/, this page is coming from the VEC repo.  It should be deleted in this repo. Can you take that @kantrowitz ?

I see Molly's issue on the copy edits ( #2040 ) and will take those.

**Comment by kantrowitz** [comment]
Wow. Will do!

**Comment by kantrowitz** [comment]
@ayaleloehr  Could you point me to the exact folder path in VEC? When I tried to delete this page in this repo locally it didn't work because I don't have VEC up and running (locally). (I understand that you were referring to the version of the page in vets-website as opposed to VEC).

**Comment by ayaleloehr** [comment]
This was closed a while ago.
