### ISSUE TITLE
Change to: https://www.vets.gov/employment/employers

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#2040]
There is a small text change for the https://www.vets.gov/employment/employers page (not logged in)
It's at the bottom, under Learn more. 

OLD TEXT: 
Research shows that hiring Veterans is good business, particularly when it comes to entrepreneurship, resiliency, mission strategy, and team-related goals and actions: “The Business Case for Hiring a Veteran: Beyond the Clichés”.

NEW TEXT: 
Research shows that hiring Veterans is good business, particularly when it comes to entrepreneurship, resiliency, mission strategy, and team-related goals and actions. The Institute for Veterans and Military Families lays out the facts that support this in a brief called, “The Business Case for Hiring a Veteran: Beyond the Clichés."

THANKS @kantrowitz

**Comment by ayaleloehr** [comment]
Edited in the VEC repo
