### ISSUE TITLE
Piano Keys are a little funky

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2042]
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/

compare to this page:
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/

**Comment by webinista** [comment]
There's probably a missing `</div>` just before the piano keys. If it can wait a day or so, we can improve how this works with the code that's in #2033.

**Comment by kantrowitz** [comment]
Ric - please see @webinista's comment above and let me know. Thanks!

**Comment by webinista** [comment]
Looks like this is fixed now.
