### ISSUE TITLE
Change "Employer" blue box to piano key

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2046]
https://vets-website-pr-1801.herokuapp.com/vre/

tag line should be:
"VA can help you find Veterans to hire and support them in your workplace."

There should be only 3 blue boxes on page now.

**Comment by kantrowitz** [comment]
Which three boxes would you like to keep?

**Comment by rcarthur** [comment]
All of them, except the Employer box
