### ISSUE TITLE
Textual inconsistency

### ISSUE THREAD

**Issue by kantrowitz** [department-of-veterans-affairs/vets-website#2047]
On https://vets-website-pr-1801.herokuapp.com/vre/family-members/ it says:

"Available Benefits"

On https://vets-website-pr-1801.herokuapp.com/vre/apply-vre/ it says:

"Potential benefits and programs"

Which one should we use?

**Comment by mollyblake** [comment]
Hi @kantrowitz I think we should stick with Available Benefits per the family member page. I also like the blue box set up on that page as well. So the eligibility points are in the blue box and then others are not. 
Make sense?  THANKS!

**Comment by mollyblake** [comment]
Also, should i make those changes or will you?  Thanks

**Comment by kantrowitz** [comment]
Change was made.
