### ISSUE TITLE
Quick Links Change

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#2054]
Change Quick links to Common questions, Popular on Vets.gov

**Comment by emilyville** [comment]
more like so, but with two columns (whereas this mockup had three)!
![screen shot 2016-05-03 at 6 00 59 am](https://cloud.githubusercontent.com/assets/1307774/14983879/a61eb1b0-10f4-11e6-83eb-7e0260e242a2.png)

**Comment by emilyville** [comment]
Ok! I believe we have landed on this as a change after usability testing and kicking it around a while internally. 

**Common Questions**
How do I apply for disability benefits? (https://www.vets.gov/disability-benefits/apply-for-benefits/)
How do I apply for education benefits? (https://www.vets.gov/education/apply-for-education-benefits/)

**Popular on Vets.gov**
Find nearby VA locations (https://www.vets.gov/facility-locator)
View education benefits available by school (https://www.vets.gov/gi-bill-comparison-tool/)
Contact the Veterans Crisis Line (https://www.veteranscrisisline.net/)

And it should look like this
![screen shot 2016-05-19 at 1 21 15 pm](https://cloud.githubusercontent.com/assets/1307774/15408338/a8d99df2-1dc4-11e6-98b2-f8a3d6dd967b.png)

@maryannbrody let me know if you would like different links or copy!

**Comment by gnakm** [comment]
Stacking on mobile sounds great!

Just wanted to put it out there that when recruiting for usability sesh last night, a Veteran actually suggested common questions/ popular links. He said he would LOVE to see that. I quietly smirked in my brain.

**Comment by mariana-almeida** [comment]
"Popular on Vets.gov" - I have learned that on "vets.gov" the "v" is lower case. Please update!

(We have a wee problem with consistency on this, esp. our logo!)

Otherwise looks great!

**Comment by emilyville** [comment]
This will also close https://github.com/department-of-veterans-affairs/vets-website/issues/1248
