### ISSUE TITLE
Migrate pages with piano keys to new version

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2066]

**Comment by emilyville** [comment]
Maybe you, @kantrowitz, and and I can divide and conquer on this.

Also - as we go let's make a list of pages that don't have the the descriptions and pass along to @bethpotts !

**Comment by webinista** [comment]
I'm also willing / able to pitch-in.

**Comment by webinista** [comment]
Closing. I think we got them all.
