### ISSUE TITLE
Fix Facility Locator tool tip

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2069]
![screen shot 2016-04-21 at 3 57 15 pm](https://cloud.githubusercontent.com/assets/354277/14726965/49f3404e-07db-11e6-9ae0-5a45da85db9e.png)

The text overflows the tool tip container boundaries.

**Comment by ayaleloehr** [comment]
@rickleegit any chance you can take this one?

**Comment by webinista** [comment]
@ayaleloehr I'm working on it now :-)
