### ISSUE TITLE
linkedin not linked-in ?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2073]
on Job-seeker page: Seems odd that linked-in has a dash in it here? 

Also feels a little unclear - does linkedin really own lynda or is it _and_ lynda?
 
![screen shot 2016-04-21 at 8 43 44 pm](https://cloud.githubusercontent.com/assets/1307774/14728361/cfc40c6e-0801-11e6-8f18-1cb7fde36883.png)

**Comment by MarinaMartin** [comment]
LinkedIn owns Lynda, but it's not Linked-In

**Comment by Drakenhart** [comment]
LinkedIn's Branding Guidelines:

https://brand.linkedin.com/policies

Note the rules for their Mark.

 >** II. Use of the "LinkedIn" Name in Text**
> 
> When referring to our company, the full name is LinkedIn Corporation. When referring to our services, the LinkedIn name should be written as one word and used as an adjective followed by a description of our services in a form similar to the following examples:
> 
> LinkedIn® professional networking services
> LinkedIn™ recruiting services
> The LinkedIn name should always be accompanied by either the ® or ™ symbol. See Attribution under the Use Requirements and Terms, for further information.

>

**Comment by emilyville** [comment]
@kantrowitz could you remove the extra "-" in linkedin from the job-seeker page?

**Comment by kantrowitz** [comment]
It's already gone? Added trademark symbol.

**Comment by emilyville** [comment]
This is done and now has added benefit of tm symbols
