### ISSUE TITLE
[Main issue] Catalog current page template styles and patterns; migrate to Front Matter where possible

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2089]
As we move forward with redesigning and redefining templates, we need a catalog of what's currently on the site. Goals here are to:

- Catalog what design patterns and components we're using across the site
- Determine common patterns in use across the site and how we can make the markup and CSS consistent and easy to reuse.
- Figure out how we can bend Markdown and Front Matter to make content easier to write, maintain, and "templatize"

Not sure how best to track this, but please link related issues to this one.

**Comment by Drakenhart** [comment]
This would be appreciated as it is not easy to track some of the changes going on to the Vet.gov templates here in github. 

(Like the changes to the links, or the updates to the buttons, and the changes to the Veteran's Crisis line, forms, and there is nothing about "sign in" or a "log in" form that we can mimic.) Some of the examples on the components page, for example, do not fit what you currently have on the site itself. (See links).

**Comment by webinista** [comment]
All related issues save #2421 (documentation) are complete. Safe to close.
