### ISSUE TITLE
"Contaminated Drinking Water at Camp Lejeune" page looks wonky

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2102]
Check the markup. [This page](https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/contaminated-drinking-water-at-camp-lejeune/) is a pretty large divergence from other pages with an `template: 6-info-page` property.

(Note that the `template` property doesn't have much meaning to date. Still, there are a lot of pages with similar `template` values that have similar layouts.

**Comment by emilyville** [comment]
Good find @webinista ....@kantrowitz Could you take a look at this page?

**Comment by emilyville** [comment]
I think this is an example of how this template should look, and it's just that the blue box needs to not be full width. 
https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/c-123/
