### ISSUE TITLE
[discovery] Solution for confirming SSN and contact info on NOD form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/vets-website#21070]
# Background
On almost every form on VA.gov we ask the Veteran to enter/ confirm their basic info like SSN and contact info even though we generally already have this information available to us. We would like to explore the options to lower the friction for Veterans as much as possible with this information, wether that means showing the Veteran the information we have on file or maybe not even showing the Veteran the information and maybe linking to the Profile, or any other options we can come up with to make the Veteran experience as low friction as possible.

Currently we have solved this by showing a static card of information to the Veteran but we are not sure this is the best way to handle this. [Here](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/139282249/simulate/sitemap) Is an example of that.

# User Story
As a Veteran I don't want to have to deal with information that I have already provided to the VA when filling out the NOD form

## Tasks
- [ ] Look at the NOD form and determine what basic contact information we ask for that we already have on file
- [ ] Ideate on ways that we can reduce the friction for the Veteran around this information

**Comment by saderagsdale** [comment]
- Scope of this ticket is to standardize this pattern so we can use it consistently in other places. Needs discovery first.

**Comment by saderagsdale** [comment]
@thehastingsp See if we can make this an enhancement. If it requires a lot of effort, hit pause.

**Comment by cohnjesse** [comment]
@thehastingsp Im not sure I understand your question, are you asking if we are able to show certain data to the user from a technical standpoint?

**Comment by cohnjesse** [comment]
@thehastingsp We have the ability to display any information that comes in the profile - name, sex, birthday - very easily. We can pull other data if needed but it will require some work to pull that data from somewhere. Not a deal breaker though.

**Comment by thehastingsp** [comment]
@saderagsdale discussed with team and concluded that this is feasible, but current research efforts will likely inform patterns like this more holistically. Recommend keeping it in backlog until we can coordinate it with other form efficiency opportunities.

**Comment by Mottie** [comment]
This is related to two Design System Tickets:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/518
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/619

**Comment by saderagsdale** [comment]
@Mottie related as dependencies, predecessors, or successors?

**Comment by Mottie** [comment]
Design system level decisions... so overriding?

**Comment by saderagsdale** [comment]
@Mottie should we move this to another team or delete?

**Comment by Mottie** [comment]
I think we can close. It's a platform-level issue that is already in progress.
