### ISSUE TITLE
delete old page that can still be accessed on the live site

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#2112]
The following page should not be accessible/live. At least we don't currently link to it--and we have a different Predischarge Claim page that we do link to--but I just searched on the live site for IDES and it took me to this old page that we don't want folks to see:

https://www.vets.gov/disability-benefits/apply-for-benefits/active-duty/

Can we get rid of it?

**Comment by ayaleloehr** [comment]
@bethpotts this page still exists in the repo here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/_disability-benefits/apply-for-benefits/active-duty.md and is still linked to from 4 pages:

https://www.vets.gov/disability-benefits/apply-for-benefits/help/
https://www.vets.gov/disability-benefits/apply-for-benefits/ways/
https://www.vets.gov/disability-benefits/apply-for-benefits/one-year/
https://www.vets.gov/disability-benefits/claims-process/date/

If you (or someone) can change those 4 links to point to the correct, new page and also delete the active-duty.md file, will you then ping me (or assign this back to me) and I can make sure it's deleted on the live site as well?

**Comment by emilyville** [comment]
@kantrowitz could you take a look at this? Let me know if you need help.

**Comment by bethpotts** [comment]
@emilyville Thank you for moving this along while I was consumed with editing new sections. I noticed that one link is wrong still. I don't think I'm supposed to do PRs until next week when I'm onboarded, but in the meantime I wanted to alert you since there's a broken link on the live site. On this page:
https://www.vets.gov/disability-benefits/apply-for-benefits/help/
...when you click on the piano key called "How do I file while on active duty?"
It needs to take you here:
/disability-benefits/claims-process/claim-types/predischarge-claim/
Thanks!
