### ISSUE TITLE
Conform Education - text under piano keys

### ISSUE THREAD

**Issue by kantrowitz** [department-of-veterans-affairs/vets-website#2119]
https://vets-website-pr-1801.herokuapp.com/education/other-educational-assistance-programs/

We eliminated this text on vre and careers. Do we want to adjust this here?

**Comment by mollyblake** [comment]
Thanks @kantrowitz the verdict is:  there are some piano keys that benefit from taglines and others that don't so we just need to be consistent page by page.  In other words, all piano keys on a page will either have taglines or they all won't ... So the stack of piano keys will be consistent. So this page is good to go!!
