### ISSUE TITLE
Coursera link buried on Job Seekers page

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#2121]
Can the Coursera link be more prominent?  If it becomes so, however, the LinkedIn and Lynda links should probably follow along with it in the same pattern. Open to ideas on the best way to do this. 

Assigning to @emilyville for now but feel free to reassign as appropriate.

**Comment by cfeeney-va** [comment]
Also, this might be a separate issue, but the job-seekers page has a link in the first blue box to "consider additional education" but this just links to the GI bill and doesn't include any of the free educational resources.

**Comment by rcarthur** [comment]
@cfeeney-va  Reason for this is that we are making a distinction between formal education and non-credentialed opportunities.

**Comment by emilyville** [comment]
@gnakm this will be much better when we adjust some of these templates - but would you mind taking a look in the meantime and seeing if you have any ideas here?

@cfeeney-va I concur that this is not ideal - to send people to "consider additional education" but I think we should likely just call that link something more accurate! @maryannbrody - any ideas here?

**Comment by maryannbrody** [comment]
I did a little digging and found some threads on Reddit about Coursera. The focus seems to be on the "free" aspect of it. Can we frame it like that? "Take a class with these free resources" or something like that?

Here's one of the links: 
https://www.reddit.com/r/army/comments/42sg9y/coursera_offers_a_free_class_credit_to_veterans/

**Comment by ayaleloehr** [comment]
For what it's worth, classes on Coursera are free for everyone.  The Veteran benefit is "one free Coursera course certificate."

**Comment by maryannbrody** [comment]
Yeah -- that could be explained in the bullet point itself for coursera. I still think "free" needs to be highlighted as it's how veterans talk about it in real life.

**Comment by emilyville** [comment]
@gnakm what do you think about - as a short-term fix before we role out new templates - to call out linkedin and coursera along the side?

https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/c-123/
![screen shot 2016-05-04 at 6 49 41 pm](https://cloud.githubusercontent.com/assets/1307774/15034302/001cf43a-1229-11e6-813a-e0a3f6242cda.png)

**Comment by gnakm** [comment]
@emilyville I like that idea. Let me put something together.

**Comment by emilyville** [comment]
closed with #2311
