### ISSUE TITLE
Careers and Employment: pre-logged-in Employer page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#2125]
Please make the following changes in the VEC repo:
1) Change the piano key that says this: Establish an Apprenticeship and On-The-Job-Resources
...to this: Establish an Apprenticeship Program

Then create a tagline (text under the above header) that says:
Apprenticeship programs are available for Veterans using their VA education benefits.

2) Add a period in the third piano key where it says this:
Improve your business by hiring Vets.

**Comment by ayaleloehr** [comment]
The page in production (https://www.vets.gov/employment/employers/) looks like it already has the first change and it only has 2 piano keys, so I don't think the #2 applies. Going to close but feel free to reopen if you disagree!
