### ISSUE TITLE
Careers and Employment not-logged-in Employers page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#2127]
This is the one I see on vets.gov (not the one in the VEC). 

In the third blue tile, please cap the word "All" where it says, "View All Hiring Commitments."

Under Learn more:
1) The period at the end of the first bullet point needs to move inside the ending quotation marks.
2) Capitalize "Veterans" in the last bullet point.

Many thanks!!

**Comment by ayaleloehr** [comment]
Done.
