### ISSUE TITLE
Zombie files in Education

### ISSUE THREAD

**Issue by kantrowitz** [department-of-veterans-affairs/vets-website#2135]
Are _education/gi-bill/post-9-11/bill-transfer.md, _education/gi-bill/post-9-11/fry-scholarship.md still necessary? Can we remove them?

**Comment by rcarthur** [comment]
@kantrowitz  - I don't understand the question.  Did the pages go away?

**Comment by emilyville** [comment]
@kantrowitz can you elaborate - are these pages we need to remove?

**Comment by kantrowitz** [comment]
These two pages say "Coming soon." Do we want this? Or delete them?
