### ISSUE TITLE
Fry Scholarship - restructure How it works

### ISSUE THREAD

**Issue by kantrowitz** [department-of-veterans-affairs/vets-website#2140]
#2139 

The how it works section reads like a subway map. Should it be changed to be one?

Original:
https://vets-website-pr-1801.herokuapp.com/education/gi-bill/survivors-dependent-assistance/fry-scholarship/

@rcarthur @kellyskennedy @bethpotts @mollyblake @peggygannon

**Comment by rcarthur** [comment]
@kantrowitz  - Why do you think this?Seems like it follows our general action page criteria.

**Comment by kantrowitz** [comment]
@emilyville @gnakm Your thoughts?

**Comment by gnakm** [comment]
@kantrowitz 
I don't think it has to be subway maps though I also think that all sections don't need to be in blue callout boxes

**Comment by emilyville** [comment]
I agree with @gnakm - I think we could trim down the blue boxes, like this page:
https://www.vets.gov/disability-benefits/conditions/
