### ISSUE TITLE
Notice of Disagreement | Add schemas for endpoints which aren't currently being validated, and validate against them

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/vets-website#21428]
For instance, the evidence upload request isn't currently validating against a schema. Identify any others.

**Comment by Mottie** [comment]
The [NOD schema is available from Lighthouse](https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current) from this endpoint: `/notice_of_disagreements/schema`

**Comment by scottymeyers** [comment]
There is not schema to validate for evidence uploads, this can be closed.
