### ISSUE TITLE
Random "one" inserted in page bug

### ISSUE THREAD

**Issue by jcklpe** [department-of-veterans-affairs/vets-website#21454]
On this page: 
https://www.va.gov/about_va/organizations.asp

![image](https://user-images.githubusercontent.com/9451726/175426508-643d1250-19b1-4396-b04e-91ab071d4ac4.png)
![image](https://user-images.githubusercontent.com/9451726/175426517-08baeb50-ee26-4dd4-99a2-967c70d9f1e4.png)

**Comment by Adityageek** [comment]
Hi @jcklpe Can i fix this issue.

**Comment by jcklpe** [comment]
@Adityageek : yeah sure! It's an open source project, feel free!

**Comment by jcklpe** [comment]
Pretty sure this isn't completed.
