### ISSUE TITLE
Intermittent Broken Link

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2155]
@ayaleloehr  We're getting an intermittent broken link on the this page
https://www.vets.gov/employment/job-seekers/one-on-one/

for the VECI page. 
Veterans Economic Community Initiative (VECI) liaisons can help you connect with local business leaders, schools, and nonprofit groups to maximize your education and economic opportunities.

From Mariana's chrome browser she was getting a "404 Authorization Required."   When I tried it on my machine it asked me for a password as well...but I guess I already had the password loaded into my browser because it took me (correctly) to this page.  
https://employment.vets.gov/employment/job-seekers/veci/

cc @mariana-almeida

**Comment by emilyville** [comment]
Merged fix, closing. @rcarthur please reopen if this didn't address the issue adequately.
