### ISSUE TITLE
Move VRE to within job-seekers

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2160]
I think it should be 

vets.gov/employment/job-seekers/vre

And fix any resulting routing, linking, breadcrumb issues. 

Tagging @mariana-almeida to verify this is the right new location.

**Comment by mariana-almeida** [comment]
It's probably as you say: vets.gov/employment/job-seekers/vre. Let's leave this open until we get concurrence comments back around May 6.

**Comment by emilyville** [comment]
closing, an issue for another day!
