### ISSUE TITLE
Rename Piano Keys on Service-disabled page

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2162]
https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/

- These piano keys are likely nested in something, and they do not look correct and should be full width.
- please remove the text above that says "Choose from the tracks listed below". I see where you were going here, but if we were to say... move these links to a sidebar etc this will just be lonely text left from this version of a page. I also don't think it reads super clear as related right now. (tagging @mariana-almeida )

**Comment by mariana-almeida** [comment]
@emilyville - thoughts on the changes below?

This is a good time to add that tagline text we discussed to piano keys. 
1) add tagline to piano key
2) I am proposing we also use a page title here. 
3) Plus removing the question format. Note the unintended side effect of having to change the breadcrumb title: https://vets-website-pr-1801.herokuapp.com/vre/service-disabled/start-business/
4) Plus re-ordering the piano keys.

@bethpotts - can you please do a quick edit of the following:

**Page title: New thing we haven't done before **
Vocational Rehabilitation and Employment Programs for Service-Disabled Veterans [I know, it's so long!! any suggestions?]

**Delete: **Choose from the tracks listed below.

**Piano key title and short tag line: **

### Develop new skills
Find a field that better suits your abilities

### Return to the job you held before mobilization
Guidance for your employer on how to accommodate your needs

### Job search counseling
Continue your current career path with the help of our counselors

### Consider whether self-employment is for you
Help starting your own business is available for service-disabled Veterans

### Independent living services
Learn what help is available to live more independently with your service-connected disability

**Comment by emilyville** [comment]
I concur @mariana-almeida !

**Comment by emilyville** [comment]
Kicking it over to you @kantrowitz !

**Comment by mariana-almeida** [comment]
Let's have @bethpotts do a quick edit lookee loo first, if you please.

**Comment by rcarthur** [comment]
@bethpotts  - Let's work through this after our Monday morning stand-up.

**Comment by emilyville** [comment]
Was this resolved? The origin of the issue was resolved so I am tempted to close.

**Comment by mariana-almeida** [comment]
Not yet resolved. Ric is working on an edit now.

**Comment by emilyville** [comment]
ok,  I renamed the issue to what I think this is for.

**Comment by rcarthur** [comment]
[PianoKeyTask_03_20160504 (1).docx](https://github.com/department-of-veterans-affairs/vets-website/files/250903/PianoKeyTask_03_20160504.1.docx)

@kantrowitz  - attached is fully edited/approved content - pls make changes in the page

**Comment by webinista** [comment]
@emilyville This looks like it can be closed.
