### ISSUE TITLE
One on One design tweaks - round 2

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2165]
@kantrowitz @mariana-almeida 
https://www.vets.gov/employment/job-seekers/one-on-one/

Seems like we should think about the following improvements"
 - Instead of "How it works" - Can we change it to "Tailored one-on-one guidance"??
 - Cut out space between the sub-sections and the bulletized list
 - What about some sort of light blue boxes for each bucket of help ("All Veterans" "Service-Disabled Veterans") to make them pop out a bit?

**Comment by kantrowitz** [comment]
@emilyville @gnakm 

Suggestions?

**Comment by emilyville** [comment]
Closing because I believe this has been done - and if not will be wrapped into future template work.
