### ISSUE TITLE
Request to set up check-in as a workspace

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/vets-website#21690]
Please let us know if any further info is needed, thanks!

cc @brdunfield @brianseek

**Comment by rmessina1010** [comment]
@acrollet, which app from the [allow list ](https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/changed-apps-build.json)is this for?

**Comment by acrollet** [comment]
@rmessina1010 it's for [check-in](https://github.com/department-of-veterans-affairs/vets-website/blob/3f9239aa4fd22fabb9f319a8d7195e675da154f2/config/changed-apps-build.json#L62), thanks!

**Comment by acrollet** [comment]
@rmessina1010 now that workspaces has been released, can we get in the queue to be set up? Thanks! :-)

**Comment by rmessina1010** [comment]
@acrollet, RTT is currently setting up Platform Teams workspaces and have a few more weeks left in the process. After that, we will start setting up app teams.
