### ISSUE TITLE
Changes to source USWDS files

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2180]
In migrating the HCA code out of the vets-website repo and into a new one, I found a few places where changes were made directly to the USWDS files instead of adding new styles in va.scss. We should probably not do this. Here are the changes I found that should probably be reverted and instead specified in va.scss. There are more, but I could not document them all. If you look look at git blame in each of the USWDS files you'll see when they have been changed.

- [ ] Form width specified from `rem` to `em`: [Link](https://github.com/department-of-veterans-affairs/vets-website/blob/master/_sass/components/_forms.scss#L3)
- [ ] `font-serif` changed from USWDS default: [Link](https://github.com/department-of-veterans-affairs/vets-website/blob/master/_sass/core/_variables.scss#L18)
- [ ] Specific `text-capitalize` styles added to buttons: [Link](https://github.com/department-of-veterans-affairs/vets-website/blob/master/_sass/elements/_buttons.scss#L155)

**Comment by webinista** [comment]
\*twitch* thanks for finding and calling out these examples.

**Comment by emilyville** [comment]
I'm just chiming in for a general 👏 at finding and fixing this!
