### ISSUE TITLE
Certificate of Eligibility | Status Application Download COE Link

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/vets-website#21864]
I've noticed the Certificate of Eligiblity Download link isn't hooked up in the Status Application.

It should:
- [ ] be hooked up to the correct endpoint
- [ ] not display the file size unless that information is somehow available

***

<img width="801" alt="Example" src="https://user-images.githubusercontent.com/969752/182970580-a42e3ce9-03af-4ca1-b293-13b261a45445.png">

**Comment by saderagsdale** [comment]
@scottymeyers what's the status on this one?

**Comment by scottymeyers** [comment]
@saderagsdale closed!
