### ISSUE TITLE
Combine .action-bar, .section.do, and .section.start?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2211]
Related to #2205, #2091, #2188. Blocks #2090. 

The `.action-bar` and `.section.do` bars are more or less the same component with the button floated to the left or right. `.section.apply` is similar, but green. Right now, they're styled slightly differently. I think we can standardize them, and reduce the CSS involved in all three.

The `.action-bar` is the gray bar at the top of [Disability Benefits > Conditions](https://vets.gov/disability-benefits/conditions/)

![screen shot 2016-05-02 at 6 21 42 pm](https://cloud.githubusercontent.com/assets/354277/14972675/4d79a92c-1093-11e6-87dc-ee9e3fd8c390.png)

----

**`.section.do`** is the gray bar found at the bottom of [Disability Benefits](https://vets.gov/disability-benefits/) 

![screen shot 2016-05-02 at 6 21 37 pm](https://cloud.githubusercontent.com/assets/354277/14972701/8ff307c6-1093-11e6-9633-caf73bd071d2.png)

----

**`.section.start`** is the green bar found at the bottom of the [Disability Benefits > Apply for Benefits](https://www.vets.gov/disability-benefits/apply-for-benefits/) page.

![screen shot 2016-05-02 at 6 32 15 pm](https://cloud.githubusercontent.com/assets/354277/14972793/cbeece1c-1094-11e6-91e1-1c6a534fd86d.png)

**Comment by emilyville** [comment]
My 2 cents...

- We should standardize on one color treatment (gray button with green button)
- I unfortunately like it on the right at the top - and the left at the bottom
- I like having both options (above and below content) but I'm not sure I can articulate why!

**Comment by KHarshawat** [comment]
+1 to  gray background+green button. I like the padding of screenshot 2 more than screenshot 1 but think there could be more margin between it and the blue buttons (conditions/claims process/etc) above it. 

Not sure how I feel about having a button both at the top and bottom of a page but I definitely like it at the bottom of a page. 

Thanks for letting me chime in!

**Comment by webinista** [comment]
This component never sits at both the top _and_ bottom of the same page. And that's something that we can enforce via templating. It's at the top on tertiary-level pages, and the bottom of secondary pages.

**Comment by angel** [comment]
I prefer the gray background and green button. I think the light green background should be kept for success messages. Also, is the purpose of the background color just to add an extra cue to button? 

I agree with @KHarshawat about the page feeling to "stripey" especially for when the button is on the bottom.

**Comment by gnakm** [comment]
Yes to gray (less cushioned) bar with green button on top. I think Emily and I went over this a while back and discussed that the button should be at the top because some users may want to make the decision to apply to something right away without having to scroll a lot (mobile view) and because the grey bar at the bottom clashed with the piano keys (maybe that's why the green decision was made? I don't think i was there for that).

However, it's a weird catch-22 because after reading all of the content, the user may decide to apply at the button and it's extra work to scroll all the way up again to apply, hence why the whole both at top and bottom may feel easier.

I know that doesn't give us a concrete solution but if we had to pick between top and bottom, I choose top.

**Comment by webinista** [comment]
To clarify: the question is whether the difference in padding around the button, the different sizes of the button, and the green background are worth the additional bytes of CSS and HTML. Whether the bar sits at the top, bottom, or both doesn't really matter here. It will be a template soon enough.

For context (and @emilyville correct me if I am wrong): we're working towards a system of templates that will make it easier to build out Vets.gov, and make changes down the line. We will be:

1. Removing as much HTML from the Markdown files as possible.
1. Using YAML / Front Matter more effectively to structure page data.
1. Using YAML / Front Matter to specify page layouts/templates.
1. Creating includes or template fragments for components/patterns that are used across the site.

This issue is related to #2090, which will eventually be used for all of three variations of this bar.

**Comment by emilyville** [comment]
@webinista and everyone- sounds perfect. No more variations in padding and color, but placement will remain flexible. I'm all for minimizing the amount of specials happening!

And thank you for chiming in everyone!
