### ISSUE TITLE
[bug] Fix NOD zipcode submission bug

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/vets-website#22148]
This bug was brought up by Robin and Drew (lighthouse team)

More info here:

https://dsva.slack.com/archives/CSKKUL36K/p1662579295177349?thread_ts=1662575350.562149&cid=CSKKUL36K

The summary is, when submitting a file for NOD submissions, we are using `user.zip` as the zipcode (which uses the users set zip code from their profile). However, it is possible for this value to be unset (`nil`) or erroneously set (`123`)

The fix Robin proposed is to take the zipcode (that is validated and set to `00000` in case of invalid/international zips) from the front end request and use that instead.

I had instead proposed making the `user.zip` method on the back end do a similar type of check so that we dont need to pass the request all the way through here (and in any other place using the `.zip` method). However if we go this way we should make sure we look to see if/where else it is being used and make sure we understand the effects.

This is where it is happening: https://github.com/department-of-veterans-affairs/vets-api/blob/c8a291ef1ef6988773b365ff3666c7e41f45500b/lib/decision_review_v1/service.rb#L361

### Done when

- [ ] A submission with a zipcode of `nil` or of an invalid zip, is not possible.
- [ ] Tests exist to confirm this
- [ ] Any downstream effects of changes are known

**Comment by saderagsdale** [comment]
@data-doge Hey! Are you able to complete this ticket w/o Kyle? If not no worries, I'll move it to the backlog until he returns.

**Comment by saderagsdale** [comment]
Dupe. I copied this to our repo.
