### ISSUE TITLE
Template page names

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2219]
@webinista - wondering if you see any value in keeping the naming consistent for templates? (Meaning, consistent with the way it is now to the future, things should be consistent site-wide) I don't actually know what, for example, `4-action-page` is referring to. I was thinking we might name things more like ...

L2-section-landing
L2-Process
L3-Detail 

If there is rationale or documentation I am missing on what all these are referring to that might change things, but I'm not aware of it. 

Referring to a slew of issues like this:
https://github.com/department-of-veterans-affairs/vets-website/issues/2099

tagging @gnakm for awareness

**Comment by gnakm** [comment]
Adding levels would be super helpful! That's my $0.02

**Comment by webinista** [comment]
@emilyville `1-topic-landing`, `4-action-page` are _current_ values for the `template` property in the Front Matter for each document. Those values track pretty well to page types, even though they're not really being used. 

I have no problem changing the names. This was totally a case of paving the cowpaths.

**Comment by webinista** [comment]
Blocks #2089

**Comment by emilyville** [comment]
@webinista and I chatted IRL and decided to move forward with page templates as they are and we will rename appropriately when we know new names and types!

**Comment by webinista** [comment]
Even though we've closed this, I'm going to use these names. As I mentioned in #2272, I'm realizing that we need a couple more templates.
