### ISSUE TITLE
Getting an icon next to links

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2223]
![screen shot 2016-05-03 at 8 28 08 am](https://cloud.githubusercontent.com/assets/14881302/14988528/1111791c-1109-11e6-81d7-1d419ad69c2c.png)

**Comment by kantrowitz** [comment]
@emilyville Do you know anything about this?

**Comment by lchski** [comment]
It looks like the link URL needs to have `http` at the beginning of it to trigger the icon (which I presume is meant to signify a URL to a different site).

**Comment by emilyville** [comment]
I'm not clear what we're looking for here. 
are you asking how to add the new window icon to a link 
or asking why it's there 
or is something broken?

**Comment by rcarthur** [comment]
@emilyville - I wasn't used to seeing this icon next to links that take us off of vets.gov.  However, now I'm seeing this on every vets.gov page (chrome and firefox) - so it must be intentional.  I'll go ahead and close it out.  Thanks!
