### ISSUE TITLE
new window icon on piano keys is a little special

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2256]
![screen shot 2016-05-04 at 5 21 48 pm](https://cloud.githubusercontent.com/assets/1307774/15033158/c2ce60fc-121c-11e6-879a-217485effcff.png)

Would be great if it were closer in to the text - or it could be we'd like to treat it differently here. Since we might soon be making modifications to piano keys we could also punt on this for now.

**Comment by webinista** [comment]
@emilyville what URL was this on?
