### ISSUE TITLE
Supplemental Claims | Create evidence submission Endpoint to submit evidence to Lighthouse

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/vets-website#22567]
In trying to capture logging for evidence submission, discovered we are currently submitting to EVSS (same as for 526) for evidence submissions. This is not going to work I dont think, we should use the Lighthouse endpoint (like NOD is using)

Most of the backend code to actually DO the submission to lighthouse already exists, it just needs exposed through a route. 

That route is going to be 
`/v1/decision_review_evidence`

currently `/v0/decision_review_evidence` already exists, and is used for NOD only.

We are going to make a V1, that support both NOD and SC submissions, as they are mostly the same, just hit a different lighthouse endpoint.

**Comment by saderagsdale** [comment]
@kylesoskin Moved it to our repo. Here is a [link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48138) to the new ticket.
