### ISSUE TITLE
Make <hr> tags more better flowed in text and find/replace the <br><hr><br>s

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2257]
an example on vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/non-hodgkins

**Comment by webinista** [comment]
Removed the `<br><hr><br>` pattern from affected pages and added styles to the `hr` element. Now it looks like this.

![screen shot 2016-05-06 at 11 30 58 am](https://cloud.githubusercontent.com/assets/354277/15082860/ddc362be-137e-11e6-81ab-9fa3b5b863ca.png)
