### ISSUE TITLE
Eligibility: zombie page

### ISSUE THREAD

**Issue by kantrowitz** [department-of-veterans-affairs/vets-website#2302]
/disability-benefits/eligibility/

and this page, too: /disability-benefits/learn-exposure-to-hazardous-materials_orig/

This page doesn't link to anything. Can we delete it?

**Comment by emilyville** [comment]
yes, we should delete these:
/disability-benefits/eligibility/
/disability-benefits/learn-exposure-to-hazardous-materials_orig/

**Comment by ayaleloehr** [comment]
@emilyville once they are deleted in the repository, ping me and I can also go delete them from the website (they will hang around otherwise...).  _Fixing that is on @joduinn's todo list_

**Comment by webinista** [comment]
@ayaleloehr @joduinn Just merged the change that deletes these files.
