### ISSUE TITLE
Updating links that are not timeless

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#2310]
Is there already a mechanism in place for yearly (or monthly, etc.) reminders to redirect links to updated pages containing new information relevant to the new year? For example, there's a link on the Yellow Ribbon page:
https://www.vets.gov/education/gi-bill/yellow-ribbon/
...that I updated with the following PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/2159/

All I needed to do was change the date in the link, like this:
![screenshot 39](https://cloud.githubusercontent.com/assets/14881910/15086768/f100b43a-1397-11e6-89e1-8bacb2624e97.png)

The question is, how do we remember to revisit these pages that contain links that periodically need updating?

**Comment by bethpotts** [comment]
Assigned this to @ayaleloehr, because I wasn't sure who should take it. Please reassign as appropriate.

**Comment by ayaleloehr** [comment]
Such a mechanism is not in place. I don't have a good solution to this either, especially since updating links automatically without knowing that the ones they are pointing to are actually updated seems pretty dangerous. Going to unassign myself and add this to the backlog.

**Comment by koconnor719** [comment]
not possible
