### ISSUE TITLE
Remove "Mentorship" from VEC description

### ISSUE THREAD

**Issue by cfeeney-va** [department-of-veterans-affairs/vets-website#2329]
On https://www.vets.gov/employment/job-seekers/
Title:
"Wherever you are in the transition process, the Veterans Employment Center provides career advice, mentorship, résumé-building assistance, and exclusive access to employers who are committed to hiring Veterans and military spouses."

Per discussion in slack channel, VEC does not have mentorship opportunities.
@mariana-almeida, would it be ok to remove that word?

**Comment by mariana-almeida** [comment]
@cfeeney-va I'm fine with removing. Thanks for your help!
