### ISSUE TITLE
Increase padding of content cards.

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#2338]
Increase padding of content cards to 1.2em 1.5em to provide more breathing room for the content in the cards. 

**Current padding:**
![image](https://cloud.githubusercontent.com/assets/103496/15233167/69b006b6-185b-11e6-8e74-4c09d68f8d96.png)

**New padding:**
![image](https://cloud.githubusercontent.com/assets/103496/15233157/4c25be38-185b-11e6-91a9-3673d673d4f3.png)

**Comment by emilyville** [comment]
@webinista -- @angel and I are going to work though getting this into a PR tomorrow (as a good excuse to get her local env set up, and we will assign to you for review!
