### ISSUE TITLE
Simplify and consolidate #content .section.xxx styles.

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2356]
Selectors include:
- `#content .section.secondary`
- `#content .section.tertiary`
- `#content .section.quaternary`
- `#content .section.coda`

May also be able to refactor, consolidate, and/or remove 
- `.section.one`
- `.section.two`
- `.section.three`

Selectors.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
