### ISSUE TITLE
Add blue sidebar to pages beyond L2

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#2365]
![image](https://cloud.githubusercontent.com/assets/103496/15412972/f3a0e87e-1de0-11e6-9d88-89ecb0c00d19.png)

**Here are the respective links:** 
Image should click to - https://www.vets.gov/facility-locator/
VA Facility Locator - https://www.vets.gov/facility-locator/
State Veterans Affairs Directors - http://www.va.gov/statedva.htm
County Veterans Service Officers - http://nacvso.org/find-a-service-officer/

**In the future:** 
If there is a phone number associated with the respective page then we'll have the phone assistance section, otherwise it should be left out. 

For the mobile view, the sidebar can drop to the bottom after the main content. 

Here is the map image: 
![va-sidebar-map](https://cloud.githubusercontent.com/assets/103496/15412958/dc85143a-1de0-11e6-8966-40c0036bd2aa.png)

**Comment by Drakenhart** [comment]
I like it, and the light blue is soft enough to avoid a hard-line division between the sections. However, this isn't a current template on the vets.gov site. Will this be new? Or will this replace one of them?

The "Get help with your applications and claims" line - is that a h-tag? If so which one?
Recent work with the 508 office, they pointed out to us that the side bars should have a heading tag of some sort to denote it's "section".

**Comment by emilyville** [comment]
Good point @Drakenhart - we'll need to revisit our templates documentation for this and a few other upcoming additions. we'll file a separate issue for that update and it will be inclusive of a slew of changes.

**Comment by angel** [comment]
@Drakenhart the "Get help with your applications and claims" will be an h4.

**Comment by emilyville** [comment]
We have a (small) design update to this side bar, reassigning to @angel to add the new design

**Comment by angel** [comment]
**Here's the updated style for the sidebar:**

![image](https://cloud.githubusercontent.com/assets/103496/15724225/fc312e3a-27fa-11e6-9fa0-fb080dbbb7ec.png)

We removed the blue from the background and are going to reserve the blue background for "tips". Since there is no blue background now the sidebar content takes the full width. We thought the top header did not add value and decided to remove it.

**We also updated the copy:**
Use the [VA Facility Locator](https://www.vets.gov/facility-locator/) to find a VA facility such as an office, medical center, and clinic. 
[State Veterans Affairs Directors](http://www.va.gov/statedva.htm)
[County Veterans Service Officers](http://nacvso.org/find-a-service-officer/)
[Search for a Veteran Service Organizations](http://www.va.gov/ogc/apps/accreditation/index.asp)

Let me know if you have any questions. Thanks!

**Comment by Drakenhart** [comment]
The "in Person assistance" and the "Phone Assistance" are they h4? Or are these duplicates of the older "Questions" side bar as seen elsewhere?

**Comment by angel** [comment]
@Drakenhart they are h4s.

**Comment by webinista** [comment]
@angel Is this going to be the new box look for _all_ pages, or just L3 (and deeper)?

**Comment by angel** [comment]
@webinista for all pages L2 and deeper.

**Comment by webinista** [comment]
@angel So this affects #2426 as well. Got it.

**Comment by angel** [comment]
@webinista correct! Sorry I forgot to update that issue as well. Thanks for checking!
