### ISSUE TITLE
Pull out breadcrumbs and heading from header to main content

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#2366]
Currently:
![image](https://cloud.githubusercontent.com/assets/103496/15332783/dc4f70f8-1c1b-11e6-8c2b-50bbfc807ed8.png)

Pull out Education heading to the main content and add the breadcrumb above it for L2 and beyond. This will help to navigate users, remove the yellow that will be specific to the crisis line, for the heading to be clearer against the white background, and for the header to be smaller. The current section should be bolded with no underline in the breadcrumbs. 

![image](https://cloud.githubusercontent.com/assets/103496/15333063/f65b60aa-1c1c-11e6-9ebb-1f6eca560334.png)

**Comment by Drakenhart** [comment]
Would this be a new template across all the current templates?
