### ISSUE TITLE
Vets.gov Poster

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#2367]
Design a poster for Vets.gov vision statement

**Comment by emilyville** [comment]
👏

**Comment by gnakm** [comment]
Vets.gov enables veterans to discover,
apply for, track, and manage the benefits
they have earned

**Comment by bethpotts** [comment]
This is very cool! Make sure you capitalize "Veterans."

**Comment by ayaleloehr** [comment]
I'm so excited!

**Comment by gnakm** [comment]
Samples!

![vetsdotgov_poster_vets gov original](https://cloud.githubusercontent.com/assets/13420618/15712223/814606b6-27df-11e6-9d4c-a49e75c2936d.png)

![vetsdotgov_poster_vets gov stack](https://cloud.githubusercontent.com/assets/13420618/15712160/4085a046-27df-11e6-8f38-6a42ede44325.png)

**Comment by gnakm** [comment]
Okay I edited it with the sticker logo that @KHarshawat suggested. 

![vetsdotgov_poster_vets gov original](https://cloud.githubusercontent.com/assets/13420618/15751476/4125365e-28b8-11e6-99fb-7db2f83e5a76.png)

![vetsdotgov_poster_vets gov stack](https://cloud.githubusercontent.com/assets/13420618/15751478/44576d38-28b8-11e6-9a49-5d8ecb37a78e.png)

**Comment by gnakm** [comment]
Closing because desktop and poster versions can now be found here: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Design/Posters
