### ISSUE TITLE
Fix related links regression.

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2378]
Occurring in my local copy. Not sure why.

![screen shot 2016-05-18 at 2 00 49 pm](https://cloud.githubusercontent.com/assets/354277/15374812/f1860708-1d00-11e6-90a5-c532164a9078.png)

**Comment by emilyville** [comment]
closing because this was merged in something before I got to https://github.com/department-of-veterans-affairs/vets-website/pull/2380
