### ISSUE TITLE
Update homepage "How can we help?" heading

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#2385]
Remove the yellow background from the "How we can help?" heading since yellow will be used for the crisis line. Change font to Source Sans Pro and bold to match the heading of all the other pages. 

![image](https://cloud.githubusercontent.com/assets/103496/15413031/8c2c8030-1de1-11e6-90e5-d5777c3d16b1.png)

**Comment by emilyville** [comment]
This will close https://github.com/department-of-veterans-affairs/vets-website/issues/1617

**Comment by emilyville** [comment]
closing this because new homepage is shipping with new title
