### ISSUE TITLE
Is it possible to add VSOs to facility locator?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2394]
Wondering if anyone has pondered adding VSOs to the facility locator, and if that's a thing we've definitively decided or scoped in any way?

@staceylanger @rcarthur @ayaleloehr

**Comment by rcarthur** [comment]
I think that would be awesome - but there are a lot of The (Veteran Service
Officers).

As far as I know this has not been discussed - Rick Lee may know more.

**Comment by emilyville** [comment]
oh! Forgot the other Rick, but you are right, @rcarthur . Adding in @rickleegit, too.

**Comment by rickleegit** [comment]
@emilyville: We have had discussions and undertaken light discover to explore adding a number of facility types such as VSO's and State Departments of Veterans Affairs facilities. Long-term, we may want to take that on, but both represent a significant data issue at the moment. Rendering them on the map is easy, the heavy lift is in finding, standardizing/normalizing, and maintaining the data. 

But both are on the roadmap to explore further.

**Comment by J-Quag** [comment]
The data is owned by OGC if you are wanting to look at Accredited VSOs (They have a view of their database here: http://www.va.gov/ogc/apps/accreditation/). We also use that view within the VSO search within eBenefits. 
However, many of their addresses may not be up to date. We also have emails within eBenefits of all the State Reps for the Request State Benefits information feature, so we could leverage that to get the list of addresses. 
[Sorry this is being added a month later]

**Comment by koconnor719** [comment]
@NatalieEMoore pls. include for enhancements

**Comment by NatalieEMoore** [comment]
This issue was moved in kudos repo.
