### ISSUE TITLE
search accuracy

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2395]
in trying to answer user voice questions, i use our our search a lot, and i think it needs review and improvement.  when i search "claim status" (i'm guessing a common search), i get the results #1 below. when i search "forms" (another popular search) i get results #2 below:  (not sure if this is enhancement or bug if search is not working properly?)

![screen shot 2016-05-20 at 10 33 38 pm](https://cloud.githubusercontent.com/assets/13770771/15446014/dc2107ca-1ede-11e6-98f4-c7aa26f780ab.png)

![screen shot 2016-05-20 at 11 03 47 pm](https://cloud.githubusercontent.com/assets/13770771/15446024/4202e360-1edf-11e6-8c03-5b28cc278a8d.png)

**Comment by ayaleloehr** [comment]
In treating Google as the authoritative source of search quality, this is what comes back when you do a query on "site:vets.gov claim status": https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3Avets.gov%20claim%20status

Our results are very similar to that, although reordered a bit.  So my instinct is that this is not in fact a problem with our search engine, but rather a content and SEO problem.  

With that said, I can manually set up our search engine to respond to specific queries with a "recommended" result at the top, but "claim status" is our 73rd most common search, being searched 9 times in the past month, so I don't think this is where I would start for that. Happy to give anyone access to our search analytics if they want to dig in more or add these "recommended" results.

**Comment by koconnor719** [comment]
If you think it's working properly pls feel free to close. I just didn't think the results were optimal.



Sent with Good (www.good.com)


-----Original Message-----

**Comment by ayaleloehr** [comment]
This is a larger issue now being tracked on our planning board. Going to close here.
