### ISSUE TITLE
Simplify .home #content .section.main-menu selector / margin on .main-menu

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2408]
Margin should not be there at smaller viewports. Caused by `.home #content .section.main-menu` selector, which overrides `.home #content .section` selector. Both should be simplified.

![screen shot 2016-05-25 at 12 11 19](https://cloud.githubusercontent.com/assets/354277/15553015/fa49a37e-2271-11e6-8c96-75aed39f27b0.png)

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
