### ISSUE TITLE
Remove padding on .primary p

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2411]
`.primary p` selector has a `padding-bottom` property of  `1em` which is a lot more spacing than we need (as shown below).

![screen shot 2016-05-26 at 2 37 28 pm](https://cloud.githubusercontent.com/assets/354277/15590986/6c957c2c-234f-11e6-8b0f-aed690b4d3e2.png)

**Comment by jcmeloni** [comment]
Addressed in PR https://github.com/department-of-veterans-affairs/vets-website/pull/4646  will close this issue after merge and not move this issue to vets.gov-team.

**Comment by jcmeloni** [comment]
Merged PR, will close after release.

**Comment by jcmeloni** [comment]
Released 17 Jan 2017
