### ISSUE TITLE
Clean up **<br> to remove the <br>

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2419]
Removing most of the markup from our Markdown means that there's a lot of extraneous HTML that's causing minor layout issues. In particular, this `**Example 2**<br>` syntax is adding extra line breaks.
#### Affected pages
- [ ] _disability-benefits/apply-for-benefits/one-year.md
- [ ] _disability-benefits/claims-process/claim-types/reopened-claim.md 
- [ ] _disability-benefits/claims-process/claim-types/secondary-claim.md 
- [ ] _disability-benefits/claims-process/date.md 
- [ ] _disability-benefits/claims-process/evidence.md
- [ ] _disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/service-outside.md
- [ ] _disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/water-vietnam.md
- [ ] _disability-benefits/conditions/special-claims/convalescence.md 
- [ ] _disability-benefits/conditions/special-claims/hospitalization.md 
- [ ] _disability-benefits/conditions/special-claims/individual-unemployability.md 
- [ ] _disability-benefits/conditions/special-claims/prestabilization.md 
- [ ] _education/gi-bill/survivors-dependent-assistance/fry-scholarship.md
- [ ] _education/other-educational-assistance-programs/veap.md
- [ ] _employment/job-seekers/service-disabled.md

**Comment by jcmeloni** [comment]
Addressed in PR https://github.com/department-of-veterans-affairs/vets-website/pull/4646  will close this issue after merge and not move this issue to vets.gov-team.

**Comment by jcmeloni** [comment]
Merged PR, will close after release.

**Comment by jcmeloni** [comment]
Released 17 Jan 2017
