### ISSUE TITLE
[Main Issue] Document Template Usage

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2421]
Updates to playbook
- Update templates on https://www.vets.gov/playbook/design/templates/
- Update components on https://www.vets.gov/playbook/design/components/
- Suggest/Consider removing this: https://www.vets.gov/playbook/design/code/ and replacing with a link to links to github repos, and guide to how to contribute (via https://github.com/department-of-veterans-affairs/vets-website/issues/682)
- Add forms https://github.com/department-of-veterans-affairs/vets-website/issues/1131

DESIGN For each template:
- (wishlist) Add downloadable design files: https://github.com/department-of-veterans-affairs/vets-website/issues/920
- Usage guidelines for components when necessary

FRONT END
- captured in this main issue https://github.com/department-of-veterans-affairs/vets-website/issues/2089

**Comment by webinista** [comment]
Blocked by #2426 / #2451
