### ISSUE TITLE
L2 Template

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#2426]
**Here are the desktop L2s:**

![l2 1 desktop db](https://cloud.githubusercontent.com/assets/103496/15623400/cf41ee0e-2427-11e6-86b3-6c7de45fd741.jpg)

![l2 1 desktop eb](https://cloud.githubusercontent.com/assets/103496/15623332/542ef9fa-2427-11e6-8159-d7043c200748.jpg)

**Here are the mobile L2s:**

![l2 1 mobile db](https://cloud.githubusercontent.com/assets/103496/15623355/839ddb70-2427-11e6-838f-fe97f46aa5e8.png)

![l2 1 mobile eb](https://cloud.githubusercontent.com/assets/103496/15623356/83a07894-2427-11e6-8324-1c5e3256ce3f.png)

**Comment by webinista** [comment]
Can we actually link directly to State Veterans Affairs Offices and County Veterans Affairs Offices in the Facility Locator?

Tagging @emilyville in case she has an answer for me.

**Comment by webinista** [comment]
@angel Where are the education links supposed to go? It's not immediately clear to me from looking at the link text and pages on the current site.

**Comment by webinista** [comment]
A version of this is almost ready to go in PR #2451. However, we've paused template work for now.

**Comment by webinista** [comment]
No longer relevant.
