### ISSUE TITLE
404 page feels overwhelming

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2439]
https://www.vets.gov/404

![screen shot 2016-05-31 at 4 18 26 pm](https://cloud.githubusercontent.com/assets/1307774/15693645/bb3025da-274b-11e6-91aa-edb865427b3d.png)

Would like a friendlier message for when one lands on this page. Does anyone have 404 messages they like better than "Please try one of the options listed below." when they aren't really options?
The title is a little snug, too.

pinging @crwallace @gnakm @angel for ideas and inspirations!

**Comment by crwallace** [comment]
What do we think about a search box with common questions?

**Comment by crwallace** [comment]
Also what do we think about changing the language to "We could not find the page you are looking for" to change the tone and put the onus on us and not the user/veteran.

**Comment by emilyville** [comment]
So it sounds like changing the yellow bar to "We could not find the page you are looking for." Plus, someday a search bar with common Qs. I only say someday because we don't have common Qs tee'd up - but I think there is some new search work on the horizon and that is an excellent idea.

**Comment by crwallace** [comment]
Oh @emilyville I thought we could use the list of common Qs that we already have with a search bar above it. It would be a ton of work to populate a search bar with common Qs. #FutureState

**Comment by webinista** [comment]
Related to #2385, #2431 and #2440.

**Comment by carlmjohnson** [comment]
When I first saw the 404, my eyes immediately jumped past the yellow bar, because I assumed it was boilerplate "Welcome to Vets.gov" text. Actually, it's the main message for page. I think to get around that, we should introduce a paragraph above "Please try one of the options listed below" that says something to the effect of "The page is missing. Maybe blame whoever linked you here. Try searching." etc. normal 404 text.

**Comment by webinista** [comment]
@crwallace Is it safe to close this PR since the 404 page is being redesigned?

**Comment by emilyville** [comment]
404 has been redesigned! Closing!
