### ISSUE TITLE
Need new map image for L2 templates

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2447]
I need a high resolution version of the generic map image. Please export from Sketch and either attach it to this issue, or add it to the repo in `/assets/images/`. 

Blocks #2426.

**Comment by angel** [comment]
Here's the map. I had it in #2365, but pasted it below. 
![image](https://cloud.githubusercontent.com/assets/103496/15732717/50e3f8e8-2834-11e6-902d-6b8e99cb6f63.png)

Let me know if you need it to be bigger. Thanks!

**Comment by webinista** [comment]
D'oh! Thanks.
