### ISSUE TITLE
Remove Playbook Code Page

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2450]
I think we should remove this page since it is not up to date and I don't know how useful it is to keep it up to date. And if not we should fix the spelling of "Robato" to "Roboto".

https://www.vets.gov/playbook/design/code/

I think there are better ways to make this information available (a link to github, or a how to contribute page, or a very robust readme), or perhaps we trim down the content to be more design focused since it's in the design section.

**Comment by plusjeff** [comment]
Agreed. This page is super out of date. Removing sounds good.

**Comment by goldenmeanie** [comment]
@crwallace I just came back to link to a PR and saw you're working on this. Feel free to ignore mine if you have a better solution in the works!

https://github.com/department-of-veterans-affairs/vets-website/pull/2474

**Comment by plusjeff** [comment]
This page is not very helpful or useful right now. OK to remove this until something better is created.

**Comment by plusjeff** [comment]
This has already happened on https://www.vets.gov/playbook/, will close the other listed PR #2474
