### ISSUE TITLE
Disability section - Contamined water duplicate

### ISSUE THREAD

**Issue by mariana-almeida** [department-of-veterans-affairs/vets-website#2453]
Remove mention of contaminated drinking water from this page. It is covered well in [another section](https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/contaminated-drinking-water-at-camp-lejeune/).

Page: https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/specific-environmental-hazards/
Remove this bullet:
Contaminated drinking water at Camp Lejeune, North Carolina, between 1953 and 1987.

Page: https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/

Update the piano key for Specific Environmental Exposure to remove mention of same:

Exposure to environmental hazards may include particulate matter and large burn pits in Iraq, Afghanistan, and Djibouti; **contaminated drinking water at Camp Lejeune**, North Carolina; and pollutants from a waste incinerator near Atsugi, Japan.

Can you please create PR? Then I can merge for us. Alerting @rcarthur, but Github won't let me actually assign to you.

**Comment by koconnor719** [comment]
@rcarthur can you pls. provide status:)

**Comment by jcmeloni** [comment]
These changes appear to have been made and deployed. cc @koconnor719

**Comment by koconnor719** [comment]
thx julie.
