### ISSUE TITLE
Update Veteran's Crisis Line designs

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2466]
Blocks #2467.

Design task for Veterans Crisis Line.

**Comment by webinista** [comment]
@gnakm Can you update this ticket with the text that's supposed to appear in this panel and the URL for the "For more resources" (?) link.

**Comment by gnakm** [comment]
[Prototype for Desktop](https://marvelapp.com/1c1eb11#12883742)
[Prototype for Mobile](https://marvelapp.com/1c1eb11) 

@webinista We're still trying to change the text. We need to get revision approved from stakeholders. If it's easier to put something as a filler, below are the content:

If you are in crisis or having thoughts of suicide, let us help. For more resources. (https://www.veteranscrisisline.net/) [Text may change]

Call **1-800-273-8255 (press 1)**

Text to **838255**

Confidential Live Chat (https://www.veteranscrisisline.net/ChatTermsOfService.aspx?account=Veterans%20Chat)

**Comment by webinista** [comment]
@gnakm is the URL for Prototype for Mobile correct?

**Comment by gnakm** [comment]
@webinista Yes the URL is correct but here are the new prototypes with the new copy. I just got the go go go from stakeholders. 

[Prototype for desktop](https://marvelapp.com/1c1eb11)
[Prototype for mobile](https://marvelapp.com/1189ab8)

Changes:

- The text has changed and now is at the bottom of the modals: 
If you are in crisis or having thoughts of suicide, 
visit VeteransCrisisLine.net for more resources. [link: https://www.veteranscrisisline.net/]

<img width="342" alt="screen shot 2016-06-09 at 11 53 21 am" src="https://cloud.githubusercontent.com/assets/13420618/15936383/cac492e4-2e38-11e6-9a6c-5921e9091861.png">


- The Confidential Live Chat on mobile will visually no longer have blue hyperlink but still go to https://www.veteranscrisisline.net/ChatTermsOfService.aspx?account=Veterans%20Chat

<img width="381" alt="screen shot 2016-06-09 at 11 53 12 am" src="https://cloud.githubusercontent.com/assets/13420618/15936387/d0c9ebb2-2e38-11e6-8ae3-bfef6e573d76.png">

**Comment by Drakenhart** [comment]
I'm curious - How do they know to touch it? 

Any links need to have at least two forms (accessibility needs). With the flat design it doesn't look button-like. They wouldn't have a hover state either in mobile.

**Comment by webinista** [comment]
@gnakm Have some questions and concerns:

- In the interest of not having more CSS than we need, can we make these lists look more similar by adding (or removing) borders in both places and keeping the text size the same?
- In the _mobile view_, should the entire "Get help from Veterans Crisis Line" bar close the modal when tapped, or just the × icon?

**Comment by gnakm** [comment]
@webinista 
1. If it's not too much trouble, I think having the font size different would be favorable because the 4 options are in a hierarchy of important actions to take. The smaller size description was intentional. 
2. I would also prefer to have the borders only for the mobile because I want to distinguish a defined clickable area for mobile and not give that impression to desktop users. 
3. I think it will be safer to make the whole yellow "get help from VCL" bar close (for people like me with fat fingers and miss clicks). The x can work more as a quick reference point to where to close (less stress and anxiety for users). Good question -- thanks for asking.
