### ISSUE TITLE
Education Counseling page need edit to eligibility 

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2470]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/_education/tools-programs/education-career-counseling.md
## @mollyblake please update eligibility and audience remarks on this page to take into account comments from VR&E SMEs

Misleading – there are many populations that are eligible for these services, as indicated in the “are you eligible for services” section of the page.

**Comment by koconnor719** [comment]
pls. provide status

**Comment by rcarthur** [comment]
@bethpotts this was a somewhat confusing comment from a VR&E SME that is being addressed during the PL rewrite and adjustment that you are making in the eligibility sub-header.   Making you the owner of this so that you're aware.

**Comment by ayaleloehr** [comment]
@rroueche was this already addressed in the plain language rewrite? Can this be closed?

**Comment by rroueche** [comment]
sounds like it to me! cc'ing @bethpotts to make sure before I close! Beth could you confirm?

**Comment by bethpotts** [comment]
This has been addressed. Closing.
