### ISSUE TITLE
Remove RobotoSlab from the Google Fonts API link

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2493]
We're dropping it site-wide. Safe to remove. Don't remove the entire link; Just the RobotoSlab reference.

**Comment by Drakenhart** [comment]
Are you dropping roboto slab entirely? Is it being replaced by anything?

**Comment by webinista** [comment]
Yes, by Source Sans Pro.

**Comment by webinista** [comment]
Duplicates #2674.
