### ISSUE TITLE
Bring Facility Locator in line with new 404, Home page, L2 pages

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2503]
Facility Locator still uses "Crisis Line yellow" in the header. Since we're limiting the use of that yellow to VCL, we should change this header as well. 

![screen shot 2016-06-22 at 3 02 56 pm](https://cloud.githubusercontent.com/assets/354277/16285338/6cc5e07e-388a-11e6-922b-fcbc99f92490.png)

The new header takes up less vertical space. And the page title + breadcrumbs sit below it. See the Disability Benefits page (below) for an example.

![screen shot 2016-06-22 at 3 07 19 pm](https://cloud.githubusercontent.com/assets/354277/16285461/1678edaa-388b-11e6-9ed9-e234f759b748.png)

Assigning to design first. The header + subtitle need to be re-thought. The markup for this header is in `facility-locator/index.html`.

**Comment by webinista** [comment]
Assigned to multiple people. Un-assign or reassign as necessary. @emilyville think of this as an FYI for what's changed, not an actual thing that you need to do obviously :-).

**Comment by crwallace** [comment]
@maryannbrody -- This was not updated with the breadcrumbs. Do you want someone to make a mock up for us to implement so it will look like the rest of the pages/applications?

**Comment by ayaleloehr** [comment]
Facility locator also has no vets.gov search box. not sure if this is expected, but just noticed and thought I would mention it!

**Comment by maryannbrody** [comment]
Yes to all of the above. Let's create a mockup that:
- Includes search
- Addresses the header/breadcrumb issue

We have a redesigned version of FL, but it's still a way's out from implementation, so this makes sense. 

@gnakm // @angel can one of you guys take this and assign to yourself?

**Comment by angel** [comment]
I have this mock:
![vetsdotgov-facility-locator](https://cloud.githubusercontent.com/assets/103496/17035718/c2a86196-4f3d-11e6-8d83-817f23f4a681.jpg)

Let me know if that works.

**Comment by maryannbrody** [comment]
@angel -- wondering if it would be better without the subtext? The two search boxes could be a little confusing but I think it's OK since it's consistent.. 

What do you think?

**Comment by angel** [comment]
@maryannbrody I think it's fine to have the other search box because it is consistent with the rest of the site, treated differently than the second search, and performs a different function. 

Here's what the mock looks like without the subtext:
![l2 facility locator no subtext](https://cloud.githubusercontent.com/assets/103496/17039144/db24ef54-4f4d-11e6-8617-5a3e2895a5ca.jpg)

If the subtext adds no value, I like it without.

**Comment by maryannbrody** [comment]
@angel -- agree -- i like this latest mock without subtext!

Assigning to @crwallace for implementation.

**Comment by crwallace** [comment]
@bshyong -- do you mind tackling this while you are doing 508 compliance stuff?

**Comment by bshyong** [comment]
👍

**Comment by bshyong** [comment]
Update: I will be implementing these changes in the revamped facility locator here https://github.com/department-of-veterans-affairs/vets-website/pull/2913

**Comment by bshyong** [comment]
@crwallace The revamped facility locator will be based on the prototype that Alex put together here (standalone Rails app) https://staging.vets.gov/service-and-facility-locator/search/show?Location=Washington,%20DC&administration=All

It will be built with React and integrated into `vets-website`. The big styling difference here is that the map component is full-width with no padding on the sides.

Here is a quick mock that I put together with Photoshop for changes that I can make to bring the new locator in line with the mock that @angel posted above. How does it look?  I can commit these changes to the `facility-locator` branch if we agree

![new facility locator](https://cloud.githubusercontent.com/assets/303289/18285231/460c1f10-7422-11e6-8acc-dec987c3d960.png)
