### ISSUE TITLE
Simplify #content .main .section.one ul.plain, #content .main .section.one ul.plain li selectors

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2506]
Can probably be simplified to `.va-list-plain` and `.va-list-plain li` selectors.

**Comment by koconnor719** [comment]
is this still an issue?

**Comment by webinista** [comment]
Yes.

**Comment by webinista** [comment]
Close enough to #1781 that this can be closed as a duplicate. Track progress in #4523.
