### ISSUE TITLE
Use permanent redirects from HTTP to HTTPS

### ISSUE THREAD

**Issue by carlmjohnson** [department-of-veterans-affairs/vets-website#2514]
When requesting a page on vets.gov with HTTP, the server issues a redirect (good) but a temporary redirect (suboptimal). Change the redirect kind to 301 Permanent.

**Comment by ayaleloehr** [comment]
Copied this issue into the repo where this work actually will happen. Going to close here.

**Comment by carlmjohnson** [comment]
Which repo is it, FTR?

**Comment by ayaleloehr** [comment]
`devops`

**Comment by carlmjohnson** [comment]
Unfortunately, I'm not able to access that repo yet.
