### ISSUE TITLE
Add RSS feeds

### ISSUE THREAD

**Issue by carlmjohnson** [department-of-veterans-affairs/vets-website#2517]
Improve SEO by adding RSS feeds and registering them with search.digitalgov.gov. 

See http://search.digitalgov.gov/blog/go-live.html for more info.

**Comment by ayaleloehr** [comment]
Not sure I'm understanding the value in vets.gov having an RSS feed? I generally think of RSS feeds for providing content updates (blog posts, articles, etc), whereas we're focused on building new functionality to accomplish tasks. Going to leave open, as I could most certainly be wrong and/or missing something, but wanted to at least document my current thinking!

**Comment by carlmjohnson** [comment]
The value to the search engine is that when we push a new page, the search engine will notice as soon as it pulls down the RSS feed instead of once it has crawled the whole site. Unfortunately, I don't see a simple way to build an RSS feed for our collection pages, so we may not be able to get the full benefit of a feed.
