### ISSUE TITLE
[Main issue] Make CSS more modular

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2518]
Goal: Make it easier to keep `va_common` gem and other projects in sync by making it clearer which portions of the CSS are "globally" required and common to all projects, and which are optional. 

This is simply a tracking issue to which all subsequent tasks should be linked.

**Comment by carlmjohnson** [comment]
I don't know if this is the right place to post CSS blog links, but I found this informative about managing a large site's CSS: https://medium.com/@shaunbent/css-at-bbc-sport-part-1-bab546184e66

**Comment by webinista** [comment]
Yes, [this the direction I am trying to move us in](https://github.com/department-of-veterans-affairs/vets.gov-design/blob/master/README.md).
