### ISSUE TITLE
Split .va-article-l2 specific styles into its own partial

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2520]
Blocks #2518 

`.va-article-l2` styles are specific to content pages. They do not need to be kept in `_va.scss`. 

New partial should include `va-supplement`, `va-supplement-title` styles and `.page-disability, .page-education` styles.

**Comment by koconnor719** [comment]
hi tiffany what is status pls:)

**Comment by webinista** [comment]
Closing. I don't think it's relevant anymore. If it is, it's probably a question for the Vanguard team.
