### ISSUE TITLE
Add OG (open graph) description tags to improve SEO

### ISSUE THREAD

**Issue by carlmjohnson** [department-of-veterans-affairs/vets-website#2527]
The [open graph protocol](http://ogp.me) specifies a description tag. It's used by many other sites to provide a page description. 

Example usage in Slack:

<img width="675" alt="screen shot 2016-06-29 at 2 32 26 pm" src="https://cloud.githubusercontent.com/assets/222245/16464024/5aafbf1e-3e06-11e6-9918-80deae79618f.png">

Page source: `<meta property="og:description" content="You too can automate all the things." />`

We should provide og descriptions for pages wherever possible.

**Comment by webinista** [comment]
We have a plugin for this already. Looks like we just need to add description tags to `includes/_header.html`.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
