### ISSUE TITLE
Breadcrumbs read as buttons

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2533]
One of our stakeholders for HCA was filling out the application and kept clicking on the breadcrumb links at the top thinking they would take them to the application, not realizing they were already on the application page. So they kept getting redirected to the general health care page and going through an endless loop. 

<img width="1095" alt="screen shot 2016-06-30 at 3 28 35 pm" src="https://cloud.githubusercontent.com/assets/3886085/16501481/95731b60-3ed7-11e6-9498-622a6f0e7ed9.png">

I think this is because:
1. The yellow highlighting reads as a button to some people.
2. The header is so tall that it pushes the critical content down on the page so it isn't as noticeable. 

Not quite sure what to do with this feedback, but I thought it was interesting and wanted to pass it along!

@crwallace @gnakm @maryannbrody

**Comment by maryannbrody** [comment]
Hi @akainic - this is a known issue site-wide and we are updating the breadcrumbs accordingly! I will close this issue -- feel free to re-open if needed. cc @crwallace
