### ISSUE TITLE
Add HCA to "Common Questions" on homepage

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/vets-website#2534]
Hey @crwallace --

Can we add "How do I apply for health care?" to the Common Questions list on the homepage?

TY!

**Comment by crwallace** [comment]
Technical Answer: Yes!
Rollout Strategy Answer: I am not sure. @staceylanger @koconnor719 @akainic -- Any thoughts on this?

**Comment by staceylanger** [comment]
From my perspective, this can be added anytime.

**Comment by crwallace** [comment]
I will put this on my todo list for tomorrow.

**Comment by koconnor719** [comment]
awesome!  i think it will be great to have it there as well!

**Comment by crwallace** [comment]
This is all done!

<img width="749" alt="screen shot 2016-07-06 at 6 20 28 pm" src="https://cloud.githubusercontent.com/assets/3453669/16636515/8baf5f70-43a6-11e6-97cc-2c4c72a1b87f.png">
