### ISSUE TITLE
Google Analytics for Health Care App

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2541]
@koconnor719  @maryannbrody @mariana-almeida 

From 7/7 Web Comms Meeting:  the question came up of where users are coming from when they arrive on the health care app.  @plusjeff who is the person to assign this to?

**Comment by akainic** [comment]
@rcarthur: @irenejlee is going to be tracking analytics for HCA, so I think she's the best person to assign this to. @plusjeff correct me if I'm wrong!

**Comment by irenejlee** [comment]
Hey @rcarthur let's connect on this!

**Comment by koconnor719** [comment]
irene,

we just need to set up GA so that we can track where traffic is coming from to HCA.  thanks.

**Comment by koconnor719** [comment]
@irenejlee i think you are aware but this is super high visibility task:)  these numbers will go to Sec and Dep Sec daily--and then from there--to congress--press--VSOs etc...just making you aware.

**Comment by jcmeloni** [comment]
@akainic @koconnor719  I think HCA is all good re: GA -- please confirm and I'll close this.

**Comment by koconnor719** [comment]
yes.  this is closed from my perspective.  anne, pls. reopen if more items?  or assign directly to dan.
