### ISSUE TITLE
Google Analytics for Veteran Crisis Line

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2542]
per previous convos; need to provide Sec and Dep Sec office with GA on VCL from homepage pls:)

we meet w/ Sloan next week (7/12); can we get this resolved by then?  :) 

i'm marking as a bug b/c it seems like we should be able to get GA for all vets.gov stuff right??
@staceylanger @maryannbrody @gnakm

**Comment by joduinn** [comment]
Notes from detective work earlier this week. There are actually two ways to get from vets.gov to https://www.veteranscrisisline.net:

1) Click on "Contact the Veterans Crisis Line" text link to get to https://www.veteranscrisisline.net/.

2) Click on yellow popup button on bottom of the vets.gov home page. This shows you a (800)number, an SMS number and also a link to https://www.veteranscrisisline.net/.

Both of these will allow a human to get to an external https://www.veteranscrisisline.net/ site. We need to count both possible paths. 

Personally, I'd like to move the yellow button up to top of page, where it is more findable, and simply remove the duplicate text-only link... but while that discussion continues elsewhere, we need to track both possible paths.

fyi: @suzchap, @gnakm

**Comment by koconnor719** [comment]
@suzchap i think i saw a response from you on this??  can you add to this issue so it's all in one place pls:)

we need to provide Dep Sec numbers on this when we meet w/ him later this week.  can you guys prioritize this so we can get Google Analytics on VCL going forward?

**Comment by koconnor719** [comment]
@suzchap i think you had a comment on VCL stats w/ Google Analytics?  somewhere:)  can you post here so it's all in one place? 

we need to report stats to Dep Sec this week.  can you guys pls. advise?  not sure what to do from here?  :)  thx.

**Comment by koconnor719** [comment]
[analytics_all_web_site_data_crisis_hotline_test_20160607-20160707__1_.pdf](https://github.com/department-of-veterans-affairs/vets-website/files/359959/analytics_all_web_site_data_crisis_hotline_test_20160607-20160707__1_.pdf)

**Comment by koconnor719** [comment]
request from VCL team for access to this report; suzanne following up.

**Comment by koconnor719** [comment]
suzanne, is this done? should it be closed?  i thought @akainic mentioned she was doing work on this??

**Comment by suzchap** [comment]
VCL team now receiving daily reports so that is done. @akainic is going to do some fine-tuning to add ability to track when the popup is opened and closed.

**Comment by jcmeloni** [comment]
@akainic Did you add that fine-tuning referenced above such that we can close this? Thanks!

**Comment by akainic** [comment]
My understanding is that this is already done? I never pushed any fine tuning changes, but I thought it was handled by Bob and Dan's analytics push. @suzchap should be able to confirm?

**Comment by suzchap** [comment]
@jcmeloni As far as I can tell, we still aren't tracking when the VCL menu is toggled open/closed, only when a link is clicked. Maybe I submit that as a new request to the analytics team and we can close this issue?

**Comment by jcmeloni** [comment]
@suzchap sounds awesome

**Comment by suzchap** [comment]
@jcmeloni ok, I submitted a request for this via the analytics slack channel and Dan Hoicowitz said he'd create a ticket. So I think you can close this now.

**Comment by jcmeloni** [comment]
thanks!
