### ISSUE TITLE
Content change to Digital Gov Search "zero results" page

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/vets-website#2552]
Hey @dannychapman -- 

Can you tweak the language on the zero search results page a tiny bit to:

> Sorry, no results found for '[**term**]'. Try again using different (or fewer) words.

(Note **bolding** of the search term.) 

Thank you!

**Comment by dannychapman** [comment]
Just looked into this. @maryannbrody - Unfortunately we can't control that text that way. Adding to the list for API integration.

**Comment by dannychapman** [comment]
Closing for now, will revisit.
