### ISSUE TITLE
Add a CSS rule that makes an exceptions for links that point to vets.gov pages

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2553]
In `_sass/components/_va-playbook.scss` on line 3, there's a selector that begins with `[href^=http] {` that adds an external link icon to links that begin with `http` (includes `https`). 

Should narrow the scope of this rule so that it doesn't affect links that begin with `https://vets.gov`. Someone is going to mess that up and use a full link.

Related to #2522/#2519

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
