### ISSUE TITLE
Footer on VEC page not displaying VCL correctly

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2555]
@gnakm 

I think you are already aware of different footers on products; pls. review the VEC footer https://www.vets.gov/employment/veterans/235834 as the VCL updates we just made have not been updated here (veterans can't call, text, or chat from homepage).  Footer is different--with feedback on the right side, not left. 

![screen shot 2016-07-12 at 11 00 44 pm](https://cloud.githubusercontent.com/assets/13770771/16790488/7fc6fabe-4884-11e6-99af-8fed331112d0.png)

**Comment by webinista** [comment]
@koconnor719 Keep an eye on department-of-veterans-affairs/veterans-employment-center#340. I believe @crwallace is working on this now.

**Comment by crwallace** [comment]
@koconnor719 -- This was just updated with the VEC deploy today. Closing this issue.
