### ISSUE TITLE
Two green buttons?

### ISSUE THREAD

**Issue by joduinn** [department-of-veterans-affairs/vets-website#2560]
I just noticed that https://www.vets.gov/healthcare/apply/ shows me two green buttons. "Apply Online for VA Health Care" and "Apply for VA Health Care". 

This seems confusing and they both go to the same URL, so can we remove one? 
![screen shot 2016-07-14 at 2 02 00 pm](https://cloud.githubusercontent.com/assets/714805/16855800/dafdec10-49cb-11e6-8ea1-683156087f65.png)

**Comment by webinista** [comment]
@crwallace Assigning to you with the understanding that you'll delegate as appropriate.

**Comment by crwallace** [comment]
@joduinn This was a design team decision to keep both. I think this pattern will change with the new templates but as it stand now they will both stay. Feel free to chat with more about this with @maryannbrody. But for now I am closing this issue.
