### ISSUE TITLE
Simple-Forms - 'ui:title' & 'ui:description' behavior/structure follow-up

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/vets-website#25626]
## Description

There are some issues with the current forms-library support of 'ui:title' (field-label) & 'ui:description' (field-description/-hint-text) uiSchema properties: 

1. If `'ui:title'` contains JSX with an `<h3>` tag, the `<h3>` gets pulled into the Review page causing a11y headers-hierachy bugs.
2. `'ui:description'` is not being read by screen-readers \[[#64780](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64780)\]
3. While avoiding `'ui:description'` and injecting description-text into `'ui:title'` fixes the screen-reader-bypass bug, this introduces a different issue with required-span positioning bug &mdash; forms-lib displays it below the description-line but Designer needs it above [next to label-text] &mdash; which required custom-styling for a manually-injected required-span and hiding the incorrectly-positioned required-span that forms-lib injected.

We have existing workarounds for all these issues in PR25581 for 21-0845, and this ticket is for fixing these issues inside form-library, for ALL existing forms \[assuming Pat & Platform agrees we want consistency across-the-board\].

**Comment by tlei123** [comment]
@rhasselle-oddball , the first thing to do, as we discussed this morning, is for us to determine the exactly behavior of default `'ui_description'` support/behacior in our current forms-library.  Whoever finishes research and has some info can update here with a new Comment \[or edit main description above\].

**Comment by 07-Chandra** [comment]
can you please assign this to me ?
