### ISSUE TITLE
Stub out 4 new vets.gov pages

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#2569]
@crwallace @dannychapman Thank you for stubbing out these four pages. 

[For.Stubbing.Disability_Have_A_Rating_07_20160719 (1).docx](https://github.com/department-of-veterans-affairs/vets-website/files/374357/For.Stubbing.Disability_Have_A_Rating_07_20160719.1.docx)
[For.Stubbing.Disability_WhattoExpectatYourCPExam_draft10_2016-07-15.docx](https://github.com/department-of-veterans-affairs/vets-website/files/374359/For.Stubbing.Disability_WhattoExpectatYourCPExam_draft10_2016-07-15.docx)
[For.Stubbing.ReviewforCorrection_Draft12_20160720.docx](https://github.com/department-of-veterans-affairs/vets-website/files/374622/For.Stubbing.ReviewforCorrection_Draft12_20160720.docx)
[For.Stubbing.ReviewForDischargeUpgrade_Draft14_20160720.docx](https://github.com/department-of-veterans-affairs/vets-website/files/374626/For.Stubbing.ReviewForDischargeUpgrade_Draft14_20160720.docx)

**Comment by maryannbrody** [comment]
Thanks, @bethpotts -- What is the thinking behind /review-dd214/ in the IA? I understand there isn't anywhere else to put it right now -- so just curious how we chose that and what we think it will become.. thanks!

**Comment by bethpotts** [comment]
Well, @maryannbrody I'm so glad you asked because I just learned that these pages started out as one originally and were broken into two. So /review-dd214/ is a holdover and should have been deleted! It is superfluous. I'll go fix that relative link everywhere it appears. Thank you for asking the question!!
@dannychapman @crwallace If you two could hold off for now, I'll reupload those four docs with the links corrected.

**Comment by bethpotts** [comment]
OK @dannychapman and @crwallace I have reuploaded the four docs above. Those are the correct ones with the relative links fixed! Thank you for your patience and for your help getting the pages stubbed.

**Comment by maryannbrody** [comment]
@bethpotts -- 

Thanks for clarifying. I'd like to make two changes here:

1. Let's put the 2 disability pages here: https://www.vets.gov/disability-benefits/claims-process/ instead of on the disability landing page. 
2. Let's hold off on publishing the other 2 pages. I don't think it makes sense to publish these if they don't have a home. I think we'll get into trouble down the line if we're adding pages at the second level (meaning homepage/[page]) without any intention of them ever being accessible from the homepage. Sorry to have not caught this sooner!!!

Let's chat in the other issue about if we'll need to follow up with our VA partners about these changes. 

Thank you!!

**Comment by jcmeloni** [comment]
@maryannbrody Is there action to take still on this old issue?

**Comment by maryannbrody** [comment]
@bethpotts -- is this stuff tracked in the content repo? If so, please close here so we don't have duplicates. 

cc: @rroueche

**Comment by ayaleloehr** [comment]
pinging @rroueche . can this be closed?

**Comment by rroueche** [comment]
@bethpotts do we have this content tracked/saved somewhere else? I'd like to close this issue, but don't want to lose access to those 4 files if we still might need them in the future.

**Comment by bethpotts** [comment]
@rroueche 
1) "Have a Rating" is already live on the site (now called "What to Expect after You Get a Disability Rating" located here: /disability-benefits/claims-process/what-happens-after-rating/)

2) "What to Expect at Your C&P Exam" is with SMEs and has been paused for a while. It is now titled "VA Claim Exam (C&P Exam)" You created a separate issue for this a couple months ago called "Integrate Feedback from SMEs on new Claim Exam page" that's in the backlog. I'll upload the version I sent SMEs to that issue.

3) Review for Correction and Review for Discharge (2 separate topics/pages). Mary Ann had us pause on these a while ago. You created a separate issue for these a couple months ago called "Discharge Upgrades and Corrections" to which I'll upload the latest versions of each.

**Comment by ayaleloehr** [comment]
@bethpotts 's last comment says to close, so I'm going to. cc @rroueche for awareness.
