### ISSUE TITLE
Inconsistent IA naming conventions in existing section URLs

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#2570]
L2 pages (the disability section is the only one that has "benefits"):
/disability-benefits
/education
/employment
/healthcare

L3 pages (all three apply conventions are different):
/disability-benefits/apply-for-benefits
/education/apply-for-education-benefits
/healthcare/apply

**Comment by jcmeloni** [comment]
@bethpotts Is there still action you want to take on this old issue? Thanks!

**Comment by rroueche** [comment]
@bethpotts I'm scheduling a meeting for us with Mikki wherein we'll discuss this plus other IA + Content alignment topics. Putting on hold until we have that conversation.

**Comment by rroueche** [comment]
@bethpotts does Mikki's proposed IA address this, or are there still inconsistencies in that short-term future state that we should discuss?

**Comment by ayaleloehr** [comment]
@rroueche should this be closed?

**Comment by bethpotts** [comment]
@rroueche The apply pages are now consistent, but disability remains inconsistent from the rest of the L2 pages. I'm not sure who is the appropriate person to address this, or how much of a priority it is:
L2 pages (the disability section is the only one that has "benefits"):
/disability-benefits
/education
/employment
/healthcare

**Comment by rroueche** [comment]
@ayaleloehr can we keep this in the icebox so we don't lose track of the need? I anticipate we'll come back to it around summer time and add some other breadcrumbs and nav-related tweaks we'll want to make.

**Comment by ayaleloehr** [comment]
No problem. 

Actual question: is this repo where you're keeping the Content icebox or is the content work mostly being tracked elsewhere?

**Comment by rroueche** [comment]
ah I didn't notice it was in this repo - yeah I'll close this one and move it over. thanks for the heads up!
