### ISSUE TITLE
[Rx] RefillApp component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2571]
This is the base application task component that wraps the following components.

Component should contain (blocked by):
- AlertBox component (#2572)
- TabNav component (#2573)
- ActivePrescriptionsPage component (#2575)
- RxHistoryPage (#2583)
- MyOrdersPage (#2629)

### Prototypes

- [Desktop](https://marvelapp.com/276d4he)
- [Mobile](https://marvelapp.com/277c9c1)

**Comment by akainic** [comment]
This is the top level component for the application. It is equivalent to the `HealthCareApp` component in HCA: https://github.com/department-of-veterans-affairs/healthcare-application/blob/master/src/client/components/HealthCareApp.jsx

**Comment by webinista** [comment]
I feel comfortable closing this. It's not 100% done. We still have child components to add to this component. But I think it's done _enough_ to warrant closing this issue.
