### ISSUE TITLE
[Rx] TrackInfoPendingFlag component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2579]
Blocks #2576 

<img width="332" alt="screen shot 2016-07-20 at 1 05 42 pm" src="https://cloud.githubusercontent.com/assets/354277/17001159/b5d55b04-4e7a-11e6-805d-56c33c6ae0c6.png">

**Comment by webinista** [comment]
@gnakm @goldenmeanie Am I correct that this component has been removed from the project? Can this issue be closed?

**Comment by gnakm** [comment]
@webinista Yes and all icons are removed as well!
