### ISSUE TITLE
[Rx] RxHistoryPage component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2583]
Blocks by #2571 

**Contains / blocked by:**
 
- GrowableTable component (#2584)
- Pagination component (#2585)

**Comment by akainic** [comment]
Equivalent to any of the section components in HCA, like for instance `InsuranceInformationSection`: https://github.com/department-of-veterans-affairs/healthcare-application/blob/master/src/client/components/insurance-information/InsuranceInformationSection.jsx
