### ISSUE TITLE
[Rx] Pagination Component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2585]
<img width="284" alt="screen shot 2016-07-20 at 3 14 23 pm" src="https://cloud.githubusercontent.com/assets/354277/17005010/b70a4ac2-4e8c-11e6-9e98-687ea711cdcb.png">

- Blocks GrowableTable (#2584) 
- Blocks RxHistoryPage (#2583) 

### Questions: 

- How best to show up to 10 pages on desktop and up to 5 on mobile?

**Comment by webinista** [comment]
Going to take this on, at least the CSS and HTML portions of it. Might take the API integration portion too, depending on how much progress you made @alexose.

**Comment by alexose** [comment]
Haven't done anything so far!

Before we get too deep into this, let's make sure there isn't already a well supported react library out there that fits the bill (thinking http://griddlegriddle.github.io/Griddle/)
