### ISSUE TITLE
Header on home page bigger than every other page

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#2597]
With the launch of new breadcrumbs, the header on the vets.gov home page is way bigger than every other page.  Can this be made consistent? 

Home page:
![screen shot 2016-07-21 at 1 10 53 pm](https://cloud.githubusercontent.com/assets/4719765/17031938/a75f7fb2-4f44-11e6-8743-2be757ee3592.png)

Other pages:
![screen shot 2016-07-21 at 1 11 09 pm](https://cloud.githubusercontent.com/assets/4719765/17031941/abd62a8c-4f44-11e6-8e7d-c216f0939d1c.png)

**Comment by jcmeloni** [comment]
@ayaleloehr I think this is moot, so closing.  Reopen and smack me if you think that's an incorrect move. Thanks!
