### ISSUE TITLE
Radio Widget Selection Changes Focus to Unrelated Area of Page

### ISSUE THREAD

**Issue by adam-antonioli** [department-of-veterans-affairs/vets-website#25985]
### Description: 

When interacting with a radio widget on a form review page which has options which change other parts of the page (using `depends`), the page focus changes to the top (or sometimes bottom) of the form instead of remaining on the radio widget.

**Specific example:**
When switching from Veteran to Sponsor in the Applicant Information section on (VA Form 40-10007: Apply for Pre-need Eligibility Determination) review page, focus is lost causing focus to shift to body instead of application accordion.

### Steps to reproduce specific example:

1. Begin the application (VA Form 40-10007: Apply for Pre-need Eligibility Determination) signed in or without signing in
2. On the first page fill out form and select the I am the service member/veteran radio button under the Relationship to veteran question
3. Continue to fill out the form until you reach the review page
4. Open the Applicant Information accordion
5. Click edit on the Applicant Information section
6. On the Relationship to veteran question click an option besides the one made in STEP 2
7. Observe page jump to the very top of the page

### Expected results:

When clicking any option of a radio widget, the focus should remain on the widget.

**Concerning specific example:**
When user selects a different radio option, the focus should jump to the Applicant information accordion.

### Actual Results:

When clicking any option of a radio widget which changes the page, the focus changes to unrelated parts of the page (away from the radio widget).

**Concerning specific example:**
When user selects a different radio option, the page jumps to the top of the page.

### Demonstration of issue:

**Example 1 (VA Form 40-10007: Apply for Pre-need Eligibility Determination):**

![4qewtfic](https://github.com/department-of-veterans-affairs/vets-website/assets/132934480/c2ccbd72-7dbf-4391-9c76-3c03a0dfd198)

**Example 2 (VA Form 21-0972: Alternate Signer Certification):**

![3txo2nty](https://github.com/department-of-veterans-affairs/vets-website/assets/132934480/cf6c91fc-c884-4a4c-9223-67fe5d45525c)

**Comment by theavitw** [comment]
@ndsprinkle hey,
Can you please assign me.
I will fix it.

**Comment by MichelleDieudonne** [comment]
For Self-Service reference only - this relates to our blocked Jira item - https://jira.devops.va.gov/browse/MBMS-46159.

**Comment by 07-Chandra** [comment]
can you assign this to me so that i can work and fix quickly ?

**Comment by itstiesto** [comment]
Please assign this to me..
