### ISSUE TITLE
[Rx] Incorporate Google Analytics

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2604]

**Comment by webinista** [comment]
I added this as a task because it's typical for most projects. I suspect there may be patient privacy concerns though. @staceylanger @ayaleloehr can one of you weigh in here (and closing the issue if appropriate)?

**Comment by ayaleloehr** [comment]
Going to leave this issue open, as we still need to set up Rx to work with Google Tag Manager.  Per the patient privacy issue, I think we should be fine if we just track metrics globally, such as total number of times the refill button was clicked. 

@rickleegit wrote up some documentation on this once [here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/analytics_procedure/readme.md) and @akainic had to do this for HCA and I know has some thoughts as well. Not a priority for this week, but definitely before launch.

**Comment by ayaleloehr** [comment]
@robertfairhead I believe you have done this and there is no further action needed. Can you confirm, and if so, close please!

**Comment by robertfairhead** [comment]
Yes, Rx is incorporated in google analytics. we scrub any unique IDs in the URLs (e.g., prescription numbers) just in case.
