### ISSUE TITLE
remove vets.gov blog

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2613]
team decision at leads meeting 7/19/16 to remove blog from vets.gov.

**Comment by webinista** [comment]
A suggested check list of tasks.

- [ ] Removing _Blog_ link from footer (the minimum we should do)

- [ ] Delete `experience/` from repo
- [ ] Delete `_posts/` from repo
- [ ] Delete the following files from S3 bucket and URLs from search
  - [ ] `/2016/05/17/when-high-bounce-rate-may-be-a-good-thing.html`
  - [ ] `/2016/03/02/designing-for-veterans.html`
  - [ ] `/2016/04/01/responsive-web-design-podcast.html`
  - [ ] `/2015/11/11/why-we-are-designing-in-beta.html`
- [ ] Remove `va-headingflag`, `splash--blog`, and other blog-specific CSS blocks.

**Comment by crwallace** [comment]
@koconnor719 -- Is this still relevant? Should we remove the blog?

**Comment by koconnor719** [comment]
we made that decision about 3  weeks ago--so i'd say yes if @maryannbrody @staceylanger @plusjeff are ok w/ removing it?  we need to keep sec message somewhere.

i don't think this is urgent--but def part of the site redesign you guys are doing.   so whenever the timing makes sense.  what do you think?  also, i think we might want to check w/ martin too?  i have not yet, but can do that today.

**Comment by MarinaMartin** [comment]
👍

**Comment by staceylanger** [comment]
Good to be removed. Thanks!
