### ISSUE TITLE
[Rx] TableRow component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2614]
Blocks #2584.

**Comment by akainic** [comment]
The way this will work is that we'll have a component for a single row of the table, similar to how HCA has a component for a single provider: https://github.com/department-of-veterans-affairs/healthcare-application/blob/master/src/client/components/insurance-information/Provider.jsx. 

Then, we pass this component to `GrowableTable` as we did in the insurance section of HCA: https://github.com/department-of-veterans-affairs/healthcare-application/blob/master/src/client/components/insurance-information/InsuranceInformationSection.jsx. Then `GrowableTable` will iterate through list of prescriptions (in this case) and will create a table row component for each one.
