### ISSUE TITLE
[Rx] TableHeader component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2615]
Blocks #2584

Table header with sorting arrows that, when clicked, sort the table by that row's property in ascending or descending order.

**Prototypes** 
- [Desktop](https://marvelapp.com/1h10heg#14227014)
- [Mobile](https://marvelapp.com/iaa9b9#14230873)

**Comment by akainic** [comment]
Just a single component for the table header. No equivalent in HCA.

**Comment by webinista** [comment]
Assigning to Eugene because he's working on them as part of #2583
