### ISSUE TITLE
Complete Interface Audit for vets.gov

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2632]
This should be similar to a content inventory, only instead of sifting through and categorizing content, please take stock and categorize the components making up our website and apps.

Let us know what is different, not-working or not on brand.

**Comment by melwoodard** [comment]
Interface audit findings can be found here: [https://github.com/department-of-veterans-affairs/vets.gov-frontend/tree/interface-audit/docs/interface-audit](https://github.com/department-of-veterans-affairs/vets.gov-frontend/tree/interface-audit/docs/interface-audit)
