### ISSUE TITLE
Change Veteran's Crisis Line mobile trigger from `a` to `button`

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2634]
Most screen readers announce links as links, which can be confusing. This would be better as a `button` element

Code in question is in `_includes/footer.html`. Change

`<a href="#modal-crisisline" class="va-crisis-line va-crisis-line--touch va-overlay-trigger">Get help from Veterans Crisis Line</a>`

to:

`<button data-show="#modal-crisisline" class="va-crisis-line va-crisis-line--touch va-overlay-trigger">Get help from Veterans Crisis Line</button>`

**Comment by jcmeloni** [comment]
@crwallace This is still an `a` -- did it get flagged by 508 folks such that you want to change this, or shall we close?

**Comment by webinista** [comment]
Fixed with a241d5b. 

According to [someone who knows (aardrian, a longtime accessibility advocate)](https://stackoverflow.com/questions/38594369/is-it-more-accessible-to-use-a-button-or-a-to-open-close-a-modal/38619310) more about a11y than I do: `button` elements can be activated using the space bar or enter key. 

And according to the comment by slugolicious below it, `button` is treated differently by screen readers, placing it in a button menu, not a link menu. Since this isn't taking users to a new page, just showing a new view, I think makes more sense to use a `button` element.
