### ISSUE TITLE
Maintenance mode page is outdated

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#2637]
It's still in production, but outdated. Can we get this updated?  https://www.vets.gov/maintenance.html

We will need to put up this page when we move VEC from AWS East to GovCloud, which we're hoping to do ASAP. 

cc @maryannbrody

**Comment by ayaleloehr** [comment]
Or is this what we want it to look like?  If so, that's fine too. but definitely wanted to check!

**Comment by crwallace** [comment]
This is def not what we want it to look like. I will check in with Mel
about getting something better up. What is your best guess timeframe on
moving to GovCloud?

**Comment by ayaleloehr** [comment]
@crwallace we will be deploying mid day Monday 8/8.

**Comment by ayaleloehr** [comment]
Just want to make sure this doesn't get lost in the shuffle. And saw @bshyong doing some 404 work today, which I believe is likely similar, so tagging for awareness.

**Comment by crwallace** [comment]
Yes this hasn't been lost. This will go up today as I am going to use the
same design as we have for the HCA maintenance page.
