### ISSUE TITLE
Team confirmation for codeowners

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/vets-website#26491]
### Description
Looks like we have four teams that either have been remove or have not been added to `vets-website`` codeowners`, this caused a minor error to be thrown during a PR's CI. Could someone confirm the existence, and name of the following teams and either remove them from the codeowners file or add them to GH so that they dint show up as "missing" 

- Unknown owner on line 177: make sure the team @department-of-veterans-affairs/vfs-mhv-medications exists, is publicly visible, and has write access to the repository …/applications/mhv/medications @department-of-veterans-affairs/vfs-mhv-medications @department-of-veterans-affairs/va-platform-cop-frontend
- Unknown owner on line 196: make sure the team @department-of-veterans-affairs/benefits-dependents-management exists, is publicly visible, and has write access to the repository …pages/dependency-verification @department-of-veterans-affairs/benefits-dependents-management @department-of-veterans-affairs/va-platform-cop-frontend
- Unknown owner on line 197: make sure the team @department-of-veterans-affairs/benefits-dependents-management exists, is publicly visible, and has write access to the repository …c-pages/view-modify-dependent @department-of-veterans-affairs/benefits-dependents-management @department-of-veterans-affairs/va-platform-cop-frontend
- Unknown owner on line 198: make sure the team @department-of-veterans-affairs/benefits-dependents-management exists, is publicly visible, and has write access to the repository -pages/view-modify-dependents @department-of-veterans-affairs/benefits-dependents-management @department-of-veterans-affairs/va-platform-cop-frontend

**Comment by acrollet** [comment]
@rmessina1010 the mhv medications team does exist but I don't have enough privs to add vets-website to it, are you able to?

https://github.com/orgs/department-of-veterans-affairs/teams/vfs-mhv-medications/repositories
