### ISSUE TITLE
[Rx] ActivePrescriptionsSort component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2653]
Should re-sort ActivePrescriptions list based on Prescription name, Facility name, or Last Requested (not last-refilled) date.  

<img width="482" alt="screen shot 2016-08-04 at 9 51 44 am" src="https://cloud.githubusercontent.com/assets/354277/17410563/2340375e-5a29-11e6-8d80-532e025433a8.png">

<img width="228" alt="screen shot 2016-08-04 at 9 52 31 am" src="https://cloud.githubusercontent.com/assets/354277/17410604/4525ba6a-5a29-11e6-947e-440497655330.png">

### Prototypes 

- [Mobile](https://marvelapp.com/iaa9b9#14230873)
- [Desktop](https://marvelapp.com/1h10heg#14227013)

Desktop view is a link list. Mobile view uses a drop down. 

Blocks #2575

**Comment by ayaleloehr** [comment]
If active prescriptions are on multiple pages, then I believe re-sorting would have to happen via an API call, as we would want to sort on the whole data set and not just on the current page. Yes?

**Comment by webinista** [comment]
I think Active Prescriptions are only shown on the _Refill Active Prescriptions_ page. That's what it looks like in the latest prototype.

**Comment by ayaleloehr** [comment]
@gnakm on the Refill Active Prescriptions page, are all the active prescriptions shown, or just like the first X active prescriptions with links to more pages?

**Comment by webinista** [comment]
Component is complete, but need the sorting functionality, which is being tracked with #2710.
