### ISSUE TITLE
Remove duplicate headings

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2660]
@melwoodard -- Wasn't sure if we saw this duplicate heading. But I am sure that it needs to be removed.

<img width="1436" alt="screen shot 2016-08-05 at 10 48 18 am" src="https://cloud.githubusercontent.com/assets/3453669/17440444/a5c7f744-5afa-11e6-8ce7-8f498221e134.png">

**Comment by melwoodard** [comment]
@crwallace definitely, forgot to pull that one out of my list for fixing. All of the exposure site pages have this issue.

**Comment by crwallace** [comment]
Sounds good. Just to be clear @melwoodard your recommendation is to pull the gray box heading and leave the other heading?

**Comment by melwoodard** [comment]
Correct

**Comment by crwallace** [comment]
@melwoodard -- I think this was taken care of partially in the vets-website migration and in some of @bshyong 's clean up. Closing this for now.
