### ISSUE TITLE
[CST] Increase test coverage to 80% for Claim Cards V2

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/vets-website#26622]

**Comment by HeatherWidmont** [comment]
Will probably be done before the sprint review today. @samcoforma & @jerekshoe to discuss in today's parking lot

**Comment by HeatherWidmont** [comment]
@jerekshoe to review today

**Comment by HeatherWidmont** [comment]
@jerekshoe & @samcoforma to discuss one last thing in the parking lot today
