### ISSUE TITLE
Team is not being transparent enough

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#2670]
We should have a blog or wiki or something that explains some of our development practices and decisions. Primary audience is both "future us" and other agencies (federal and otherwise) who may be pursuing similar projects.

Examples might be questions that come up constantly like "What are you doing for rural users?" and perhaps short case studies of each major product.

**Comment by ayaleloehr** [comment]
Agreed. Per #2613 this shouldn't be on vets.gov, but should be somewhere.

**Comment by jcmeloni** [comment]
@MarinaMartin @plusjeff @ayaleloehr Is the content in the vets.gov-team repo re: How We Work (and related) sufficient or shall we keep this open/move it to an issue in the vets.gov-team repo?

**Comment by MarinaMartin** [comment]
@jcmeloni I would like to see the team be more transparent to external audiences, especially potential team members.

**Comment by jcmeloni** [comment]
@ayaleloehr @plusjeff Please move to team repo and label as you see fit.

**Comment by plusjeff** [comment]
Will leave this to @ayaleloehr . Not sure if this is for just vets.gov or USDS@VA. If USDS@VA, then I think this is covered by usds.gov and the Medium blog.

**Comment by ayaleloehr** [comment]
USDS HQ tells us blogs are easy to write now. Anyone have great ideas for what we should write about?

**Comment by jcmeloni-usds** [comment]
I believe @raquelromano-gov is working on one; I'm working on one re: identity.

**Comment by raquelromano-gov** [comment]
ha...no, I'm not! Yay for one about identity @jcmeloni--I was wondering if that would be a good idea, or if we would have to explain why we're not using login.gov  (but maybe explaining that is fine)

@annekainicUSDS is working on one with @jbalboni about react-json-schema-form...yay, again

My idea was to appeal to candidates who would choose a startup over USDS b/c they want to work on modern software stacks in modern environments and don't think that's possible in government, but @CyberKoz thinks that would be super boring

In any case, I think DSVA is in a better position than other agency teams to share technical stuff externally and possibly attract engineers who see the impact but think their skills will get rusty here so don't even consider it, so glad to see there are 2 in the works!

**Comment by jcmeloni-usds** [comment]
@raquelromano-gov See, I thought your idea was a super good one and very interesting.  There's a reason I tell people who need a break from other teams to come to the VA and put hands on keyboards for a sprint to get their focus and chops back.

Also, we're not using Login.gov because it still doesn't exist as a FICAM-approved LOA3 IdP and CSP, and  really didn't a year ago when this was all being planned. :)

**Comment by ayaleloehr** [comment]
Anne's blog got published this week, as did the GI Bill one a few weeks ago and Raquel and I are working on a blog about how we have a (mostly) modern development environment on Vets.gov. 

While there is always more to do being transparent, I think that the above paragraph constitutes an improvement over what we had previously been communicating and am going to close this issue. If anyone disagrees, feel free to reopen and post ideas!
