### ISSUE TITLE
Change all appearances of Helvetica and Roboto Slab to Source Sans Pro

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2674]
Exception (for now): Home page "How can we help?" heading

**Comment by melwoodard** [comment]
Font stack for Source Sans Pro: `"Source Sans Pro", "Helvetica", "Arial", sans-serif`

*Note: a few font issues in VEC/GIBCT are not included here - they will be resolved in #2694*

Specific tasks:

[GIBCT initial search page](https://www.vets.gov/gi-bill-comparison-tool/):
- [ ] "Learn about education programs..." --> `p:first-of-type`
- [ ] "$" above Tuition/housing/books --> Source Sans Pro

![education-gi-comparison-0](https://cloud.githubusercontent.com/assets/4106356/17752656/af546672-6481-11e6-9cf1-3f00cc33fbd0.png)

[GIBCT search results page](https://www.vets.gov/gi-bill-comparison-tool/institutions/search?utf8=%E2%9C%93&source=home&military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&institution_search=seattle&commit=Search+Schools):

- [ ] Institution name --> `h4`
- [ ] # of GI bill students value --> Source Sans Pro
- [ ] Tuition/housing/books benefit text --> Source Sans Pro

![education-gi-comparison-results-0](https://cloud.githubusercontent.com/assets/4106356/17753161/9d3ec494-6483-11e6-9c6e-c30aeefab247.png)

[GIBCT institution detail page](https://www.vets.gov/gi-bill-comparison-tool/institutions/profile?military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&source=home&institution_search=31808047&facility_code=31808047&)

- [ ] Institution name --> `h1`
- [ ] # of GI bill students value --> Source Sans Pro
- [ ] "Your Estimated Benefits" heading --> `h3` + remove blue background
- [ ] Tuition/housing/books headings --> `h5`
- [ ] Tuition/housing/books benefit text --> Source Sans Pro
- [ ] "Calculate Your Detailed Benefits" heading --> `h3`
- [ ] "Calculator Results" heading --> `h4`
- [ ] Outcome rate chart headings --> `h3`

![education-gi-comparison-results-institution](https://cloud.githubusercontent.com/assets/4106356/17753656/a4f785f2-6485-11e6-950e-fab2546457c5.png)

---

![education-gi-comparison-results-institution](https://cloud.githubusercontent.com/assets/4106356/17753672/b39cca0e-6485-11e6-9ebc-bc43d34a3702.png)

---

![education-gi-comparison-results-institution](https://cloud.githubusercontent.com/assets/4106356/17753685/c33ff1e8-6485-11e6-9a10-fd88439187aa.png)

[Skills Translator](https://www.vets.gov/employment/job-seekers/skills-translator)

- [ ] Skills checkboxes and "See more skills" refresh button --> Source Sans Pro
- [ ] "Tips for using..." heading --> `h3`

<img width="880" alt="veterans_employment_center__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/17753891/c813a1e6-6486-11e6-8e52-a1498cdc74f1.png">

[Résumé Builder](https://www.vets.gov/employment/job-seekers/create-resume)

- [ ] Section headings --> `h3`

<img width="1265" alt="resume_builder_veterans_employment_center__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/17753959/1c4bb1cc-6487-11e6-93c8-178ca16aea04.png">

- [ ] Veteran name --> `h1`
- [ ] Section headings --> `h3`

<img width="1272" alt="view_profile_veterans_employment_center__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/17754195/399f75d2-6488-11e6-9ed3-982886b211a6.png">

[Job Search](https://www.vets.gov/employment/job-seekers/search-jobs?searchType=&tm=&kw=Engineer&zc=&moc=&onet=&ind=&cname=&fed=&tm=)

- [ ] "Featured Jobs" and "More Jobs" headings --> `h3`
- [ ] "From employers that have committed to hiring Veterans." --> `p:first-of-type`

<img width="1276" alt="search_results_veterans_employment_center__vets_gov_" src="https://cloud.githubusercontent.com/assets/4106356/17754355/f8393d16-6488-11e6-81d2-4be481353dde.png">
