### ISSUE TITLE
Apply consistent placement of "Apply for Benefits" buttons above the fold(ish) on core pages

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2678]
@maryannbrody -- I know we have had conversations about this before, would love for you and @melwoodard to weigh in so we can have this decision documented at least for now.

**Comment by maryannbrody** [comment]
Hi @crwallace and @melwoodard -- I agree that we want this to be more consistent, but I know that the current approach (Call to action/apply button on top right of page in the grey bar) doesn't really test well is usability testing (users miss it), so I would just want to think about what the "consistent placement" is. I would not recommend removing the CTA buttons at the bottom of pages until we figure this out.

**Comment by Drakenhart** [comment]
@crwallace @maryannbrody @melwoodard What if you had the button closer to the content that was talking about the function? 

You have the two column side bar for items like "Questions" or "More Information" in your templates, Maybe this could be used as well for a placement for the apply button? Maybe with a short informational blurb under it?

Maybe make on sr-only? Or mobile-only? Or if the page is long keep the one at the bottom (task-flow / story of read-first then apply)?

**Comment by jcmeloni** [comment]
@maryannbrody @melwoodard confirming that a decision is still needed on this?

**Comment by melwoodard** [comment]
Some fresh conversation on this is happening now in #4259, will close this one out
