### ISSUE TITLE
Create a consistent pattern for headings & subheadings inside callout boxes

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2680]

**Comment by melwoodard** [comment]
The mockup below outlines use cases for headings in the context of a callout box. A couple things to note:

- H3's in callout boxes are most commonly some form of "Are you eligible?" and "Who is covered"
- Use of H6 will be rare, like calling out an eligibility exception

The styles outlined here should match up with the heading styles implemented in #2675

![headings-callout-box](https://cloud.githubusercontent.com/assets/4106356/17636182/863f1dda-6090-11e6-94fe-5e3e11378eb1.png)

**Comment by crwallace** [comment]
Would love some light feedback from @dannychapman since he is working with the content team on design. Let us know if there are any glaring issues with this and if this seems like the correct implementation based on the content we create for these boxes.

**Comment by dannychapman** [comment]
I think this makes good sense for now. Couple thoughts: 

1. I think we need to do some clean up work on headings in general. I'd like to simplify and have a consistent bold, no caps standard on h1 - h6. Also line height and padding should get addressed. 
2. Ideally, a call out box should have all that much content in it that we need headings beyond h4.

**Comment by melwoodard** [comment]
@dannychapman re: #1 - you can take a look at the general heading cleanup @bshyong has been working on in #2675 / #2741. Is there anything specific about line height and padding you can provide?

re: #2 - Agreed. Above is an extreme example to account for all cases that currently exist. ~90% of callout boxes currently only use H3, a few use H4 and I've only found one with the H6 example above.

**Comment by dannychapman** [comment]
@melwoodard thanks for the heads up re: existing PRs. Added comments directly on #2675.

**Comment by crwallace** [comment]
@bshyong -- Do you know if this was taken care of in a previous PR?

**Comment by bshyong** [comment]
@crwallace Yes, I revised heading usage in progress lists and other places around the site https://github.com/department-of-veterans-affairs/vets-website/pull/2741—I'll close out this issue; we can reopen if needed
