### ISSUE TITLE
Use a consistent heading style for process lists

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2682]
@melwoodard -- Can you provide a mockup for this? Just want to know bold vs non bold, spacing, etc.

**Comment by melwoodard** [comment]
Spacing didn't seem to be an issue for this case, just font size/weight. The styles outlined here should match up with the heading styles implemented in #2675 

![headings-process-list](https://cloud.githubusercontent.com/assets/4106356/17634262/9fbeacda-6086-11e6-8264-f3189e2e24e8.png)

**Comment by bshyong** [comment]
Update: these should have been resolved with the fixes that I implemented in #2675 but I will take one more pass through the process lists to confirm.

**Comment by melwoodard** [comment]
Thanks @bshyong! With the heading styles already updated, the main thing to do here is confirm that the right types of headings are being used across the board.

**Comment by bshyong** [comment]
Finished another pass through and caught some issues with h4/h5 usage. Resolved in #2785
