### ISSUE TITLE
Consistent font-size for form labels, e.g. radio button text

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2685]
This will require time other repos in addition to this one

`/healthcare/apply/application`
https://github.com/department-of-veterans-affairs/healthcare-application

`/facility-locator`
https://github.com/department-of-veterans-affairs/service-and-facility-locator

`/gi-bill-comparison-tool`
https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool

`/employment`
https://github.com/department-of-veterans-affairs/veterans-employment-center

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
