### ISSUE TITLE
Use a standard error state across vets.gov

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2686]
Differing styles appear in the Résumé Builder, Skills Translator

**Comment by melwoodard** [comment]
Proposed fix for Résumé Builder: 

- [ ] Remove error message banner that appears at the top of the form
- [ ] Use [US web standard](https://standards.usa.gov/form-controls/#text-input) `.usa-input-error`, the same as the [Healthcare Application](https://www.vets.gov/healthcare/apply/application/veteran-information/personal-information) 

Proposed fix for Skills Translator:

- [ ] Remove error message text that appears below the "Translate" button
- [ ] Move the fields for the Skills Translator to a single column format, to make the next task possible with the layout
- [ ] Use [US web standard](https://standards.usa.gov/form-controls/#text-input) `.usa-input-error`, the same as the [Healthcare Application](https://www.vets.gov/healthcare/apply/application/veteran-information/personal-information)

Here's a mockup of what the Skills Translator should end up looking like. @crwallace I'd like your input on the single-column approach, which does make this section taller. We still need a deeper assessment of the interface for tools like these, but this will aid with consistency in the interim and doesn't sacrifice any usability.

![error-skills-translator](https://cloud.githubusercontent.com/assets/4106356/17640181/cb185056-60af-11e6-8697-4bd9bf30bab6.png)

**Comment by crwallace** [comment]
@melwoodard & @bshyong -- I like the single-column approach for now as it does create consistency between "forms" on vets.gov. I do think we should take some more time later to revisit the design of these apps, but in the short term this is a great solution.
