### ISSUE TITLE
Use consistent language for submit

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2689]
"Search" and reset - "Clear search" buttons

**Comment by beckah** [comment]
Hello! Wanted to contribute and I thought this might be a start (hope that's alright!) 

Where are the button assets currently located? Is there any kind of wiki that has a description of the folder structure?

**Comment by crwallace** [comment]
@beckah -- we are working off of this list that was compiled from the interface audit documented [here](https://github.com/department-of-veterans-affairs/vets.gov-frontend/tree/interface-audit/docs/interface-audit). 

Looking through all of these docs might provide more clarity.

**Comment by crwallace** [comment]
I think we are also waiting for more direction from @melwoodard.

**Comment by beckah** [comment]
@crwallace oh! :+1: looks like the issues are documented [https://github.com/department-of-veterans-affairs/vets.gov-frontend/blob/interface-audit/docs/interface-audit/07-search.md](here)

I'll make a branch and make the search button after search is preformed match that of the search button before the search is performed, unless there is additional direction from @melwoodard

**Comment by melwoodard** [comment]
@beckah if you look [here](https://github.com/department-of-veterans-affairs/vets.gov-frontend/blob/interface-audit/docs/interface-audit/01-global-themes.md#search-tools) under the "Search button language" and "Reset button" bullets, you'll see the different types of language being used for these buttons. The issue you're referring to is separate (not sure if we're tracking it yet on GH) - for this issue, it's specifically about using consistent words for the call-to-action text on a search or reset button.

**Comment by beckah** [comment]
@melwoodard 

> Search button language
> Broad "Search" (Jobs, Facilities, Commitments)
> Specific "Search Schools" (GI Bill)

should the search buttons be revised to have broad or specific text? 

> "Reset search" navigates back to initial search page (GI Bill)
> "Clear search" clears my field inputs on the same page (Jobs)

Should the reset buttons be uniform to say "clear search" or "reset search"?

**Comment by melwoodard** [comment]
@beckah let's use the broader "Search" for submit buttons and "Reset" for starting over.

**Comment by beckah** [comment]
@melwoodard awesome! i'll get cracking on it tonight

**Comment by jcmeloni** [comment]
@melwoodard are there still inconsistencies that we need to sweep through, to your mind?

**Comment by melwoodard** [comment]
Looks like GI tool is the only remaining outlier, I can address this separately with that project.
