### ISSUE TITLE
Use a consistent style & format for informational sidebars

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2694]

**Comment by melwoodard** [comment]
Sidebars in GIBCT and VEC should be updated to match the pattern seen [here](https://www.vets.gov/employment/job-seekers/). This touches:

- GI Bill Comparison tool
 - [Search page](https://www.vets.gov/gi-bill-comparison-tool)
 - [Institution detail page](https://www.vets.gov/gi-bill-comparison-tool/institutions/profile?military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&source=search&institution_search=seattle&page=1&facility_code=31356047)

- Veteran's Employment Center
 - [Job search](https://www.vets.gov/employment/job-seekers/search-jobs)
 - [Employer commitments](https://www.vets.gov/employment/commitments)

(See mockup examples below)

Tasks:
- [ ] Move sidebars up to align with the top of the page heading on [GIBCT](https://www.vets.gov/gi-bill-comparison-tool/), [Job Search](https://www.vets.gov/employment/job-seekers/search-jobs), and [Employer Commitments](https://www.vets.gov/employment/commitments)
- [ ] Implement a uniform style according to the spec below that includes H4 heading, paragraphs, lists, and button styles with correct spacing.

![sidebar-style-specs](https://cloud.githubusercontent.com/assets/4106356/17718032/8d388ac0-63c6-11e6-8a8a-57aa189e1f15.png)

![sidebar-gibct](https://cloud.githubusercontent.com/assets/4106356/17718050/adc08536-63c6-11e6-84d1-8ffd5e442aa1.png)

![sidebar-commitments](https://cloud.githubusercontent.com/assets/4106356/17718047/a94ef118-63c6-11e6-81ca-83bdb4ae922c.png)

![sidebar-job-search](https://cloud.githubusercontent.com/assets/4106356/17718064/b699791a-63c6-11e6-827d-4c3e50d3409b.png)

**Comment by crwallace** [comment]
@melwoodard -- This look great. Feel free to assign this to me when you are done with all of the documentation here.

**Comment by crwallace** [comment]
@bshyong -- This would be great to have before veterans day but should be lowest priority.

**Comment by melwoodard** [comment]
If the changes to VEC happen, this will only affect GIBCT.

**Comment by bshyong** [comment]
Will these changes get overwritten by changes in the overall site redesign?

**Comment by melwoodard** [comment]
I think this is worth addressing now to get these elements lined up and standardized. The redesign effort won't be addressing anything in the way of templates for a while.

**Comment by melwoodard** [comment]
Regarding my comment above about VEC, we should still plan on addressing the sidebars there too.
