### ISSUE TITLE
Implement a consistent pagination component used by all search tools

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2695]
Site search, GI Bill Comparison, Job Search, Employer Commitments, Facility Locator

**Comment by Drakenhart** [comment]
@crwallace I think this came up in the US WDS git hub as well. There was a conversation about this point, in consideration that some pagination doesn't fit well with some content types. (Articles vs image gallery)

Also how that would look on mobile as well. ^.^

https://github.com/18F/web-design-standards/issues/959

**Comment by melwoodard** [comment]
@Drakenhart thanks! We ended up with something pretty similar for one of the new features we're developing. 

@bshyong there's a PR up for the basic design [here](https://github.com/department-of-veterans-affairs/rx/pull/33). You should coordinate with @webinista to get this component going across the site.

**Comment by bshyong** [comment]
Sweet. What do we do about apps like Veteran's Employment Center which are Rails and ERB views? Is there a long term plan to migrate some of those to React views?

**Comment by crwallace** [comment]
The idea is to migrate them at some point to react but we are not sure when
that will happen. So in the meantime, I think we will try to integrate the
styles into the main core scss and use the html to build out these
components in the rails apps.

**Comment by bshyong** [comment]
@webinista After I spend some more time looking at the error states on VEC I'll start implementing the RX interface across the site. We will need to get it into the html templates for MetalSmith/non-React pages and probably make a Rails view helper for the Rails apps

**Comment by bshyong** [comment]
- [ ] Site search
- [ ] GI Bill Comparison
- [ ] Job Search
- [ ] Employer Commitments
- [ ] Facility Locator

**Comment by bshyong** [comment]
@crwallace is the Site Search (search.vets.gov) in the Department of Veterans Affairs org? I don't see a repo for it

**Comment by bshyong** [comment]
update: we're going to need to punt on the Site Search pagination for now—USDS runs the search service separately and we have no access for modifying the views.

https://github.com/department-of-veterans-affairs/vets-website/blob/master/docs/HowSearchWorks.md

**Comment by crwallace** [comment]
True! We should also let @dannychapman know about the other places that we have changed pagination so he can work it into the design he is working on for search.

**Comment by bshyong** [comment]
@crwallace @dannychapman 

The pagination has been updated for the Gi Bill Tool and Facility locators.

For the other ones in the list, let's make a decision on whether to table.

- Site Search — under control of USDS; we have no access to make changes on styles/views
- Job Search — this will take quite a bit of effort to work on/refactor. There are two sections with pagination and it looks like a custom wrapper for job searching (see screenshot below)
- Commitments — this is a dataTable that uses jQuery DataTable for pagination. Will also take a big effort because it will require writing a (one-off?) custom pagination plugin

**Comment by dannychapman** [comment]
@crwallace Thanks for the heads up. I will incorporate this when I get back into site search.

**Comment by jcmeloni** [comment]
@crwallace Confirming there are still outstanding needs here?

**Comment by jcmeloni** [comment]
Closing as no further action needed based on conversation above (and time).  If there is still an outstanding need please create an issue in vets.gov-team.
