### ISSUE TITLE
Use positive filter for files in metalsmith. Probably just .md and .html

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#2696]
Currently there also seem to be .pdf files being processed by metalsmith. This is weird. We should move those out into assets or something...

**Comment by crwallace** [comment]
@awong-dev -- This was taken care of here:

https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.js#L156

correct?

**Comment by awong-dev** [comment]
I think we're still missing it on `https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.js#L117`
