### ISSUE TITLE
Should blog posts use permalinks?

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#2709]
They are inconsistent with other parts of the site.

However, there are external references to these URLs meaning that we can't just change them without breaking other people.

**Comment by awong-dev** [comment]
@dannychapman

**Comment by ayaleloehr** [comment]
We are supposed to be removing the blog, although this PR probably has enough going on already that I'm not sure adding more to the one you're working on right now is the right play. 

https://github.com/department-of-veterans-affairs/vets-website/issues/2613

**Comment by awong-dev** [comment]
Thanks for the context. Priority right now is getting master pushable to
production so explicitly deciding now to care about this.

Right now, just trying to reduce deltas from master to production. We can
revisit later.

**Comment by crwallace** [comment]
Since we are removing the blog I am going to close this for now.
