### ISSUE TITLE
[Rx] Sorted by Facility View

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2710]
Affected by #2769

### Prototypes

- [Desktop](https://marvelapp.com/1h10heg#14227015)
- [Mobile](https://marvelapp.com/iaa9b9#14368763)

Shows prescriptions grouped by name of the prescribing facility.

Blocks #2575
Related to #2653

**Comment by webinista** [comment]
@ayaleloehr I think I've flagged these issues earlier, but wanted to document it here: for the sort-by-facility feature, I need:

1. the sorting parameters to work

**Comment by ayaleloehr** [comment]
Sorting parameters should be good to go now! Let me know if they are not!

**Comment by webinista** [comment]
Not sure why/how I closed this, but I'm still working on it.

**Comment by webinista** [comment]
Slow progress. I've got the sorting in place. Still need to:

1. Adapt `PrescriptionList` to handle the grouped-by view
2. Figure out where to place this sort code. Right now, it lives in `/src/components/Active.jsx` and that feels like the wrong place for it (although it does work).

**Comment by webinista** [comment]
Current status: trying (and so far, struggling) to make this adhere to the Redux pattern.
