### ISSUE TITLE
Fix metalsmith migration issues and push to production.

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#2711]
Task burndown list:
- [x] Footer issues with seal, logo, feedback tool and crisis line
 - [x] Bring back the VA seal (`.footer-address`)
 - [x] Ensure the crisis line button is removed on mobile
- [x] Fix issue with layouts not being applied
- [x] Links on blog posts at /experience are broken
- [x] Ideally blog post permalinks should match product, or if not, have htaccess redirects
- [x] Ensure all differences in file lists are shown.
- [x] Timestamps on blog posts show "undefined" in place of the month (works on /experience, just not on the individual post page)
- [x] Breadcrumb links lack proper casing, e.g. "Ptsd" instead of "PTSD" (not sure if this is related to metalsmith migration or other)

vvvvv invalid vvvvv
~All former dependencies on Jekyll global `page` variables in layouts and includes need auditing. They were converted incorrectly. Things like `<title>` tag are not being populated.~

**Comment by dannychapman** [comment]
- [ ] 1. Footer issues with seal, logo, feedback tool and crisis line
- [ ] 2. Links on blog posts at /experience are broken
- [ ] 3. Ideally blog post permalinks should match product, or if not, have htaccess redirects

**Comment by bshyong** [comment]
@dannychapman can you clarify what you mean in the following?

> Ideally blog post permalinks should match product, or if not, have htaccess redirects

**Comment by bshyong** [comment]
Hey all, I think I've fixed all of the issues in the list. The only remaining issues are the two that I don't understand.

Also, @awong-dev do you know who added the task for "Ensure the crisis line button is removed on mobile"? I removed it, but wanted to confirm that it was intended. There's a mobile friendly yellow button and mobile friendly modal that shows up on mobile only; based on that task there will no longer be a crisis line CTA on mobile.

**Comment by awong-dev** [comment]
Nice! 

`Ensure all differences in file lists are shown.` means when you diff the lists of files in the jekyll build vs the metalsmith build, all the changes make sense.

I added one more, relatively nasty, bug. AFAICT, there's no direct way in metalsmith to fix this. I think we have to write a custom plugin...

**Comment by awong-dev** [comment]
Nevermind.I think I was wrong. I'm too tired. Signing off for the night.

**Comment by awong-dev** [comment]
`og:url` is not being set.

**Comment by dannychapman** [comment]
@bshyong Typo - I meant should match production, not product. The blog links: 1. Do not match up, and two, do not work from the blog post titles on /experience. If you can fix that, and @awong-dev 's og:url issue, I think we are in good shape to push to production.

**Comment by dannychapman** [comment]
Also, @awong-dev @crwallace for the footer bar, should we remove the feedback URL from the bottom bar? The rest of it looks good.

**Comment by carlmjohnson** [comment]
> Ideally blog post permalinks should match product, or if not, have htaccess redirects

Nit: htaccess is an Apache-ism, and AFAICT, we're not using Apache, so we'll need another method for doing redirects if there's a page that needs redirecting.

**Comment by dannychapman** [comment]
@carlmjohnson good to know, thanks!

**Comment by melwoodard** [comment]
@bshyong I added the task to remove the crisis line button - since we're removing on desktop, I think it was just an oversight that the mobile version of the button wasn't removed. You may want to confirm with @crwallace or someone else who was involved in that decision.

**Comment by awong-dev** [comment]
@melwoodard how certain are we that we should remove it?  If we don't have a definitive answer, for this push, we should bias towards matching what's currently deployed and just opening an issue to fix after we get production matching master.

**Comment by melwoodard** [comment]
@awong-dev agreed, I'll open a separate issue.

**Comment by awong-dev** [comment]
Production is pushed. Closing issue.
