### ISSUE TITLE
[Rx] Sorted by Facility View

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2714]
### Prototypes

- [Desktop](https://marvelapp.com/1h10heg#14227015)
- [Mobile](https://marvelapp.com/iaa9b9#14368763)

Need to show prescriptions grouped by name of the prescribing facility.

**Comment by Drakenhart** [comment]
@webinista I like this personally, but I was curious - why not display them as DT lists (see Panel Filters Page Template - https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/)?

Trying to sort out the design patterns I see, and was wondering about the logic/process behind doing it this way?

**Comment by webinista** [comment]
Whoops. Duplicate of #2710. This is what happens when you have too many tabs open at once.
