### ISSUE TITLE
[Rx] RefillPrescriptionButton component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2715]
For use on the Prescription card and the [prescription detail page](https://marvelapp.com/1h10heg#14227011). 

Suggested way to work is to use a `button`, but set class list of `usa-button` or `usa-button-unstyled rx-refill-trigger` based on where it's being used. Probably a `mode` prop kind of thing.

**Comment by Drakenhart** [comment]
@webinista Is it something that submits a form? (button)  Or is it something that links to a new page which hosts a form? (link) I think answering those might help answer this. :)

**Comment by webinista** [comment]
Can probably repurpose `<SubmitButton>` in both places.
