### ISSUE TITLE
Remove crisis line button from footer on mobile

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#2717]
@crwallace with the feedback / crisis line footer removed on desktop, can you confirm the crisis line button and overlay should also be removed on mobile?

<img width="399" alt="vets_gov_and_new_issue_ _department-of-veterans-affairs_vets-website" src="https://cloud.githubusercontent.com/assets/4106356/17629245/4c737a82-606e-11e6-95dd-04d82d3e23ec.png">

**Comment by joduinn** [comment]
> "...with the feedback / crisis line footer removed on desktop..."

@melwoodard I'm confused by your comment above. I still see the "Get help from Veterans Crisis Line" button at the bottom of the screen on my laptop. Maybe this change is landed but not yet deployed?

Also, is this work related to the proposal in #2500 about moving button from footer to top of screen?

**Comment by melwoodard** [comment]
@joduinn this was on staging - we got confirmation that the footer should in fact stay, so I'll close this one out.
