### ISSUE TITLE
Header incorrect sets og:type to article

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#2719]
```
{% if title %}
<meta content="article" property="og:type">
{% else %}
<meta content="website" property="og:type">
{% endif %}
```

in `content/includes/header.html` seems wrong. I think it should always be website or at least not keyed off the presence of title which is true always.

**Comment by awong-dev** [comment]
Passing to Danny for triage. (tick-tocking danny and courtney now)

**Comment by carlmjohnson** [comment]
http://ogp.me/#types has good info about the meaning of the tags. An article, unlike a website, has a `published_time` and `author`s, but those don't apply to vets.gov, so I think it's a website.

**Comment by jcmeloni** [comment]
Addressed in PR https://github.com/department-of-veterans-affairs/vets-website/pull/4646  will close this issue after merge and not move this issue to vets.gov-team.

**Comment by jcmeloni** [comment]
Merged PR, will close after release.

**Comment by jcmeloni** [comment]
Released 17 Jan 2017
