### ISSUE TITLE
/memorial-benefits/* is disabled?

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#2721]
This seems to be some vestigial part of the website in the original source tree. It was marked as disabled in jekyll.

I've moved the files over but have told metalsmith to NOT process them. Can someone verify if this content is supposed to be on our site or not?

**Comment by crwallace** [comment]
@maryannbrody -- Can you verify this still needs to be in here?

**Comment by maryannbrody** [comment]
@crwallace - there's no content related to memorials right now, I'm guessing this is a placeholder from launch. Let's pull it down for now. 

Thanks!

**Comment by crwallace** [comment]
@maryannbrody -- There is content for memorial benefits here: https://github.com/department-of-veterans-affairs/vets-website/tree/master/content/pages/memorial-benefits

**Comment by maryannbrody** [comment]
@crwallace -- That content is out of date and never went live. that does not need to be in there, you can pull it out.
