### ISSUE TITLE
blog permalinks incorrectly make a directory with an index.html

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#2722]
Currently metalsmith builds blog entries files like:
  build/development/2015/11/11/why-we-are-designing-in-beta.html/index.html 

This manages to work okay, but is in fact sorta broken.

**Comment by crwallace** [comment]
@dannychapman -- should the blog entries be `/2015/11/11/why-we-are-designing-in-beta.html ` or can they be `/2015/11/11/why-we-are-designing-in-beta/ `?

**Comment by dannychapman** [comment]
I prefer the latter, but I think it's important we handle redirects.

**Comment by crwallace** [comment]
@dannychapman -- Just to be clear `/2015/11/11/why-we-are-designing-in-beta/` is what we are aiming for?

**Comment by dannychapman** [comment]
Yep, provided we handle redirects from the old urls.
