### ISSUE TITLE
link to "work in progress" is incorrect

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2727]
this link was going to Sec Bob's blog post
![screen shot 2016-08-12 at 11 10 46 pm](https://cloud.githubusercontent.com/assets/13770771/17641144/076f2c0a-60e2-11e6-8d1c-f7e2eae2590a.png)

now it's going to the playbook page?  https://www.vets.gov/playbook/design/ which is an error (i think?); it should still be going to sec bob's blog https://www.vets.gov/2015/11/11/why-we-are-designing-in-beta.html -- not the playbook.  that doesn't really make sense:)

@maryannbrody i was not sure whom to assign; can we pls. prioritize this fix??/

**Comment by crwallace** [comment]
@koconnor719 @maryannbrody -- This has never been linked to sec bob's blog post.

These are the changes to the banner.

[Link added to banner -- Github url](https://github.com/department-of-veterans-affairs/vets-website/commit/8130249b6e099ce67be5dd9e87b04e7100c718b9#diff-822e9cf54ee310f9a7ebd0d16c9ae066)

[Link changed to playbook url](https://github.com/department-of-veterans-affairs/vets-website/commit/cfffebeb40544bef13b53230eacdcccf694881f9#diff-822e9cf54ee310f9a7ebd0d16c9ae066)

[Playbook url opens in a new window](https://github.com/department-of-veterans-affairs/vets-website/commit/9f6057dd5717dfdc84108224db4bb57dde9029ac#diff-822e9cf54ee310f9a7ebd0d16c9ae066L109)

Would you like for me to change this link to sec bob's blog post now?

**Comment by crwallace** [comment]
If you want this link to be sec bob's blog post, should I ignore #2613 where we want to remove the blog from the site entirely?

**Comment by koconnor719** [comment]
it was always sec bob's blog--when did it get changed to the playbook?

**Comment by crwallace** [comment]
@koconnor719 -- I looked through the history on github and I didn't see anytime that it was ever sec bob's post. According to github it has been directed to the playbook since Nov 16, 2015 and before that it was directed to `github.com/department-of-veterans-affairs/vets-website/`. I know `Message from the Secretary` in the footer goes to his post.

**Comment by koconnor719** [comment]
thanks for looking up all this info @crwallace --im sorry you spent time on this i know you are busy:) .  i swear this went to the sec bob post? i don't think the link really makes sense b/c it doesn't explain how the site is a "work in progress" at all? i think our playbook pages really need a rewrite.--it should talk about "developing in the open" and how the site is a work in progress...i'll leave to you all.  it doesn't feel like my design feedback from demos is helpful at all and i don't want to create extra work.  thanks.
