### ISSUE TITLE
Social Security and VA file number

### ISSUE THREAD

**Issue by mayacoforma** [department-of-veterans-affairs/vets-website#27285]
Screenshot from staging
<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOCtSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--377a0f4abafbc7c755829bce9958d5ed32aaf637/Apply-For-Pension-Benefits-Veterans-Affairs.png" alt="Apply-For-Pension-Benefits-Veterans-Affairs.png" />

Social security and VA file number fields are not grouped in accordance to the the VA's design system standards and the proposed designs approved by Julie Strothman. 

Social Security Number and VA file number fields should be grouped together, as depicted in this mockup.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcc3f1b2d7cd5d2f1b365d5f4049316b8de18ae6/Screenshot%202024-01-02%20at%209.45.57%E2%80%AFAM.png" alt="Screenshot 2024-01-02 at 9.45.57 AM.png" />

Please review the guidance published on https://design.va.gov/patterns/ask-users-for/social-security-number and make sure we are following the approved design pattern.

**Comment by asg5704** [comment]
@mayacoforma for future reference can you ensure these are created in the va.gov-team repository?
