### ISSUE TITLE
pension/ and pension/family are completely broken...

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#2732]
This was true on the old site as well. It seems to be left over from a much older version of vets.gov?

I tried briefly to make it look readable but then found out that nothing on vets.gov linked to these two. Leaving it alone for now, but these pages either need to be fixed or removed.

**Comment by awong-dev** [comment]
Assigning to kelly for triage since I can't even tell if this is valid content.

**Comment by koconnor719** [comment]
albert can you provide a link?  i don't know which pages:)  i searched "pension" on vets.gov but got no results for a pension page:)  ric arthur can validate if it's a valid content page.

**Comment by koconnor719** [comment]
Thx!!



Sent with Good (www.good.com)


-----Original Message-----

**Comment by awong-dev** [comment]
http://www.vets.gov/pension
http://www.vets.gov/pension/family

**Comment by dannychapman** [comment]
@rcarthur Do you know the history of these pages? They appear to be orphaned, or stubbed out pages to me.

**Comment by koconnor719** [comment]
yep these should def be deleted:)  can someone delete? @maryannbrody @dannychapman 

<img width="1358" alt="screen shot 2016-08-15 at 10 50 27 am" src="https://cloud.githubusercontent.com/assets/13770771/17668183/1ff5e264-62d6-11e6-9b04-ffe2b28b8ffb.png">

**Comment by dannychapman** [comment]
Created a PR to fix this here: #2746

**Comment by rcarthur** [comment]
Is this issue still open?

**Comment by dannychapman** [comment]
@rcarthur Nope, closed here: #2746
