### ISSUE TITLE
Mockups for education benefits form

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2744]

**Comment by cweber** [comment]
In progress wireframes can be found here: https://classic.moqups.com/greg@adhocteam.us/l32hJ36b/p:a3c1b5b8f

Currently:

- None of the elements are linked, so navigate through the sitemap on the left.
- Military History is a mess right now, as I’ve duplicated a bunch of pages so I can break things down into more discrete sections
