### ISSUE TITLE
Agent Orange page is missing "Apply for Benefits" CTA banner

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#2747]
[Diseases Associated with Agent Orange](https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/diseases/) is missing the "Apply for Disability Benefits" green button and grey banner present on all other disability benefits pages.

<img width="1272" alt="diseases_associated_with_agent_orange__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/17708723/137a6404-639b-11e6-9db8-31351913e036.png">

**Comment by crwallace** [comment]
@melwoodard -- Should all pages have this banner? Right now many other urls like these:

[Evidence](https://www.vets.gov/disability-benefits/claims-process/evidence/)
[Presumed Disability](https://www.vets.gov/disability-benefits/claims-process/presumed-disability/)

do not have this banner. Should we add it to everything in this section?

cc - @maryannbrody

**Comment by melwoodard** [comment]
Thanks for the find @crwallace - yes, these and any other pages within the Disability and Education sections should have their respective banners.
