### ISSUE TITLE
Implement consistent color for green CTA buttons

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#2748]
The "Import into Résumé Builder" button on the [Skills Translator](https://www.vets.gov/employment/job-seekers/skills-translator) uses a non-standard green. It should be `#2e8540`

**Comment by webinista** [comment]
Corresponds to the `$color-green` SCSS variable from https://standards.usa.gov/colors/

**Comment by bshyong** [comment]
I'll fix this issue

**Comment by bshyong** [comment]
@melwoodard the button is currently blue `#0071bc`. Should I make a 'secondary button' class or 'green' class and make that CTA green instead?

![screen shot 2016-08-24 at 1 36 21 pm](https://cloud.githubusercontent.com/assets/303289/17947049/c9e8cdce-69ff-11e6-85c7-6f21c17b4b26.png)

**Comment by melwoodard** [comment]
@bshyong if you select that translate button, you'll see the Import button further down the page - that's the one we need to fix:

<img width="775" alt="screen shot 2016-08-24 at 1 42 33 pm" src="https://cloud.githubusercontent.com/assets/4106356/17947240/b927991a-6a00-11e6-9ac8-c9e8dfc4aebe.png">

**Comment by bshyong** [comment]
Got it thanks!

**Comment by bshyong** [comment]
Resolved by https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/349
