### ISSUE TITLE
Get heroku deploying PRs for pre merge review

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2760]

**Comment by bshyong** [comment]
Thanks for assigning. FYI I think it is related to Heroku buildpack settings—currently looking into this.

**Comment by bshyong** [comment]
@crwallace I think this stuff is resolved—probably vestigial failures from the metal smith migration. That's the only explanation for why Heroku was trying to use Ruby buildpack...

Closing for now—we should file a new issue if we see this again.
