### ISSUE TITLE
Determine whether we need to compile a facility list

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2769]
[Latest mockups](https://marvelapp.com/1h10heg#14227015) indicate a "sort by Facility name" feature. Mock API returns a `facility-name` field, with names such as `ABC123` and `SLC4`. We need names that are more like "Baltimore VA Medical Center."

### Questions that need answers

1. Does the production API return facility _names_ such as "Baltimore VA Medical Center" or something more like the facility _codes_ (e.g.: _SLC4_) from the mock API?
1. If it returns facility _codes_, 
    1. Where do we get the full names of the facilities those codes reference?
    1. Once we have the list, how do we access, store, and maintain it?

Affects #2710.

**Comment by ayaleloehr** [comment]
Email sent to Ken and Barry on the API team asking, with Tiffany's VA email cc'd.

**Comment by webinista** [comment]
Answer: we do not need to compile that list. Closing.
