### ISSUE TITLE
[Rx] Possible bugs in rx/components/Prescription.jsx?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2772]
Noticed `const requested = attrs['refill-requested'];` in the code. Where is this prop coming from? The mock API doesn't have a `refill-requested` field. Should this be `is-refillable` instead?

Also, check lines 35-40. Because `requested` never gets defined, it will never be `true`.

```javascript
if (trackable) {
    action = <button type="button">Track package</button>;
} else if (requested) {
     action = <div className="rx-prescription-refill-requested">Refill requested</div>;
}
```

**Comment by webinista** [comment]
@alexose @U-DON not sure which of you worked on this part of `Prescription.jsx`, but can you take a look?

**Comment by U-DON** [comment]
Ah, that was me. I think I must've misread one of the attributes and thought it was there while I was looking for one that corresponded to the appearance of the 'Refill requested' text. But no, definitely not a valid attribute. Although, now I'm not sure what attribute (or combination of them) determines whether that text should appear.

**Comment by webinista** [comment]
> Although, now I'm not sure what attribute (or combination of them) determines whether that text should appear.

Raised a question about this for the API team in department-of-veterans-affairs/prescriptions-api#54.

**Comment by webinista** [comment]
#2775 should fix this once merged.
