### ISSUE TITLE
[Rx] Detail component / route no longer works

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2776]
(This was working in the `rx` repo.)

When the user clicks on the prescription card title, nothing happens. Console error says:

`Warning: [react-router] Location "/prescription/777736" did not match any routes`

**Comment by ayaleloehr** [comment]
should it be prescriptions (plural) instead of prescription?

**Comment by webinista** [comment]
No. This is when you click a particular prescription card in order to view the detail page.
