### ISSUE TITLE
[Rx] Directly going to route other than root (/rx) fails

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-website#2780]
## Steps to Reproduce:
1. Navigate to /rx/history.
2. Refresh.
3. "Cannot GET /rx/history"

**Comment by webinista** [comment]
I suspect this is a server configuration issue. @alexose @akainic any insight?

**Comment by awong-dev** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.js#L171 That  needs to be true.

**Comment by alexose** [comment]
Yay thanks @awong-dev!  I thought this was going to need some proxy rule or something.

https://github.com/department-of-veterans-affairs/vets-website/issues/2780
