### ISSUE TITLE
`button:hover, [type="button"]:hover` is too broad of a selector

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2797]
It's creating some side effects for outline buttons.

![screen shot 2016-08-18 at 5 01 18 pm](https://cloud.githubusercontent.com/assets/354277/17794564/6e2b7a8e-6565-11e6-8506-cf4965075afd.png)

It should look like this:

![screen shot 2016-08-18 at 5 03 12 pm](https://cloud.githubusercontent.com/assets/354277/17794590/b21078c6-6565-11e6-8e6e-10d06dd1bf29.png)

Background should remain transparent, or change to another color.

**Comment by crwallace** [comment]
@bshyong -- Did we give the button hover a color because that satisfied some 508 concern or is this just a bug?

**Comment by bshyong** [comment]
ah @crwallace I think I did add a hover color for 508; it should not be applied to the white buttons though. 

https://github.com/department-of-veterans-affairs/vets-website/issues/2633#issuecomment-237646265

> Change buttons with a background-color of #0071BC to #205493 (about 25% of buttons already use this color).
