### ISSUE TITLE
[Rx] GlossaryPage component / route

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2805]
Just a page with some text. Maybe put the text into a config file.
https://marvelapp.com/iaa9b9#14584509

**Comment by gnakm** [comment]
Glossary

Active
If you have refills, you may request a refill of this prescription from your VA pharmacy.

Discontinued
This prescription is no longer available. Contact your VA provider if you need more of this medication.

Expired
Prescription too old. Call your VA healthcare team if you need more.

On hold

**Comment by gnakm** [comment]
@webinista Updated status glossary text #99

**Active**
If you have refills, you may request a refill of this prescription from your VA pharmacy.

**Discontinued**: This prescription is no longer available. Contact your VA health care team if you need more of this medication.

**Expired**: This prescription is too old to fill. Contact your VA health care team if you need more of this medication.

**On hold**: This prescription cannot be refilled until a hold is resolved by the pharmacy. Contact your VA pharmacy when you need more of this medication.
**Pending**: This prescription was sent to the pharmacy for review. Contact your VA pharmacy if you need this medication now.

**Submitted**: Your prescription refill has been submitted.

**Suspended**: It is too early to request a refill for this prescription. It should be sent to you before you run out. Contact your VA pharmacy if you need this medication now.

**Unknown**: An unknown error has occurred. Contact your VA pharmacy if you need this medication now.
