### ISSUE TITLE
Switch to inline SVG for logo

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2808]
In light of #2491 and #2807, we should probably shift to an SVG logo, placed inline. (Inline is currently more accessible than using `object`.)

SVG offers:
- Smaller, single file that can serve devices at multiple resolutions without losing quality.
- A single asset to manage and maintain, rather than a dark logo, white logo, and rollover state images for both.
- A better rollover experience (with CSS)

With the `title` element, we don't lose any accessibility.

**Comment by webinista** [comment]
@emilyville Do we have an SVG version of the **VA | Vets.gov** logo handy?

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
