### ISSUE TITLE
[Rx] Order history sort fields?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2809]
There's a [sort option](https://marvelapp.com/iaa9b9#14368789) shown. Are the fields the same as the sort fields on the Active tab (prescription name, last requested, facility)?

**Comment by gnakm** [comment]
Yes! 

<img width="433" alt="screen shot 2016-08-22 at 11 51 19 am" src="https://cloud.githubusercontent.com/assets/13420618/17861386/d611074e-685e-11e6-920a-89c9c713a28c.png">

I also just added it to the prototype.

**Comment by U-DON** [comment]
@gnakm @angel Sorry to open this up again, but why is there an option to sort by prescription name for order history if it's the history for the same prescription? In the desktop view, the only table header that looks sortable is 'order date' (https://marvelapp.com/1h10heg#14227011). That brings me to the next point...

The default option in the mocks (linking again: https://marvelapp.com/iaa9b9#14368789) is 'sort by order date', but with recent discussion, it seems that order date will not be available with each entry, so I don't think we can sort by that field either.

AFAIK, the other fields on the table in desktop view are 'order status' and 'tracking number'. Is there anything else to sort by?

**Comment by gnakm** [comment]
I was not aware that order date will not be available with each entry. I may have totally missed this conversation @ayaleloehr could you verify?

Whether it is or not, I think you make a good point. Let's take out sort for both desktop and mobile for Order History in the detail page and keep the most recent date on top as default!

**Comment by gnakm** [comment]
Also, this is actually not the same issue as the one above since @U-DON concern is about the prescription detail page as opposed what Tiffany was talking about at the top (view history). Just wanted to clarify.

**Comment by ayaleloehr** [comment]
@gnakm this is about the prescription detail page (as far as I can tell by looking at the links to the mockups). 

I say that the prescription detail page should not have a sort drop-down (even though it's in the mockup linked at the top of this issue).  Each tracked shipment for a prescription has a shippedDate, so let's just have it default showing the most recently shipped first and going in order from there. 

@U-DON If the API is not returning results in the correct order to do this, please let me know and we can adjust that

**Comment by U-DON** [comment]
Because of the linked mock and our terminology for the OrderHistory component vs History view/page, I used this issue for the discussion. So it looks like we're removing the sort field for the order history on the detail page, and we just have to ensure that the order is by most recent shipping date. Sounds good to me.

**Comment by U-DON** [comment]
@ayaleloehr The API is returning in the reverse order, but has an option to give it in descending order if I supply the param to do so. Should the API return in the desired order by default?

**Comment by ayaleloehr** [comment]
Yes. Slack conversation [here](https://dsva.slack.com/archives/vetsgov-prescriptions/p1472499808000026).  @saneshark is on it!

**Comment by saneshark** [comment]
Actually, I only did this for shipped_date on tracking. Does it need to be done elsewhere?

**Comment by saneshark** [comment]
Nevermind, went ahead and did it for refill_date as well.
