### ISSUE TITLE
Markup appearing in body text

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#2812]
See the table on [https://www.vets.gov/education/gi-bill/survivors-dependent-assistance/](https://www.vets.gov/education/gi-bill/survivors-dependent-assistance/)

<img width="739" alt="survivors__and_dependents__assistance__vets_gov_" src="https://cloud.githubusercontent.com/assets/4106356/17818201/5d45caa2-65f7-11e6-9773-1c8a5af610eb.png">

**Comment by webinista** [comment]
Try adding `markdown=0` to `div.va-table-overflow` or remove the indent before each <p>.

**Comment by jcmeloni** [comment]
No longer happening.
