### ISSUE TITLE
Terms of Use Declined Page Content Update 

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/vets-website#28307]
## Issue Description
Using [this](https://www.figma.com/file/nxW1NHF0q1EasvUGp1eh5a/Terms-of-Use---Final?type=design&node-id=149-8&mode=design&t=k0vUeoqtGrEbvlbi-0) as reference, apply content updates to Terms of Use Decline Page. 

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Content changes match figma.  
- [ ] Tests have been updated to reflect content changes. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joeniquette** [comment]
@asg5704 the issue with sessionindex has been resolved, the team has decided we will not implement these changes.
