### ISSUE TITLE
Can we add additional fields to form?

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#2834]
Check with Shay about whether it's ok to to add additional fields to our version of the form. This is not about the nuance of additional fields for information already being collected or about formatting, but rather about new fields that will collect new information.

Right now I only have one such field in mind. It would be:

How would you prefer to be contacted by the VA regarding questions about your application? (_Italics about official communications only by mail._)

- [ ] email
- [ ] phone
- [ ] mail

**Comment by J-Quag** [comment]
Usually its a bit iffy to get them up. But I think asking for a contact preference wouldnt be a big issue.

**Comment by cweber** [comment]
Ok. I'll add and assuming it shouldn't be a big deal and we can argue for it or remove it easily later.
