### ISSUE TITLE
Which information, if omitted, would mean that an application is rejected?

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#2836]
Neither the VONAPP form or paper firm note which fields are required. My sense from our research is that the approach is really "Tell us as much as you can", but very little is required. That said, if there is a baseline of data that is necessary for the application to NOT get rejected, I'd like to be able to indicate that.

Name, address, ss#, at least one service period?

**Comment by J-Quag** [comment]
We'll probably want to follow up with Shay on that. I'll forward her that question.

**Comment by cweber** [comment]
Shay's response:

"
Here are the fields we HAVE to have before they can submit an application (required) –
 
Last Name
First Name
Sex
DOB
SSN
Address
Service Info       
                EOD
                RAD
                Branch/component
Email address
 
We also have fields we would like to have completed. In VONAPP these give “warnings” meaning, you can continue to submit without them, but it would be preferable if they were completed.
 
Day phone number
Date of graduation (only month and year needed)
Date of GED (only if no HS graduation)
"
