### ISSUE TITLE
Does submitting the application commit them to the relinquishment immediately?

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#2837]
In question 9a-9e on the form, there is very strong language about relinquishment of additional benefits when electing CH 33.

"By checking the box below, I am acknowledging that I understand that this election is irrevocable and may not be changed, and that failure to check one of the boxes below may cause a delay in the processing of this claim."

Does the submission of the form trigger this? (Or is it perhaps sealed when payments start being made?)

I'm imagining a scenario where someone completes the form, determines their eligibility and chooses not to use it for 5 years. Have they relinquished their other benefits or could they choose to use the relinquished eligibility at that time?

This also seems important given that I heard one story about people submitting the form with many benefits checked because they didn't know what they qualified for.

This is an 'in the weeds' question, but given the importance of clarity emphasized in the research and the attention paid to this in the form, I want to make sure we've got it right.

**Comment by J-Quag** [comment]
Yes, the language is strong for that reason because it is a one time revoke of previous benefits. Once you submit that, you can't go back even if you were at one time eligible.

**Comment by cweber** [comment]
Ok. Thanks.
