### ISSUE TITLE
Do veterans have access to their DD-214 and kicker statements online?

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#2838]
We've heard that the DD-214 and Kicker are the documents that are most useful for the VCEs to have access to. With the DD-214 in particular, it's used to validate service dates to avoid the lengthy process of verifying with DOD. 

If the veteran submits dates that are aligned with what is in BDN (I think), then verification is not necessary, but if the dates do NOT align, then it triggers an extra verification step. If we can encourage Veterans to check their DDT for accurate dates (during the period during which we won't be accepting document uploads), it could help expedite the process.

**Comment by J-Quag** [comment]
They can get their DD-214 through a DoD website called DPRIS. They can use a SSO through ebenefits to get it.

**Comment by cweber** [comment]
Do they get it in digital form is it just ordering a paper version?

**Comment by J-Quag** [comment]
They get the digital copy that they can download

**Comment by cweber** [comment]
Cool. Thanks.
