### ISSUE TITLE
Use USWDS heading styles for h3-h6

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#2843]
<img width="658" alt="screen shot 2016-08-23 at 10 27 17 am" src="https://cloud.githubusercontent.com/assets/4106356/17902436/39b519b2-691c-11e6-833a-6903a68fbc66.png">

**Comment by webinista** [comment]
Related to #2347

**Comment by jcmeloni** [comment]
@melwoodard Is this old guidance, or does it still represent what you'd like to see? (I think it's old, but didn't want to close without your say so yet).

**Comment by melwoodard** [comment]
@jcmeloni old guidance at this point, we're in the midst of revisiting headings with the branding updates.
