### ISSUE TITLE
setup new SSL certificate for vets.gov before 22oct2016

### ISSUE THREAD

**Issue by joduinn** [department-of-veterans-affairs/vets-website#2857]
The current SSL certificate used on vets.gov will expire on 22oct2016. We should replace/renew the SSL cert before then. 

Note: I'd really like to make vets.gov use Let'sEncrypt auto-renewing certificates, so this will never be a problem going forward - and it will serve as good example to other VA sites. I've filed https://github.com/department-of-veterans-affairs/devops/issues/509 to track that work and am happy to take that on.

fyi: @koconnor719 @MarinaMartin @staceylanger

**Comment by plusjeff** [comment]
Assigning to @jkassemi to update. Feel free to assign out as needed.

**Comment by plusjeff** [comment]
@greggersh : Do you have details on how this was generated last year?

**Comment by joduinn** [comment]
Summary from slack:

0) The existing cert in production will expire in 3 days. It would be publicly embarrassing for DSVA to have expired publicly-visible SSL certs.

1) @greggersh got a new cert from SSLMate a couple of weeks ago and handed it to @ShawnArnwine . Shawn passed the new cert onwards to Mark Riggs @ NSOC, but it has not been deployed yet. Shawn is now working with Mark@NSOC to schedule deployment and will update this ticket when he has an ETA. As this is being handled by Shawn and Mark, I'm reassigning this ticket to @ShawnArnwine 

2) @greggersh is currently the only person who gets notified by SSLMate when this cert is about to expire. Exploring some options to find out how others will also get notified, so there is no single point of failure in future.


John.
fyi:  @MarinaMartin @staceylanger @koconnor719 @plusjeff

**Comment by greggersh** [comment]
For posterity.


[2016.wildcard.vets.gov.certs.zip](https://github.com/department-of-veterans-affairs/vets-website/files/539787/2016.wildcard.vets.gov.certs.zip)

**Comment by ShawnArnwine** [comment]
Done.

**Comment by joduinn** [comment]
@shawn.arnwine @greggersh 

Looks like we are not out of the cert-renewal-woods yet. When I browse to vets.gov, I do see the new 2017 expiry date, which is good. However, I also see:
* a downgraded “B” grade on ssl labs caused by incomplete certificate chain.
* http://dnssec-debugger.verisignlabs.com/vets.gov reporting DNSSEC errors, similar to what we had NSOC fix back in september. See https://github.com/18F/pulse/issues/533 and emails with Mark Riggs @ NSOC for details.

Reopening.

**Comment by greggersh** [comment]
From Shawn from NSOC:

```The certificate you sent us last year included the Server Certificate, Intermediate Cert and Root cert. Testing externally I was receiving certificate chaining errors for all three of your URLs. The certificate you sent this time only contains the Server Certificate in the bundle but no intermediate or root certs. I applied a configuration to use the intermediate and root certificates that were provided for your previous certificate and appears to have cleared the errors I was seeing. Can you test and verify functionality is working as expected?```

Checking the site, we now have an A+ rating on SSLLabs, so I think we're all set.

**Comment by joduinn** [comment]
@ShawnArnwine @greggersh (ccing @plusjeff @jkassemi )

Now finally all good, so thanks for closing. 

1) I confirmed the cert chain is fixed in https://www.ssllabs.com/ssltest/analyze.html?d=vets.gov. 

2) I confirmed the DNSSEC errors are fixed in http://dnssec-debugger.verisignlabs.com/vets.gov. For the record, email from Mark Riggs @ NSOC describes how they fixed the DNSSEC error back in August - and I assume again now. Posting here, so people dont need to rely on my remembering and forwarding this email again!



-----Original Message-----
From: Riggs, Mark (Triple-i/VA-NSOC) [mailto:Mark.Riggs@va.gov] 
Sent: Friday, September 2, 2016 1:23 PM
To: Hyatt, Matthew (Triple-i/VA-NSOC) <Matthew.Hyatt@va.gov>; O'Duinn, John EOP/OMB <JODuinn@omb.eop.gov>; Kalathas, Michael (Triple-i/VA-NSOC) <michael.kalathas@va.gov>
Cc: Arnwine, Shawn M. <Shawn.Arnwine@va.gov>; Polanco, David (VA-NSOC) <David.Polanco@va.gov>; Copenhaver, Chad (VA-NSOC) <chad.copenhaver@va.gov>; Hall, Mark (VA-NSOC) <mark.hall@va.gov>
Subject: RE: DNSSEC errors with vets.gov?

Mr. O'Duinn,

We have been working with vendor on your DNSSEC issue. On their
recommendation we've taken some actions on our end. We are seeing
improvements in DNSSEC resolution but the issues are not completely
resolved. They have identified a couple bugs with DNSSEC from their end but
the BugIDs for the issues are only available internally to the vendor. 

One of the bugs identified was for the DNSVIZ error you were seeing about
the malformed response. This error is due to the way the DNS appliances
handle large records. The record length for a DNS response over UDP is
limited to a 512 byte size. DNSSEC answers however typically are much larger
than 512 bytes so the resolver sets the a bit in the header called the TC
bit which tells the client to ignore this particular DNS answer and
reattempt the same query over TCP instead which can support much larger
payloads. Our DNS server is correctly flagging this bit to truncate and
retry over TCP however doing so they do not include a field in the header
for the opcodes which are required per the RFC for DNSSEC. Some DNS
resolvers see the TC bit set and properly ignore the packet and make a new
request over TCP, some DNS servers check for the rest of the RFC
requirements see that the packet is missing some information and mark the
packet as malformed which in turn invalidates the DNSSEC request causing a
SERVFAIL reply to be issued to the client. I believe this behavior is what
is causing the DNS lookups you referenced in your github post to fail. The
resolver being used to automate their service is seeing what it considers to
be malformed responses and is invalidating the record instead of
reattempting the request over TCP. This variance in behavior can be seen
with the behavior of DNSVIZ reporting this malformed error whereas the DNS
Debugger from verisignlabs is not reporting errors about malformed responses
just the timing issues. We continue to work with the vendor to get a
resolution for this malformed bug but it sounds like it may involve a hotfix
to the version of code we're running and that is going to be something
they're going to have to craft for us which may take some time.

For the timing issues we're seeing with some of the DNSKEYs and RRSIGs
reporting their inception time as being too recent, we have additional calls
scheduled with the vendor to continue troubleshooting this issue and hope to
have a resolution for that problem soon. 

Please let me know if you have any questions, thanks!

Mark Riggs
