### ISSUE TITLE
Should veterans be able to select more than one benefit?

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#2861]
My understanding is that veterans can only receive one benefit at a time. This leads me to believe they should only be able to mark one on the form. (something that can't be restricted on paper, but can digitally.) [correlates to 9a-9d]

Should veterans be able to mark more than one benefit that they are relinquishing in favor of their selected benefit? [correlates to 9e]

**Comment by J-Quag** [comment]
Correct. I should test this in VONAPP as well, but I think in there you can also only choose 1.

**Comment by cweber** [comment]
In VONAPP you can select all of the benefits when choosing what to apply for (9a-9d). VCEs told us sometimes veterans will do this when they don't know what they're eligible for.

9e is set to only allow one selection in VONAPP.

**Comment by J-Quag** [comment]
This is something we'll want to ask Shay then. How they would like to proceed forward. I think it would take up more of the VCE's time if they select all of them. But they might have left it open like that for a reason.

**Comment by cweber** [comment]
Shay's response:
"We need to allow them to choose more than 1 because they can be eligible for more than one.
 
On the 33 election, though, they should only be allowed to select one benefit to relinquish."
