### ISSUE TITLE
Does the application process produce a confirmation number or something similar?

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#2863]
If it does, we could share this on the submission confirmation screen as well as potentially send by email.

It may not be much better than having your name/SS# when it comes to looking it up, but I think it my lend a sense of being able to check in, even if we aren't providing that online.

(This also came up in convo earlier this week.)

**Comment by J-Quag** [comment]
Yes it does currently, opened 2902 to ask backend folks if we're going to generate this and how we're going to be able to get it.

**Comment by cweber** [comment]
These are incorporated into wireframes. Mark is looking into how to create them in #2902
