### ISSUE TITLE
playbook error on page

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2897]
this is appearing on playbook page--have we updated this recently?  do we test after we deploy updates to catch these types of errors??? if not, can we start?   https://www.vets.gov/playbook/ 

@crwallace @plusjeff 

<img width="389" alt="screen shot 2016-08-30 at 8 52 16 am" src="https://cloud.githubusercontent.com/assets/13770771/18089705/457f65b8-6e8f-11e6-8a74-12ea7198f61a.png">

**Comment by crwallace** [comment]
@koconnor719 -- This should be all fixed up now on dev and will be deployed to production within the week.
