### ISSUE TITLE
Hover on back button styles wrong

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2904]
<img width="430" alt="screen shot 2016-08-30 at 2 21 07 pm" src="https://cloud.githubusercontent.com/assets/3886085/18101537/0f95f11e-6ebd-11e6-8bfd-1a561a2a044a.png">

**Comment by jbalboni** [comment]
Couple other related things:

- Disabled styles aren't noticeable
- border on GrowableTable buttons are larger than production hca ones
