### ISSUE TITLE
Link on HCA page ... stays on HCA page

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#2911]
If you click on the link to "find the form you need" on the top of /healthcare/apply, you stay on the page.  But the URL indicates it should go to: /healthcare/apply/#additional-forms. @dannychapman is this something you can look into?  THANKS!!! 

<img width="811" alt="screen shot 2016-08-30 at 2 37 08 pm" src="https://cloud.githubusercontent.com/assets/16196072/18106208/e9a8c4b0-6ebf-11e6-8ad6-99bab3a4fba6.png">

**Comment by rroueche** [comment]
@mollyblake and @dannychapman I'm going through Content issues in GitHub -- is this one still a problem or can we close it?

**Comment by mollyblake** [comment]
@rroueche you can close. Appears to have been fixed. Thanks
