### ISSUE TITLE
Make Facility Locator 508 Compliant

### ISSUE THREAD

**Issue by bshyong** [department-of-veterans-affairs/vets-website#2912]
The facility locator is 0% 508 compliant.

⚠️ Compliance is required for the 508 office to issue a letter authorizing us to operate the Vets.gov website. cc @crwallace 

Suggested fix by 508 office:
- Generate a hidden table with facility information so that screen readers can view it
- Make sure information in the table displays all the adequate information (type of facility, address, etc)
- No need to generate navigation directions
- Test with screen reader to see that the facility locator is usable

Some info on standards for the curious:
https://section508.gov/content/quick-reference-guide#1194.21a

**Comment by crwallace** [comment]
I think we can close this out given that the new compliant facility locator is about to launch.
