### ISSUE TITLE
Process for starting a react application not ready for production?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#2914]
Thinking about the Service and Facility Locator James is working on, as well as Secure Messaging, which we'll be starting on next week...

@crwallace it looks like Prescriptions was specifically added to [build.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build.js#L96) to say that it's not ready for production. When starting other applications, is adding to this file a step we should take in our first PR?  Are there other things we should do when starting applications to make sure they aren't accidentally deployed?

**Comment by jkassemi** [comment]
cc @bshyong, since I'm not _currently_ addressing anything within the Service and Facility Locator

**Comment by crwallace** [comment]
@ayaleloehr -- Yes, that is correct. Anything that you don't want to go live to production immediately should be added to `ignoreList` in build.js.

**Comment by crwallace** [comment]
@ayaleloehr -- would it be helpful for vanguard to put together a readme for how to bootstrap a new react project?

**Comment by ayaleloehr** [comment]
Mostly just didn't want to deploy to prod by mistake!  For example, if we do a production push tomorrow, it looks like edu-benefits would be pushed live? (cc @akainic ).  

So yes, maybe just writing up whatever the steps someone should take are would be great!

**Comment by akainic** [comment]
Education is included in the ignore list in build.js, so I think we should be good.
