### ISSUE TITLE
[Rx] Update disclaimer language, function

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2927]
[Prototype](https://marvelapp.com/iaa9b9)

- [x] Rather than closing and disappearing entirely, disclaimer box should instead toggle open / closed.
- [x] Change the words to reflect what's in the new prototype.

**Comment by webinista** [comment]
@gnakm Can you save us some typing and add the disclaimer in a comment on this issue?

**Comment by gnakm** [comment]
@jenny-h-l has been assigned to come up with the final disclaimer message here: https://github.com/department-of-veterans-affairs/kudos-team/issues/85

Here are placeholder text that I used in the mockups:

THIS LIST MAY NOT INCLUDE ALL YOUR MEDICATIONS

We only list prescriptions VA can refill by mail. If you have any questions about your medication list, please contact your healthcare team.

**Comment by jenny-h-l** [comment]
For now, do this -- one spacing change:

THIS LIST MAY NOT INCLUDE ALL YOUR MEDICATIONS

We only list prescriptions VA can refill by mail. If you have any questions about your medication list, please contact your health care team.

**Comment by ayaleloehr** [comment]
should be unblocked.

**Comment by gnakm** [comment]
We need to change the text again. 
Blocked by https://github.com/department-of-veterans-affairs/kudos-team/issues/85
