### ISSUE TITLE
Some SVGs don't render in HCA or EduBenefits apps

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#2930]
There's a comment to this effect in the hca scss file. Places where it's notable:

- Checkbox checks
- Alert callout icons

**Comment by webinista** [comment]
- Is there a particular browser this occurs in? It seems to work in Chrome, Firefox, and Safari. 
- Are you viewing it on the VA network? What happens when you aren't on the VA network? (WFM, when I'm not connected)

**Comment by akainic** [comment]
I see all the icons when I use Chrome, even on the VA network. I believe this was an issue on Internet Explorer only with HCA, but I'm curious what exactly you're seeing @jbalboni. I can't seem to recreate.

**Comment by jbalboni** [comment]
Strange. I don't have access to the VA network and I'm only talking about when running vets-website locally. I'll put up some screenshots in a little bit.

**Comment by webinista** [comment]
Reproduced it. I'm only seeing this with SVG background images using data URIs in Chrome, Firefox when developing locally.

**Comment by alexose** [comment]
Using the `success` alert as an example:

`background-image: url(data:image/svg+xml;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICI0YmExZDE5OGQ5NDg3ZWU5N2U0Y2Y4NTFlZDJkZTFmMy5zdmciOw==);`

This base64 string decodes to:

`module.exports = __webpack_public_path__ + "4ba1d198d9487ee97e4cf851ed2de1f3.svg";`

So, that doesn't seem right.  Trying to track down what's causing the problem.  90% sure it's the resolve-url module.

**Comment by alexose** [comment]
This is fixed with #3098.
