### ISSUE TITLE
Update navigation to support skipping pages

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#2949]
We need to have the ability to skip certain pages in the form based on information the user has entered.

Tasks:

- [x] Move Nav, NavHeader, and NavButtons to common components folder
- [x] Create edu benefits specific components that wrap Nav and NavButtons and filter out pages that aren't being displayed

Pages that are conditionally shown:

- ROTC History
- Dependent information

**Comment by alexose** [comment]
This is merged as of #2999 and should be ready to go.
