### ISSUE TITLE
[Rx] Add `X-Key-Inflection` header to API calls

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2953]
We have a solution to the camelCase vs snake_case vs kebab-case debate: pass a header to change the separator used in the JSON keys.

This means our API calls now need to have be accompanied by an `X-Key-Inflection` header. 

**For now, set it to `X-Key-Inflection: dash`. This will match the keys we are currently using.**

If you are inclined to put in some extra effort, add: 

- [ ] `X-Key-Inflection: camel`
- [ ] Change existing keys for API attributes to camelCase.

- [Backgrounder on `X-Key-Inflection`](https://www.viget.com/articles/introducing-olivebranch)
- [How to add headers to the `fetch` API](https://hacks.mozilla.org/2015/03/this-api-is-so-fetching/)
- [Fetch API specification](https://fetch.spec.whatwg.org/)

**Comment by U-DON** [comment]
Already merged in a change to make it `dash`, but keeping this in progress since I want to change everything to camel case.

**Comment by U-DON** [comment]
Would also like to pull out the attribute names into constants along with this.

**Comment by webinista** [comment]
Is this task complete for Rx? If so, please close this.
