### ISSUE TITLE
Rename section to page in HCA and styles

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#2963]
We want to use a naming convention of chapter > page > block for forms. HCA is using section in place of page and a variety of other names for chapter/block. This should be be cleaned up in the code.

We also need to update the styles (primarily the navigation styles) to use chapter and page instead of section and subsection.

**Comment by jcmeloni** [comment]
@jbalboni Is this something that still needs to be done or was it handled elsewhere? Thanks!

**Comment by jbalboni** [comment]
Still needs to be done, but @akainic should weigh in on if we still want to do it.

**Comment by akainic** [comment]
It would be nice to do but definitely not a priority. Probably will be easiest to do once we clean up the validation functions as well. How long are we comfortable keeping a ticket open thinking it will get done at *some* point in the future?

**Comment by ayaleloehr** [comment]
Pinging here 3 months later to see if this still needs to happen (and if so, please label it so it will show up in the Waffle board)

**Comment by J-Quag** [comment]
@annekainicUSDS  @raquelromano-gov  @jbalboni  Not sure if this is something to do while we're moving to RJSF?

**Comment by jbalboni** [comment]
@J-Quag I think this will get done for the most part by moving to rjsf.

**Comment by J-Quag** [comment]
I think we can close this if it will be mostly done with rjsf. Unless there are objections?

**Comment by jbalboni** [comment]
Nope, go for it
