### ISSUE TITLE
Feedback from user: 1010EZ-AD not working as it should. 

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/vets-website#2966]
Hey @koconnor719 --

We got this feedback from feedback@va.gov, so I wanted to post it here for tracking. @akainic mentioned that it might be a redirect issue. Is this something you are tracking? If not, feel free to reassign.. 

"I do not have an idea, but rather a comment to make about a feature. When the Healthcare application process moved to Vets.gov it was not available to those applying while on Active Duty. Then a short time later it showed up in an additional forms area. However that form is not working at the completion of the form and during the submission part. Once you check the "Confirm" box and send the form to the VA for processing you get the two boxes; the first one you click allow, the second you click yes, and then what used to happen is that an I.E. window would open and you would be presented with a Submission ID number indicating that your form was indeed received. Now, what happens is you get to the end, and then the I.E. window opens, but it just hangs and then reloops back to a Vets.gov page that does not fully load correctly. There is a short circuit in the submittal process."

**Comment by koconnor719** [comment]
this is an enhancement we have documented for future; unsure of when this work will begin.

**Comment by akainic** [comment]
@koconnor719 This issue sounds like more than just the current AD form doesn't work well. It sounds like a redirect issue when trying to actually submit the form after completing it. It sounds like once you clicked submit you were redirected to another page with a confirmation number. I'm guessing that page now redirects back to Vets.gov, which is confusing for the user. We may need to take down the redirect on this confirmation page. Assigning back to you for that.

**Comment by koconnor719** [comment]
duplicate ticket; the AD form is being removed.
