### ISSUE TITLE
Talk to Shawn about GovCloud

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2969]
We may need special permission to connect to the VA endpoint through GovCloud. Connect with Shawn Arnwine about this.

**Comment by joduinn** [comment]
@akainic @markolson if it helps, both @orischwartz and myself have also done various VA-to-govcloud projects and would be happy to help.

**Comment by akainic** [comment]
Yes, thanks @joduinn! Will let you know.

**Comment by akainic** [comment]
Provided Shawn with the IP addresses and the ISA MOU: https://github.com/department-of-veterans-affairs/vets.gov-ato/issues/204
