### ISSUE TITLE
Breadcrumbs appearing twice on HCA

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2987]
<img width="1068" alt="screen shot 2016-09-07 at 2 21 17 pm" src="https://cloud.githubusercontent.com/assets/3886085/18323617/67458006-7506-11e6-8f55-a87acac6af69.png">

**Comment by jcmeloni** [comment]
@akainic Can't duplicate any more, so closing...

**Comment by akainic** [comment]
Yep, this has been fixed. Thanks!
