### ISSUE TITLE
API calls failing for /rx on dev.vets.gov

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3011]
I believe this is because of the proxy settings in build.js not being there in dev, so requests are going to https://dev.vets.gov/rx-api/prescriptions/active instead of https://dev.vets.gov/api/v0/prescriptions/active

Then there may also be authentication errors as well, depending on where auth is being added for local development. 

Would be great to have this fixed this week so we can demo dev.vets.gov/rx to the team. 

cc @webinista @U-DON

**Comment by U-DON** [comment]
Not sure where to make this change. We currently use a local config file to handle auth. I guess there are environment variables we can set wherever dev is being deployed? Any ideas, @alexose?

**Comment by alexose** [comment]
I think the best thing to do is to make the URL the same on local and dev:

https://github.com/department-of-veterans-affairs/vets-website/pull/3026

**Comment by ayaleloehr** [comment]
Working now.
