### ISSUE TITLE
Refactor validation functions

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3012]
There's a validations.js file in common/ and one in edu-benefits/. The validations in common/ have hca specific functions and generic functions. The generic ones are duplicated in edu-benefits/. 

Should reorganize the code so that common, generic validation functions live in common and app specific ones live in the application folders.

**Comment by alexose** [comment]
A good first pass might be to look at exact matches with jsinspect.   At first glance, there are [quite a few](https://gist.github.com/alexose/443807e1af56a98456856768f4f6e7e1).

The second pass would probably be to identify validations that *should* be the same but have diverged.  This is the tricky part, since it will surface all kinds of subtle differences.

**Comment by akainic** [comment]
I agree, figuring out how to bring together validations that have diverged will be tricky. I would suggest doing this first, but it might be tedious to sort through all the validation files and find the validation functions for the same field/purpose that are slightly different, as this will naturally become clear as we start to consolidate them.

I wonder if we could break up the work in this way:
1. Consolidate validations for general fields (e.g. `isBlank`, `isValidRequiredField`, etc.)
2. Consolidate validations for components in `common/questions` (e.g., `isValidFullName`, `isValidAddressField`, etc.)
3. Consolidate anything that remains that isn't specific to a particular app

Each of these will require making sure that all components using these validation functions are now using the correct ones at the correct file path, and that all other validation functions using these validations (like section validation functions, e.g., `isValidSpouseInformationSection`) are using the right ones as well. Will also need to import validations from `common/utils/validations.js` into the validation files for education and health care.

**Comment by alexose** [comment]
That sounds great to me.  Do you prefer breaking the work down into sub-issues, or does a task list suffice?

- [ ] Consolidate validations for general fields (e.g. `isBlank`, `isValidRequiredField`, etc.)
- [ ] Consolidate validations for components in `common/questions` (e.g., `isValidFullName`, `isValidAddressField`, etc.)
- [ ] Consolidate anything that remains that isn't specific to a particular app

**Comment by leannammiller** [comment]
@jbalboni will review and coordinate with @akainic

**Comment by leannammiller** [comment]
@akainic is working on this

**Comment by leannammiller** [comment]
@akainic or @jbalboni can you please estimate remaining work on this ticket?

**Comment by akainic** [comment]
I think it is 6-8 more hours of work for me. I can complete this week.

**Comment by akainic** [comment]
Completed.
