### ISSUE TITLE
Resolve Issue with Cypress Test

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/vets-website#30399]
# Description
In order to upgrade from Cypress 12 to Cypress 13 several test specs belonging to this team needed to be marked skipped. Please see the below list of test specs --

- src/applications/appeals/995/tests/995-supplemental-claim-maximal.cypress.spec.js

# Acceptance Criteria
- [ ] The test marked skip in order to upgrade to Cypress 13 is no longer skipped

**Comment by Mottie** [comment]
Complete in #30473
