### ISSUE TITLE
Update existing pages to match latest wireframes

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3056]
Some of our form pages are likely out of date now, we should make another pass through each one and make any necessary updates.

**Comment by cweber** [comment]
- [ ] Year of commission (text field) - move from bottom of [Military History](Year of commission) to top of [ROTC](https://dev.vets.gov/education/apply-for-education-benefits/application/military-history/rotc-history)

**Comment by goldenmeanie** [comment]
- [ ] viewport doesn't scroll back to top of page on "continue" so you frequently have to scroll manually to the start of the form.

**Comment by jbalboni** [comment]
Year of commission is fixed in #3081.
