### ISSUE TITLE
[Rx] "Refill in process" glossary definition

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3068]
We don't currently have a glossary definition for the "Refill in process" status. We need one.

**Comment by gnakm** [comment]
@webinista The Glossary definition is still in discussion with stakeholders. Will put the definitions here once we get a final verdict.

**Comment by gnakm** [comment]
**Active** – A prescription that can be filled at the local VA pharmacy. If you have refills, you may request a refill of this prescription from your VA pharmacy.

**Deleted** - Waiting from stakeholder

**Discontinued** – A prescription your provider has stopped. It is no longer available to be sent to you or pick up at the VA pharmacy window. Contact your VA healthcare team if you need more of this medication.

**Expired** – A prescription which is too old to fill.  This does not refer to the expiration date of the medication in the bottle. Contact your VA healthcare team if you need more.

**Hold** - This prescription cannot be refilled until a hold is resolved by the pharmacy. Contact your VA pharmacy if you need this prescription now.

**nonVerified** - Waiting from Stakeholder

**Suspended** - An active prescription that is not scheduled to be filled yet.  You should receive it before you run out.  Contact your VA pharmacy if you need this medication now.

**Unknown** - There has been an unknow error from our end. Contact your VA healthcare team for more information.

**Comment by webinista** [comment]
@gnakm does this mean that the `refillinprocess`/"Refill in process" status should never be linked?

**Comment by webinista** [comment]
Based on our chat today, _Refill in process_ and _Refill submitted_ do not have glossary definitions and should not be linked. Is that correct?

**Comment by gnakm** [comment]
Updates from call with Tiffany:
- [ ] Hold + Suspended should be in view history page, so none of the prescription status with link should be shown on cards (related to issue #3383).
- [ ] `Refill in progress` + `Submitted` should be in bold, no link to definition
- [ ] Last fill date: Alex is getting answers from Ken Graham
- [ ] Deleted and Non-verified should all be defaulted to Unknown
--

### Mocks of Active Cards 

- [ ] We need to have Call provider changed to Message my provider with a link to SM

When Rx is refillable + package can be tracked
<img width="204" alt="screen shot 2016-10-18 at 2 08 37 pm" src="https://cloud.githubusercontent.com/assets/13420618/19490253/6fb44442-953c-11e6-82b6-0fe2e1b10fb7.png">

When Rx was just submitted + package can be tracked
<img width="250" alt="screen shot 2016-10-18 at 2 08 25 pm" src="https://cloud.githubusercontent.com/assets/13420618/19490278/8628e9a8-953c-11e6-8b70-f904f52fc665.png">

When Rx is refillable + package can be tracked + 0 refills left
<img width="370" alt="screen shot 2016-10-18 at 2 10 27 pm" src="https://cloud.githubusercontent.com/assets/13420618/19490316/acfab200-953c-11e6-8698-22d0cf85dddf.png">

When Rx was just submitted + package can be tracked + 0 refills left
<img width="256" alt="screen shot 2016-10-18 at 1 57 35 pm" src="https://cloud.githubusercontent.com/assets/13420618/19490292/931b88aa-953c-11e6-9527-e0177140e358.png">


### Glossary Revision

**Active** - A prescription that can be filled at the local VA pharmacy. If you have refills, you may request a refill of this prescription from your VA pharmacy.

**Discontinued** (discontinued, discontinuedByProvider, discontinuedEdit) - A prescription your provider has stopped. It is no longer available to be sent to you or pick up at the VA pharmacy window. Contact your VA healthcare team if you need more of this medication.

**Expired** - A prescription which is too old to fill. This does not refer to the expiration date of the medication in the bottle. Contact your VA healthcare team if you need more.

**Hold** (hold, providerHold) - This prescription cannot be refilled until a hold is resolved by the pharmacy. Contact your VA pharmacy if you need this prescription now.

**Suspended** - An active prescription that is not scheduled to be filled yet. You should receive it before you run out. Contact your VA pharmacy if you need this medication now.

**Unknown** (deleted, nonVerified, unknown) -There has been an unknow error from our end. Contact your VA healthcare team for more information.
