### ISSUE TITLE
EDU walkthrough with larger stakeholder group

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-website#3071]
Including others in a walkthrough (of what, depends on what is ready) with the full charter stakeholder group.
Will set depending on their availability.

**Comment by akainic** [comment]
This is happening today! Will document outcomes here once the meeting happens.

**Comment by akainic** [comment]
Got valuable feedback from stakeholders on a number of issues:
1. Concern with adding a checkbox to allow users to select all benefits on benefits selection page
2. Recommendation to default current relinquishment date to current date
3. Recommendation to remove all claims status questions
4. Recommendation to move military service questions to the end

Scheduling a follow up meeting to go through the form in more detail with a smaller group and ask for more detail on the above recommendations.

**Comment by J-Quag** [comment]
Was #4 to move it to the end or if it was just that question "Use this period of service for the current benefit selection or for another benefit" to the end of the military service section. (ie after the entering of the military service, then this question would appear.) @akainic

**Comment by akainic** [comment]
Hmm not sure, that's all I have written in my notes. It might be the later, let's confirm with @cweber and @goldenmeanie.

**Comment by cweber** [comment]
@J-Quag I'm having a hard time following your question, but if I'm reading it right... I believe the recommendation was to move it to the end of that section. We've heard that comment twice now and I actually think we're all set to do that, but maybe worth bring up so we can just confirm "yes". 

(The original question on the paper form is framed in a particularly complex way, so it probably warrants a walk through just to make sure we all agree that we're accomplishing the same goal by handling it how we are.)

**Comment by J-Quag** [comment]
@cweber   Sorry, it was poorly worded on my part :)
  But yes, that is what I mean.
