### ISSUE TITLE
Continue loads new form but doesn’t scroll to the top

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3073]
When you click continue to go to the next part of the form. The page stays at its current scroll position. This means you frequently have to scroll back to the top of the screen to fill out the next field. As far as I can tell this is on all screens.

**Comment by goldenmeanie** [comment]
Might be a duplicate of [Add scrolling](https://github.com/department-of-veterans-affairs/vets-website/issues/2925)

**Comment by akainic** [comment]
Yes, this is a duplicate of the other ticket. Closing this one and keeping the other open.
