### ISSUE TITLE
Should we have a React style guide?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3078]
Now that we've committed to React, I think we should document our practices using it. A lot of this is covered our ESLint configuration. I think those standards should also be documented elsewhere for the sake of text editor setup. But other things are not. 

Things to discuss:
- Whether to include the file extension for imports
- Whether to use string literals or exported constants for, uh, constants.
- Importing multiple functions from a package on one line vs multiple lines
- camelCase (a settled point for front end, but AFAIK, not a documented one)

Good idea? Bad idea?

**Comment by alexose** [comment]
At some point in the distant past we started following the [AirBnB style guide](https://github.com/airbnb/javascript) which is where most of our strict eslint rules come from.  They give some guidance on a few of these topics, like camel case and imports.

As for file extensions, we could enforce them with [this plugin](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md).

For constants I think the rule should be that if they're used in more than once place, they get imported.  I know that I've broken this rule in the past :P

**Comment by bshyong** [comment]
Good idea! We should document so that there is a source of truth to refer to when writing code - also can be useful during code reviews

**Comment by jcmeloni** [comment]
@crwallace is there an actionable item here you want to track for vanguard?

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
