### ISSUE TITLE
Fieldset <legends> and headers lack hierchy

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3079]
The current system of `<legends>` and `<h4>`s doesn't account for the visual hierarchical difference between a page title and a collection of fields. (e.g. address)

`<fieldsets>` in HCA/Education Benefits are currently being used to collect all fields in a section rather than intimately related fields (e.g. Address). This could potentially be rethought and would provide more logic for label collections of fields appropriately.

**Comment by goldenmeanie** [comment]
This seems like an opportunity to expand USDS guidelines

**Comment by jcmeloni** [comment]
@crwallace Is this something you want to address from a vanguard perspective or keep it in the application teams' buckets?

**Comment by cweber** [comment]
This actually just got a second issue ( #4222 ) submitted by our team based on a design review that @melwoodard did.

Happy to consolidate to whichever one is clearer, but I agree that figuring out who needs to have this on their radar is important.

**Comment by melwoodard** [comment]
@cweber I think it makes sense for the edu team to tackle the fieldset hierarchy issue since you've been working closely with it. The larger discussion / implementation around site-wide patterns can go in the Vanguard bucket.

**Comment by cweber** [comment]
👍  I see a future for this to get tackled as we approach the next Edu form(s).

cc @jbalboni

**Comment by jcmeloni** [comment]
Closing;  subsumed by https://github.com/department-of-veterans-affairs/vets.gov-team/issues/576 (and others)
