### ISSUE TITLE
Make Recommendation: Date fields to follow US WDS (field, field, field)

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3080]
Current date fields on HCA are handled with two drop downs and a text field. This was presumably done to make it easier to handle the data inputs, but it's not as friendly for the user filling out the form.

Recommendation:
Three text areas that can programmatically handle the variation in entry (jun, june, 6)

**Comment by jcmeloni** [comment]
@akainic I recall this was perhaps handled elsewhere. Can you confirm?

**Comment by akainic** [comment]
We haven't made this change yet. @cweber is this still something you want to do?

**Comment by cweber** [comment]
Yes, I think so. But probably worth @goldenmeanie and I taking another look to make sure we're proposing the best alternative.

Generally, any time we can handle the complexity of field entry on behalf of the user, the better the experience will be for them. This applies to the issues we have around accepting different phone formats, but also the potential to format phone/SS entries to look like what they are AS the applicant is filling it out.

Ehancements, for sure.

**Comment by leannammiller** [comment]
to discuss in sprint planning 12/12

**Comment by leannammiller** [comment]
more conversation needed

**Comment by leannammiller** [comment]
@goldenmeanie will make a recommendation

**Comment by goldenmeanie** [comment]
We'd like the date fields to switch from drop-down to text entry. It would be great if they could recognize 01|1|Jan|JAN|January. But limiting it to numbers only would be an acceptable fallback ; )

**Comment by leannammiller** [comment]
okay so next steps here would be to write the tickets for this work, correct @goldenmeanie ?
