### ISSUE TITLE
Facility Locator Questions

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3086]
A few UX questions we will need to decide on are written out below, as well as what I (mostly arbitrarily) went with on the prototype for reference.  

If a user blocks geolocation (or before a user accepts geolocation)
- [ ] Should a map show up at all?
  Prototype = Yes
- [ ] What should the default zoom level be? 
  Prototype = 5
- [ ] What should the default location be?
  Prototype = 38.8, -95.50 = center of US

If a user accepts geolocation
- [ ] What should the default zoom level be?
  Prototype = 10
- [ ] Should a pin representing the users location show up on the map?
  Prototype = No

Before the user does a query
- [ ] Should pins representing VA facilities show up on the map preemptively?
  Prototype = No. 

After a user does a query
- [ ] Should there be a default zoom level?
  Prototype = 10 (but should actually probably be determined by Mapbox (or whoever is doing the geolocation so that a query for Seattle is more zoomed in than a query for Kansas, for example). 
- [ ] Should we show all the results within the map or only the first X results?  And if the latter, how do we define "first" and what is X?
  Prototype = Shows all results.  

cc @gnakm @bshyong @crwallace @NatalieEMoore

**Comment by ayaleloehr** [comment]
On the detail page:
- [ ] In the map view, should all the facilities from the search be there? Just the one facility the user clicked on? How about the search location?  Prototype: just the one facility and not search location
- [ ] When there are only one benefits type for a facility (which is the general case; it's rarer that there are both health and benefits at the same place), should we show two tabs on the detail page or just one?  Prototype: we showed both, but this was mainly because I was struggling with JS to only show one and still have it look good. Ideally, I think I would have only had tabs for things that were actually at the facility.

**Comment by gnakm** [comment]
@ayaleloehr RE: detail page

- [ ] In the map view, we should *only* show the facility that the user clicked on. In some cases of showing both search location + facility location, the map may be zoomed out a lot and it is more important to show the location more in detail. Also, users will have a link to driving directions so don't think we need both on map. 

- [ ]  We will no longer be using tabs for benefit types but instead have a list view. 
Example: This is an example of having only one facility type with one service. Detail page should only show whatever benefit types is available.
![mobile facility choice act](https://cloud.githubusercontent.com/assets/13420618/18635470/354fd7bc-7e53-11e6-822d-84226a8eb39f.png)

vs. 

Example: facility with more options. 
![mobiel facility detail](https://cloud.githubusercontent.com/assets/13420618/18635594/92394882-7e53-11e6-88e4-185e16a5faa6.png)

**Comment by NatalieEMoore** [comment]
Can this issue be closed?

**Comment by bshyong** [comment]
@NatalieEMoore yep, it's out of date—closing
