### ISSUE TITLE
[Rx] Refactor ConfirmRefillModal to use same modal pattern as Secure Messaging

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3091]
See #3088.

~~Then move to `src/js/common`~~ **Update:** Moving is already done. Just need to make `ConfirmRefillModal` use the common component.

**Comment by jcmeloni** [comment]
@webinista With the merged PR I think this is close-able -- please confirm?

**Comment by webinista** [comment]
Can't close yet. This task is to refactor the `ConfirmRefillModal` component to use the common modal component instead.

**Comment by webinista** [comment]
Just added a PR that _will_ close this
