### ISSUE TITLE
Facility Locator Design Iterations

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3094]
These are the iterations I made after our design review meeting yesterday. Please leave any comments, feedback or questions here! 

### Notes from meeting 
- Search box should have Address & Facility type as default. Filtering Service type is an option.
- Results and detail page should have facility type (health, benefits, cemetary...)
- Pins: Use numbers. Explore how to make facility types distinct
- Your location vs. numbered results pins should be distinct
- Phone number: We should always default to the "main phone" number. If there is no main number but another one, we will create a logic to always have 1 number available (Alex Y-L)
- Make Phone number and directions bigger, more clickable, more accessible for users with different motor skills

## Mobile view

Default search
![mobile search](https://cloud.githubusercontent.com/assets/13420618/18587612/ebc20a66-7bf0-11e6-8285-2df1feff0a6d.png)

Advanced search
![mobile advanced search](https://cloud.githubusercontent.com/assets/13420618/18587621/f2407e4a-7bf0-11e6-8fc7-571f45983b69.png)

Results list
![mobile results list](https://cloud.githubusercontent.com/assets/13420618/18587633/ff71d03c-7bf0-11e6-8ec9-d74c487d0b77.png)

Results map
![mobile results map](https://cloud.githubusercontent.com/assets/13420618/18587661/1506e694-7bf1-11e6-9ac7-3ac2b50edffa.png)

Facility detail
![mobiel facility detail](https://cloud.githubusercontent.com/assets/13420618/18587673/2adea5ce-7bf1-11e6-98f6-a54ddbe03fb9.png)

## Desktop view

Default search
![desktop search](https://cloud.githubusercontent.com/assets/13420618/18587695/448d3346-7bf1-11e6-9b4e-1ea631841c82.png)

Advanced search
![desktop advanced search](https://cloud.githubusercontent.com/assets/13420618/18587715/58d3aae2-7bf1-11e6-8a52-d6282a4253ed.png)

Results list
![desktop advanced resu ts](https://cloud.githubusercontent.com/assets/13420618/18587720/5faf9290-7bf1-11e6-9a51-9a9eeccf185d.png)

Facility detail
![desktop facility detail](https://cloud.githubusercontent.com/assets/13420618/18587732/6ab034f6-7bf1-11e6-94e2-a509d1d2c84e.png)

## Long list view

![mobile facility long list](https://cloud.githubusercontent.com/assets/13420618/18587751/7b89d304-7bf1-11e6-8bdc-87013831d386.png)

![desktop facility long list](https://cloud.githubusercontent.com/assets/13420618/18587756/80590350-7bf1-11e6-871f-ab8a98869ec4.png)

## Choice Act (short content)

![mobile facility choice act](https://cloud.githubusercontent.com/assets/13420618/18587767/8b775138-7bf1-11e6-8698-2813e771a1c0.png)

![desktop facility detail for choice act](https://cloud.githubusercontent.com/assets/13420618/18587772/8ed95150-7bf1-11e6-918a-abb2934c8321.png)

**Comment by bshyong** [comment]
Thoughts on making the search panel sit flush with the left side of the map?

Personally it is clearer to me that there is one usable/visible map area on the right, and one search control pane on the left where the two are visually distinct. The floating search control makes me wonder if there are markers hidden underneath and also makes it difficult to implement, e.g. how do we know that some of the results in the list are not covered by the control?

**Comment by bshyong** [comment]
Design question: How should we display multiple phone numbers if a facility has them? Or should we only use the main number?

![screen shot 2016-09-16 at 12 14 38 pm](https://cloud.githubusercontent.com/assets/303289/18598380/4794bfc6-7c07-11e6-8697-bc6dd51d184f.png)

**Comment by gnakm** [comment]
@bshyong 
The floating search panel hiding results is a legitimate problem so thanks for flagging that! Teasing out some other possibilities so will get back to you on that. 

We will only display the main number. If a main number is not available, we should have it default to what's available. However we should put in order what the next default is so that for example, Fax is not the immediate default. @ayaleloehr Could we chat about this?

**Comment by gnakm** [comment]
### Font Awesome Icons


<img width="57" alt="screen shot 2016-09-21 at 2 05 44 pm" src="https://cloud.githubusercontent.com/assets/13420618/18722914/81127a26-8004-11e6-9b32-11252ef6296d.png">

fa-phone `[&#xf095;]`

For directions we are going to go with a map instead:

<img width="60" alt="screen shot 2016-09-21 at 2 03 48 pm" src="https://cloud.githubusercontent.com/assets/13420618/18722850/3e6bf224-8004-11e6-9f6b-6487fe99e41c.png">
fa-map `[&#xf279;]`

**Comment by bshyong** [comment]
@gnakm a SVG for the icon will be awesome.  I can make a NumberedIcon component to render them on the map
