### ISSUE TITLE
add an accessibility principle

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#3104]
We have 9 design principles on our site - yay! but nothing about accessibility. I propose adding a tenth, that is about designing to be accessible first. I will add one at the bottom here, please rewrite it if you have better words!

https://www.vets.gov/playbook/

Design Principles
1. Understand human need: design for people, rather than VA’s systems
2. Assume every visitor is new
3. Speak clearly, respectfully and directly
4. Help people reach their goals every time
5. Connect with customers. Create opportunities for feedback and dialog
6. Research, observe, test and continuously improve
7. Measure what matters
8. Be device agnostic
9. Employ modern development practices – be agile
10. Design for accessibility and a diverse set of people with physical, mental, or environmental conditions.

**Comment by maryannbrody** [comment]
Great idea @emilyville !

I wonder if we want to make the point more about designing for *everyone* and *universal design* -- something like, "Design to meet the needs of everyone — including users with disabilities — no matter how they go online." 

OR something like that/similar?

cc: @crwallace

**Comment by emilyville** [comment]
I think this wording is a significant improvement, @maryannbrody.

**Comment by maryannbrody** [comment]
@emilyville whenever this gets added, I'd love to change what I wrote -- 

"Design to meet the needs of everyone — users of all abilities — no matter how they access the web."

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
