### ISSUE TITLE
FL map and search box design for desktop

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3111]
Related to: #3094 
@crwallace @bshyong 

Ben brought up a really good point about the floating search box + results blocking some search result pins from being clickable. There were some suggestions such as having a left side bar but visual issues came up such as weird alignment problems. 

<img width="662" alt="screen shot 2016-09-19 at 11 14 12 am" src="https://cloud.githubusercontent.com/assets/13420618/18650417/fa462eba-7e92-11e6-98ee-7c2a47fb06e3.png">

Courtney from your design perspective, if the alignment isn't bothersome, we could move forward with something like this:

![desktop left side bar](https://cloud.githubusercontent.com/assets/13420618/18650451/2308ab8e-7e93-11e6-9d77-af92bed74e23.png)

or other suggestions:

Not doing a full bleed map:
![desktop search alignment](https://cloud.githubusercontent.com/assets/13420618/18650468/30264506-7e93-11e6-9ca4-6aff0cd03f36.png)

Consider tools having a different treatment from other sections of vets.gov and changing placement of breadcrumb and title

![desktop search breadcrumb](https://cloud.githubusercontent.com/assets/13420618/18650498/5d3a6d4c-7e93-11e6-91ac-aecec5d10665.png)

Open to suggestions, feedback, votes, etc!
Courtney feel free to assign this back to me!

**Comment by crwallace** [comment]
I think keeps things in alignment is important especially since all of our other content pages follow that same structure.

I am inclined to not make the map full bleed as the map is not the "main" source of information for the user.

**Comment by bshyong** [comment]
I agree with @crwallace's comments above. If we want more map real estate, how about we align the left side and let the map bleed all the way to the right?  Will that look less weird?

**Comment by gnakm** [comment]
These are all great comments. Let's go with design 2 (not full bleed). @bshyong I do not think we should bleed to the right. The page will feel unbalanced and it will be a right side alignment problem :p 
I think it will be a combination of zoom and possibly make the page visually pop a little more. 

_goes to tweak design..._

**Comment by gnakm** [comment]
@bshyong Courtney and I chatted about design. This is what it would look like and search results broken down into steps. 

Default search look
![desktop search 1](https://cloud.githubusercontent.com/assets/13420618/18682989/69f0fab6-7f3c-11e6-8737-2f3a209f2602.png)

Search fields are hidden and results are shown
![desktop search 2](https://cloud.githubusercontent.com/assets/13420618/18682994/6d94b02c-7f3c-11e6-8278-040e3e0be377.png)

If user chooses to search again, s/he could edit search and results will be pushed to the bottom
![desktop search 3](https://cloud.githubusercontent.com/assets/13420618/18683001/7367f86a-7f3c-11e6-8709-fec3a8bc6ffb.png)

**Comment by bshyong** [comment]
@gnakm Do we want to show the user what they filtered for? Similar to how one can currently see that the results are all near the `20001` zip code.

Also, what is included in the "More options" panel? The down arrow makes it look like it's currently closed. Or is it actually opened and only includes the "choice act providers" check box?

**Comment by crwallace** [comment]
@gnakm -- I agree with @bshyong we can display the facility type that the user selected if they select a facility type, however, if they do not we can just show the zipcode. 

I think we should start wrapping up our changes so we can get ready for user testing next week and make changes based on user feedback.

**Comment by gnakm** [comment]
@crwallace @bshyong Yup agree with you both on the facility type and zip results. 
More options  shows service types. That didn't change from previous design.

<img width="222" alt="screen shot 2016-09-20 at 3 49 40 pm" src="https://cloud.githubusercontent.com/assets/13420618/18686423/df4be1e2-7f49-11e6-9580-03d9c7ed81cf.png">



If there is a better way to document all of this, please let me know. Other than that, i don't think we have any pressing design changes.

**Comment by bshyong** [comment]
Looks good to me! Will we need the app to be functioning, or can the user testing be done with screenshots? Depending on the availability of API data (it's currently VA VPN only) we might need to use hardcoded/mock data

**Comment by crwallace** [comment]
@bshyong --
I think we can use the mock data the Alex has give us and we will direct the user research around that data if the API is not ready.

**Comment by gnakm** [comment]
Closing this because it's an older design and were already implemented in the past.
