### ISSUE TITLE
Branch of Service should be a dropdown

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3116]
Branch of Service in 3.0 Military History is displaying as a text field, but is selectable as a dropdown.

Needs to display as a dropdown.

**Comment by jbalboni** [comment]
@cweber What browser are you looking at this in? We're using a dropdown for this field, but maybe the css is messed up somewhere?

**Comment by cweber** [comment]
It was in Chrome. I was messing with it while we were in our checkin. It's possible I was mistaken. I'll doublecheck.

**Comment by jbalboni** [comment]
@cweber Did you get a chance to check this again?

**Comment by cweber** [comment]
I think I'm crazy. Closing.
