### ISSUE TITLE
Add 'Date for relinquishment'

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3130]
A date field should get exposed on the benefits eligibility page when you select a benefit to relinquish. (This field should handle future dates.)

![screen shot 2016-09-21 at 11 04 43 am](https://cloud.githubusercontent.com/assets/417657/18716561/47f4b132-7feb-11e6-8e07-9b59d8c42328.png)

**Comment by jbalboni** [comment]
This field exists now in master, but the label is "Effective date". The change for this issue is just to update the label, I believe.

**Comment by cweber** [comment]
Effective date is good for now. We need to make sure that's plain language and the content folk missed it on their first pass.
