### ISSUE TITLE
Add 'Are you applying using...' question to Benefits Eligibility

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3133]
**DO NOT begin implementing this until after the stakeholder review**

We've added a new question to Benefits Eligibility that will help catch people that may be using the wrong form to apply for benefits.

This field will have a couple of dependencies that will display redirect messages for those that are in the wrong place.

Check the wireframes for all variations, but this is the idea of the question:

![screen shot 2016-09-21 at 12 18 00 pm](https://cloud.githubusercontent.com/assets/417657/18719468/77e10ec2-7ff5-11e6-8a20-f253855596e9.png)

**Comment by jbalboni** [comment]
FYI for devs: this question is commented out in the code for the BenefitsSelectionFields component.

**Comment by jbalboni** [comment]
@goldenmeanie Is this something we want to do at some point?

**Comment by cweber** [comment]
I think not at this point and I think that probably means not before Vets day. And in that case, if we come back to this, hopefully it means we're resolving the greater problem of implementing more of the forms.

So if the question is about whether you should remove the comment code, I'd say yes.

But maybe leave this in the backlog so we can find it again if it comes up?

**Comment by cweber** [comment]
Closing. I think this has evolved into our conversation about multi-forms. But it's interesting to see how long ago we started searching for a solution to clarify that point of confusion!
