### ISSUE TITLE
Add support in other languages

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#3135]
This came via email:

> One of our team members just got back from Puerto Rico and one of the VAMC. One of the comments they got back was there they felt isolated because they didn’t know they could use the service since everything is in English. I don’t know what we could do other than mentioning a translator can be available as requested or if there is something to not isolate them. I know this isn’t an immediate fix, but we do have several Veterans who live in that area. Thanks in advance!

This could be addressed by adding multilingual support, a spanish version of vets.gov, a call center or support number with multilingual support ...

The priority and workload is unknown. Labeling as enhancement.

**Comment by ayaleloehr** [comment]
While this is interesting and be valuable, it is not currently in scope and thus not actionable at this time. Closing.
