### ISSUE TITLE
Are we allowing veterans to select multiple benefits?

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3154]
Overview: Selecting "I don't know which benefit to apply for" selects all benefits. Do we want to encourage veterans to be able to select all benefits out of confusion, or should we provide better resources to help veterans understand which benefit to apply for before completing this form?

Follow-up: schedule meeting with Shay Norton and Tom Alphonso. Invite Caitlin, Alex, Jeff, Anne, Mark, and Josh.

**Comment by J-Quag** [comment]
Yes, they are allowed
