### ISSUE TITLE
USWDS error styling alignment

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3162]
When the field has an error it pushes everything in by a few pixels and this messes up the alignment.

**Comment by cweber** [comment]
Additionally, when a field has an error it is collapsing vertical (top) padding between form elements.
`.usa-input-error` needs `margin-top: 3rem;`

US WDS
![screen shot 2016-09-23 at 10 32 48 am](https://cloud.githubusercontent.com/assets/417657/18789727/09a5973a-817a-11e6-9baa-207445267772.png)

Education Benefits
![screen shot 2016-09-23 at 10 33 31 am](https://cloud.githubusercontent.com/assets/417657/18789732/0e3677ec-817a-11e6-9a19-f0ee847564c7.png)
