### ISSUE TITLE
Broken link on filing a claim page

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3165]
This page 

https://www.vets.gov/disability-benefits/apply-for-benefits/help/index.html

has a broken link if you click "How do I file while on Active Duty" near the bottom.  I don't know if the best approach is to remove that piano key or to change the link to elsewhere?

**Comment by crwallace** [comment]
@rickleegit and @dannychapman  -- What do you want to do with this broken link?
