### ISSUE TITLE
Primary button color is inconsistent with HCA

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3170]
Primary button in the Edu Bennies form should use primary blue #0071bc instead of #112e51

**Comment by jbalboni** [comment]
@akainic It looks like we're doing this intentionally in _m-button.scss:

```
.usa-button,
.usa-button-primary,
.usa-button:visited,
.usa-button-primary:visited,
button,
[type="button"],
[type="submit"],
[type="reset"],
[type="image"] {
  background-color: $color-primary-darker;
}
```

Any idea why?

**Comment by akainic** [comment]
Not sure, @crwallace @bshyong is this something that you added? Looks like it might have been for 508 compliance?

**Comment by bshyong** [comment]
@akainic I think we might have added it because there was an issue with contrast ratios—which page is this on?

**Comment by jbalboni** [comment]
@bshyong That code is in the generic button styles: src/sass/modules/_m-button.scss

**Comment by bshyong** [comment]
@jbalboni I think we can change it back—that selector might be too broad. If the buttons are on top of a white background, I think contrast won't be an issue.

```
background-color: $color-primary;

  &:hover {
    background-color: $color-primary-darker;
  }
```
