### ISSUE TITLE
Anchor on apply for health care page broken

### ISSUE THREAD

**Issue by chrisfrommann** [department-of-veterans-affairs/vets-website#3178]
The link taking a user to additional forms is broken (#additional-forms). To reproduce
1. Go to https://www.vets.gov/healthcare/apply/
2. Click on "FIND THE FORM YOU NEED."

**Expected:** Jumps to additional forms section
**Actual behavior:** Nothing

Appears to just be an instance of forgetting to add a "name" attribute down by the missing forms.

**Comment by Carmezim** [comment]
This issue seems to have been fixed. Close it?

**Comment by jcmeloni** [comment]
Anchor works now.
