### ISSUE TITLE
Casing style on edu benefits form

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3196]
We have a few different ways we're doing casing on the edu benefits form. We should get a solid answer and clean up the form.

Here are the areas and the current status:

- Field titles: mostly sentence case, some title case
- Subway map chapters: title case
- Subway map pages: title case
- Mobile nav header chapter name: title case
- Title at the top of each form page: sentence case
- Block/section titles on in form pages: sentence case (some title case, maybe?)
- Review page titles: title case
- Buttons: title case

**Comment by jbalboni** [comment]
@goldenmeanie @cweber I know we've talked about this before, wanted to get it fully documented somewhere.

**Comment by cweber** [comment]
I'm actually going to add @mollyblake to this. I'm sure her version of the copy is correct, but getting an explicit answer to casing based on your list would be helpful for enabling us to do our own auditing.

Molly, I'm assuming this is something you have an answer to, but if the source of truth is someone else, let us know.

**Comment by bethpotts** [comment]
@jbalboni I can answer this question. Can you give me context so I can see where "field titles," "subway map chapters," etc. appear in the form?

**Comment by mollyblake** [comment]
Thanks @bethpotts . @cweber  -- Beth is the source of truth! :)

**Comment by jbalboni** [comment]
@bethpotts Sure! Screenshots below.

Field titles: mostly sentence case, some title case

![screen shot 2016-09-27 at 5 24 21 pm](https://cloud.githubusercontent.com/assets/634932/18892365/4578ec16-84d7-11e6-993d-54e7095d1e16.png)


Subway map chapters: title case

![screen shot 2016-09-27 at 5 24 57 pm](https://cloud.githubusercontent.com/assets/634932/18892388/5679a4d8-84d7-11e6-8e46-3975ad8e1a50.png)


Subway map pages (the items in the list below the numbered step): title case 

![screen shot 2016-09-27 at 5 25 23 pm](https://cloud.githubusercontent.com/assets/634932/18892402/6484992a-84d7-11e6-970e-701dc6e7a05a.png)


Mobile nav header chapter name: title case

![screen shot 2016-09-27 at 5 25 52 pm](https://cloud.githubusercontent.com/assets/634932/18892428/759f8486-84d7-11e6-9792-e6c7f7069e40.png)


Title at the top of each form page: sentence case

![screen shot 2016-09-27 at 5 26 18 pm](https://cloud.githubusercontent.com/assets/634932/18892445/86e96c8e-84d7-11e6-8aab-4ff883265b05.png)


Block/section titles on in form pages: sentence case (some title case, maybe?)

![screen shot 2016-09-27 at 5 26 40 pm](https://cloud.githubusercontent.com/assets/634932/18892463/9221c790-84d7-11e6-80f8-5cae86ed005e.png)


Review page titles: title case

![screen shot 2016-09-27 at 5 27 03 pm](https://cloud.githubusercontent.com/assets/634932/18892481/9ee13510-84d7-11e6-8e5c-844d7c578699.png)


Buttons: title case

![screen shot 2016-09-27 at 5 27 21 pm](https://cloud.githubusercontent.com/assets/634932/18892492/aa1a228e-84d7-11e6-84ac-08365b4f21d4.png)

**Comment by bethpotts** [comment]
@jbalboni thank you for this very clear list of elements! Let me know if you have questions. I would love to know the answer to my question about subway map chapters!

Field titles: Sentence case, but still cap any proper nouns (Social Security number).
Subway map chapters: Title case (...unless these get repurposed when clicked as subheads under a broader heading--might be weird to have two headers stacked that are in title case. Should we look at this together?)
Subway map pages: Sentence case, but still cap any proper nouns.
Mobile nav header chapter name: Title case.
Title at the top of each form page: Sentence case, but still cap any proper nouns.
Block/section titles on form pages: Sentence case, but still cap any proper nouns.
Review page titles: Do these appear only once? I would go with sentence case, but still cap any proper nouns.
Buttons: Title case, which is how we style buttons (except for "Go to eBenefits to apply") across vets.gov.

**Comment by jbalboni** [comment]
@bethpotts Thanks! 

Those numbered chapter titles are only used in two contexts: the subway map and the mobile nav header. So I don't believe there's an example where you'd see them underneath another header.

Review page titles are the same as the subway map page titles and appear only once in that list.

**Comment by cweber** [comment]
@bethpotts We were talking about where a good place to preserve this information might be and were pointed to the Vets.gov Content Styleguide. Looks like that's you!

I think maybe we would benefit from adding a section in 'Style and formatting' either as part of or in addition to  'Interface elements'. Perhaps 'Form elements'
