### ISSUE TITLE
Format edu form field data with common patterns

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3199]
We could be more helpful to users by formatting certain information into standard patterns.

Fields:
- Zip+4: 12345-1234
- SSN: 123-45-6789
- Phone: (555) 555-5555

We could provide these patterns while the user is typing information in the field.

**Comment by cweber** [comment]
From @goldenmeanie in now closed issue #3264

In the review screen:

- [ ] SSN should preview as xxx-xx-xxxx
- [ ]  Phone as xxx-xxx-xxxx
Ideally this would be matched by being able to enter data with less rigorous requirements. For example, a phone number with dashes.

**Comment by cweber** [comment]
Can we reopen this? I think it's still an outstanding issue.

I know we've made some progress when it comes to validation, but I don't think we've nailed the UX/Frontend pieces yet.
