### ISSUE TITLE
User Feedback: Help figure out healthcare benefits they're eligible for 

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/vets-website#3209]
Just had a chance to sit down with a vet, and showed them a few things on vets.gov, some feedback for things they were interested in and couldn't find:

Healthcare:
- They wanted to know what healthcare benefits they are eligible for (my guess is that a schedule of the priority groups would be helpful)

Disability side:
- How often should I be re-evaluated, can I have my percentage bumped?

**Comment by ayaleloehr** [comment]
@rroueche is this maybe covered in the health content you're working on?

**Comment by rroueche** [comment]
thank you for the notes @paultag !! and for cc'ing me @ayaleloehr !

yes healthcare eligibility is coming up in the new content we're writing, but I'm not sure if we attend to his Disability question -- or whether that type of info is in scope.

we launch content iteratively, so I'll keep track of that note for us to consider for when we go through iteration 3 of Disability content. we'll have to prioritize it and scope it among other needs so I can't guarantee it's content we'll actually add, but I'll add it to the list of things to consider!

@bethpotts @amybehrens cc'ing you

**Comment by ayaleloehr** [comment]
@rroueche sounds like you're tracking this via other tickets, so I will close here.

**Comment by rroueche** [comment]
correct! here: https://waffle.io/department-of-veterans-affairs/vets.gov-team/cards/58fa2556ba36e8130130af3d
