### ISSUE TITLE
Update layout for /education

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3224]
The new layout for this L2 level page should look like below.

Note:
- The horizontal grey bars with green button have been removed.
- The only elements in blue boxes are the tools/services
- Remaining content (links to pages with information) are below, using the nav component more commonly seen on L3s.

*This layout and content structure is intended to be replicated across all form intro pages. Implementing that is future task.*

 
![education](https://cloud.githubusercontent.com/assets/417657/18961642/b071ad86-863b-11e6-8d8c-963c7335004d.png)

**Comment by akainic** [comment]
@emilyville @crwallace wanted to tag you both in this to see the new layout that @cweber has come up with for the education page. @crwallace mentioned we might be getting rid of piano keys, so wanted to tag you all so you can discuss!
