### ISSUE TITLE
Move edu benefits Address component to common and move existing on to HCA

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3227]
The current common Address component is HCA specific and the one in edu benefits is probably the better generic component.

**Comment by jcmeloni** [comment]
@jbalboni Did this work get done or do you want to keep it open here?

**Comment by jbalboni** [comment]
@jcmeloni Still needs to be done.

**Comment by leannammiller** [comment]
@jbalboni should this be pushed to next sprint?

**Comment by jbalboni** [comment]
The changes here are:

- Move the edu benefits Address component to common/
- Add an optional line 3 to the component
- Update the HCA veteranToApplication function to reformat the address to one that matches the schema and/or work with Mark to change the format on the backend.

**Comment by leannammiller** [comment]
will close and open ticket 626
