### ISSUE TITLE
Add field group highlighting and animation

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3231]
We're adding some visual indicators that some fields are grouped together and have been expanded.

We're also removing the grey border around form pages on mobile

**Comment by goldenmeanie** [comment]
![grouped-inputs](https://cloud.githubusercontent.com/assets/1969/18971993/541812e4-8665-11e6-8924-83bcbf1f85da.png)
Changes:
- When a choice reveals more options. The group should get a blue #333333 bar to the left.
- Bar should animate in
- Assumes removal of the hairline box in small screens (go wall to wall)
