### ISSUE TITLE
Add autoprefixer to webpack pipeline

### ISSUE THREAD

**Issue by carlmjohnson** [department-of-veterans-affairs/vets-website#3235]
This will make it easier to write CSS that works in all the browsers we support.

**Comment by carlmjohnson** [comment]
https://github.com/postcss/autoprefixer

**Comment by webinista** [comment]
After checking CanIUse.com and our stats, we might be at the point where we don't need prefixes _at all_. @staceylanger @crwallace What's our current browser support level?

**Comment by carlmjohnson** [comment]
http://caniuse.com/#feat=css-grid will keep us in prefixes for years to come, I'm afraid. 😬

**Comment by jcmeloni** [comment]
@crwallace given official browser support levels, what do you want to do here?

**Comment by webinista** [comment]
My $.02: we can close this, and just not use grid layouts until they're supported without prefixes. Fallbacks IME tend to add bloat, and we're not creating layouts that _need_ to use the grid.

**Comment by jcmeloni** [comment]
Closing in agreement w/ @webinista
