### ISSUE TITLE
Vets.gov homepage reporting an error in JS console

### ISSUE THREAD

**Issue by carlmjohnson** [department-of-veterans-affairs/vets-website#3237]
Steps to reproduce:

1. Go to https://vets.gov

2. Open JavaScript console

Expect Output:

None

Actual output:

1 error

> Uncaught Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]=%20Check%20the%20render%20method%20of%20%60e%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by crwallace** [comment]
This fix for this is already in master (#3217). We just need another production push which will most likely happen next week.
