### ISSUE TITLE
Move do not apply to this benefit to bottom of form

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3238]
The "This period of service should be counted towards another education benefit." checkbox needs to move to the bottom of the _add tour of duty_ chunk of the form.
- [ ] Move checkbox
- [ ] Update language with text from Shay

**Comment by jbalboni** [comment]
@goldenmeanie Do we have that text yet?

**Comment by akainic** [comment]
Shay owes us language for this

**Comment by goldenmeanie** [comment]
This is still in flux. We had a clarifying conversation about this with the VA today. Will update on tomorrow.

**Comment by akainic** [comment]
Already moved to bottom, and we're changing the question. Closing this issue.
