### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3243]
I was looking at [Google Page Speed](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fvets.gov&tab=mobile) and it looks like no-react.entry.js and no-react.css are both made as synchronous calls in the HTML `head` element.  

<img width="1262" alt="screen shot 2016-10-01 at 12 01 31 pm" src="https://cloud.githubusercontent.com/assets/4719765/19015260/d984fe50-87ce-11e6-80b4-a031f3bda4f8.png">

Would it be possible to load these later on the page or asynchronously to make our first page load faster?

**Comment by jbalboni** [comment]
We should be able to use the `defer` attribute for the JS. For the CSS, you could try to inline the above the fold CSS (like the header styles), but it's pretty difficult, I think.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
