### ISSUE TITLE
Split benefit selection into two screens

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3249]
If Post-9/11 is chosen, show relinquishment questions on a separate screen. Updated language, including framing, coming.

**Comment by cweber** [comment]
@akainic If there is opportunity to prioritize this over other small/medium things, it would help @mollyblake as she works on making the copy on these pages clearer.

**Comment by akainic** [comment]
@cweber what exactly is needed for Molly? For us to make the change so she can then work on the content? Or just a guarantee that this will make it in before launch?

**Comment by cweber** [comment]
A guarantee is really important. This is pretty critical to us making this form functional.

Molly had just expressed that she has an easier time working on copy if she has a visual of the pages. She's working on it regardless though.

**Comment by akainic** [comment]
Ah gotcha. Okay will move this up in the priority for the current sprint

**Comment by jbalboni** [comment]
@goldenmeanie Is all of the text underneath the Post 9/11 option moving to another page?
