### ISSUE TITLE
Review stage defaults to "No" for unanswered questions

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3250]
Reviewing the entered data shows "No" in cases where no answer was provided. We should not show data for empty questions.

**Comment by jbalboni** [comment]
This is an hca thing that we picked up. Those Yes/No questions are True/False fields right now on the back end, so we treat no and not answered as false. We could change them on the front end, but I'd also want to know if there's a difference between no and not answered that the back end needs to handle.

cc: @markolson

**Comment by akainic** [comment]
@jbalboni @goldenmeanie Yes, we decided to handle it this way on HCA because we wanted to make it super clear to users what they selected and didn't. We were concerned if we didn't show options they didn't select, this wasn't a complete review. But we can certainly discuss changing this.

**Comment by akainic** [comment]
2 things needed here:
1. For questions they didn't see because they are only shown based on a previous answer, we should not show those questions in the review stage.
2. For questions they see but do not select something for, leave the answer blank instead of "No" on the review page

**Comment by jbalboni** [comment]
@akainic We would still be sending `false` for those questions to the backend. Is that ok?

**Comment by akainic** [comment]
Yep! I think that's fine, but that's something we can confirm in testing.
