### ISSUE TITLE
Split Military Service form into 3 screens

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3251]
- ~~Screen 1~~ should end after active duty question (including sub-questions)
- ~~Screen 2~~ should be the growable table. _Small copy change coming._
- ~~Screen 3~~ ROTC with sub-questions (All users will now see this page, just not all the questions)

**Update**: See Caitlin's comment below!

**Comment by cweber** [comment]
@alexose The page swap I mentioned in Slack.

The split above is mostly correct in terms of what goes on each page, but we'd like to switch the order. We think leading with the Active duty question is setting people of for confusion.


- [ ] Screen 1 **growable table**
- [ ] Screen 2 **commission / active duty questions**
- [ ] Screen 3 ROTC with sub-questions (All users will now see this page, just not all the questions)
