### ISSUE TITLE
Add 'required key' to all pages

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3257]
- [x] Display the "(*) Indicates a required field" message on all pages, not just ones that have required fields.

 - [x] Make asterisk bigger!

**Comment by goldenmeanie** [comment]
![required-fields](https://cloud.githubusercontent.com/assets/1969/19055184/c5754136-8990-11e6-9a86-1c1f891272c9.png)
effectively 1.5em

**Comment by cweber** [comment]
@goldenmeanie I added the required key to all pages, but is probably worth seeing if you can get that asterisk better...and get rid of those parenthesis.

**Comment by cweber** [comment]
Asterisks are modified in the edu-benefits-copy-10-18 branch

![screen shot 2016-10-18 at 6 03 32 pm](https://cloud.githubusercontent.com/assets/417657/19498062/37e8e81c-955d-11e6-99a6-ccce56afa3a3.png)
