### ISSUE TITLE
Day optional date field

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3261]
In some cases the need to an exact day is stressing people out unnecessarily. We should offer a Month/Year date field variant that can check for a match to a specific month (this one) and insert the day field if it makes a difference in the application.

![smart-date](https://cloud.githubusercontent.com/assets/1969/19082760/866b1cc0-8a2d-11e6-9a5b-28da5422fc12.png)

**Comment by cweber** [comment]
We no longer need to do this. We will only display month and year.
