### ISSUE TITLE
FontAwesome is being included twice

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3266]
Was wondering why `/generated/messaging.css` is an absurdly large _1.3MB_. Huge contributing factor: FontAwesome is being [bundled twice](https://www.vets.gov/generated/no-react.css) in our CSS. One of those instances inlines the SVG font as a data uri, adding about 400Kb. 

To fix this bug:
- [x] Figure out why FontAwesome's CSS is being bundled twice and address that.
- [x] Remove the SVG font altogether. WOFF and WOFF2 covers 98% of our audience. (We don't actually need to serve .eot files either.)

Possibly related to #3057.
Related to department-of-veterans-affairs/messaging-fe#94

**Comment by bshyong** [comment]
Looks like this is related to the new login component requiring `styles`, which essentially doubles our file sizes as all common styles are duplicated.

This the following fix being tracked in this issue will bring the file size down to ~600kb.  Are we confirmed that the SVG font should be removed?

https://github.com/department-of-veterans-affairs/vets-website/issues/3312
https://github.com/department-of-veterans-affairs/vets-website/commit/3f9ce70d6a637306311c85d01486df9706ab7ba2

**Comment by webinista** [comment]
Yes.

SVG font support [no longer exists](http://caniuse.com/#search=svg%20font) in most browsers. It's been replaced with WOFF in all but IE8, and we aren't supporting IE8.

**Comment by bshyong** [comment]
@crwallace thoughts? ^

I can issue a PR for any necessary it once we have a decision

**Comment by webinista** [comment]
Any movement on this?

**Comment by jcmeloni** [comment]
@crwallace Still holding per comment here? https://github.com/department-of-veterans-affairs/vets-website/issues/3312#issuecomment-255442327
