### ISSUE TITLE
Update review page for better UX

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3267]
The current HCA implementation of the review screen has caused confusion in all of our user testing. 

This redesign addresses these existing issues:
- Not being able to see all of the information easily
- Not understanding the mechanics of the next button
- Users intuitively trying to select the title of each section to expand it
- Problems with inconsistent pattern for how the existing buttons function, dependent on what you have or have not already looked at or clicked on.
- Clustering by page creates too many sections to click through
- Section titles don't look like titles

This is one basic example of the redesign, additional views (expanded, editable, etc.) can be found [here](https://github.com/department-of-veterans-affairs/edu-benefits-team/blob/master/design-documents/edu-bennies-review.pdf).

![review-first-view](https://cloud.githubusercontent.com/assets/417657/19092384/5e1bad44-8a54-11e6-9e5c-c6880204c744.png)

**Comment by leannammiller** [comment]
@cweber - who is responsible for this?

**Comment by akainic** [comment]
If @jbalboni @alexose or myself have time to take this before launch we will, but not critical for launch

**Comment by cweber** [comment]
@jbalboni Here's how we'll deal with Education/Employment sections.

1. cluster stray questions at top with no section title and one edit button. (It breaks some of our rules, but I think it follows the spirit of them.)
2. For employment, if they change the first question to 'no' we need to hide their other answer. (We're currently not handling this appropriately.)

Also, see issues #4067 and #4065. Found those two while I was working this out.

Let me know if this doesn't make sense.

![review-basic-edit-education](https://cloud.githubusercontent.com/assets/417657/20500986/caff4a5c-b005-11e6-8aa9-3d5b83fc006a.png)
