### ISSUE TITLE
Display issues with 'Note' in review section

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3272]
The note in the review section and the paragraphs below it are displaying without the correct padding.

@goldenmeanie Should the note even appear at this stage?

![screen shot 2016-10-05 at 12 54 19 pm](https://cloud.githubusercontent.com/assets/417657/19123094/571377dc-8afb-11e6-849c-753cef75337d.png)

**Comment by goldenmeanie** [comment]
I would say no, it should not appear in the review>edit veteran information pane.
