### ISSUE TITLE
Animate growable table transitions

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3274]
When the GrowableTable rows expand and contract, it would be less jarring to users if there were css transitions to smooth out those changes.

**Comment by ayaleloehr** [comment]
@jbalboni is this still an issue with RJSF?

**Comment by jbalboni** [comment]
Yes, though it's really low priority.

**Comment by cbandrow** [comment]
Hi all - I'd love to be able to help out and try to solve this issue. I understand it's low priority for your team, but I think it's a good first bug for a new contributor. Would someone be able to provide me with a little additional context?

I've attached a gif of what I believe is being discussed here. Is the issue referring to the sudden change in size of the GrowableTable component at specific media points? If not, maybe another gif or steps-to-reproduce would be helpful in guiding me in the right direction. Thanks for any help!

![issue gif](http://g.recordit.co/qUatkY8Z2T.gif)

**Comment by rtluu** [comment]
not critical and not relevant at this point. closing
