### ISSUE TITLE
Add ability to override breadcrumbs for specific path sections

### ISSUE THREAD

**Issue by dannychapman** [department-of-veterans-affairs/vets-website#3285]
In the Jekyll iteration of vets.gov, there was functionality that enabled custom overrides of the default capitalize the folder name rule. 

For examples, see config > site.js

Current use case: 
Home > Vocational Rehab and Employment (VR&E)

rather than folder name capitalization: 
Home > Vocational rebhab and employment

**Comment by bethpotts** [comment]
@crwallace It would be great to be able to capitalize appropriately, especially in cases like this where we now have "Gi bill":
Home Education > Gi bill > Post-9/11 GI Bill

**Comment by jcmeloni** [comment]
Closing as this will be subsumed by other issues in vets.gov-team when discovery is complete for the content discussion.
