### ISSUE TITLE
Allow for international numbers

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3289]

**Comment by ayaleloehr** [comment]
Was this completed @cvalarida or @goldenmeanie ?  (I saw this PR which made me think it might be: https://github.com/department-of-veterans-affairs/vets-website/pull/4896)

**Comment by goldenmeanie** [comment]
I believe this is solved by relaxing validation on the phone number field. Minimum 10 digits, don't care about anything else? Do I recall that correctly @cvalarida?

**Comment by goldenmeanie** [comment]
Looked at that PR and yeah I think we can close this.
