### ISSUE TITLE
Make phone number field validation more flexible

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3290]
Moving here from the edu-benefits repo

It should be able to:
- [x] Accomodate -.,() and spaces
- [x] Submit the value in some cleaned up agreed upon format (e.g. 111-222-3333)

**Comment by rtluu** [comment]
work to still be done, format the value in the input when you come back to a phone number in the RJSF forms.

**Comment by cehsu** [comment]
@jbalboni would it make sense to accomplish this by:
- format on blur (while the applicant is filling out the form) and update validation to something like:
```
^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$
```
source: https://stackoverflow.com/a/123666/5812175
- use a migration to convert phone number values to a specified format (when the applicant reopens a form in progress), and
- and then reformat them back before submission?

**Comment by jkassemi** [comment]
@rtluu or @goldenmeanie is there an associated vets.gov-team issue for this?

**Comment by goldenmeanie** [comment]
This can be closed.
