### ISSUE TITLE
Changes to chapter and page names

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3291]
Below is the page structure with modified page and chapter names.

@goldenmeanie, @mollyblake and I went through the existing pages to try to clarify some vague names as well as creating names for new pages that are being created in a couple of other issues (#3251 and #3249).

This structure/naming also poses combining eduction and employment into one chapter called Non-military Experience (#3292).

- [x] **Veteran Information**
- [ ] **Benefits** [remove 'eligibility']
  - [ ] Benefit selection
  - [ ] **Benefit relinquishment** [singular]
- [x] **Military Experience**
  - [x] Service periods
  - [x] Military service
  - [x] ROTC history
  - [x] Contributions
- [ ] **Non-military Experience** [new section to contain the pages below]
  - [x] Education history
  - [x] Employment history
- [x] **School Selection**
- [x] **Personal Information**
  - [x] Contact information
  - [x] Secondary contact
  - [x] Dependents
  - [x] Direct deposit

**Comment by cweber** [comment]
Noted this with @akainic already, but this is really trying to address changes (in a holistic way) that are happening in other issues in a piecemeal way.

Combining Education/Employment History can be skipped, but it will be important to make sure that all of the pages have titles and that the page title matches with the subway-map title. The outline on this page is trying to take care of naming conflicts that are arising as we're splitting and moving pages.

**Comment by jbalboni** [comment]
@cweber Do we still want to do the "Non-military Experience" change?

**Comment by cweber** [comment]
I would still like to do that. (It was occurring to me again as we're going through future forms.) @goldenmeanie Do you concur?

**Comment by goldenmeanie** [comment]
I think so. Only hesitation is whether one of the employment questions (rating?) could be from during military service.

**Comment by cweber** [comment]
We have come to agreement:

Military Experience
and 
Non-military Experience

**Comment by cweber** [comment]
Updated list above.

**Comment by ayaleloehr** [comment]
@jbalboni @annekainicUSDS does this still need to happen?

**Comment by raquelromano-gov** [comment]
Just saw this for the first time--am guessing it originally applied to the 1990, so I updated the checkmarks to reflect what's live.

@goldenmeanie is this still desirable across all edu forms? i.e.
  - Benefits eligibility -> Benefits
  - Move all employment and work history pages into a "Non-military experience" chapter

**Comment by annekainicUSDS** [comment]
I'm not sure if this is still something we want to do, would have to loop @J-Quag into this.

**Comment by J-Quag** [comment]
Thanks @annekainicUSDS    
  I'd like to review this with @goldenmeanie  since the other forms have come out since this point. It is most likely much more work now if the other forms were needing to also match this. I will bring this up with Alex when he gets back on Monday.

**Comment by raquelromano-gov** [comment]
Just saw https://github.com/department-of-veterans-affairs/vets-website/issues/3292 that says not to do the non-military experience thing after all

**Comment by J-Quag** [comment]
@raquelromano-gov  Thanks! I'm going to close both of them.
