### ISSUE TITLE
Combine Education and Employment history into 'Non-military Experience'

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3292]
Education and Employment history are both small sections that will potentially have few people filling them out. We'd like to combine them into a new chapter called 'Non-military Experience'. This will also minimize the number of major steps in the form.

**Comment by annekainicUSDS** [comment]
@goldenmeanie do you have a sense of if this is still something we'd like to do? My sense is that the forms have changed since this ticket was created, and both of these sections can get quite lengthy on the 1990e and 5490. I think I'd prefer to keep them separate. Thoughts?

**Comment by goldenmeanie** [comment]
Agree with keeping them separate
