### ISSUE TITLE
Adjustment to Q14 (do not apply this period...)

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3320]
The end of service period form position is fine, but we would like to replace the radio buttons with a text area to allow for more intent to be communicated. Checkbox is checked by default. Unchecking reveals additional UI as in previous design.

[X] Apply this service period to the benefit I'm applying for.  

---

[ ] Apply this service period to the benefit I'm applying for.  
_Please explain how you'd like this service period applied._

[text area]

A single period of service may not be applied toward more than one benefit. 

There is one exception: If your period of service began before August 1, 2011, you may use it to establish eligibility to Chapter 33 even if it has already been used to establish eligibility to a different benefit.

**Comment by mollyblake** [comment]
@rcarthur

**Comment by jbalboni** [comment]
@goldenmeanie Is the textarea a required field?

**Comment by goldenmeanie** [comment]
No, it shouldn't be @jbalboni
