### ISSUE TITLE
Check scrolling on form submissions with errors

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3330]
In at least one case when an error is triggered on page submission, the page is scrolling to a point that does not correlate to the actual error.

This is probably worth checking for all errors. It currently is happening on Military history if someone chooses to apply the service period to a different benefit and does not select which benefit. In this case it sends you to the top of the tour section instead of the top of the error.

**Comment by jbalboni** [comment]
This is also necessary for screen reader users, since there's no real indication of what happened when validation fails right now. We should scroll to and focus on the erroring field. We may need to add `alert` roles to some of the error messages in our input components.
