### ISSUE TITLE
Service branch questions

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3332]
Options: 
1. Add options to dropdown
2. Make text field

Confirm with Shay

**Comment by cweber** [comment]
![screen shot 2016-10-12 at 2 07 52 pm](https://cloud.githubusercontent.com/assets/417657/19322192/117ad860-9086-11e6-8b3e-3179490cc058.png)

**Comment by akainic** [comment]
Decision is to make this a text field instead of a dropdown.
