### ISSUE TITLE
No pagination on prescription history if only one page

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3337]
If there is only one page of results, this should not exist on this history page under the results:

![screen shot 2016-10-13 at 1 36 11 am](https://cloud.githubusercontent.com/assets/4719765/19337707/78ff48fe-90e5-11e6-9506-4ede74fd3039.png)

**Comment by webinista** [comment]
Fixed with 0f96856 / #3360
