### ISSUE TITLE
Rx glossary back button

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3341]
Currently the back link on the Glossary page always says "back to detail page", even if you didn't come from the detail page. The back functionality works in that it sends you back to whatever page you came from, it's just that the title of the link is static.

Best case: link should be dynamic, so it would be "back to detail page", "back to history page", or "back to active prescriptions" (or some similar text), as appropriate

Alternative if that proves difficult: change link to just say"back"

**Comment by webinista** [comment]
@U-DON Can this be closed?
