### ISSUE TITLE
Rx detail page doesn't load when no tracking information prescription

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3342]
One current example is the detail page for prescription_id: 13651310 when using the staging API (so http://localhost:3001/rx/prescription/13651310 locally).

Page should load as much information as it can, and say something to the effect of "no tracking information available" instead of just leaving a blank space. Feel free to ask back in this issue if that's not specific enough and we can work through the look/wording/details!

**Comment by U-DON** [comment]
@gnakm Any specific design for the details page when there is no tracking information? Is just having no table good enough?

**Comment by gnakm** [comment]
@U-DON Could you give me situations when this information would not be available?
e.g. User received medication from VA medical center and there were 0 refills, therefore no order history, There was an error on our end.

**Comment by gnakm** [comment]
@ayaleloehr Clarification question: Does order information expire after 30 days after delivery or 30 days after user submits order?

**Comment by U-DON** [comment]
I'm not sure when it wouldn't be available. The API just doesn't have any data on tracking history when we query for it. Maybe all of it has expired. The specific example mentioned here is a prescription that has a status of 'Discontinued'. I don't know if that's related.

**Comment by ayaleloehr** [comment]
From Carnetta a while back: "Veterans can track refills shipped from a CMOP for 30 days after the shipment date. Then the tracking information is archived from MHV."

This will be a common occurrence: any prescription that the Veteran has not had shipped to them in the last 30 days will not have any tracking information.  This will be the majority of historical prescriptions.

**Comment by U-DON** [comment]
@gnakm For now, we're not showing the table if there's no available tracking info. We can create another issue if you come up with a particular way to deal with this case.

**Comment by gnakm** [comment]
@U-DON 

<img width="323" alt="screen shot 2016-10-14 at 5 24 47 pm" src="https://cloud.githubusercontent.com/assets/13420618/19403137/2a25166a-9233-11e6-9e56-df957c6a3a05.png">

Could we have a message under the Order History bar that says "* Tracking information for each order expires 30 days after shipment." and have Order History and this message show even when there aren't any available tracking info, that way users who are used to seeing this section doesn't get confused when it disappears.

**Comment by U-DON** [comment]
@gnakm Sure, can do. Same thing for the desktop version? There's no line under the header in the desktop version; should that be added?

**Comment by gnakm** [comment]
@U-DON Yes please!
