### ISSUE TITLE
Rx moving between pages should jump to top

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3344]
Right now, if I go to the bottom of this Active prescriptions page and click a prescription to go to the detail page, it goes there, but instead of being at the top of the detail page, I am at the bottom. 

In the general case when someone moves between pages, they should enter the new page at the top. The exception is from the Active prescriptions page, if you click "track package" it should take you to the tracking section on the detail page, which is lower down the page (I don't know if we have any prescriptions that are in this state on the active page though...if we don't and this makes it difficult to test, let me know and I can get the data in the API changed as needed)

Going to leave this unassigned for either @U-DON or @webinista to grab as time allows.

**Comment by webinista** [comment]
I think this is a hazard of building single-page apps. We may need to add a `scrollTo(0,0)` or similar. Looks like HCA is using `react-scroll`. We can repurpose it here.
