### ISSUE TITLE
Place error message above fieldset rather than on individual field

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3354]
Currently messages for these fields get applied to each field which causes weird stacked text and different heights between fields.

![screen shot 2016-10-13 at 12 00 02 pm](https://cloud.githubusercontent.com/assets/417657/19356686/a5988c34-913c-11e6-8de5-05e18df7f997.png)

Change error message to appear above the fieldset, with specific language and highlighting only the particular field that is erroring.

![screen shot 2016-10-13 at 12 25 10 pm](https://cloud.githubusercontent.com/assets/417657/19357540/21ca5910-9140-11e6-89f7-42e1470dccd2.png)

**Comment by rtluu** [comment]
not applicable with new RJSF. closing
