### ISSUE TITLE
Card format should remain if you add one then remove

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3358]
Currently if you add a second record to growable tables, the first record is displayed as a card. If you choose to remove the second record, the first one is turning back into basic fields.

Instead, it should remain as a card. ( @goldenmeanie, do you agree with that? I'm trying to avoid too many back and forth state changes.)

**Comment by goldenmeanie** [comment]
I wrestled with this too, but I feel the opposite. I think the one-way transition to greybox is odd when there are no other blocks. It's a trade-off.

**Comment by cweber** [comment]
I think I now recall that happening... because he did it my way based on a call, then changed for you based on showing us the outcome of the call.

This is fun. More!

**Comment by goldenmeanie** [comment]
Form tennis!

**Comment by akainic** [comment]
From Caitlin: "It's fine how it is. Move on."
