### ISSUE TITLE
Phone numbers should display with dashes, box gets bigger

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3361]
Phone numbers should format with the dashes wether entered that way or not initially. The box needs to get wider to accommodate this.

- [ ] display with dashes
- [ ] wider box
- [ ] make sure validation (can continue, not just no red) accepts dashes

**Comment by akainic** [comment]
For the 3 options above:
- I think displaying with dashes should be a future improvement. I will create a separate ticket for that.
- The wider box I think was an issue just on Internet Explorer (on Chrome I don't seem to be having the problem of the contents getting cut off), but I will still increase the width.
- Taken care of in a previous PR.
