### ISSUE TITLE
Copy updates from E2E with Shay

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3370]
- [x] [Military service](https://dev.vets.gov/education/apply-for-education-benefits/application/military-history/military-service)

Change "Are you receiving...coursework" to:
" ...coursework or training."

- [x] [First page of form](https://dev.vets.gov/education/apply-for-education-benefits/application)

**Copy edited**
Fill out this application to get your official Certificate of Eligibility (COE) for the education benefit you want.

**You won't be able to save your work or come back to finish.** So before you start, it's a good idea to gather information about your military and education history, and the school you want to attend.

This application is based on VA Form 22-1990.

Get Started >>

- [x] [Employment information](https://dev.vets.gov/education/apply-for-education-benefits/application/employment-history/employment-information)

**New**
Have you ever held a license or a journeyman rating to practice a profession (for example, as a contractor, electrician, or plumber)?

- [x] [Military service](https://dev.vets.gov/education/apply-for-education-benefits/application/military-history/military-service)

**New**
Please tell us which benefit you'd like this service applied to.

- [ ] [Review page...and elsewhere](https://dev.vets.gov/education/apply-for-education-benefits/application/military-history/military-service)

- VA will usually process your claim within 30 days.
- Usually processed within 30 days [sticky box]

**Comment by akainic** [comment]
Done
