### ISSUE TITLE
Remove placeholder text in almost all text-fields

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3371]
Single exception:
- [ ] City field should say "City or APO/FPO/DPO"

**Comment by akainic** [comment]
Oh really? We want to remove all the placeholder text? Just confirming!

**Comment by akainic** [comment]
We're doing it!

**Comment by goldenmeanie** [comment]
Is this in progress @akainic ? If not I can work on it.
