### ISSUE TITLE
[Rx] Increase height of each prescription card

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3382]
Blocks / See #3306 

> The heights of the cards are going to have to increase because Track Package and Refill Prescription buttons may be stacked if both are available. 

Cards do not have a specific `height` value. Need to add one, however to accommodate stacked buttons if it occurs.

![available for refill track](https://cloud.githubusercontent.com/assets/13420618/19193749/4dcdcc98-8c79-11e6-8d04-c9e74bc6c6c1.png)

**Comment by webinista** [comment]
@gnakm Can you provide a specific height value? Each prescription card doesn't actually have one.

**Comment by gnakm** [comment]
@webinista Could we make the height 275px ?
