### ISSUE TITLE
Rx detail page shouldn't always allow prescription refill

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3399]
It looks like the prescription detail page has a "Refill Prescription" button that is always there, no matter the prescription status. This button should actually only show up with the same logic that has the Refill Prescription button show up on the Active page (i.e. if the prescription is refillable, but there may be more to it than that?).  

@webinista worked through a lot of that logic so might have better context than I do.

**Comment by webinista** [comment]
Related to #3383. That's where the updates to the logic are happening.
