### ISSUE TITLE
Monitoring and logging

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3405]

**Comment by akainic** [comment]
- [ ] Alerting when validation failure occurs (maybe not PagerDuty, look more into CloudWatch)

**Comment by akainic** [comment]
@markolson @lihanli do we have any updates on this?

**Comment by lihanli** [comment]
devops added sentry to vets-api, alerts still need to be setup though

**Comment by akainic** [comment]
Things we need to check off here:

- [ ] Create and implement log management plan

- [ ] Define log collection and analysis architecture
- [ ] Test log collection and analysis architecture
- [ ] Define production versus debugging logging standards
- [ ] Document method to enable debugging log level on production system
- [ ] Test enabling different logging levels
- [ ] Verify correct log messages produced at different logging levels

**Comment by lihanli** [comment]
devops is adding splunk which will be our log collection and analysis architecture https://github.com/department-of-veterans-affairs/devops/issues/617

the rails logger allows different logging levels. we are outputting all log levels in the production log to have access to all possible information.
```ruby
logger.debug "Person attributes hash: #{@person.attributes.inspect}"
logger.info "Processing the request..."
logger.fatal "Terminating application, raised unrecoverable error!!!"
```

Document method to enable debugging log level on production system
```ruby
Rails.application.configure do
  config.log_level = :debug
end
```

**Comment by akainic** [comment]
Follow up with devops and make sure we can access the logs and are getting alerts

**Comment by akainic** [comment]
@knkski wanted to loop you into this ticket and make sure that we can access the logs for edu-benefits and that we're getting alerts for issues. Do we need to get access to anything in particular for this?

**Comment by lihanli** [comment]
we have access to the logs through cloudwatch. me and mark both have access and tested it out already. i still need to set up sentry access and test out alerts though

**Comment by lihanli** [comment]
i'm registered on sentry and subscribed to alerts now

**Comment by knkski** [comment]
If anybody else needs CloudWatch access, just file a ticket over in the devops repo. As far as alerting, we are sending alerts currently whenever the server gives a 500 error. Will the validation failure alerts that you'd like above be included in that?

**Comment by akainic** [comment]
Got it, thanks @lihanli and @knkski for that information! I think we need some kind of alerting when a validation failure occurs, but I'm not sure what the right tool is for this. @lihanli do you have thoughts on this?

**Comment by lihanli** [comment]
i made a pr to add the validation errors to sentry which can send out alerts when they happen https://github.com/department-of-veterans-affairs/vets-api/pull/404

**Comment by akainic** [comment]
Awesome, thanks @lihanli!

**Comment by akainic** [comment]
As all of these items are checked off now, going to close this ticket.
