### ISSUE TITLE
Demos for Congress, VSOs

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3407]
@koconnor719 let us know what is needed here

**Comment by goldenmeanie** [comment]
Couple minutes screencast (no cats) walking through the app?

**Comment by koconnor719** [comment]
Awesome!! HAha



Sent with Good (www.good.com)


-----Original Message-----

**Comment by koconnor719** [comment]
Alex is there any way to show the " before" super quickly but just how ugly and not mobile it is?? ( I can't open right now so maybe it's in there)



Sent with Good (www.good.com)


-----Original Message-----

**Comment by goldenmeanie** [comment]
We could capture a small bit of the VONAPP form. It will make the movie longer...

**Comment by J-Quag** [comment]
Completed the demo (5 1/2 min). Uploaded to the slack channel.

**Comment by koconnor719** [comment]
awesome; done.
