### ISSUE TITLE
SSN fields allows more than 9 characters (or 11 with dashes)

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3411]
![image](https://cloud.githubusercontent.com/assets/950486/19448159/91b9ef2a-946e-11e6-8eee-0235bc21c95d.png)

Steps:

- Go to the Veteran Information page
- Enter SSN

Environment:

- Chrome

**Comment by jbalboni** [comment]
I can't reproduce this directly with my change in #3445. I've added a case to the unit tests for this particular invalid SSN there.
