### ISSUE TITLE
SSN produces invalid error

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3412]
![image](https://cloud.githubusercontent.com/assets/950486/19448234/faa3e266-946e-11e6-98b9-fafdc561806e.png)

Steps:

1. Go to Veteran Information
1. Enter a long SSN
1. Delete to the valid number of digits

Environment:

- Chrome

**Comment by austin-martinez** [comment]
The validation for SSN doesn't allow all the same digits
```javascript
function isValidSSN(value) {
  if (value === '123456789' || value === '123-45-6789') {
    return false;
  } else if (/1{9}|2{9}|3{9}|4{9}|5{9}|6{9}|7{9}|8{9}|9{9}/.test(value)) {
    return false;
  } else ...
```

**Comment by plusjeff** [comment]
Thanks for the find @austin-martinez !

Two questions:

- Can someone ever have a single digit appear nine times in an SSN?
- If not, can the error message be updated to reflect that (since the user has technically entered 9 digits, which is what the error requests)...realizes this is an edge case, but a common testing one

**Comment by jcmeloni** [comment]
@plusjeff I actually know the answer to #1 -- yes, it's possible.  9 2s, 9 4s, and 9 5s happen to be valid SSNs for real people, while the others aren't.

**Comment by plusjeff** [comment]
@jcmeloni Thanks! Then we'll have to fix this.

**Comment by akainic** [comment]
Hm this is interesting. I think when we originally created the SSN component, we used the validation logic from the original 1010ez, which did not allow 9 of the same digit. Which means the old 1010ez was using the wrong logic (oops!), so we'll have to update this.
