### ISSUE TITLE
Date of birth allows years less than 18 years (i.e. for children)

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3413]
![image](https://cloud.githubusercontent.com/assets/950486/19448413/bc25d278-946f-11e6-90af-b7a4996c1d0d.png)

This is true in a few areas throughout the application. 

Environment:

- Chrome

**Comment by jbalboni** [comment]
I think I ended up removing this when we were making the date validation handle past and future dates.

What's the reasoning behind doing this check? Is 18 an actual minimum age for these benefits? You can enlist before 18, so it seems like we could be preventing people from using their benefits?

cc: @cweber @goldenmeanie @akainic

**Comment by plusjeff** [comment]
Good point! You can enlist when 17. This isn't a deal breaker feature, but seems like it would be handy to prevent folks from accidentally entering the current year (since that will never be valid). Since all of this manually gets processed, we should validate as much as we possibly can upfront to prevent downstream delays (both for the veteran and the VA).

http://www.military.com/join-armed-forces/join-the-military-basic-eligibility.html

**Comment by akainic** [comment]
On HCA we validated to make sure they were at least 15 years of ago, but if the eligibility age is 17 might as well validate for that! I agree with @plusjeff that as much as possible if we can prevent errors that would delay their application, we should.
