### ISSUE TITLE
Confusing prompt for benefits eligibility

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3414]
This is more of a question around the design of this screen within the 1990. Do veterans generally know which of these services they are eligible for? This might be confusing to get through if they don't have a description of what they can choose?

![image](https://cloud.githubusercontent.com/assets/950486/19448514/279d2236-9470-11e6-9c27-ccb7dc8bf46c.png)

**Comment by cweber** [comment]
Ideally you could say something like, "Veterans who served after 9/11/2011 maybe be eligible for this benefit. For those that are, this is most often the most valuable option." But we've heard concern about providing too much guidance here.

We're going to try adding links below each benefit type to let people initiate research again. Those links will take them to the same place that we point them from the initial 'Apply' page.

Working on how to phrase those links here: https://github.com/department-of-veterans-affairs/edu-benefits-team/issues/76

**Comment by cweber** [comment]
Resolved in recent copy commit.
