### ISSUE TITLE
Overlapping tours of duty are valid (should they be?)

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3415]
![image](https://cloud.githubusercontent.com/assets/950486/19448657/c5d89f52-9470-11e6-827d-f360de2508d4.png)

Steps: 
1. Get to the Military History page
1. Add multiple tours of duty, with overlapping dates

Expected result:

Not valid and error is presented (business question: can this ever happen?)

Actual result:

No error presented

**Comment by akainic** [comment]
Question for Shay. @J-Quag do you happen to know the answer to this? @cweber and @goldenmeanie do you mind following up on this one?

**Comment by cweber** [comment]
I don't know the rules for this, but based on some of the use cases Tom was talking about, I think flexibility might be more important than rules.

E.g. Someone from the Army Reserve that submits their total time in the reserves. But then also chooses to submit to 3 month periods of active duty that occurred during the first period they entered.

**Comment by goldenmeanie** [comment]
Agree with @cweber. Fat-fingered dates are resolvable by VCEs during the course of their work. Flexibility to deal with pretty common reserve situation seems preferable.
