### ISSUE TITLE
Hours completed can be not-a-number

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3417]
![image](https://cloud.githubusercontent.com/assets/950486/19448841/6f84f6a4-9471-11e6-9556-f4ababedda8c.png)

Steps:

1. Get to the Education history page
1. Enter letters into the Hours completed field

Expected results:

Error saying the text entered is not a number

Actual results:

Only numbers can be entered, and an error message if letters are entered

**Comment by akainic** [comment]
Should probably be using the `ErrorableNumberInput` instead here

**Comment by jbalboni** [comment]
This will be done with #3446
