### ISSUE TITLE
Number of months worked not an integer

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3418]
![image](https://cloud.githubusercontent.com/assets/950486/19449030/fd1b21a0-9471-11e6-99cb-996b04daa90e.png)

Steps:

1. Get to Employment history page
1. Fill in a decimal number in the Number of months worked

Expected result:

Error message saying that the entry isn't valid (i.e. needs to be an integer)

Actual result:

No error

**Comment by akainic** [comment]
Closing, duplicate of #3424
