### ISSUE TITLE
Premature error message for phone number entry

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3419]
![image](https://cloud.githubusercontent.com/assets/950486/19449155/6a7a6b20-9472-11e6-874a-86fac8062dd5.png)

Steps:
1. Go to the Personal information
2. Start entering a phone number

Expected results:

No error message received until there is a problem

Actual result:

Error message displayed before the user has had a chance to enter in all the data

**Comment by akainic** [comment]
The only way I could recreate this error was by starting to enter information, going to another screen, and then returning to this page again. The error goes away as expected once the phone number is correctly entered.

**Comment by goldenmeanie** [comment]
This is fixed in EDU/Common. Still a problem in HCA.
