### ISSUE TITLE
Adding in the benefit you'd like this service to be applied to prevents submission

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3420]
@J-Quag mentioned that including this field can prevent submission

![image](https://cloud.githubusercontent.com/assets/950486/19449627/56939a58-9474-11e6-888c-7b121f4d816c.png)

Steps:

1. Get to the military history screens
1. Answer `Were you involuntarily called for active duty during this period?` as No
1. Uncheck `Apply this service period to the benefit I'm applying for.`
1. Enter text into `Please tell us which benefit you’d like this service applied to.`

Expected results:

No issue

Actual result:

Unable to submit

**Comment by jbalboni** [comment]
I think this is a json schema issue that may be fixed now?

**Comment by jbalboni** [comment]
I think someone is supposed to verify that this is fixed? @J-Quag maybe?

**Comment by J-Quag** [comment]
Just verified. It allowed me to submit :)

**Comment by jbalboni** [comment]
Closing!
