### ISSUE TITLE
Switch waiver back to relinquishment

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3429]
@mollyblake and @goldenmeanie, I was not on whatever call that this came up, but it sounds like 'relinquishment' may be a word we need to use.

In which case, Alex or I can take care of it while we're making copy changes.

**Comment by mollyblake** [comment]
Yes. Agree. It was, coincidentally, one of the answers to the NYT mini crossword the other night ... so it's a sign. :)  (MINI bc I cannot do the big one)

**Comment by cweber** [comment]
Realized this is more of a frontend task (routes?) than copy task. I changed it on the page title, but the url, routes, etc. need changed.
