### ISSUE TITLE
Phone and SSN display with dashes

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3433]
On the review screen, phone number and SSN should format with the dashes whether entered that way or not initially.

**Comment by cvalarida** [comment]
I also found that it accepts alphabet characters as well. Should that be addressed with this?

**Comment by cvalarida** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/4859 formats the SSN, so just the phone is left.
