### ISSUE TITLE
Do not allow empty cards to be added

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3434]
Currently we allow users to submit blank entries for Employment and Education history. This is good. But we're also allowing users to add a new record without completing any data.

For places where you can add additional entries (periods of service, employment periods, etc.):

We should require at least one field to be filled before they add a new record. If not true, scroll up an display an error that says, "Fill out this record before adding a new one." (Or maybe just scroll up with no message?)

**Comment by kellymiller6** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by rtluu** [comment]
this is partially prevented and doesn't seem to be causing any problems. closing
