### ISSUE TITLE
[Rx] Prescription detail page layout is broken

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3438]
![screen shot 2016-10-18 at 12 23 52 pm](https://cloud.githubusercontent.com/assets/354277/19493033/d8ec4e1e-952d-11e6-86c0-5e2c0c18de25.png)

**Comment by U-DON** [comment]
I'm not seeing this. Have you rebuilt? Sometimes when watch is running, it doesn't always register the Sass changes, so I just save something else to get it to rebuild. Currently looks like this for me:

<img width="796" alt="screen shot 2016-10-18 at 4 17 59 pm" src="https://cloud.githubusercontent.com/assets/1067024/19494730/7ef38708-954e-11e6-81ea-6feca9adfb9e.png">

**Comment by webinista** [comment]
My screen shot is what it looks like in Chrome and Safari.

**Comment by U-DON** [comment]
Ah, I see now. Okay, I can take this.
