### ISSUE TITLE
Previous Training "To" dates do not provide accurate error message

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-website#3450]
When entering a date, the fields do not allow for a future date. However the error message that appears is not specific and asks only to "Please provide a response."

**Comment by J-Quag** [comment]
![image](https://cloud.githubusercontent.com/assets/15879513/19524658/7c8b854e-95ec-11e6-91dd-19b3de0dd79f.png)

**Comment by jbalboni** [comment]
This was completed with the merged PR
