### ISSUE TITLE
URL routes for Prescriptions and Secure Messaging 

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3477]
Currently, the prescriptions application has the base URL of /rx, so if this was in production and someone was looking at their historic prescriptions, the URL would be https://www.vets.gov/rx/history and if someone was looking at the details of prescription 123, the URL would be https://www.vets.gov/rx/prescription/123.  

Secure messaging is at /messaging, so if this was in production and someone was looking at their inbox, the URL would be https://www.vets.gov/messaging/folder/0 and if someone was looking at a message thread it would be https://www.vets.gov/messaging/thread/634998

The `/rx` and `/messaging` as the roots for each of these were largely chosen arbitrarily. I do not have strong opinions on Rx, but I do believe messaging should probably be namespaced under `/health` or something similar to be clear that it's about messaging a healthcare provider and not general messaging (such as tech support, which we don't have now on vets.gov but hopefully will in the future). 

 @gnakm @angel @emilyville thoughts?

**Comment by ayaleloehr** [comment]
Reminder to self, once we figure this out, do something similar to [this] (https://github.com/department-of-veterans-affairs/devops/pull/785) so that SM and Rx routes don't get 404s.

**Comment by emilyville** [comment]
I was thinking we should follow this pattern:

https://www.vets.gov/healthcare/apply/
https://www.vets.gov/healthcare/rx/
https://www.vets.gov/healthcare/messaging/

Unless... we want to break out managing and general healthcare and treat them differently. but I don't think we do.

**Comment by ayaleloehr** [comment]
OK awesome, so changes are:
1) all routes need `/healthcare` prepended to them.
2) the prescription detail page should drop the `/prescription` before the prescriptionId in the URL.

**Comment by angel** [comment]
@ayaleloehr @emilyville should we use prescription instead of rx since we don't use rx in the app itself?

**Comment by ayaleloehr** [comment]
👍 Sounds good!

**Comment by ayaleloehr** [comment]
Actually, waiting for @gnakm to chime in on whether it should be `prescription` or `prescriptions`.

**Comment by gnakm** [comment]
It should be `prescriptions`

https://www.vets.gov/healthcare/prescriptions/
https://www.vets.gov/healthcare/prescriptions/history
https://www.vets.gov/healthcare/prescriptions/123
https://www.vets.gov/healthcare/prescriptions/glossary

**Comment by U-DON** [comment]
Any opinions on messaging URLs? Specific folders, message threads, etc.

**Comment by gnakm** [comment]
Subbing in for Angel :wave:

https://www.vets.gov/healthcare/messaging/inbox
https://www.vets.gov/healthcare/messaging/inbox/123 (individual messages)
https://www.vets.gov/healthcare/messaging/draft
https://www.vets.gov/healthcare/messaging/sent
https://www.vets.gov/healthcare/messaging/deleted
https://www.vets.gov/healthcare/messaging/personal-folder-name (could we get custom folder names in URL?)
https://www.vets.gov/healthcare/messaging/settings

Things that don't need special URL:
Manage folders
Creating folders
Message Threads

**Comment by U-DON** [comment]
@gnakm So would viewing messages in other folders be something like:

https://www.vets.gov/healthcare/messaging/draft/456?

**Comment by gnakm** [comment]
@U-DON Yes!

**Comment by U-DON** [comment]
@gnakm Custom folder names in the URL should be possible. So the hyphens are stand-ins for spaces? From what I know, folders can only be named with alphanumeric characters and spaces, so hyphens, which are not allowed in the names, should be able to represent the spaces in those URLs. So I would expect something named 'this has spaces' to show up as:

https://www.vets.gov/healthcare/messaging/this-has-spaces

**Comment by gnakm** [comment]
@U-DON Yep. I was implying that the hyphens are for spaces. Thanks for explaining all of that above.
