### ISSUE TITLE
Confirm dialog after refilling Rx not always visible

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3486]
If I am scrolled to the bottom of the active page in Rx and click refill a prescriptions then confirm that I want to do the refill, a green confirmation box saying "Refill for X has been requested" appears at the very top of the page just under the header, but is not visible to the user, since they are scrolled to the bottom of the page. 

1) Is this a feature or bug?  If feature, please close this issue. 
2) If bug, what should be the proper behavior?

Assigning to @gnakm with cc to @webinista who has been working the active page.

**Comment by gnakm** [comment]
@ayaleloehr Thanks for pointing that out. @webinista Could we jump to the top of the page after confirming a refill? This probably also applies for Secure Messaging.
