### ISSUE TITLE
Use asset fingerprinting to enable caching

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets-website#3490]
[Google Page Speed](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fvets.gov&tab=mobile) reveals issues with caching for stylesheet, javascript, and image resources. Implementing a `Cache-Control` header would provide details to the browser that would help it determine whether or not a resource can be cached.

While this may improve performance, it also means newly deployed assets may not be downloaded by the client. This may mean that clients are not operating with the newest version of the site. It may also, in certain circumstances, cause particularly nasty issues when the HTML for a page isn't in sync with the application JS.

Including an asset digest or fingerprint (http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark) in the asset filename allows us to update the reference to the asset on deployment, meaning we can instruct the browser to cache the asset, but still provide updates as soon as they are shipped.

For `vets-website` this involves updating the build to generate fingerprints for assets and updating all references to point to these fingerprinted files instead of static resources.

**Comment by jcmeloni** [comment]
@jkassemi Making a note here that we talked about cachebusting in Friday 11/18 go/no-go call, and it was generally thought to be a good thing.  So perhaps we revisit this?

**Comment by jbalboni** [comment]
Webpack has writing bundles with hash codes in the file name built in. We would need to turn that on and then make a modification to the `metalsmith-webpack` (or give `ms-webpack` a shot) plugin to pass that information as metadata that the templates could use when writing the script tag.

**Comment by jcmeloni** [comment]
@crwallace @robbiethegeek What do you think?

**Comment by robbiethegeek** [comment]
I think this looks promising as a solution for sure.
I will add this to the list of build optimizations that @aub and @alexose will work on. https://www.npmjs.com/package/metalsmith-webpack
https://github.com/nealgranger/ms-webpack

**Comment by jcmeloni** [comment]
Not moving over to vets.gov-team as comments lead me to believe it will be covered in current work. PLEASE correct me if I'm wrong @aub @alexose @robbiethegeek and I'll move it over to vets.gov-team

**Comment by carlmjohnson** [comment]
AFAICT, no one has solved this issue. If you load vets.gov in a browser, there is still no fingerprinting of assets.

**Comment by robbiethegeek** [comment]
I don't think this is being worked officially.  @aub @crwallace @alexose can you confirm?

**Comment by aub** [comment]
I'm not aware that it is being worked on, but it definitely should be.

**Comment by jcmeloni** [comment]
I thought it was being worked out as part of the build work happening.

**Comment by jkassemi** [comment]
We haven't started working on this. 

It can be considered part of the build, but is tied more closely to the application.

**Comment by jcmeloni** [comment]
Ok, bad reading on my part then. I'll move this over to a team ticket and throw it in the backlog to discuss further before it has a tactical place in a sprint.

**Comment by robbiethegeek** [comment]
I talked to @aub he is going to take a look at this and talk with @jkassemi and @crwallace to try to get this done this week

**Comment by jcmeloni** [comment]
hey, that's cool!

**Comment by aub** [comment]
This work has been completed in our code. @jkassemi is working on setting the caching headers so browsers will make use of it, but we can handle that separately.
