### ISSUE TITLE
Tab order starts with the continue button inside the edu flow

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3498]
Currently the page loads with focus on the continue button. It should default to the top of the page.    If practical, "Skip to content" could become "Continue with form".

X of y step name at the top of the form should use https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role

**Comment by goldenmeanie** [comment]
Updated original issue description

**Comment by akainic** [comment]
Perhaps set tabindex to a higher-order component on the page (breadcrumbs?)
