### ISSUE TITLE
Rx Accessibility testing

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3499]
We need to set up and run automated accessibility testing for Rx.  Talking to @crwallace, it seems the steps are:
- Create a file like [this example from HCA](https://github.com/department-of-veterans-affairs/vets-website/blob/master/test/accessibility/hca-508.spec.js) that goes through each page of Rx and runs `.axeCheck('.main')` on it. 
- Then to run the tests, first start selenium: `npm run selenium:bootstrap`
- Then run the accessibility tests: `npm run build && npm run test:accessibility`

Last time we were going through issues, @webinista and @U-DON seemed to prefer things just get assigned to one of you then reassigned later if needed, so going to assign to @webinista , as @U-DON has been focused more on the unit tests. Let me know if you want those switched though!

**Comment by ayaleloehr** [comment]
@crwallace or @bshyong any chance we could get help getting this set up for Rx this week?  

If so, the steps I wrote out above say we'll need to know all the different pages of the application; the four pages of Rx are 
- the "active page" (/healthcare/prescriptions)
- the "history page" (/healthcare/prescriptions/history)
- the "detail page" (/healthcare/prescriptions/[prescription_id], where [prescription_id] is dynamic depending on the prescription)
- the glossary (/healthcare/prescriptions/glossary)

**Comment by crwallace** [comment]
PR has been created for this but it will fail because some issues need to be addressed.
