### ISSUE TITLE
Last requested date and Fill Date tweaks

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3515]
- [ ] Last requested date = `refillSubmitDate`.
  Not sure what currently last requested date links to but Last Requested Date found on the history page should be `refillSubmitDate`
- [ ] If Last Fill Date is not a future date, it should say "Not Available"
- [ ] All last requested labels should be "Last requested date"
  - View History on mobile currently says "Refill requested on"
  - Refill page says "Last Requested"
  - Both sorts say "Last Requested"
- [ ] Fill Date on mobile history should says "Last fill date"

<img width="1016" alt="screen shot 2016-10-24 at 10 14 20 am" src="https://cloud.githubusercontent.com/assets/13420618/19649433/c6605a74-99d3-11e6-910f-5addb97a9b96.png">

<img width="390" alt="screen shot 2016-10-24 at 10 14 30 am" src="https://cloud.githubusercontent.com/assets/13420618/19649862/5f58d976-99d5-11e6-8801-b97de182fef2.png">

**Comment by bshyong** [comment]
@gnakm Looking at this issue, these are all visual tweaks and copy changes, right?

**Comment by gnakm** [comment]
Sorry @bshyong. I mixed up our developers :)

**Comment by U-DON** [comment]
@gnakm Currently, 'Last requested' on refill page is linked to `refillDate`. That should also be `refillSubmitDate`?

**Comment by gnakm** [comment]
@U-DON 

"Last requested date" should be `refillSubmitDate`
"Last fill date" should be `refillDate`

**Comment by U-DON** [comment]
@gnakm Currently, none of the last fill dates (which are `refillDate`) are in the future, so all of them would show 'Not available'. Is that okay?

**Comment by gnakm** [comment]
@U-DON  Yeah. The idea is that users should haven't to calculate what the future date means to them. 

They should know the last fill date and the other option should point them to clicking a Refill prescription button. Not available is if a prescription just got requested for refill and it is in the process of getting refilled. I kept not available vague instead of pending or in process incase there is an error.

**Comment by ayaleloehr** [comment]
I'm confused here.  Why are "last fill dates" showing as "Not available" on the history page when we do have a date for them?

**Comment by ayaleloehr** [comment]
Re-reading this issue, it's the second bullet at the top that I'm confused on: `If Last Fill Date is not a future date, it should say "Not Available"`.  Can you explain this @gnakm?  I would think that the "last fill date" _should_ be in the past for us to show it, not the opposite?  Am I missing something?

**Comment by U-DON** [comment]
@gnakm: Same question as @ayaleloehr asked directly above. Point of clarification: when do we show 'Not available'? If the date is in the past, or if the date is in the future?

**Comment by gnakm** [comment]
@ayaleloehr @U-DON

If Last fill date is past date, we show it. 
If Last fill date is a future date, we show not available.
