### ISSUE TITLE
ErrorableNumberInput removing decimal unexpectedly

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3542]
On the hours input on the education history page in education benefits:
1. Enter 70.00
2. Backspace to delete both 0s
3. Decimal place is removed and cursor is moved to the beginning of the input

This seems to happen because the DOM event we get in the React component is "70" instead of "70.", so we when we put it in the Redux store and re-render, the value in the input field changes.

This is a little odd and unexpected.

**Comment by jcmeloni** [comment]
Confirmed still an issue.

**Comment by jbalboni** [comment]
This is a React bug: https://github.com/facebook/react/pull/7359, which is fixed in 15.5.
