### ISSUE TITLE
Ensure Bus. Owners comms to VCEs

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-website#3561]
Part of the pre launch checklist is to make sure the business owners are communicating to their downstream staff (in this case VCEs) that there would be something new coming and pushing those 1990 applications. Doing a quick check in. Cant remember if this was part of the comms plan. Will look into this.

**Comment by J-Quag** [comment]
I believe @akainic  has started discussing this with Tammy from EDU.

**Comment by akainic** [comment]
This is done.
