### ISSUE TITLE
Follow up with Mark re: downtime/maintenance schedule for SFTP

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-website#3562]

**Comment by J-Quag** [comment]
@markolson   We just wanted to check in to make sure we knew what the scheduled down times were for the SFTP server and how we're accounting for those. 
@akainic Let me know if I forgot something.

**Comment by markolson** [comment]
> The only scheduled downtime is usually once a month for Microsoft patches.  Preprod would be at 5am and Production on a Sunday from 7pm-9pm. The exact date changes monthly, but you should be able to avoid these timeframes in general.

Our job runs at 3AM Eastern, so planned downtime shouldn't impact us. For unplanned downtime, our job auto-retries with a larger backoff each time until it succeeds.

**Comment by J-Quag** [comment]
@akainic  What else do you need me to do on this?

**Comment by akainic** [comment]
Nope I think we're good, sounds like this won't affect us.
