### ISSUE TITLE
Consume Encrypted SAML Changes

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/vets-website#3572]
### Context

`vets-api` has an [open PR](https://github.com/department-of-veterans-affairs/vets-api/pull/355) to consume encrypted SAML assertions from ID.me.  Until the front-end consumes these changes, this PR may not be merged.
### Vets-api Changes
- Calls to `/session/new` can optionally now include a `location` query param (ex. `/session/new?location=/some/resource`).  `location` represents where the browser will be rediected on vets.gov once autentication is complete.  `location`: _must_ begin with a forward slash / and _must_ only contain the following characters (separates by pipes) a-z | A-Z | 0-9 | _ | - | / .  An invalid `location` will default to `/profile`.
- `token` is returned as url query param once auth is complete and vets-api has validates the ID.me SAML Assertion.  Ex. `302 http://www.vets.gov/profile?token=abcd1234`

For more info, see [the design doc](https://github.com/department-of-veterans-affairs/platform-team/blob/encrypred-saml-doc-update/identity/authentication_and_authorization.md)
### To be done
- [x] Update auth calls to include `location` param where necessary / desired
- [x] Fetch token from url query param `token`
- [x] Notify Bill Ryan where authentication failures should be redirected to
- [x] Notify Bill Ryan when front-end work is ready to be merged to master

**Comment by crwallace** [comment]
@omgitsbillryan -- We are complete on this correct?

**Comment by omgitsbillryan** [comment]
Yay
