### ISSUE TITLE
Estimate and Finish HCA port

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#3583]
@alexose will spend 10ish minutes evaluating current state and will confirm whether this is possible by vets day. 

I THINK IT WILL TAKE ME X NUMBER OF HOURS

if so, he will complete. 

@leanna - need to label HCA

**Comment by leannammiller** [comment]
@akainic this is the card for ongoing HCA work if you have questions or comments before we chat today.

**Comment by alexose** [comment]
@akainic Ended up taking this on.
