### ISSUE TITLE
Hide tuition top-up option

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3602]
Hide tuition assistance top-up option from dropdown if they select a benefit that doesn't apply to this.

**Comment by jcmeloni** [comment]
@akainic I can't figure out where to check this (my bad) - is it still an issue?

**Comment by akainic** [comment]
Yes, still an issue, but we might need more information from Shay on this one. Perhaps @cweber can look into this one?

**Comment by cweber** [comment]
Yeah. I can send an email about this. I think I missed whenever this came up, but I think I understand the gist.

**Comment by cweber** [comment]
Yeah. I can email about this. I think I missed when this question came up, but I think I understand the premise enough to ask the clarifying question.

**Comment by cweber** [comment]
Upon writing this email...I should probably double check with you that I understand this.

**Comment by cweber** [comment]
Confirmed: 

"only people who have selected Post 9/11-GI Bill or MGIB-AD should be able to select 'Tuition-assistance top-off' as an option."

**Comment by leannammiller** [comment]
hey @cagedcrown - we'll do the front end walk-thru tomorrow and then get you started on this one.

**Comment by cagedcrown** [comment]
@leannammiller Sounds good!

**Comment by leannammiller** [comment]
@cagedcrown how is this going?

**Comment by cagedcrown** [comment]
This is still in progress and I'll try to finish today.

**Comment by leannammiller** [comment]
hey @cagedcrown - did you complete this?
