### ISSUE TITLE
Write a11y test for all react apps

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#3605]
Each reactJS app must have an a11y  test written for the 508 scanner to run over it. Pleas include all routes for your apps.

Feel free to use `/test/accessibility/hca-508.spec.js` as an example.

- [x]  Facility Locator
- [x]  Auth
- [x]  Disability Benefits
- [x]  Education Benefits
- [x]  Login
- [x]  Messaging
- [x]  Prescriptions
- [x]  User Profile

Please check your app off once it has been completed.

**Comment by akainic** [comment]
Is everyone able to run the hca-508 test successfully locally? This test fails for me when I try to run it locally :(

**Comment by jbalboni** [comment]
@akainic It was working for me. What are you seeing?

**Comment by akainic** [comment]
This error @jbalboni:    
```
- Begin application (4.032s)
   Timed out while waiting for element <.form-panel> to be present for 1000 milliseconds.  - expected "visible" but got: "not found"
       at Object.Begin application (/Users/vacokainia/Desktop/coding/vets-website/test/accessibility/hca-508.spec.js:13:8)
```

**Comment by akainic** [comment]
Running `npm run build` fixed the issue for me!

**Comment by crwallace** [comment]
Thank you everyone we are all set here! I am closing this out.
