### ISSUE TITLE
Make "Compose a message" button bigger

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3614]
Can we make the top and bottom padding 1.75rem and the font size the closer to 18px like so:

![image](https://cloud.githubusercontent.com/assets/13420618/19873523/cf69c62e-9f95-11e6-8ff1-923176d9ad77.png)

**Comment by angel** [comment]
Moved this issue over to the [messaging-fe repo](https://github.com/department-of-veterans-affairs/messaging-fe/issues/130) so all the messaging issues are in one place.
