### ISSUE TITLE
Make text field alignments

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3617]
**This is for post launch**

<img width="735" alt="screen shot 2016-10-31 at 5 06 27 pm" src="https://cloud.githubusercontent.com/assets/13420618/19871756/b269f57a-9f8c-11e6-8321-78fbcde188cd.png">

For consistency throughout Vets.gov, we should have text fields all left aligned with text above, like this: 

<img width="551" alt="screen shot 2016-10-31 at 5 40 45 pm" src="https://cloud.githubusercontent.com/assets/13420618/19872641/3468be04-9f91-11e6-83a3-880ea5ef271b.png">

**Comment by angel** [comment]
Moved this issue to the [messaging-fe repo](https://github.com/department-of-veterans-affairs/messaging-fe/issues/133) so all the messaging issues are in one place.
