### ISSUE TITLE
Change From to To in draft section

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3620]
**From** should be changed to **To** in Draft table.

<img width="959" alt="screen shot 2016-10-31 at 6 36 28 pm" src="https://cloud.githubusercontent.com/assets/13420618/19874072/04089df8-9f99-11e6-9a56-9a58c4c69227.png">

Should look like this:
<img width="702" alt="screen shot 2016-10-31 at 6 42 02 pm" src="https://cloud.githubusercontent.com/assets/13420618/19874179/b7e1dfec-9f99-11e6-8943-ba6ed656f7dc.png">

**Comment by angel** [comment]
Moved this issue to the [messaging-fe repo](https://github.com/department-of-veterans-affairs/messaging-fe/issues/134) so all the messaging issues are in one place.
