### ISSUE TITLE
Number of messages in thread next to recipient name in folder view

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#3621]
![image](https://cloud.githubusercontent.com/assets/103496/19874277/387d9114-9f81-11e6-8614-16f8ed7e1110.png)

Messages with threads should have the number of messages in that thread next to the recipient name like so: 
![image](https://cloud.githubusercontent.com/assets/103496/19874300/55278612-9f81-11e6-8c19-33ab5cd020c8.png)

**Comment by U-DON** [comment]
@mphprogrammer or @saneshark: It's not possible to include the number of messages in the thread for messages in a collection, is it?

**Comment by mphprogrammer** [comment]
I'll check, but if memory serves any collection can be paginated.

**Comment by U-DON** [comment]
@mphprogrammer I meant adding the number of messages in the thread of each entry from a `GET /messaging/health/folders/:id/messages`.

**Comment by angel** [comment]
Moved this issue to the [messaging-fe repo](https://github.com/department-of-veterans-affairs/messaging-fe/issues/135) so all the messaging issues are in one place.
