### ISSUE TITLE
Remove date column from Drafts folder

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#3624]
Since we don't have a date for drafts, I think it would better to take out that column. "Not available" sounds that there was some error.

![image](https://cloud.githubusercontent.com/assets/103496/19874535/274f32d8-9f83-11e6-9a0c-1d17bdb6bd01.png)

**Comment by U-DON** [comment]
Duplicate of department-of-veterans-affairs/messaging-fe#121.

**Comment by angel** [comment]
Closing this issue since this is a duplicate as @U-DON mentioned above!
