### ISSUE TITLE
Add last submit date to Refill cards

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3626]
Users wanted to know they date they submitted their refill.
Add Last submit date before Last fill date on cards.
API: `refillSubmitDate`

<img width="794" alt="screen shot 2016-10-31 at 7 22 30 pm" src="https://cloud.githubusercontent.com/assets/13420618/19874994/a263f7bc-9f9f-11e6-88ff-3021ad864326.png">

**Comment by ayaleloehr** [comment]
@gnakm i believe cards can also have both Track Package and Refill Prescription buttons, right? Can you give an image of that, as that will likely make the cards taller?

**Comment by gnakm** [comment]
@webinista Considering the case that a prescription can be refillable, have a recent trackable package and run out of prescription, card have to be bumped up to 470px in height. These mocks are most accurate:

<img width="977" alt="screen shot 2016-11-01 at 10 53 21 am" src="https://cloud.githubusercontent.com/assets/13420618/19893985/a69057e0-a021-11e6-8382-b6800b7ea89c.png">

**Comment by webinista** [comment]
470px seems like a really tall box. Just want to verify that it wasn't a typo.

<img width="1077" alt="screen shot 2016-11-01 at 10 36 41 am" src="https://cloud.githubusercontent.com/assets/354277/19899959/29b2b94a-a01f-11e6-9cfe-5069b9c6d995.png">

**Comment by gnakm** [comment]
@webinista that was totally a typo! It's 270px.
