### ISSUE TITLE
Change Prescription name to default sort on Refill prescription page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3627]
User prefer Prescription name as default sort on Refill prescription page

**Comment by gnakm** [comment]
RE: Kam's comment on making default the same for Refill page and view history page.

Backend 
default = prescription name

Frontend 
Refill prescription page default = prescription name
History page default = last submit date

**Comment by webinista** [comment]
Final decision is to do this on the client side, adding a sort parameter to the initial request.
