### ISSUE TITLE
Add content for Active and History pages

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3630]

**Comment by gnakm** [comment]
Add 1 line description to refill and history page so that users know refill page is only active meds. 

<img width="590" alt="screen shot 2016-11-01 at 2 54 17 pm" src="https://cloud.githubusercontent.com/assets/13420618/19903965/fe7e5432-a046-11e6-95b9-e2028588fd1d.png">
<img width="591" alt="screen shot 2016-11-01 at 2 54 29 pm" src="https://cloud.githubusercontent.com/assets/13420618/19903966/fe92a25c-a046-11e6-9859-c7cbb8d4aa1e.png">

Refill prescriptions page:
Your active VA prescriptions

History page:
Your VA prescription refill history

**Comment by U-DON** [comment]
@gnakm The descriptions from the screenshots are different from the descriptions you wrote. Should they be the latter ('Your active VA prescriptions' and 'Your VA prescription refill history')?

**Comment by webinista** [comment]
@gnakm Let me know if you're okay with the spacing here.

<img width="1280" alt="screen shot 2016-11-01 at 1 40 22 pm" src="https://cloud.githubusercontent.com/assets/354277/19906712/21c98d70-a039-11e6-82b9-ac1d043f1c1a.png">

**Comment by gnakm** [comment]
@webinista  Could we make top and bottom 1 rem bigger?

**Comment by gnakm** [comment]
The copy should be the latter. The mocks are from earlier version. I also added periods.

Refill prescriptions page:
Your active VA prescriptions.

History page:
Your VA prescription refill history.
