### ISSUE TITLE
Update glossary page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3631]
![rx glossary](https://cloud.githubusercontent.com/assets/13420618/19875476/67f2e7e2-9fa3-11e6-942f-6ea6df4126b5.png)

**Refill in Process**: This prescription was sent to the pharmacy for review. Contact your VA pharmacy if you need this medication now.

**Submitted**: Your prescription refill has been submitted.

Add headers `Prescription status` and `Refill Status`

**Comment by webinista** [comment]
Fixed with 9bed1f7
