### ISSUE TITLE
Fix language around "relinquish" on benefits page

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#3652]
From Shay: On the last call there was discussion on the text under the Post 9/11 selection. The user only has to give up one benefit, not “other benefits”. I believe there was a request to change the wording to something more like, “you will have to relinquish (give up) another benefit you may be eligible for” or, “you will have to relinquish (give up) one other benefit you may be eligible for”

**Comment by leannammiller** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/22749867/19900601/7d25c89a-a03a-11e6-9786-82314c1af20b.png)

**Comment by mollyblake** [comment]
@akainic Do you have a minute to make this quick fix on this URL: https://dev.vets.gov/education/apply-for-education-benefits/application/benefits-eligibility/benefits-selection

<img width="575" alt="screen shot 2016-11-01 at 1 53 02 pm" src="https://cloud.githubusercontent.com/assets/16196072/19904995/90ccfa9e-a03a-11e6-8181-d7b658a8a25e.png">

CURRENT: When you choose to apply for your Post-9/11 benefit, you have to relinquish (give up) other benefits you may be eligible for. You’ll make this decision on the next page.

Please change to: When you choose to apply for your Post-9/11 benefit, you have to relinquish (give up) 1 other benefit you may be eligible for. You’ll make this decision on the next page.

THANK YOU!
