### ISSUE TITLE
Add Sentence to Effective Date

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#3653]
From Shay: Effective date wording – Needs another sentence which states, you may select a date in the past if you have already started school.

**Comment by leannammiller** [comment]
![unnamed-2](https://cloud.githubusercontent.com/assets/22749867/19900666/b82cf850-a03a-11e6-9ff9-8d5045c7de97.png)

**Comment by mollyblake** [comment]
@leannammiller Thanks -- I think the wording that Shay requested was written and is in another issue. I'll search around for it and get it to you!

**Comment by mollyblake** [comment]
@cweber I feel like this might need your attention. The date situation is getting clunky sounding.  Can we bullet them?  
- Use today's date unless you aren't going to use your Post 9/11 GI Bill benefits until later.
- If you pick a future date, you can't get benefits until then. 
- If your classes started less than 2 years ago, enter the date they began. 

@leannammiller Working on this!  I'll let you know when it's GTG! Thanks

**Comment by cweber** [comment]
I wish we could shorten it instead, but bullets seem reasonable to help clarify.

**Comment by mollyblake** [comment]
Ok, thanks @cweber!

**Comment by akainic** [comment]
@mollyblake is the content for this finalized? happy to jump on this today!
