### ISSUE TITLE
Change "British" to Great Britain in Drop Down  in Personal Information

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#3655]
From Shay: 3)      Looking at the country drop down. Is “British” a country? I did not see Britain or Great Britain, but there is a United Kingdom in the list.

**Comment by leannammiller** [comment]
![unnamed-3](https://cloud.githubusercontent.com/assets/22749867/19900745/f57b9b58-a03a-11e6-950b-ed5c773ab832.png)

**Comment by mollyblake** [comment]
@goldenmeanie  or @cweber this looks like something you'll have to address. Thanks!

**Comment by goldenmeanie** [comment]
England is listed as United Kingdom. This is supposed to be [British Indian Ocean Territories](https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory). PR coming.
