### ISSUE TITLE
Update glossary link functionality for Detail page.

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3657]

**Comment by eli-lewis** [comment]
@U-DON not seeing the glossary link

**Comment by U-DON** [comment]
@eli-lewis The "glossary link" refers to the status that you see for the refill status of each prescription. Like "Active", "Submitted", "In process", etc. Clicking it pops up the modal with a definition of the glossary term.

**Comment by eli-lewis** [comment]
@U-DON ahhhh, ok... got it... terminology euphemisms ;)
