### ISSUE TITLE
Unify ruled heading styles

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3660]
We currently have `.va-h-ruled` and now/soon`.rx-heading`. They're styled a bit differently, but aren't so radically different that they can't be combined. 

Example of `.va-h-ruled`
<img width="532" alt="screen shot 2016-11-01 at 12 44 36 pm" src="https://cloud.githubusercontent.com/assets/354277/19904711/004a4a48-a031-11e6-9a47-589985d07b59.png">

Example of `rx-heading`:

<img width="373" alt="screen shot 2016-11-01 at 12 45 23 pm" src="https://cloud.githubusercontent.com/assets/354277/19904725/19112c54-a031-11e6-84d4-1b161c2a33a7.png">

This is also affected by #2347.

**Comment by jcmeloni** [comment]
Not moving over to vets.gov-team as open PR should close this one soon  https://github.com/department-of-veterans-affairs/vets-website/pull/4606
