### ISSUE TITLE
Unify .va-tab-content styles

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3665]
We have `.va-tab-content` in `_va-tabs.scss` with a top `padding-top: 4rem` (soon to be 0rem), and again in `disability-benefits.scss` with `padding-top: 2em`. 

They have the same border style, so we just need to:

1. reconcile whether we actually need to have two different `padding-top` values
2a. If yes, add a `.disability-tab-content` class for the disability variant.
2b. If no, remove `.va-tab-content` from `disability-benefits.scss`

**Comment by webinista** [comment]
@melwoodard Can you weigh in here? Is this an issue that's accounted for elsewhere?

**Comment by melwoodard** [comment]
@webinista the padding is visually the same between claims and Rx, so we shouldn't need two different values.
