### ISSUE TITLE
Create month year component

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3675]
On Edu benefits we had a need for a month/year date input. We ended up adding a prop to DateInput to handle this, but it might make sense to create a separate component. The current DateInput component is complicated as it is.

**Comment by cweber** [comment]
Did this get resolved now that we have Month/Year for high school graduation?

**Comment by jbalboni** [comment]
This is still outstanding. We likely want to make a separate component for month/year, instead of using the normal date component.

**Comment by alexose** [comment]
The big problem with my approach to altering `DateInput` is that it causes the date validations to not play especially well with each other.  @cweber noticed the following:

![date-junk](https://cloud.githubusercontent.com/assets/627264/20807559/849331aa-b7a3-11e6-9832-f8f4d54e0f78.gif)

We also need to update the review component:

![image](https://cloud.githubusercontent.com/assets/627264/20807629/cca8c84c-b7a3-11e6-921c-c223309bffb4.png)

**Comment by leannammiller** [comment]
@alexose - could you give an update on this?

**Comment by alexose** [comment]
We weren't able to recreate the bug that @cweber noticed, but the review component is fixed.  Closing!
