### ISSUE TITLE
Access to Care design feedback

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3702]
@crwallace Could you leave your feedback about the access to care section? Thanks!

![desktop detail access to care](https://cloud.githubusercontent.com/assets/13420618/19952925/30e2f68c-a13f-11e6-8654-bf1e04ee9913.png)

**Comment by crwallace** [comment]
@gnakm -- Is access to care something that should be as important as services listed? It feels like this should be part of the main content but it is currently secondary.

**Comment by NatalieEMoore** [comment]
@crwallace/ @gnakm -- I think it should be treated as less important, which is what @staceylanger and I decided on.  @staceylanger do you still agree?

**Comment by gnakm** [comment]
We are going to move forward and build this as secondary information. Any design iterations for after launch.
