### ISSUE TITLE
Blank refill status in some cases

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3711]
Not yet sure whether this is an issue in `Prescription.jsx,` or with the mock API data, but this is happening with some cards.

<img width="357" alt="screen shot 2016-11-03 at 10 23 44 am" src="https://cloud.githubusercontent.com/assets/354277/19977105/a7d09d06-a1af-11e6-847b-c1a3a497b2c6.png">

**Comment by webinista** [comment]
The card for which this is happening has a status of `on hold`. I don't think `on hold` is an actual status, however. The production API would either be `hold` or `onhold`. If `on hold` is an actual status, I can add it to the config file. Otherwise, I think this is a mistake in the mock API.

Can you confirm @ayaleloehr?

**Comment by ayaleloehr** [comment]
The status in the mock was "on hold" it should have been "hold".  This is why mocks stink. it has been corrected. Please close if that fixed this.

**Comment by webinista** [comment]
Yep. That fixed it!
