### ISSUE TITLE
Handle 'Record not found' prescriptions for detail page

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-website#3730]
When accessing the route `/healthcare/prescriptions/:id` with a random id that doesn't exist, we should display an error message rather than try to render the usual components. It also displays current dates in the date fields rather than showing null.

**Comment by webinista** [comment]
Now it says: 

> We couldn't retrieve your prescription. Please refresh this page or try again later.

That seems to resolve things, unless we specifically want to say that no such prescription exists, rather than we couldn't retrieve it.
