### ISSUE TITLE
Research standards for using animation for UX enhancements while maintaining accessibility

### ISSUE THREAD

**Issue by dannychapman** [department-of-veterans-affairs/vets-website#3736]
CSS animation can provide great opportunities for UX improvements, but we need to maintain the highest possible adherence to accessibility when doing so. 

Starting this issue to explore this in more depth.

**Comment by dannychapman** [comment]
**Articles**

- http://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity
- http://alistapart.com/blog/post/more-resources-for-accessible-animations

**Comment by ayaleloehr** [comment]
@dannychapman is there any followup here? is this something that should be researched further or not at this time?

**Comment by dannychapman** [comment]
@ayaleloehr Not at this time. Closing.
