### ISSUE TITLE
Add 'alternate forms' language to /apply-for-education-benefits-new/

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3740]
Since this page will house the fork-modal that we're directing education benefits applicants to, we want to make sure that there is language on this page that can direct people back to VONAPP if our form won't serve their needs. 

There will also be a modal that sits over this page. That is being handled in #3741.

Changes and reference image below:

Button in sticky box should now say: [Start Form 22-1990](url)

# Apply for Education Benefits

Servicemembers and Veterans who are interested in education and training can use this online application (**Form 22-1990**) to get their Certificate of Eligibility (COE).

--- 

### For Forms 1990E, 1990N, 1995, 5490, 5495

You must apply for education benefits using eBenefits.va.gov if you are:

- A spouse or dependent
- A survivor of a Veteran
- A candidate for The National Call to Service program
- A student who wants to change programs or school

[Apply on eBenefits
](https://www.ebenefits.va.gov/ebenefits/vonapp)

--- 

## What are the steps to apply with form 22-1990?

![screen shot 2016-11-04 at 1 14 58 pm](https://cloud.githubusercontent.com/assets/417657/20015239/07ee2abe-a291-11e6-9d4f-1c341c702447.png)

cc @goldenmeanie

**Comment by cweber** [comment]
I just added the copy for this in edu-benefits-alternate-forms-copy but there are some CSS rules and markdown interpretations that cause it to look funky.

This seemed important to Shay in her email and we have the solution in hand. Would be good to get in soon. cc @akainic 

**Bugs**
 - p:first-of-type (font-size, color, etc.)
 - Space after blue box
 - Space after button (markdown is dropping it in a <p>)

Passing off...

**Comment by cweber** [comment]
Also worth noting. We want to change the apply button language, but i didn't touch that since I think it's in a common component?

**Comment by goldenmeanie** [comment]
- [ ] eBenefits button needs the external link icon (/assets/img/icons/exit-icon-primary.png) in it.
- [ ] Ghost button style is transparent background not white.
