### ISSUE TITLE
Add fork modal to /apply-for-education-benefits-new/

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3741]
This modal will be in place to help direct people to the correct form. We expect our form to handle about 50% of all Education Benefits application cases, but the other 50% need to know how to find their way to VONAPP(as an iframe in eBenefits) for the other forms.

The base page for this has additional language to reinforce the single purpose of our form. That's addressed in #3740.

(@staceylanger, this is the solution we arrived at.)

The modal should sit on top of /apply-for-education-benefits-new/ and should take advantage of existing modal styles elsewhere on the site.

# Which form do you need to use?

## Servicemembers and Veterans applying for education benefits

[Apply with Form 22-1990](url)

---

If you are:

- A student who wants to **change programs or schools**
- A spouse or dependent
- A survivor of a Veteran
- A candidate for **National Call to Service**

[Apply on eBenefits](url)

![edu-fork-modal](https://cloud.githubusercontent.com/assets/417657/20015367/97da83de-a291-11e6-9dbb-c301c40a168d.png)

cc @goldenmeanie

**Comment by cweber** [comment]
@goldenmeanie, I just realized we probably need to mock up what this looks like in mobile. Stacked?

**Comment by goldenmeanie** [comment]
![apply-for-benefits-mobile-modal-or-left](https://cloud.githubusercontent.com/assets/1969/20064733/b610f960-a4d9-11e6-83dc-a0eb74af5b56.png)

**Comment by staceylanger** [comment]
Looks good.

**Comment by alexose** [comment]
Quick call with @goldenmeanie revealed a few items:

* We should implement a non-react modal from scratch using the existing styles
* Future modals may need a close box, but this one won't
* The modal should open when there is a url param (e.g., `?modal` or maybe `#modal`)

**Comment by alexose** [comment]
Work started in [add-modal#3741](https://github.com/department-of-veterans-affairs/vets-website/compare/add-modal%233741?expand=1).

The modal + content is scaffolded out but still needs styles.

![image](https://cloud.githubusercontent.com/assets/627264/20412883/7c227294-acf7-11e6-8ddb-039541910d0d.png)

**Comment by alexose** [comment]
Desktop styles:

![image](https://cloud.githubusercontent.com/assets/627264/20452561/af7ddcf8-adda-11e6-9419-e62456c5ea7f.png)

There are minor differences with the mock, but it is in line with the other modals across the site.  We can definitely make tweaks.

**Comment by alexose** [comment]
I'm having issues getting my local install to serve mobile styles.  Continuing to debug...
