### ISSUE TITLE
[UX question] Define consistent error checking / error display behavior for ErrorableTextInput

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3753]
This originated with department-of-veterans-affairs/messaging-fe#139, but affects a common component.

> Right now when you are in the "Create new folder" modal and put in a name and then delete it all the way an error automatically pops up before the Veteran even tried submitting it. 

For [HCA](https://www.vets.gov/healthcare/apply/application/veteran-information/personal-information), the error checking happens if the veteran enters data, then deletes it all. But it does not happen if the veteran focuses on the field and then skips it without entering data.

In Secure Messaging (try creating a new folder), this error checking happens `onBlur`, whether or not the veteran has entered anything. I _assume_ the same is true for other post-HCA applications.

### Questions:

1. Is the assumption correct? Does error checking always happen `onBlur`, regardless of whether the veteran has entered anything?

2. What _should_ happen here? Should we only flip the `dirty` flag to `true` `onBlur` when the veteran has entered data?

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
