### ISSUE TITLE
sign in link disappears on home page on mouse hover

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3761]
On staging, when I hover over the sign in or register links, they are no longer visible. 

![screen shot 2016-11-07 at 7 50 54 am](https://cloud.githubusercontent.com/assets/4719765/20058443/1ad4fed4-a4bf-11e6-8cee-d97d2eeac910.png)

**Comment by ayaleloehr** [comment]
Similarly, the "hello [user's email address]" in the header isn't visible either. I believe this is site wide so going to leave assigned to @bshyong for now, but if this is something we need to fix specifically to Rx and SM, please let me know @crwallace 

![screen shot 2016-11-07 at 7 55 43 am](https://cloud.githubusercontent.com/assets/4719765/20058584/b5e51eea-a4bf-11e6-8567-d71655b6d05b.png)

**Comment by bshyong** [comment]
Closing resolved issue
