### ISSUE TITLE
[HOMEPAGE] Remove homepage hero image from blog post

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#3768]
We need to remove the same header as the homepage from the secretary's blog post.

We also need to think about the treatment of the "Experience" flag to the left.

![screen shot 2016-11-07 at 10 33 31 am](https://cloud.githubusercontent.com/assets/3453669/20063624/edb92f30-a4d5-11e6-8be1-fabf96c3d016.png)

source: /2015/11/11/why-we-are-designing-in-beta/

@angel // @melwoodard -- Do you have thoughts?

**Comment by angel** [comment]
@crwallace @melwoodard:

Maybe something like this?

![image](https://cloud.githubusercontent.com/assets/103496/20073416/119ef0e6-a4e1-11e6-8fd3-f6d2438f22cb.png)
or

![image](https://cloud.githubusercontent.com/assets/103496/20073493/567d9e92-a4e1-11e6-9806-6bff67b31008.png)

**Comment by melwoodard** [comment]
@angel I think this works well - two thoughts:

1. What does this look like on a larger display? Does it stay attached to the left edge of the screen, or stay attached to the main column?

2. What does it look like on a single-column mobile layout?

@bshyong this also needs to be addressed on the blog index page - /experience

**Comment by angel** [comment]
@melwoodard 

1. I think it would stay attached to the left edge like this: 
![image](https://cloud.githubusercontent.com/assets/103496/20079738/f2e27b40-a4fa-11e6-8c95-bf3c9d1f824e.png)
What do you think?

2. This is what the mobile layout could look like:
![image](https://cloud.githubusercontent.com/assets/103496/20079839/6dcebc74-a4fb-11e6-8602-da2ca7d3e7f1.png)

**Comment by melwoodard** [comment]
Continuing the design conversation in #3807
