### ISSUE TITLE
[HOMEPAGE] Profile Link Hover

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#3770]
Because the hover or non-link color is white, the text disappears if it is not a link or if it is in a hover state. @melwoodard -- Please advise.

On mouse over:
![screen shot 2016-11-07 at 10 27 48 am](https://cloud.githubusercontent.com/assets/3453669/20064080/6f15b714-a4d7-11e6-9ce9-dbf8600f6464.png)

Non link text:
![screen shot 2016-11-07 at 10 30 13 am](https://cloud.githubusercontent.com/assets/3453669/20064084/718bf21a-a4d7-11e6-9fe8-cac50b6b6842.png)

**Comment by melwoodard** [comment]
@bshyong I think it would be better to use our baseline `<a>` text link style here - the lack of visual cues right now makes it difficult to tell these are links.
