### ISSUE TITLE
[HOMEPAGE] Stacked Navbars

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#3771]
@melwoodard // @angel - I think this is something that can be addressed soon after veterans day but we should think about addressing it very soon after.

![screen shot 2016-11-07 at 10 32 00 am](https://cloud.githubusercontent.com/assets/3453669/20064152/b8d5b9a8-a4d7-11e6-866d-403bc3843a81.png)

![screen shot 2016-11-07 at 10 31 13 am](https://cloud.githubusercontent.com/assets/3453669/20064156/bb5a42fc-a4d7-11e6-92d4-dcf6dc76fd21.png)

![screen shot 2016-11-07 at 10 49 19 am](https://cloud.githubusercontent.com/assets/3453669/20064197/ded1852e-a4d7-11e6-8101-8e73dce6aa3d.png)

**Comment by melwoodard** [comment]
Tracking the solutions to these issues in a few separate stories:

#4027 - Updates to notice banner (beta notice/VCL)
#4028 - Improve visual integration of account links and global nav
#4029 - HCA Apply page alert banner design update
#4030 - Rx alert banner design update

**Comment by jcmeloni** [comment]
Closing because I believe this is all subsumed by https://github.com/department-of-veterans-affairs/vets.gov-team/issues/681
