### ISSUE TITLE
[HOMEPAGE] heavier font weight in top banner

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#3780]
The text in the top banner & crisis line dropdown is a little light and hard to read at font-weight 300. Recommend bumping up to 400. @angel thoughts?

<img width="1279" alt="vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20068784/d383071e-a4ce-11e6-80b7-5ff3ee631838.png">

**Comment by dannychapman** [comment]
+1 on this.

**Comment by jcmeloni** [comment]
Addressed in PR https://github.com/department-of-veterans-affairs/vets-website/pull/4646  will close this issue after merge and not move this issue to vets.gov-team.

**Comment by jcmeloni** [comment]
Merged PR, will close after release.

**Comment by jcmeloni** [comment]
Released 17 Jan 2017
