### ISSUE TITLE
[HOMEPAGE] Mobile: crisis line carat icon doesn't change when overlay is closed

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#3781]
Because the crisis line panel on mobile opens in an overlay instead of a dropdown, the carat icon isn't being triggered to switch back to downward-facing when the overlay is closed.

<img width="398" alt="vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20068967/81f8c1d0-a4cf-11e6-842d-eb40ecec98cd.png">

**Comment by jcmeloni** [comment]
Confirmed still an issue.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
