### ISSUE TITLE
[HOMEPAGE] Search UI broken on mobile

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#3784]
At smaller breakpoints, search should revert to a button that opens an overlay containing the search field. 

@angel should this use the same button style that's currently live on vets.gov?

![img_3587](https://cloud.githubusercontent.com/assets/4106356/20069494/af3a9f4a-a4d1-11e6-8c4d-9fdf0cc88536.PNG)

**Comment by bshyong** [comment]
@angel @melwoodard I had this functionality in a previous iteration—do we have a final decision to revert to the previous behavior? 

this was the original mobile mockup 
https://cloud.githubusercontent.com/assets/103496/19365028/9c323ef2-9145-11e6-90e3-5e158f16b034.png

**Comment by angel** [comment]
@melwoodard @bshyong the search button style on the current site works for me.
