### ISSUE TITLE
Be more explicit about who needs employment info

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3787]
3) Employment history is only needed if they were a journeyman. I would not want people to gather all their employment records and not be asked about it. Suggest taking that off or putting that work history is only needed if you were a journeyman.

**Comment by mollyblake** [comment]
@cweber can we break that question into two parts? 

Have you ever held a license to practice a profession?  (if you click yes or, then it goes to next page)

Have you ever held a journeyman rating to practice a profession?  (if yes, employment history drawer opens) 

OR If only the journeyman rating matters, then can we take off the content about the license? 
Have you ever held a journeyman rating (for example, as a contractor or plumber) to practice a profession?

Yes - drawer opens
no - next page

**Comment by cweber** [comment]
So I think she's actually referring to https://www.vets.gov/education/apply-for-education-benefits-new/ where we suggest what people should have on hand.

**WHAT YOU NEED TO FILL OUT THIS APPLICATION**

- Social Security number
- Bank account direct deposit information
- Education, military, and employment history **(for example, journeyman or licensed plumber)**
- Basic information about the school you want to attend

**Comment by mollyblake** [comment]
@cweber can we just say for that bullet? 

"Education and military history"

**Comment by cweber** [comment]
I'm ok with that given it's likely a minority of applicants. Let's try it and see if the absence is a problem.

**Comment by mollyblake** [comment]
Sweet!
