### ISSUE TITLE
Remove "Apply for Education Benefits" from secondary pages

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3789]
- [ ] 5) The “Apply for Dependents Educational Assistance (DEA)” link does not take you to where you apply, but to an information page. At the top of the page is an “APPLY” button that takes you to the 22-1990 which is very misleading.

 - [ ] 7) Learn about NCS takes you to the information page, but again at the top the Apply button takes the person to the 22-1990. They would apply on the 22-1990N.

**On these pages:**
_Some of these pages should direct to the apply page in a different way or should direct to eBenefits/VONAPP. **Place new buttons below intro paragraph**_

- /education/gi-bill/transfer/  **(Links are embedded elsewhere on this page. Leave as is for now.)**
- /education/gi-bill/survivors-dependent-assistance/ [Apply on eBenefits](https://www.ebenefits.va.gov/ebenefits/vonapp)
- /education/other-educational-assistance-programs/call-to-service/ [Apply on eBenefits](https://www.ebenefits.va.gov/ebenefits/vonapp)
- /education/gi-bill/ **(This already has the buttons it needs)**
- /education/tools-programs/ **(No additional button)**
- /education/advanced-training-and-certifications/ [Apply for Education Benefits](/education/apply-for-education-benefits/)
- /education/work-learn/  [Apply for Education Benefits](/education/apply-for-education-benefits/)
- /education/other-educational-assistance-programs/  [Apply for Education Benefits](/education/apply-for-education-benefits/)

**Comment by cweber** [comment]
This is a solid point. I think we should be removing that 'Apply for Education Benefits' button from all of these secondary (tertiary?...) education pages. But that probably means we do need to link directly from that page to eBenefits/VONAPP.

@goldenmeanie Does that make sense?

Probably need to slog through those pages and see where else we should be directing more clearly to eBenefits/VONAPP.

**Comment by goldenmeanie** [comment]
Yes!

**Comment by cweber** [comment]
I am worried that it will be very difficult to track down all instances of this. The list I added above is everything with a direct link from /education and /education/apply-for-education-benefits

**Comment by leannammiller** [comment]
Let's discuss at the end of sprint planning today.

**Comment by akainic** [comment]
This is a larger vets.gov conversation about page navigation. To be discussed with vets.gov design and UX team. Moving to backlog for immediate term.

**Comment by cweber** [comment]
Closing. This is being handled at a global level by #4274.
