### ISSUE TITLE
Make sure legalese is covered in benefit election/relinquishment

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3792]
3) In the current VONAPP there is content regarding if the claimant relinquishes chapter 30, then they are only entitled to the amount of chapter 30 benefits they have remaining. We need to make sure that text is included.

- [ ] **“If electing chapter 33 in lieu of chapter 30, my months of entitlement under chapter 33 will be limited to the number of months of entitlement remaining under chapter 30 on the effective date of my election.”** 

It’s one of the bullets that was previously one of the 4 bullets on the benefits eligibility page (below). It could also be right after the chapter 30 on Benefits relinquishment (below). 

In addition, we need to put the following statement or similar after the 1607 selection on the relinquishment page. 

- [ ] **“(You are only eligible to relinquish 1607 if you received 1607 benefits for a semester, quarter, or term that included the date of November 24, 2015, or was the last semester, quarter, or term to end prior to November 24, 2015.)”**

**Comment by mollyblake** [comment]
@cweber  will the first one be a check box? An agreement of sorts?

**Comment by cweber** [comment]
I just put those checkboxes there so we can indicate that we've solved both of those problems.

My instinct is to make these statements appear below your relinquishment for either Chapter 30 or Chapter 1607 if you select one of them. (Similarly to how we handled the statement that appears below Chapter 33 on the previous page.)

cc @goldenmeanie

**Comment by mollyblake** [comment]
@cweber So under the respective line of content? 
<img width="564" alt="screen shot 2016-11-07 at 2 02 45 pm" src="https://cloud.githubusercontent.com/assets/16196072/20075782/e9dc910a-a4f2-11e6-9ef5-061aa6b9a94c.png">

**Comment by cweber** [comment]
Yes.

**Comment by goldenmeanie** [comment]
Le sigh.

**Comment by mollyblake** [comment]
@goldenmeanie Ditto

**Comment by cweber** [comment]
Yup.

**Comment by mollyblake** [comment]
@cweber 
If you pick the Post 9/11 GI Bill (Chapter 33) in place of MGIB-AD, you'll get benefits only for the number of months you had left left under MGIB-AD.

AND 

You can only give up REAP benefits if you had them for a semester, quarter, or term that ended on or before  November 24, 2015.

**Comment by cweber** [comment]
Much better!
First one looks great. 

For the REAP one, I'm not sure this part is coming through clearly: 

...or was the last semester, quarter, or term to end prior to November 24, 2015.

It's not just 'any time before that date' it seems to be the most recent term (at your school?) prior to that date. :-/

**Comment by mollyblake** [comment]
Yea, I was researching the whole REAP cancellation thing online ... very confusing. Standby

**Comment by mollyblake** [comment]
You can only give up REAP benefits if you had them for the last semester, quarter, or term that ended on or before November 24, 2015.

**Comment by cweber** [comment]
There it is! Sounds right to me.

**Comment by cweber** [comment]
@mollyblake Was just dropping this in and wondering if we can make the MGIB-AD one a bit shorter.

How about: 

If you choose to give up MGIB-AD, you'll get benefits only for the number of months you had left left under MGIB-AD.

![screen shot 2016-11-09 at 9 52 30 am](https://cloud.githubusercontent.com/assets/417657/20142409/9288d852-a662-11e6-8389-80f9d8380691.png)

@goldenmeanie, we already have an expanding situation going on there. For simplicity, maybe we just expose those lines outright?

Another alternative would be to expose each sentence and relinquishment date directly under the selection. Sounds more complicated to implement but I think tying the date to the specific selection would be better in the long run.

**Comment by goldenmeanie** [comment]
I like the pairing idea. I haven't looked at the logic on this yet. It doesn't currently differentiate between which button is selected does it?

**Comment by cweber** [comment]
I don't think so. I actually mocked that up in browser. Haven't opened the code yet.

**Comment by mollyblake** [comment]
We can shorten the paragraph at the top too if that will help: 

"If you're eligible for both the Post 9/11 Gi Bill and another program, like MGIB-AD, you'll have to choose which one you want to use. Once you apply for one or the other, your decision is irrevocable (meaning you can't change your mind).

**Comment by cweber** [comment]
We need to add new language to a couple of the selection options on the relinquishment page. These statements will appear upon selection, along with the Effective Date field. The effective date field should show up nested in an expanding group for each individual radio selection.

The example below shows what it would look like with **Montgomery GI Bill (MGIB-AD, Chapter 30)** selected. (Note that the blue bar would only expand from that radio button and accompanying text and fields.)

New language for this page includes:

**Top of page**
 - [ ] If you're eligible for both the Post 9/11 Gi Bill and another program, like MGIB-AD, you'll have to choose which one you want to use. Once you apply for one or the other, your decision is irrevocable (meaning you can't change your mind).

**Montgomery GI Bill (MGIB-AD, Chapter 30)**
 - [ ] If you choose to give up MGIB-AD, you'll get benefits only for the number of months you had left left under MGIB-AD.

**Reserve Educational Assistance Program (REAP, Chapter 1607)**
 - [ ] You can only give up REAP benefits if you had them for the last semester, quarter, or term that ended on or before November 24, 2015.

![image](https://cloud.githubusercontent.com/assets/417657/20147204/2f899b2a-a675-11e6-9a41-44dc80c7e4ce.png)
