### ISSUE TITLE
Irrevocable is 'irrevocable'. Sorry Molly.

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3794]
On the benefits relinquishment page, it states Once you apply for one or the other, you can’t change it. We need to include the word irrevocable. The current statement in VONAPP is “I am acknowledging that I understand that this election is irrevocable and may not be changed, and that failure to check one of the boxes below may cause a delay in the processing of this claim. (PLEASE CHECK ONLY ONE BOX FOR THE BENEFIT YOU RELIQUISH FOR CHAPTER 33.)” We have had legal issues with that word not being included. 

Could we just add, “**It is irrevocable.**” After the, Once you apply for one or the other, you can’t change it., so it would read: **Once you apply for one or the other, you can’t change it. It is irrevocable.**

**Comment by mollyblake** [comment]
@cweber how's this?

Once you apply for one or the other, your decision is irrevocable (meaning you can't change your mind).

**Comment by cweber** [comment]
Looks good to me. Changing to label to a frontend task.
