### ISSUE TITLE
Remove staggered behavior on va-cards

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#3797]
The va-card component shows a staggered layout on viewport widths of 994-1024px. It should use the 2-column layout here instead.

![img_0001](https://cloud.githubusercontent.com/assets/4106356/20073006/661104a4-a4df-11e6-826d-8f0e39b4207a.jpg)

**Comment by bshyong** [comment]
Looking into this—it's only happening on Safari, whenever the window size is somewhere within the range of the medium breakpoint
