### ISSUE TITLE
[HOMEPAGE] Hero design for blog & playbook pages

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#3807]
...Continued from #3768

**Comment by melwoodard** [comment]
@angel on larger screens it might be better to detach the gold line from the side, since there isn't an existing pattern anywhere else of bleeding elements in the body out to the edge like that.

Mobile looks good!

**Comment by angel** [comment]
@melwoodard true, so like this?
![image](https://cloud.githubusercontent.com/assets/103496/20081586/63a5b702-a505-11e6-9cf6-4701b85a34bd.png)

**Comment by jcmeloni** [comment]
@melwoodard @angel This doesn't seem to be the current style at all (see screenshot) -- is this old/moot or is there a bigger issue happening at the moment?

![screenshot 2016-12-06 13 39 00](https://cloud.githubusercontent.com/assets/347178/20938559/86ec3482-bbb9-11e6-938f-33496459937d.png)

**Comment by melwoodard** [comment]
This is on hold for now, pending discussion on the future of the blog & playbook.

**Comment by jcmeloni** [comment]
Closing; when it comes back around we'll make actionable issues in vets.gov-team
