### ISSUE TITLE
Enhancement: Hover explanation for initialisms

### ISSUE THREAD

**Issue by carlmjohnson** [department-of-veterans-affairs/vets-website#3829]
<img width="634" alt="screen shot 2016-11-08 at 2 47 16 pm" src="https://cloud.githubusercontent.com/assets/222245/20114431/54056e60-a5c2-11e6-9fd7-3b4b5a425a69.png">

When there's unclear initialism/acronym like "COE" in the screenshot above, it might be nice if you could hover over it to get the expanded version ("Certificate of Eligibility").

**Comment by ayaleloehr** [comment]
The pattern it looks like we're using explaining acronyms and content is "Learn More" links, which I think makes sense. See example below. Closing. 

![screen shot 2017-04-28 at 8 02 19 am](https://cloud.githubusercontent.com/assets/4719765/25527922/16d79e16-2be9-11e7-813d-f4fdc7d89de3.png)
