### ISSUE TITLE
Rx 401's right after login; wrong token?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3834]
When I login to prescriptions on staging, prescriptions often don't load and I'm just shown the page scaffolding with no data in it.  Looking at developer tools, the API request got a 401:

<img width="1174" alt="screen shot 2016-11-08 at 4 25 57 pm" src="https://cloud.githubusercontent.com/assets/4719765/20117938/aa3c6d52-a5d0-11e6-9a91-c4b3d2f3a6e0.png">

I then refreshed the page, and when I did that the same call succeeded:

<img width="1175" alt="screen shot 2016-11-08 at 4 28 33 pm" src="https://cloud.githubusercontent.com/assets/4719765/20117947/b9c0b0ee-a5d0-11e6-938e-3159782c672a.png">

#### **The most interesting thing here is that if you look at that second image, the authorization token is different than the first one.**

@saneshark can you test this out as well and see if you get the same thing?
@U-DON is it possible that this API call is being made before the userToken is updated with the new one?

**Comment by U-DON** [comment]
I've seen the 401 happen right after login. Just looking into this now, I think we load a function too early, so it gets `localStorage` when the page loads.
