### ISSUE TITLE
Header bar displays profile link and greeting when session expires

### ISSUE THREAD

**Issue by austin-martinez** [department-of-veterans-affairs/vets-website#3836]
My session expired and I refreshed the page, the header bar still displayed a greeting and profile/sign out links.

![screen shot 2016-11-08 at 1 44 38 pm](https://cloud.githubusercontent.com/assets/16657563/20118510/9a6545d2-a5b9-11e6-9ccc-b3b33cb1a8e3.png)

**Comment by crwallace** [comment]
This will be addressed with #3834.

**Comment by U-DON** [comment]
#3834 does reveal the issue, but it's also a problem specific to Rx that is separate from the 401 for `user`.
