### ISSUE TITLE
State search not working

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3841]
This is related to:
https://github.com/department-of-veterans-affairs/kudos-team/issues/218
https://github.com/department-of-veterans-affairs/kudos-team/issues/255

Currently, when you search for a state, it is zoomed in and search results shows as error. Technically it is not wrong. 

> For the state searches not showing results, it's happening because the state search makes the map center on the state, where there are not usually facilities. An exception is when a facility is located near the center of the state, e.g. Delaware. If a user zooms out, the facilities will come into view and show up.

@bshyong could change the logic so that when a user types in a state, the zoom level shows the whole state? Right now, it is zoomed in so much that a user probably doesn't know he/she is on the map. I don't know the exact zoom level right now but it's too high.

<img width="1088" alt="screen shot 2016-11-08 at 5 52 23 pm" src="https://cloud.githubusercontent.com/assets/13420618/20120769/27df9954-a5dc-11e6-99b0-7e189e93bb1b.png">

**Comment by NatalieEMoore** [comment]
For new York for example it shows nothing if you type in just New York.  Where did we land on this?

**Comment by bshyong** [comment]
We need to change the zoom level dynamically depending on the search string—I'm looking into it. This should be discussed in more depth post launch as there are quite a few cases to think about.

For example by typing in New York a user could mean either a state or a city..

**Comment by NatalieEMoore** [comment]
This issue is being solved on another issue.
