### ISSUE TITLE
Map in detail page not consistent with results map

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3844]
The map in the detail page does not have the appropriate pin with the facility type. Having a red pin may through a user off who is in a detailed page for cemetery or benefit and confuse it to be a health facility. Small detail that might throw people off. 

<img width="350" alt="screen shot 2016-11-08 at 5 49 32 pm" src="https://cloud.githubusercontent.com/assets/13420618/20121180/0cf26c14-a5de-11e6-9c4f-ee1c02accf2e.png">

**Comment by ayaleloehr** [comment]
@NatalieEMoore is this something you want done?  If so, can it get moved to vets.gov-team?

cc @leannammiller for awareness.

**Comment by NatalieEMoore** [comment]
I think this is important and will move it.  cc: @angel too, curious your thoughts here.

**Comment by NatalieEMoore** [comment]
moved to vets.gov-team issue number 2505.
