### ISSUE TITLE
Long service names in dropdown needs treatment

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3845]
Some of the service names are too long and overlaps with the dropdown icon in dropdown box. 

<img width="255" alt="screen shot 2016-11-08 at 5 50 35 pm" src="https://cloud.githubusercontent.com/assets/13420618/20121282/8b26334a-a5de-11e6-8c8e-d9b24961c47f.png">

For anything longer than 20 characters, _add"..."_

Example:
Vocational Rehabilitation Claims Assistance
becomes
Vocational Rehabilit...

@bshyong this is not a high-priority thing but lies somewhere in the middle.

**Comment by bshyong** [comment]
FYI we will need to create a custom dropdown to get the behavior. Right now the control is a native select, so we can't truncate the options like that. I'll investigate doing this in CSS but we might need to resort to a custom dropdown to get what we want
