### ISSUE TITLE
Change you are here icon

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3847]
Need change out older yellow icon for new icon. The white on yellow is most definitely not 508 compliant. 

<img width="114" alt="screen shot 2016-11-08 at 5 48 08 pm" src="https://cloud.githubusercontent.com/assets/13420618/20121484/c03d7024-a5df-11e6-8569-aec5e7164127.png">

<img width="119" alt="screen shot 2016-11-08 at 6 21 53 pm" src="https://cloud.githubusercontent.com/assets/13420618/20121561/3fa9fd14-a5e0-11e6-8d9f-194858473d0a.png">

**Comment by bshyong** [comment]
closed by https://github.com/department-of-veterans-affairs/vets-website/pull/3885
