### ISSUE TITLE
Add mental health number in detail page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3849]
In the detail page, primary number should be labeled "main" and under it should be "mental health" with mental health number. 

![desktop detail access to care](https://cloud.githubusercontent.com/assets/13420618/20121683/e548f05e-a5e0-11e6-9a8f-73bf9b06b7c7.png)

/cc: @patrickvinograd for mental health data.

**Comment by patrickvinograd** [comment]
Mental health clinic phone number is exposed in API as `"mental_health_clinic"` under the `"phone"` section.

**Comment by bshyong** [comment]
resolved by https://github.com/department-of-veterans-affairs/vets-website/pull/3852
