### ISSUE TITLE
Turn off Atlanta RPO by 14th/15th

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3854]
Effective the 28th Atlanta will no longer be processing Education Applications. Realignment are being switched over this weekend.

Stop creating a file for Atlanta as soon as possible. (By the 14th. End of 14th would be ideal.)

Everything created on the 15th should go to:

Georgia and Puerto Rico will be going to Muskogee

North Carolina and Virgin Islands to Buffalo.

**Comment by akainic** [comment]
@lihanli sounds like this is coming up. Can you start working on this?

**Comment by lihanli** [comment]
where should `APO/FPO AA` applications go

**Comment by cweber** [comment]
Uh oh. I don't know. 

I feel like we've collected this info from Shay before, but I don't have it on hand. Might need to reach out to Shay who is not in the office on Wednesdays. Or, @akainic might nows. Or...It sounded like maybe @alexose had talked to someone about this at some point.

**Comment by alexose** [comment]
Hrm, I'm not sure either...

**Comment by akainic** [comment]
I don't know off the top of my head. Adding @J-Quag to see if he knows, otherwise we're going to have to email Shay to ask her. Where are we sending those addresses now?

**Comment by lihanli** [comment]
atlanta

**Comment by J-Quag** [comment]
![image](https://cloud.githubusercontent.com/assets/15879513/20156721/86a4d67a-a69f-11e6-9f72-221108f85034.png)

**Comment by J-Quag** [comment]
Though we will need to update this because they are losing an RPO at the end of the month. Have we gotten that info yet?

**Comment by akainic** [comment]
That's what this ticket is for

**Comment by J-Quag** [comment]
Per Rodney, All Atlanta cases will either go to Buffalo or Muskogee. That being said, he doesnt ahve it in front of him at the moment and will provide in the AM.

**Comment by lihanli** [comment]
any updates? need to know which region for `APO/FPO AA`

**Comment by J-Quag** [comment]
@lihanli 

GA & PR -> Muskogee
NC, VI, APO/FPO AA -> Buffalo

**Comment by markolson** [comment]
@lihanli we can add this to https://github.com/department-of-veterans-affairs/vets-api/pull/503

**Comment by markolson** [comment]
Possibly https://github.com/department-of-veterans-affairs/vets-api/pull/514
