### ISSUE TITLE
Data on "Access to Care" issues.

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3861]
https://dev.vets.gov/facilities/facility/vha_675GG 
https://dev.vets.gov/facilities/facility/vha_674BY

This site's access to care data should only show primary care.  It should not say 0%, the entire line should be removed.  

![o percent](https://cloud.githubusercontent.com/assets/13317147/20150084/0682fda4-a682-11e6-9dec-f7483d3e59a6.jpeg)

Name of Facility: Lake Baldwin VA Clinic and Austin VA clinic.

0 % actually means N/A in this case, very different than 0%.  Please remove row.

**Comment by NatalieEMoore** [comment]
This should apply to any health facilities with access of care that have a 0% field.

**Comment by patrickvinograd** [comment]
API is returning `null` for these values so I believe this is a frontend issue, null should be mapped to 'N/A'
https://dev-api.vets.gov/v0/facilities/va/vha_675GG

**Comment by bshyong** [comment]
@NatalieEMoore unless you think keeping the row and adding "N/A" is better, I'm going to remove the entire row if the data `null`

**Comment by NatalieEMoore** [comment]
@bshyong please delete row.

**Comment by NatalieEMoore** [comment]
added Patrick to this one because the data is off right now and he is working on fixing it.
