### ISSUE TITLE
Map issue on IE for FL

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3867]
Jenny flagged that when using IE, images on the map display seem missing  -- little boxes with “x” where there should be image.

@jenny-h-l can you upload an image or provide more information?

**Comment by jenny-h-l** [comment]
it's working now -- after I confirmed i wanted to ignore the security warnings.

**Comment by bshyong** [comment]
Can somebody send a screenshot of the security warnings? This might be related to our use of Mapbox (3rd party map imagery vendor) but I'd like to confirm

**Comment by jenny-h-l** [comment]
yes, i think it's yoru vendor.
[11-9-2016 5-59-48 PM.pdf](https://github.com/department-of-veterans-affairs/vets-website/files/582126/11-9-2016.5-59-48.PM.pdf)
[11-9-2016 5-55-38 PM.pdf](https://github.com/department-of-veterans-affairs/vets-website/files/582125/11-9-2016.5-55-38.PM.pdf)

**Comment by bshyong** [comment]
cannot replicate—was this tested on a VA VPN connection?

**Comment by jenny-h-l** [comment]
no. it was tested in a VA office, using a VA computer

**Comment by NatalieEMoore** [comment]
is this different from the other PR about certificates?

**Comment by NatalieEMoore** [comment]
This seems like an isolated issue and we will further investigate.
