### ISSUE TITLE
Facility detail page issue in FF in FL

### ISSUE THREAD

**Issue by jenny-h-l** [department-of-veterans-affairs/vets-website#3872]
after searching for zip code 32669, selected a facility and it’s scrolled down part of the page already when I get there.

**Comment by NatalieEMoore** [comment]
@jenny-h-l can you add the link?

**Comment by jenny-h-l** [comment]
I clicked to https://dev.vets.gov/facilities/facility/vha_573QC
 from the 32669 results (after i zoomed out) and  here's the page [11-9-2016 5-11-22 PM FF Clinic Detail Page FL.pdf](https://github.com/department-of-veterans-affairs/vets-website/files/581995/11-9-2016.5-11-22.PM.FF.Clinic.Detail.Page.FL.pdf)

**Comment by bshyong** [comment]
@jenny-h-l I can't replicate this issue on Firefox—is it a screen size issue?

**Comment by jenny-h-l** [comment]
@bshyong bug no longer happening. don't know what changed.
