### ISSUE TITLE
[Homepage] Copy changes

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#3874]
The copy on the homepage is a little different what I have in the final design, and is likely from an older version. 

In the hero it should read: 
"Get the VA services you've earned." (No "that")

And the line below the stars should read
"Explore Services and Benefits"

cc @angel and @maryannbrody 
![vets gov-homepage-11-11-updated-copy2 2](https://cloud.githubusercontent.com/assets/1307774/20155196/c010b174-a698-11e6-838d-8d6e08e0b36e.png)

**Comment by emilyville** [comment]
I'd love to get this out by Veterans day, but I know there's a lot happening, so assigning to @crwallace to triage.

**Comment by maryannbrody** [comment]
Thanks for catching this @emilyville!

**Comment by emilyville** [comment]
Hey! This looks awesome. We missed the first edit, so reopening. This is not urgent, but let's remove the "that" in the hero so it says 

"Get the VA services you've earned.

**Comment by emilyville** [comment]
Reopening again so that we can fix the copy in the hero section.
