### ISSUE TITLE
Extensions missing on mental health phone numbers

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3878]
All phone number extensions are missing. @patrickvinograd checked the data and the extensions are there.

**Comment by patrickvinograd** [comment]
Looks like front end may not be using the right phone number. Example:
https://dev-api.vets.gov/v0/facilities/va/vha_640
(note mental_health_clinic phone number with extension)
```
{"data":{"id":"vha_640","type":"va_facilities","attributes":{"unique_id":"640","name":"Palo Alto VA Medical Center","facility_type":"va_health_facility","classification":"VA Medical Center (VAMC)","website":"http://www.paloalto.va.gov","lat":37.40174887,"long":-122.13987822,"address":{"physical":{"address_1":"3801 Miranda Avenue","address_2":null,"address_3":null,"city":"Palo Alto","state":"CA","zip":"94304-1207"},"mailing":{}},"phone":{"main":"650-493-5000 x","fax":"650-852-3228 x","after_hours":"650-493-5000 x60462","patient_advocate":"650-493-5000 x65544","enrollment_coordinator":"650-493-5000 x65804","pharmacy":"800-311-2511 x","mental_health_clinic":"6506149997 x 22234"},"hours":{"monday":"24/7","tuesday":"24/7","wednesday":"24/7","thursday":"24/7","friday":"24/7","saturday":"24/7","sunday":"24/7"},"services":{"health":[{"sl1":["MentalHealthCare"],"sl2":[]},{"sl1":["PrimaryCare"],"sl2":[]}]},"feedback":{"health":{"primary_care_routine":null,"primary_care_urgent":null,"specialty_care_routine":0.885,"specialty_care_urgent":0.774}}}}}
```
But https://dev.vets.gov/facilities/facility/vha_640 shows Mental Health number as same as Main phone number.

**Comment by bshyong** [comment]
Got it—should look like this. Do we know if all the phone numbers are in this format? If so I can do some formatting clientside to insert hyphens and make it look better

![screen shot 2016-11-09 at 3 06 56 pm](https://cloud.githubusercontent.com/assets/303289/20158271/32475604-a68e-11e6-80c8-ecfe16fe8c1a.png)

**Comment by bshyong** [comment]
formatted number

![screen shot 2016-11-09 at 3 12 20 pm](https://cloud.githubusercontent.com/assets/303289/20158407/f11c6876-a68e-11e6-8e3c-df37ccd10a05.png)

**Comment by NatalieEMoore** [comment]
When will this show up on dev link? @bshyong
