### ISSUE TITLE
Wrong Data for Mental Health Numbers 

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3879]
The data validators for mental health care phone numbers said that the numbers showing up now are all wrong.  It appears that the mental health number listed is actually the same as the main number. 
 
<img width="296" alt="screen shot 2016-11-09 at 6 01 57 pm" src="https://cloud.githubusercontent.com/assets/13317147/20158151/a2d42ec0-a6a6-11e6-8e16-1ebb2daba6e8.png">

Looks like that may be pulling from the wrong field but i'm not sure. @patrickvinograd and @bshyong please advise.

**Comment by patrickvinograd** [comment]
This is the same issue as #3878 - missing extensions - the extensions were missing because the wrong phone number was being displayed.
