### ISSUE TITLE
add option to delete search field.

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3882]
In mobile, could we add an x to delete a whole search field. Currently if there is a long address, users will have to manually delete everything. 

![screenshot_20161109-183916_720](https://cloud.githubusercontent.com/assets/13420618/20159037/432b4f20-a6ac-11e6-987a-a2ea19486d0f.png)

**Comment by bshyong** [comment]
@gnakm where should we put it? Will users accidentally click it and wipe out their search?

**Comment by gnakm** [comment]
@bshyong 

I think it should be okay as long as it only pops up when the field is clicked. 
Also, when it is clicked, could we have it so that the text cursor is at the (far right) end of the text?

**Comment by NatalieEMoore** [comment]
This was on an android phone.
