### ISSUE TITLE
Pop-up stuck at "Logging you in..." after entering username/password

### ISSUE THREAD

**Issue by jcmeloni** [department-of-veterans-affairs/vets-website#3887]
Please see closed issue https://github.com/department-of-veterans-affairs/vets-api/issues/460 for description and @omgitsbillryan's comment that "I was able to root cause to a XHR request race condition. If the response from /v0/user beats the response from /sessions/new?level=3 then the state.verifyUrl is read before it is ever set"

**Comment by ayaleloehr** [comment]
Happened again tonight at 12:59am Eastern. The popup stays frozen with "Logging you in..." as the text. I then opened my console in the parent window (didn't have it open beforehand unfortunately). The console looked like:

<img width="1175" alt="screen shot 2016-11-10 at 1 00 25 am" src="https://cloud.githubusercontent.com/assets/4719765/20168203/9e751d42-a6ee-11e6-8add-18a430c2e663.png">

**Comment by ayaleloehr** [comment]
Reopening this, as it just happened to me twice in staging.  Second time was at 9:23am Eastern. As requested last time, the console looks like the below, but warning that this console error popped up much earlier on page load than the pop up freezing, so I do not think it is related. 

![screen shot 2016-11-15 at 9 21 35 am](https://cloud.githubusercontent.com/assets/4719765/20309243/3e41b32e-ab15-11e6-9b23-52942d081bd5.png)

**Comment by crwallace** [comment]
@ayaleloehr -- Have you seen this recently? If so, what browser and which of our environments?

**Comment by ayaleloehr** [comment]
will log in from a bunch of browsers to test again. will report back in a bit.

**Comment by ayaleloehr** [comment]
Happens to me in chrome still on staging, logging in from the vets.gov homepage, and in both incognito and regular windows. Here is a screenshot including the same TypeError that in in that comment above (which I _do not_ believe is related to this but am posting for completeness). 

<img width="1344" alt="screen shot 2016-11-18 at 7 54 52 pm" src="https://cloud.githubusercontent.com/assets/4719765/20451572/015cfade-adc9-11e6-851b-e0fc6c9b1754.png">

When I then close the "logging you in" window and refresh the home page, I am not logged in. This is happening consistently to me right now, but only from the homepage. When I tried logging in from https://staging.vets.gov/healthcare/prescriptions it did work.

**Comment by ayaleloehr** [comment]
Then similarly, once I am logged in, when I try to log out, that window freezes as well. Happy to open a different issue for this if that's preferred. 

<img width="1244" alt="screen shot 2016-11-18 at 8 04 23 pm" src="https://cloud.githubusercontent.com/assets/4719765/20451680/4972c032-adca-11e6-939a-f138cad6fe11.png">

**Comment by eli-lewis** [comment]
A Veteran experienced this issue today and reported the following:  "Well I get stuck here.  It just spin at logging in and never moves forward.  Here is a screen shot.  This is after I created an account using my Premium DS login.  Every attempt to log in ends up here for me so far."
Screen shot below:
![login_freezing](https://cloud.githubusercontent.com/assets/23019174/20487260/b31a54de-afd0-11e6-876b-65e5dce2ad56.jpg)

**Comment by jcmeloni** [comment]
Just noting for the record that the above comment COULD be a different issue because of the path through using DS Logon. My gut tells me it isn't, because by this point they are bouncing back from id.me regardless of where they started, but noting it anyway.

**Comment by crwallace** [comment]
This has most likely been resolved. This was likely due to some `nil`s being passed on the api side and some other errors on the ID.me side.

Even though this should be fixed we are going to keep this open while we test through the weekend.

Please note if you see this again.

**Comment by jcmeloni** [comment]
I haven't heard more reports of this in testing.  Please reopen if it happens again.
