### ISSUE TITLE
Need to refresh /profile after successful proofing

### ISSUE THREAD

**Issue by jcmeloni** [department-of-veterans-affairs/vets-website#3889]
Please see original issue https://github.com/department-of-veterans-affairs/vets.gov-team/issues/415 by @staceylanger (I can also confirm after going through same process).

Please refresh /profile after ID.me modal closes subsequent to proofing flow.

**Comment by plusjeff** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/vets.gov-team/issues/416 (this issue came first, but the other one has steps to recreate, so keeping that one open)
