### ISSUE TITLE
VBA service data (services + website) missing

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3891]
Where are we with getting VBA services up?  They are available in the search field but not on details page.  Website also needs to be up.  @patrickvinograd

**Comment by bshyong** [comment]
The benefits facilities that I've checked have no website info and no service data https://dev-api.vets.gov/v0/facilities/va/vba_343p

**Comment by patrickvinograd** [comment]
Many of the smaller VBA facilities (the on-campus ones for example) have no website, but the regional offices do:
https://dev-api.vets.gov/v0/facilities/va/vba_314
Above link has services as well.

**Comment by bshyong** [comment]
this will be resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/3885; services not showing up was due to the change today in data keys. Dropdown options and Facility Detail pages are now updated
