### ISSUE TITLE
Allow a user to extend their session before expiration

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#3897]
Proposed feature: 

Introduce a timeout warning to tell a user they're about to be signed out 2 minutes before and give them the option to stay logged in. Something like:

For security, you'll be automatically signed out in 2 minutes. To stay signed in, click Continue. **CONTINUE**

To investigate:

- Are there any security implications in allowing this behavior that we should be aware of / need to get approval for?

**Comment by AnitraAppa** [comment]
Thanks for filing! Can further tweak text as needed once we know if this is a go/no-go security wise.

**Comment by jcmeloni** [comment]
Need to discuss feasibility before determining LOE and schedule.  Multiple sessions at play make this potentially something that cannot be solved easily or at least without more coordination among backend services.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
