### ISSUE TITLE
The service type drop down list is inactive on the Facilities Locator site

### ISSUE THREAD

**Issue by avrildavid** [department-of-veterans-affairs/vets-website#3899]
Site: https://dev.vets.gov/facilities
Environment: IE, Chrome, Firefox
Expected Outcome: Ability to select from a dropdown list of service types
Actual Outcome: Unable to select from a dropdown list - appears to be inactive
![service type drop down](https://cloud.githubusercontent.com/assets/23316175/20186472/2758608e-a73e-11e6-9ca3-04deb2c93d88.PNG)

**Comment by bshyong** [comment]
@avrildavid this is expected behavior. The service filter is only active for Benefits facilities

**Comment by NatalieEMoore** [comment]
closing this issue.
