### ISSUE TITLE
Select facility type drop down menu on the facility locator site doesn't reflect my selection - IE only

### ISSUE THREAD

**Issue by avrildavid** [department-of-veterans-affairs/vets-website#3900]
Site: https://dev.vets.gov/facilities
Browser: IE only - it worked in Chrome and Firefox
Expected outcome: Ability to select an individual drop down option, have it stick, and then have the option reflected on both the map and the sidebar list
Actual outcome: The "select facility type" drop down menu doesn't reflect my selections in the dropdown itself, on the map or the sidebar. I'm unable to get an individual option to stay highlighted in the drop down menu (so can't take a screenshot of it).

**Comment by bshyong** [comment]
What version of IE and Windows are you using? The dropdown is working for me in Windows 10 and IE 11.

video: http://recordit.co/ohS70P5aTC

**Comment by patrickvinograd** [comment]
At some point during testing did you select type=Benefits and select a benefits service to filter on? This could be the same issue as #3903.

**Comment by avrildavid** [comment]
Hi Patrick,

Yes – the feature works in Chrome and Firefox when you select Benefits to filter on. In IE 11 I’m unable to filter on Benefits or any other option, so can’t check this part.

Avril

**Comment by NatalieEMoore** [comment]
I'm on IE 11 and it doesn't work. @bshyong @patrickvinograd

**Comment by avrildavid** [comment]
IE 11 and Windows 7 version 6.1

**Comment by NatalieEMoore** [comment]
I'm still having this issue on IE on the va desktop computer...

**Comment by NatalieEMoore** [comment]
@bshyong This is still a bug and a fairly big issue because most stakeholders use IE to access the site.

**Comment by bshyong** [comment]
Does anything show up in the javascript/developer console when clicking? I don't have a native Windows machine to test but I've been unable to replicate that bug on IE 11 and Windows 10 in Parallels

http://recordit.co/ohS70P5aTC
