### ISSUE TITLE
Chrome - Facility Type gets stuck as Benefits, later selections/searches don't reflect new type.

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-website#3903]
I was clicking/panning around/paging through results with all types selected. I then tried selecting Benefits facilities and filtering by type. This worked fine. Then I tried selecting Cemetery or Health facility type but the map and result list were stuck on the benefits search. 

Sentry indicates the problem is that the "services" param is sticky and is not getting cleared out when you go back to select a different facility type. It is showing InvalidFieldValue exceptions where a benefits services filter is specified but type=health or cemetery:
```
services[]:	VocationalRehabilitationAndEmploymentAssistance
type:	        health
```

**Comment by patrickvinograd** [comment]
It's possible #3900 is the same issue if the

**Comment by NatalieEMoore** [comment]
@patrickvinograd can you label high/low priority and/or launch blocker?
