### ISSUE TITLE
How to display VBA facilities that are appointment only.

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3906]
Billy showed me some of our data, and we came across Scott Air Force Base (below) and noticed that the excel doc's comment column info/hours are not showing for this facility.  This location is by appointment only, which is why there are no hours of operation.  We also noticed that another facility is not displaying the comment hours, so we assume this is a global issue.  

![airforce](https://cloud.githubusercontent.com/assets/13317147/20189509/7f67408a-a74b-11e6-8b6b-62b973eeeded.jpg)

**Comment by NatalieEMoore** [comment]
currently VBA facility hours that are "appointment only" are showing as always closed. For those with no hours, can we just have this message:  This facility is by appointment only.  Please call first to make an appointment.

**Comment by patrickvinograd** [comment]
I think we should consider always showing the Comments field if it is non-empty - there is so much variation that would make it hard to determine "No hours". Some have CLOSED every day, some have CLOSED every day but Monday but then the comments say "Only open 3rd monday of the month", etc.

**Comment by patrickvinograd** [comment]
Here is a query showing just facility name/hours/comments so you can see the range of data:
https://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VBA_Facilities/FeatureServer/0//query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=Facility_Name%2CMonday%2CTuesday%2CWednesday%2CThursday%2CFriday%2CSaturday%2CSunday%2CComments&returnGeometry=true&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=pjson&token=

**Comment by NatalieEMoore** [comment]
okay sounds good to me, is that possible?  if no hours are shown, please just include comment field?

**Comment by patrickvinograd** [comment]
I think it just needs to be "display comments field if non-empty", across the board for all VBA facilities. FWIW 70% of VBA facilities have no comments, the rest are all over the map in terms of whether they have some hours some days, no hours, etc.

**Comment by bshyong** [comment]
Agreed. Here's what the notes field looks like for one of the facilities

![screen shot 2016-11-10 at 11 58 16 am](https://cloud.githubusercontent.com/assets/303289/20192086/2c6f6186-a73d-11e6-96cd-2cca1a35200f.png)

**Comment by bshyong** [comment]
![screen shot 2016-11-10 at 12 44 00 pm](https://cloud.githubusercontent.com/assets/303289/20193570/618db9f2-a743-11e6-99c7-9b169ad3ed31.png)

**Comment by NatalieEMoore** [comment]
This is a data issue and I need to talk to @staceylanger about how to show this.  Will report to @bshyong once I have an update. 

@patrickvinograd do you know how many facilities have no hours data but just put info into the comment field?

**Comment by staceylanger** [comment]
If we don't have meaningful hour data - we should not display the entire Hours section for that facility. Is that feasible @bshyong @patrickvinograd?

**Comment by bshyong** [comment]
@staceylanger @crwallace where do we draw the line for meaningful/non-meaningful? 

For example the Scott Air Force Base facility is appointment only, so all of the hours are blank.

**Comment by staceylanger** [comment]
I don't know enough about what the data looks like. But in the example above, if hours are blank in the data, do not show the hours section. Let me know if there are more scenarios anyone knows about and we can decide quickly.

**Comment by bshyong** [comment]
possible values for those fields
- byAppt
- AppointmentOnly
- '-'
- CLOSED
- '' empty string
- 8AM-5PM and variants thereof

It's incredibly difficult to correctly choose when to show/hide the hours data or define what is meaningful because of the variance in data. We'd want to look at all of the field values in the data set, but even then, if the facilities update their data in a different format, that could throw us off on the front end side//

**Comment by patrickvinograd** [comment]
There are 10 facilities that have no hours information at all (not even "Closed"). Those facilities also have no "comments" section, and 9/10 have no phone number!
http://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VBA_Facilities/FeatureServer/0/query?where=Monday%3D%27%27+and+Tuesday%3D%27%27+and+Wednesday%3D%27%27+and+Thursday%3D%27%27+and+Friday%3D%27%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=Facility_Name%2CFacility_Number%2CPhone%2CMonday%2CTuesday%2CWednesday%2CThursday%2CFriday%2CSaturday%2CSunday%2CComments&returnGeometry=true&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=pjson&token=

There are only 3 facilities that have "Closed" for 7 days a week. They all have explanatory comments:
http://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VBA_Facilities/FeatureServer/0/query?where=Monday%3D%27closed%27+and+Tuesday%3D%27closed%27+and+Wednesday%3D%27closed%27+and+Thursday%3D%27closed%27+and+Friday%3D%27closed%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=Facility_Name%2CFacility_Number%2CPhone%2CMonday%2CTuesday%2CWednesday%2CThursday%2CFriday%2CSaturday%2CSunday%2CComments&returnGeometry=true&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=pjson&token=

There are many facilities that are open one day a week and are "closed" the other days. That's a harder query to do. I'd guess in the low double digits.

**Comment by patrickvinograd** [comment]
Other variants I've observed in hours data:
- "NONE"
- "BY APPOINTMENT"
- "42586" (?!)
