### ISSUE TITLE
VA showing no facilities on IE 11

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3908]
![va](https://cloud.githubusercontent.com/assets/13317147/20189850/ebf98630-a74c-11e6-894c-dbfa8a8e9055.PNG)

https://dev.vets.gov/facilities/?zoomLevel=6&page=1&address=virginia&location=38.00234,-78.224935&context=Virginia, United States 

tried zooming out and in

**Comment by NatalieEMoore** [comment]
@patrickvinograd this may be related to the API being down.

**Comment by patrickvinograd** [comment]
We suspect this was a blip in vets-api service availability in dev/staging.

**Comment by NatalieEMoore** [comment]
Yes this is fixed although there are other zoom issues but I will close this.
