### ISSUE TITLE
Middle of Map, when clicked on says "You are here"

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-website#3911]
Browser: IE 11
Expected Result: Nothing(?)
Actual Result:
  When searching and moving the map around, if you click in the center of the map a new icon will appear with the pop up text of: "You are here," even if that is not actually your current location.

![image](https://cloud.githubusercontent.com/assets/15879513/20190434/69a052b0-a74f-11e6-8087-74fbd2395147.png)

**Comment by NatalieEMoore** [comment]
Not sure that this is a bug, will continue to investigate after launch.

**Comment by J-Quag** [comment]
Yeah, I'm unsure. I just thought it was weird if I moved the map and it said I was at that particular location, but I wasn't.

**Comment by NatalieEMoore** [comment]
@gnakm @crwallace we may want to further investigate this.  If you think it's fine as is we can close this.

**Comment by gnakm** [comment]
No let's keep this issue open but talk about it at our 2pm meeting. Adding to agenda. It's not usual to have it move but might not be the appropriate UX for our particular purpose.

**Comment by NatalieEMoore** [comment]
@bshyong @gnakm this can be closed out because we are changing the map and removing panning, right?

**Comment by bshyong** [comment]
Yes, closed
