### ISSUE TITLE
NCA hours of operation [launch blocker]

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3914]
![logoissuesie](https://cloud.githubusercontent.com/assets/13317147/20191222/9a9ac51e-a752-11e6-848a-45312448269b.PNG)

NCA hours not showing which is fine because they have a general sun up to sun down.  Will update once I have content message for how we can show these.

**Comment by bshyong** [comment]
I'll add as soon as we know what we want to show as the message

**Comment by plusjeff** [comment]
@NatalieEMoore : Assigning to you for updates on what to put in here. cc @staceylanger

**Comment by NatalieEMoore** [comment]
@bshyong I can close this PR right?  Looks like hours of operation got completely removed (for now) on the site since there is no data.

**Comment by bshyong** [comment]
Yes, there is no data so the section is hidden
