### ISSUE TITLE
some mental health numbers have "-" (dash) and others are like this 2309234209

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3917]
![mhnumbers](https://cloud.githubusercontent.com/assets/13317147/20191380/3e2d0db8-a753-11e6-947f-66686ef10594.PNG)

please - all MH numbers

**Comment by bshyong** [comment]
This is happening because of inconsistent formatting between the various facilities—some already have dashes, some look like this, some have extensions.. Fixing in https://github.com/department-of-veterans-affairs/vets-website/pull/3918
