### ISSUE TITLE
Signout link not working in IE

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#3926]
Logout function does not trigger in IE 11 on Windows 7 when clicking singout link.

**Comment by bshyong** [comment]
Having trouble replicating this in IE 11 on Parallels, but I'll try to see if I can get a hold of a Windows machine somewhere to see what's happening.

If somebody can click that signout with the dev console open on IE it might give us some clues...

Also on a related note, BrowserStack is free for open source: I wonder if we can get a free account to help with some of this multiple browser testing
https://www.browserstack.com/accounts/subscriptions
