### ISSUE TITLE
facilities search for "53130" returns result in Brazil

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-website#3942]
https://www.vets.gov/facilities/?address=53130

53130 is a valid zip code in Wisconsin, but the map centers on a location in Brazil. This is an issue in MapBox's geocoding service, so we should file an issue with them, but if there's any way to hint the geocoding to be US-centric maybe we consider that as well.

**Comment by NatalieEMoore** [comment]
@patrickvinograd when you say hint to geocoding do you mean reach out to GeoBISL?  I can connect you all.  

Do we want it to be US-centric if we are realizing some facilities have sites outside of continental USA?

**Comment by patrickvinograd** [comment]
@NatalieEMoore No, I mean hint to the API call that we make to Mapbox to do reverse geocoding - i.e. letting it know you are generally in the US vs. Brazil. Ben was able to restrict it to US/PR/VI, apparently a few other locations are necessary. 

Nothing to do with GeoBISL.

**Comment by NatalieEMoore** [comment]
Okay, thanks.  

Yes, on the call today with the call center one of them put in their address and it took them to France.  This issue will eventually address this right?

**Comment by bshyong** [comment]
@NatalieEMoore yes this will fix the issue. We need a list of all country codes that are eligible for a user to search.

So far I have
- US 
- PR puerto rico
- VI virgin islands

Let me know if there are other ones.

**Comment by patrickvinograd** [comment]
You can wait for official response from stakeholders but based on scanning the range of state codes listed in the data:
- VBA facilities in Puerto Rico, US Virgin Islands, Guam, and Philippines
- VHA facilities in American Samoa, Guam, Northern Mariana Islands, Philippines, and US Virgin Islands
- NCA facilities in Puerto Rico

**Comment by NatalieEMoore** [comment]
VHA= American Samoa, Guam, Northern Mariana Islands, Philippines, US Virgin Islands and Puerto Rico
NCA= Puerto Rico
