### ISSUE TITLE
Website links in search results

### ISSUE THREAD

**Issue by bshyong** [department-of-veterans-affairs/vets-website#3945]
![slack for ios upload](https://cloud.githubusercontent.com/assets/303289/20234824/659d8e06-a837-11e6-892f-b3fafe8c07b7.jpg)

Website links are not working in mobile/icon is not showing up

@gnakm were website links supposed to show up in search results?

**Comment by gnakm** [comment]
@bshyong Yes website links should be showing up on search results.

**Comment by NatalieEMoore** [comment]
Currently they are showing up for all facilities on mobile but the link is broken and there isn't an icon.

**Comment by NatalieEMoore** [comment]
I don't know if they need to be there at all.  @gnakm do you want them there for a reason?

**Comment by gnakm** [comment]
@NatalieEMoore No I thought it was a requirement but i guess now. How about we keep it out of search results and only have it in detail page?

**Comment by NatalieEMoore** [comment]
That's what I think we should do.  At least for now. 

@bshyong is this represented in the PR?

**Comment by gnakm** [comment]
Also, hours of operations should no longer be here. It's not on desktop but on mobile. 

So for @bshyong, 
- [ ] Take out website link
- [ ] Take out hours of operations for mobile
- [ ] Make sure icons are aligned with each other; make sure text are aligned with each other
- [ ] Add the word number next to main so it says, "Main number:"
