### ISSUE TITLE
Change main to primary care number?

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3950]
@NatalieEMoore Should change Main number to primary care? If not, we should add "number" next to main. Something about just main being there looks strange to me. Would love to hear your thoughts. 
<img width="527" alt="screen shot 2016-11-14 at 8 57 31 am" src="https://cloud.githubusercontent.com/assets/13420618/20267409/9c4cd796-aa48-11e6-9870-efae3b9f625b.png">

**Comment by NatalieEMoore** [comment]
It's not the primary care number so that won't work but I like your idea of having Main Number!

**Comment by NatalieEMoore** [comment]
Maybe we should also have mental health number then?

**Comment by NatalieEMoore** [comment]
@gnakm Can we have it say Main Number and then Mental Health Number?  @bshyong can you connect with @gnakm on this?

**Comment by bshyong** [comment]
@gnakm let me know what the decision is and I'll add it in. I'm not sure if the entire phrase "mental health number" can fit on one line in which case there might be overflow issues.  Would Mental Health # work if it's too long?

**Comment by gnakm** [comment]
We are going with:

Main number
Mental health

**Comment by NatalieEMoore** [comment]
This can be closed out right? @bshyong @gnakm
