### ISSUE TITLE
Tab design needs to be consistent

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3953]
This is currently what it looks like on my android phone:
![screenshot_20161114-120335_1024](https://cloud.githubusercontent.com/assets/13420618/20274401/77588498-aa62-11e6-9af3-9ce04fac57fa.png)

Other tabs on Vets.gov looks like this:
<img width="274" alt="screen shot 2016-11-14 at 12 02 34 pm" src="https://cloud.githubusercontent.com/assets/13420618/20274411/7d49ff12-aa62-11e6-8b8f-127a5a28ec71.png">

@NatalieEMoore (or anybody) Could you check if this is also happening on your iphone?

**Comment by ayaleloehr** [comment]
pinging @NatalieEMoore to follow up.

**Comment by NatalieEMoore** [comment]
@phiden can you look into this?  On my iPhone I think it is showing up correctly.

**Comment by phiden** [comment]
Looks correct to me on iOS Chrome & Safari.

**Comment by NatalieEMoore** [comment]
okay, just need to see if it's still happening on an android phone and if not, i'll close this.

**Comment by NatalieEMoore** [comment]
@gnakm said there are still bugs.

**Comment by gnakm** [comment]
The last bug got fixed but now there are new bugs!

- [ ] Tab highlight alignedment
The blue highlight in the tab is a little higher than the other tab. All the tabs should be aligned.
![image](https://cloud.githubusercontent.com/assets/13420618/24218334/49accd9e-0f19-11e7-85fa-ae3b465890b5.png)

- [ ] The dropdown is showing something behind it
![image](https://cloud.githubusercontent.com/assets/13420618/24218406/9d383c0a-0f19-11e7-9ac0-fbde786cb447.png)

- [ ] All should be aligned with All Facilities 

![image](https://cloud.githubusercontent.com/assets/13420618/24218490/e4810e52-0f19-11e7-8853-f7a91a98a63c.png)

**Comment by gnakm** [comment]
@NatalieEMoore @ayaleloehr who is the engineer I should assign this to?

**Comment by ayaleloehr** [comment]
Letting @NatalieEMoore take that.
