### ISSUE TITLE
Profile page thinks I'm signed in when I'm not

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3954]
After logging in, then getting timed out, then going to the profile page, this is what it looks like:

![screen shot 2016-11-14 at 2 04 55 pm](https://cloud.githubusercontent.com/assets/4719765/20278624/75161716-aa73-11e6-9af0-b5238108b5f3.png)

In the top right, there is "hello | profile | sign out" as if I am signed in, but I'm not actually signed in anymore.  These should instead say "Sign in | Register".

**Comment by melwoodard** [comment]
Right now if I go directly to /profile while logged out, I see the profile page instead of the sign up roadblock.

![profile](https://cloud.githubusercontent.com/assets/4106356/20450415/46d4e3c0-ada5-11e6-823a-7c8fb5fcbf01.png)

**Comment by ayaleloehr** [comment]
I am now able to reproduce Mel's comment above as well.

**Comment by ayaleloehr** [comment]
This looks like 2 issues now actually. one is what Mel posted. Let's use this issue to track that. I opened https://github.com/department-of-veterans-affairs/vets-website/issues/4046 to track the separate issue of the header still thinking a user is signed in after signing out.

**Comment by crwallace** [comment]
This was something that didn't get caught in PR review. I changed `authRequired={1}` to 0 while testing so no login was required. This has been resolved.
