### ISSUE TITLE
Search results showing wrong information

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3955]
![new orleans new york](https://cloud.githubusercontent.com/assets/13317147/20279052/04123d5e-aa75-11e6-9066-6fa04a1ce9ce.PNG)

Typed in New York City and got a result in New Orleans.

**Comment by NatalieEMoore** [comment]
Similar issue happened for @gnakm

**Comment by gnakm** [comment]
<img width="1054" alt="screen shot 2016-11-14 at 2 16 35 pm" src="https://cloud.githubusercontent.com/assets/13420618/20279628/37d850a4-aa77-11e6-95e1-e0fe56c47846.png">

**Comment by bshyong** [comment]
@patrickvinograd the New Orleans result is really strange; here is the bounding box API call 

https://api.vets.gov/v0/facilities/va?bbox[]=-74.20783996582033&bbox[]=40.58475654701271&bbox[]=-73.75396728515626&bbox[]=40.94360177170975&page=1

The PA results for Montana seem like a different issue; looking into it.

**Comment by patrickvinograd** [comment]
Yeah the New Orleans lat/long in the GIS database is straight-up wrong. @NatalieEMoore can you flag this one to the VBA data owner:
https://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VBA_Facilities/FeatureServer/0//query?where=Facility_Number%3D%27321%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=*&returnGeometry=true&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=html&token=

https://www.google.com/maps/place/40%C2%B043'18.7%22N+73%C2%B059'07.5%22W/@40.7218543,-74.0554665,12z/data=!4m5!3m4!1s0x0:0x0!8m2!3d40.7218543!4d-73.9854287

**Comment by NatalieEMoore** [comment]
@patrickvinograd yeah will do that now.  Is the address in the data wrong or is the problem with geocoding?  Trying to figure out if it's a VBA issue or a GeoBISL issue.

**Comment by patrickvinograd** [comment]
The address is fine.

**Comment by NatalieEMoore** [comment]
okay emailed GeoBISL.

**Comment by NatalieEMoore** [comment]
I think GeoBISL fixed that one specific issue.  @patrickvinograd does it look correct now?  @bshyong any updates on the Montana issue?

**Comment by patrickvinograd** [comment]
Yes, the New Orleans location looks correct now.

**Comment by NatalieEMoore** [comment]
Great, I would close this but I think the Montana issue is still being worked on?

**Comment by bshyong** [comment]
Let's close it—the Montana issue is due to something else; the previous query was probably in pennsylvania and it didn't refresh. We can reopen if it happens again but I cleaned up the logic and do not see that issue any more
