### ISSUE TITLE
Facility Locator should always show minimum of 10 results

### ISSUE THREAD

**Issue by bshyong** [department-of-veterans-affairs/vets-website#3956]
Related to issue here: https://github.com/department-of-veterans-affairs/vets-website/issues/3948

There are a couple of cases where entering a search result, e.g. a rural area or a zip code does not result in any facilities being shown. The solution we discussed is to disable searching via panning/zooming, making the only input the search box. The map will be purely for displaying where the facilities are in relation to each other.

@patrickvinograd what do we need to do to always surface a minimum of 10 results? If a bounding box call results in no facilities, could we show the 10 closest facilities to the center of the box?  

tagging @NatalieEMoore @gnakm @crwallace for awareness

**Comment by patrickvinograd** [comment]
We could change the API semantics to show n results from center...but then how do you deal with pagination - just keep expanding out from center forever?

Can the frontend do adaptive zooming - so if the default zoomlevel doesn't include any results, zoom out until it does?

**Comment by bshyong** [comment]
@patrickvinograd I considered adaptive zooming but it seems non-optimal as we might need to send off 3-4 sequential requests. I guess it just feels finicky to me but I'm going to explore further to see how it behaves. 

Does it break API semantics to show results even if there are none in the queried bounding box?

**Comment by patrickvinograd** [comment]
Well, in the sense that we called the parameter "bounding box" it implies that we're returning results within those boundaries and no more. That said we can redefine the semantics...it would make less sense as an abstract/generic API but being practical, the semantics should be driven by the requirements of the front end. 

As currently designed, I will have to do adaptive/repeated querying to the GIS backend to find the desired minimum number of results although it seems like I will be doing that one way or another, whether it's driven by multiple frontend requests or a single one. Just pointing out that there's no way to request this natively from the GIS backend.

**Comment by crwallace** [comment]
@bshyong -- Where did we get the number 10 from? I think that might not make sense from a user perspective. For instance: I just looked at Billingsley, AL (zip: 36006) and upon zooming out the 10th health facility in the list was 61 miles away. I think that it makes sense to have at least 1 that falls in the query but I am not sure that a user would see much need in driving past all other locations to the one that was 61 miles from them so I am not sure that displaying it is necessary. Also, I think many rural users are used to making searches closer to major towns/cities so I would like to get some user feedback about needing more results before we do that. Thoughts @NatalieEMoore ?

**Comment by NatalieEMoore** [comment]
- When you say 1 that falls in the query what do you mean @crwallace ?

- We need to move away from having results show only in the zip code entered and toward having a certain number of results show, regardless if it's in the zip code.

- We can make it less than 10, that number was just randomly picked. What do you suggest @crwallace ?

- What has been happening is a user enters a zip code and it shows no results.  That shouldn't ever happen.  If you enter a zip code it should still show the closest places, even if it's outside of the zip. 

- This happened on the phone call today with the call center, someone entered a Manhattan zip and it showed no results.  It's not just a rural issue.

**Comment by NatalieEMoore** [comment]
Here is another example:

![zipissue](https://cloud.githubusercontent.com/assets/13317147/20322275/6c01375e-ab46-11e6-8be3-05f33c63c143.PNG)

**Comment by bshyong** [comment]
@natalieEMoore @crwallace it is finicky to do the 10 results from the front-end; if we want to do that we ideally to do it on the backend. Regardless, we will need multiple requests with larger and larger bounding boxes or restructure the API to use a location instead of bounding boxes (and talk about pagination and other issues)

Let's try the adaptive zooming that I implemented on this branch and reassess the user feedback. If there are no results, the map will automatically zoom out until there are results. We can change the threshold from >1 to >10 if we like
