### ISSUE TITLE
GI Bill Comparison Tool Integration

### ISSUE THREAD

**Issue by typesend** [department-of-veterans-affairs/vets-website#3960]
The overall plan is to replace the GIBCT Rails app by implementing its backend and frontend within vets-api and vets-website respectively. This will eliminate header/footer synchronization problems and the need to maintain a separate standalone rails app. GIDS will likely still publish data to an isolated database but this is still being discussed.

*Related issues*
department-of-veterans-affairs/gi-bill-comparison-tool#438
department-of-veterans-affairs/gibct-data-service#160

**Comment by jcmeloni** [comment]
@plusjeff This seems like it should be labelled somehow, but not sure how you'd like it.

**Comment by typesend** [comment]
_Recent discussions have generated a number of proposed enhancements. Comments welcome._

### Data Previewing
- A "preview mode" feature will be implemented in the React app.
  - A url param determines the version of the data to display.
  - There will be an obvious visual indication that preview mode is active and showing which version of data is being served.
  - Just like the Preview app, the intention is that preview/experimental data is only going to be reviewed by a few known people. However, viewing it will no longer require login/authorization.
- The Preview app instance and its database will be decommissioned.
- _Benefits: fewer apps and databases to operate, data display logic in one place_

### Data Publishing
- The Data Service app will cease injecting data directly into external databases.
- Instead, vets-api will rely on postgres to maintain a read-only connection to the data service database (using the postgres_fdw foreign data wrapper extension).
  - Specifically, the data_csv table and a new table containing constants used during benefit calculations will be loaded as **foreign tables**
  - vets-api won't serve data out of those tables directly, instead copying the data to its own local tables when a new release is created. (Because performance, versioning.)
- Publishing data will now be triggered by the Data Service app calling a new endpoint in vets-api
- _Goals: keep vets-api database isolated and secure, simplify how data gets shoved around_

### Data Versioning
- Inside the Data Service app, a `data_version` auto-incrementing column will be added to its `data_csv` table. New data sets will be appended to this table (instead of replacing historical data.) The same pattern will be applied to the constants table. @mphprogrammer 
- Vets API will be responsible for tracking when data and constants are actually published (when the endpoint for that purpose is called)
- The goal is to be able to answer two questions (with little additional development work): "What data was displayed by the website on [date] at [time]?" and "What constants were used as the basis for benefit calculations at that time?"

### Content and Design
- We're also taking this opportunity to improve content, look and feel. (See department-of-veterans-affairs/vets.gov-team#508)
@melwoodard @emilyville 

Creating a separate issue to track the devops implications of this. @patrickvinograd

**Comment by patrickvinograd** [comment]
I'm on board with this with the possible exception of the copying data from GIDS to vets-api tables and the triggering mechanism for that. With the AWS restriction that the foreign data wrapper must point to the same db instance (see linked devops issue), I wonder how much performance is an issue.  Could GIDS just update an "active_version" table and vets-api read that to determine which data to select?

**Comment by typesend** [comment]
@patrickvinograd Good points. GIDS and vets-api are developed and deployed independently, though. We lose that property of the system if we start sharing tables directly. A GIDS schema change could break the entire GIBCT until the vets-api schema is also updated.

That said, I am open to serving Preview data out of the GIDS foreign tables because it is low traffic and errors there shouldn't be able to take down public-facing features. (I admit it wouldn't be the end of the world if Preview Data requests returned 500s until schema changes in GIDS could be reflected in vets-api.) IOW, we could have Preview Data come from the GIDS tables and Published Data come from the GIBCT tables.

**Comment by patrickvinograd** [comment]
Thinking through deployment implications.

- It looks like there is a rails Gem that helps with foreign data wrapper migration, so it can be done mostly in line with standard rake workflow and not need a lot of special casing.

- Developers will need to have the GIDS schema installed in their local database in order for vets-api to work, since vets-api's `db:migrate` step will fail to set up the foreign server/table if not present. Not a huge burden but worth calling out. I wonder if we can stash a local copy of the GIDS schema in vets-api, and have a rake task to install it, since it will likely not change very often. Would be suitable at least for people not directly touching this part of vets-api.

- Devops deployments will now have GIDS deployment as a precondition of vets-api deployment. But given how infrequently we have a green-field deployment I don't think this is a big issue.

- Schema changes in GIDS will need to be managed. Generally not too different from ordinary db/application schema changes - we will need to ensure that existing columns are not renamed/removed unilaterally from GIDS. I think adding columns will be okay - GIDS can deploy and add column, then vets-api can be redeployed with a db migration that consumes the new column.

**Comment by patrickvinograd** [comment]
Also while I know implementation of the above approach is under way, I wonder whether having GIBCT pull data from GIDS via a REST API would not be a better architecture. I feel like I saw a ticket by @mphprogrammer or @ayaleloehr a while back suggesting this, but can't find it to see whether it was discussed at any length. 

In this model GIDS would be much the same, but would expose an additional REST endpoint exposing the data. GIBCT would, like much of the rest of vets-api, become a pass-through to a backing web service, just in this case one that we happen to own. Presumably GIDS would have separate preview and production data endpoints, which could be versioned to insulate against schema changes.

**Comment by ayaleloehr** [comment]
@saneshark should this still be left open or can it be closed?

**Comment by saneshark** [comment]
Yes.
