### ISSUE TITLE
Search form input needs a label

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3965]
Need to change:

 `<input autocomplete="off" type="search" name="query">`

to:

 `<input autocomplete="off" type="search" name="query" id="search-field-small">`

**Comment by jcmeloni** [comment]
Addressed in PR https://github.com/department-of-veterans-affairs/vets-website/pull/4646  will close this issue after merge and not move this issue to vets.gov-team.

**Comment by jcmeloni** [comment]
Merged PR, will close after release.

**Comment by jcmeloni** [comment]
Released 17 Jan 2017
