### ISSUE TITLE
Header has inaccessible text

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#3967]
`.va-header-logo a` has inaccessible text. 98.2% sure that it's due to `overflow: hidden`. Rather than using `text-indent: 180%` try:

- `text-indent: -180%` 
- `position: absolute; left: -9999rem`. 

May be able to use `usa-sr-only` class.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
