### ISSUE TITLE
Columbus Benefit Facility Showing up Twice

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3974]
![columbusdup](https://cloud.githubusercontent.com/assets/13317147/20320737/ed26ddf8-ab40-11e6-9cf8-1100d4f03acb.PNG)

**Comment by NatalieEMoore** [comment]
@patrickvinograd it looks like the Chalmers P Wylie benefit facility is listed twice.  The only difference is the Room 1A piece.  Is it showing up twice in the data?  I'll have VBA specify which is correct.

**Comment by patrickvinograd** [comment]
Yes, it shows up under facility codes "757" and "757a":

https://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VBA_Facilities/FeatureServer/0//query?where=Facility_Number+like+%27757%25%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=*&returnGeometry=true&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=html&token=

**Comment by NatalieEMoore** [comment]
![daytondup](https://cloud.githubusercontent.com/assets/13317147/20322622/c281b7ba-ab47-11e6-8f84-14f195d2f227.PNG)

**Comment by NatalieEMoore** [comment]
I will work with VBA to have them clean this data @patrickvinograd

**Comment by NatalieEMoore** [comment]
Closing this as I have another thread open regarding duplicates and these will be solved with VBA's new data.
