### ISSUE TITLE
Rx list view for refill page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3978]
At our most recent usability testing session, we had some Veterans from the Paralyzed Veterans of America and they shared with us that the list view is much more helpful for those who have difficulties with mobility. This is for post-launch but still in scope for 2016. 

![rx refill list view](https://cloud.githubusercontent.com/assets/13420618/20321987/66aadf36-ab45-11e6-823a-c74717e394e8.png)

**Comment by bshyong** [comment]
@gnakm what is the default sort on this list?

**Comment by U-DON** [comment]
@bshyong I presume it would be prescription name, but the component should be taking the same sort values from the state that're being passed to the original card view anyway (and the default there is also prescription name).

**Comment by gnakm** [comment]
@bshyong Exactly what Eugene said. Card is prescription name, so list view should be as well.
