### ISSUE TITLE
Can't logout in Safari because of pop-up blocker

### ISSUE THREAD

**Issue by carlmjohnson** [department-of-veterans-affairs/vets-website#3980]
STR:

Log in at https://staging.vets.gov/disability-benefits/track-claims/your-claims

Click log out

Expected:

Log out pop up window opens.

Actual:

In Chrome when I try to log out, the pop-up blocker warns me that it blocked a pop-up, and I can override it. In Safari, there is no warning and I can't workaround it at all.

**Comment by jcmeloni** [comment]
@ayaleloehr @carlmjohnson could you please run through your scenarios again and see if you can reproduce?  We believe @crwallace implemented a fix (I tested it in prod and can't get a popup to be blocked any longer). Thanks!

**Comment by ayaleloehr** [comment]
Can no longer reproduce, so seems fixed to me. Going to close this issue, but @carlmjohnson feel free to reopen if you can reproduce still.
