### ISSUE TITLE
Spacing issue between text

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#3987]
@dannychapman @vanguard-team There are a number of pages where text and links appear stacked in a way that is visually too tight. In the blue box in this example, there needs to be more space between the link and the "Who's covered?" subhead. A similar scenario happens on numerous pages. Do you need a list of the other instances or do you have a way to search for them?:
https://vetsgov-pr-3324.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/

![screenshot 69](https://cloud.githubusercontent.com/assets/14881910/20326146/64c5d648-ab3c-11e6-8d94-59930c40b5b5.png)

**Comment by jcmeloni** [comment]
@dannychapman @bethpotts I'm not seeing this issue in production unless I'm looking in the wrong place (possibly!) -- can you confirm if this is still an issue for you?

**Comment by dannychapman** [comment]
@jcmeloni It's not happening on production since this particular combo of content is currently occurring only on a PR / branch that is being worked on. That said, the CSS behind it is still in prod, and this content will be merged soon, so I'd like to keep the issue open for now.

**Comment by ayaleloehr** [comment]
@dannychapman is something supposed to happen here? Can this be closed?

**Comment by dannychapman** [comment]
@ayaleloehr I think this was resolved when the content changed. Closing since it's likely that the content patterns have moved on at this point.
