### ISSUE TITLE
PL changes to titles of Disability pages for updating folders/breadcrumbs

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#3992]
@dannychapman @rroueche The 19 pages in Disability that have new titles are attached here. I need help getting these changes to be reflected in the breadcrumbs. 
[new titles for pages.xlsx](https://github.com/department-of-veterans-affairs/vets-website/files/593783/new.titles.for.pages.xlsx)
The content team is addressing the changes to piano keys because of these new page titles.

**Comment by jcmeloni** [comment]
@bethpotts @dannychapman I spot-checked some of these and it looked like changes had been made -- still need to keep this open?

**Comment by dannychapman** [comment]
@jcmeloni Please keep open - @rroueche has this in the works.

**Comment by rroueche** [comment]
On hold as we research whether it's possible to develop a solution -- PR #4293. Right now (with metalsmith) there's no way to override breadcrumb names, which are pulled from the folder name.

**Comment by ayaleloehr** [comment]
@rroueche was this completed with the plain language edit?

**Comment by rroueche** [comment]
was not resolved, but mainly bc we don't really have the functionality. I'm going to close this anyway though bc it's not something we're going to attend to - thanks for the reminder!
