### ISSUE TITLE
New CSS class for more flexible treatment of paragraph text

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/vets-website#3993]
Currently, there's a first-child rule in place such that special styling is applied to the first instance of paragraph text on a page or within a div (screenshots attached). Often times however, the content doesn't warrant that special styling. So, instead of the first-child rule, we'd like to have a more flexible option. One idea is creating a couple of CSS classes that we can use when we want to give text that special styling, and otherwise paragraph text would always have normal styles.

Before these changes are made, there needs to be a sweep of all existing content to add the CSS class(es) to text that currently has the special first-child styling. This way, once the rule is revoked, any intentional usage of that styling will be preserved.

![screenshot_2](https://cloud.githubusercontent.com/assets/8680732/20350886/95f24d4e-abde-11e6-9bd6-862b3866bd7a.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/8680732/20350887/95f219a0-abde-11e6-8883-32b6391f7fda.png)

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
