### ISSUE TITLE
Remove playbook styles from non-playbook pages

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#3997]
Playbook styles are being loaded for every page and I don't see any reason they should be.

Also, maybe we should remove the playbook.

**Comment by jbalboni** [comment]
+1 to this. It's a pretty large chunk of css that we could remove from the React apps, which don't need it.

cc: @crwallace @bshyong

**Comment by webinista** [comment]
Suggested fix:

- [ ] Remove playbook partial from `style.scss`
- [ ] Add it to `no-react.scss`

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
