### ISSUE TITLE
Change text length to web standards

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4011]
Content on both sign in and verify page is long. Could we change to make it the web design standard length (2/3)?

<img width="1049" alt="screen shot 2016-11-17 at 11 12 49 am" src="https://cloud.githubusercontent.com/assets/13420618/20399178/0321827e-acbe-11e6-99b7-6829b3968c89.png">

**Comment by crwallace** [comment]
Can we get a little more context for this?

**Comment by jcmeloni** [comment]
@gnakm ping re: note above -- what is the change you want to make?

**Comment by gnakm** [comment]
The body copy should be in a 2/3 grid format so that it is consistent with other pages on Vets.gov.
Example:
<img width="1029" alt="screen shot 2016-12-06 at 3 41 45 pm" src="https://cloud.githubusercontent.com/assets/13420618/20942698/8cc955e0-bbca-11e6-90f5-561c4ec144e7.png">

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
