### ISSUE TITLE
Loading animation for user actions

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-website#4015]
How should the loading indicator be used when the user has performed an action that hits the API?

Right now, when transitioning between pages or tabs, we display the loading indicator in place of the section that will appear when we get the relevant data from the server.

But for actions like refilling a prescription or sending a message, we should also indicate that something is happening. I'm not sure if it makes sense to just replace the entire view with just the loader similar to how loading a page works. For example, if we just clicked to confirm a refill or send a message, it wouldn't look right to replace everything with the loader, and then show everything back again when the action is done. Some actions will redirect and transition to a different page when successful, so the loading indicator would work there, but when there's an error, the modal or page would remain.

So I'm wondering what the UX for these things should look like. My initial thought is to overlay the full page with a transparent background and have the loader fixed in the center. Let me know if my descriptions weren't clear.

**Comment by U-DON** [comment]
Or maybe the loader isn't even the right element to use in these cases. Maybe the relevant button could be disabled temporarily and replaced with something like 'Sending...' in the case of a message being sent.

Some other cases where we need some type of wait indicator are moving a message, deleting a message, creating a folder, and deleting a folder. Might be missing some, but in general, SM has a lot more possible user actions, so those should be covered.

**Comment by gnakm** [comment]
@U-DON I think we were thinking to show the loader but with different messages at the bottom depending on what it was: Here is the previous issue for this: https://github.com/department-of-veterans-affairs/kudos-team/issues/169

ex. 
For sending a secure message: 
[Loader on top]
**is sending your message...**

For refilling a prescription:
[Loader on top]
**is submitting your refill request...** 

I'm not really sure if we need to show a different kind of loader for other scenarios. What about a more generic message for the ones mentioned above:

For moving a message, deleting a message, creating a folder, and deleting a folder
[Loader on top]
**is submitting your request...**

@angel please chime in your thoughts!

**Comment by angel** [comment]
@U-DON @gnakm 

I agree with showing different messages where we can with the same loader. I think it should just say "Sending your message..." without the "is". I don't think the "is" is necessary.

I think it makes sense have the loading take the entire view so then the Veteran can know that something is happening. If it's just happening in a small part of the page then it might be easy for them to miss it.

I think if the loading is needed after submitting from a modal then I think the loading should replace the modal box with the transparent background, but if it was say sending a message it should just take the entire view with no transparency and just a white background with the loading. The second one would still have the header and footer. What do you think @gnakm?

**Comment by gnakm** [comment]
Yeah I agree @angel and yeah we can take out "is."
We are having sorta similar discussion around [logging in and out of vets.gov ](https://github.com/department-of-veterans-affairs/vets-website/issues/3840)

<img width="341" alt="screen shot 2016-11-21 at 10 16 16 am" src="https://cloud.githubusercontent.com/assets/13420618/20488043/9908cb7c-afd3-11e6-98ed-aa27c3e7000d.png">

<img width="342" alt="screen shot 2016-11-21 at 10 16 07 am" src="https://cloud.githubusercontent.com/assets/13420618/20488042/99033374-afd3-11e6-8889-a933cac26a51.png">

<img width="344" alt="screen shot 2016-11-21 at 10 16 25 am" src="https://cloud.githubusercontent.com/assets/13420618/20488041/98feb114-afd3-11e6-8955-1906ccfb3ccd.png">

@angel Are these mocks what you had in mind? If so, please assign back to @U-DON

**Comment by angel** [comment]
@gnakm @U-DON looks good. I think for when it's not a modal we should leave the title of the page there. So we would leave "Prescription Refills" and "Message your Healthcare Team" and have the loading be underneath that with some padding.

**Comment by gnakm** [comment]
@U-DON noticed that all the loaders across Vets.gov are not looking the same. Related to: https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/33

@angel tagging you for awareness.

**Comment by jcmeloni** [comment]
@gnakm @U-DON With the merged PRs, are there actionable items remaining here?

**Comment by U-DON** [comment]
Yes, there are still multiple other changes I need to make before this can be closed.

- [x] Submitting a refill
- [ ] Sending a message
- [ ] Deleting a message
- [ ] Moving a message
- [ ] Creating a folder
- [ ] Deleting a folder
