### ISSUE TITLE
Improve visual integration of account links and global nav

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#4028]
- Moves account links into blue header container
- Adds responsive behavior to account links position
  - By default, the links appear on one line between the logo and search bar
  - If the links can't fit on one line in this position, they float right below the search bar
  - If the links can't fit on one line below the search bar, they may wrap
- Makes logo smaller at smallest breakpoint
- Retains full search bar at medium breakpoint; only changes to the button at smallest breakpoint
- Displays the search icon instead of text button at smallest breakpoint

<img width="984" alt="account-responsive" src="https://cloud.githubusercontent.com/assets/4106356/20444529/3d0f0a60-ad86-11e6-8a57-11e0508d0554.png">

<img width="987" alt="account-specs" src="https://cloud.githubusercontent.com/assets/4106356/20444532/3fe117e2-ad86-11e6-9ef5-750daeeafc6c.png">

**Comment by melwoodard** [comment]
@angel since we're still a ways out from adding a full site nav, this seems like a good interim solution based on what we were working with. Thoughts?

**Comment by angel** [comment]
@melwoodard this looks good! My only concern is when we don't have people's names and just an email. I pretty sure that is a possible use case. In which case, it can sometimes be pretty long, I'm wondering how that would look in this design specifically for large and small. I think it'll be fine for medium.

**Comment by melwoodard** [comment]
Thanks, good point! 

My thought is that the responsive behavior for the account greeting and links is not dictated by viewport width, it's dictated by wherever it can all fit on one line. 

If all the text fits on one line between the logo and search bar it will go there, otherwise it'll drop below. 

When it's dropped below and still can't fit on one line, then it would break up into multiple lines like so:

<img width="320" src="https://cloud.githubusercontent.com/assets/4106356/20496099/a40500f4-afd8-11e6-8fb1-0aceb2b5663e.png">

**Comment by angel** [comment]
@melwoodard cool, that looks good to me! Thanks!

**Comment by melwoodard** [comment]
Thanks!

@crwallace this isn't high priority, let me know where this goes and if we're able to address this before launch.

**Comment by bshyong** [comment]
@melwoodard @angel is it possible to have the sign-in/register links sit on the line below the search and logo on all viewports? In the mockups, large is the only exception. Implementation-wise it's a little finicky to have the links hop down like that. If the design is completely set in stone, I can implement as-is in the mock up, LMK

**Comment by melwoodard** [comment]
How much more time would you estimate it could take to get that behavior to work? It's not a deal breaker, so happy to simplify if it's going to take quite a bit of effort.

**Comment by bshyong** [comment]
@melwoodard The best way to get the behavior in the mockups is to duplicate that header; the one on the top line only shows up on large viewports, and the one on the bottom only shows up on small/medium.

If it's on the same line in both viewports, it's just a matter of moving it out of its own line where it currently sits and into blue header with the logo; no duplication needed.

**Comment by melwoodard** [comment]
@bshyong sorry for the delay - I think it's fine to go with the single layout. Thanks!

**Comment by bshyong** [comment]
No worries! I plan to have this in a PR today
