### ISSUE TITLE
HCA, Rx & Claims alert banner design update

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#4029]

**Comment by melwoodard** [comment]
Alerts should be based on the USWDS `usa-alert-warning`, with these modifications:

![alert-warning](https://cloud.githubusercontent.com/assets/4106356/20440540/72fc644e-ad75-11e6-9ee2-af96697934e7.png)

Apply this style to the following alerts:

1. [Health Care Apply page](https://www.vets.gov/healthcare/apply/)

2. [Prescriptions page](https://www.vets.gov/healthcare/prescriptions)
  - Also adds a close button and a "Don't show this message again" link, which will hide the alert when a user visits this page in the future

3. [Claim Status](https://www.vets.gov/disability-benefits/track-claims/your-claims) system downtime message

![alert-warning-hca](https://cloud.githubusercontent.com/assets/4106356/20440633/bf72f8b0-ad75-11e6-8027-7c35181ebab4.png)

![alert-warning-rx](https://cloud.githubusercontent.com/assets/4106356/20441268/a56bd4fc-ad78-11e6-8cd0-125a74d946ae.png)

![alert-warning-claims](https://cloud.githubusercontent.com/assets/4106356/20441870/1d6a34d8-ad7b-11e6-90f5-0f8e7be0eb9f.png)

@gnakm @staceylanger @suzchap thoughts? The solution here aims to accomplish a few things:
  - Address the issue of stacking bars captured in #3771
  - Standardize on an alert style (pulled from US web design standards)
  - Visually separate the alert from the nav bar to show it's contextual to that specific page/application - when it's glued to the nav bar, it's more likely to be overloooked
  - For Prescriptions, give users the option to permanently hide the alert - @crwallace is it technically feasible to save this preference on a user's account?

**Comment by gnakm** [comment]
Thank you for doing this @melwoodard I likes these and I think it does accomplish the list of things you mentioned above. 

Let's say for Rx, a user were to X-out the alert box. When would it show again if the user doesn't choose to hide the alert permanently?

My concern is that we went back and forth a lot with stakeholders a lot with this and landed on an expandable banner, so that the disclaimer doesn't disappear forever incase users may need to read it again. I don't think it will be a big problem but worth flagging. Thoughts @staceylanger ?

**Comment by melwoodard** [comment]
Thanks, good points to consider. If a user were to X-out the alert, I'd imagine it would remain hidden for the duration of their current session, then it would show again the next time the user logged in to view prescriptions.

Since the prescriptions app will for most be used a regular basis (rather than one-off like applying for benefits), this message makes sense for onboarding instruction, but would be nice to provide the option to not see it again. That said, I'm happy to defer to what you think will be best based on conversations with stakeholders. At the very least we could update this to match the `usa-alert-warning` style and retain the original expand/collapse functionality.

**Comment by staceylanger** [comment]
I'd like to retain the behavior that we aligned on with pharmacy SMEs. Thanks!

**Comment by melwoodard** [comment]
Can do - updated design here and in the original post above to retain approved behavior while modifying visual style for consistency.

![alert-warning-rx-expanded](https://cloud.githubusercontent.com/assets/4106356/20495780/54e31b24-afd7-11e6-9a98-d50a825337b8.png)
---
![alert-warning-rx-collapsed](https://cloud.githubusercontent.com/assets/4106356/20495778/536ccc36-afd7-11e6-92c3-8f3faf829ccd.png)

**Comment by suzchap** [comment]
claim status looks good - thanks!

**Comment by goldenmeanie** [comment]
Should this use the accordion +/- toggle style?

**Comment by melwoodard** [comment]
@goldenmeanie I was thinking about that too. @gnakm did you explore this before? I'm wondering if, because the alert starts out in an expanded state, the "-" icon isn't very clear.

**Comment by cweber** [comment]
@melwoodard, do you think there is still a case for the oversized alert box styling or should this supplant it in all instances? e.g. can the global usa-alert styles get modified so this propagates out? (We're using that in edu.)

Likewise, this might be a good PR for US WDS.

**Comment by melwoodard** [comment]
@cweber I think this adjusted style should be used across the board for all alerts - success, error, etc. The icon and font sizing works a lot better in a responsive setting than the USWDS default. I'll spin up some additional issues to address those, it would be great if you can add instances you know of that need to be addressed.

**Comment by gnakm** [comment]
@melwoodard So the "^" came from the previous VCL at the bottom of the footer because the box are being pushed up. I think over time, we reused it. We haven't tested the old VCL box. I think our hypothesis was also that "^" is easier to understand than +/-

**Comment by gnakm** [comment]
@melwoodard @cweber @goldenmeanie Just so I understand the verdict of our +/- discussion above, we are sticking with +/- for consistency? I want to say expanded or closed is going to depend on each case by case scenario. Claims has it open depending on what phase you're on. SM + Rx has the alert open because stakeholders wanted all info to be available once a user signs in. I think all alerts should be expanded.

How about we keep it open by default and depending on each project, we can have them closed when necessary.

**Comment by goldenmeanie** [comment]
I'd advocate for closed by default with a clear headline, but respect that you’ve already had that discussion with the stakeholders. :)

**Comment by goldenmeanie** [comment]
I've been looking at the profile page this morning and am struck again by how much of our first view on small screens are navigation and warnings.

**Comment by cweber** [comment]
@goldenmeanie Seems like that could be a new issue itself.

**Comment by melwoodard** [comment]
Moving this issue to the patterns repo: https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/28
