### ISSUE TITLE
No link to CareerScope on page that should link to CareerScope

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#4035]
@rroueche can we add a link to CareerScope on this page where indicated?  THANKS. If this is a big ask, we can think about waiting until the PL push, but it's kind of a bad UX to have this page not link to anything. Your call!  THANKS!

https://www.vets.gov/education/tools-programs/careerscope/

In addition to career counseling, VA provides the interest and aptitude assessment tool, CareerScope, to all eligible benefit recipients. CareerScope has been used frequently by Veterans to determine the best career path when transitioning to civilian life. [Access the CareerScope Tool]  (https://va.careerscope.net/gibill). 

@maryannbrody FYI

**Comment by jcmeloni** [comment]
@rroueche Is this in progress?

**Comment by rroueche** [comment]
Apologies! Was still getting used to GitHub flow and only just now saw thing. Evaluating now.

**Comment by rroueche** [comment]
@mollyblake that link should definitely be there - great catch!! please go ahead and create a new branch in the vets website repo, and once you've made the update, create a PR and assign Beth and I as reviewers, and I'll check it out + merge as soon as possible.

cc @maryannbrody

**Comment by mollyblake** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/4535

Here is the PR @bethpotts  and @rroueche. Let me know if there are any changes!  Thanks.

**Comment by rroueche** [comment]
Complete: https://www.vets.gov/education/tools-programs/careerscope/
