### ISSUE TITLE
Duplicate Facilities Issue

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#4036]
Issue 1: 
Chalmers P. Wylie Veterans Outpatient Clinic

 
420 North James Road
Columbus, OH 43219-1834

Distance: 28.2 miles

Facility type: Health

Main:
614-257-5200
Mental Health:
614-257-5491
Directions
Chalmers P. Wylie Ambulatory Care Center

 
420 N James Road
Columbus, OH 43219

Distance: 28.2 miles

Facility type: Benefits

Main:
614-388-7014
Directions
Chalmers P. Wylie Ambulatory Care Center

 
420 N James Road
Room 1A-052
Columbus, OH 43219

Distance: 28.2 miles

Facility type: Benefits

Main:
614-257-5200
Directions

**Comment by NatalieEMoore** [comment]
Ms Moore – our Dublin facility (station 557) has noted that two of their CBOC facilities currently active in VAST are not populating the Vets.gov facility locator.  These are the Tifton (557GF) and Brunswick, GA (557GE) CBOCs; we wanted to bring this to your attention for correction, if there’s any other information needed from us please let me know, thanks.

**Comment by NatalieEMoore** [comment]
Issue 3: 
I think there is a bug with the Chalmers P. Wylie Ambulatory Care Center.   It shouldn’t be appearing twice under benefits.

**Comment by NatalieEMoore** [comment]
Issue 4: 

When typing in Tennessee, the map does not have a red pointer for all the available sites in TN—many are missing.  Also, the way the sites are listed in the results box does not make sense.  It starts with TN sites then KY, then AL, then GA, then back to TN, etc with no clear reasoning (i.e., distance, etc).  This will be confusing for users and with the TN sites not indicated on the map, one might stop scrolling once the stations listed are non-TN sites.  Suggest all TN sites are listed first before other states are listed.

**Comment by NatalieEMoore** [comment]
Issue 1: Should be resolved with new VBA data refresh.  That refresh is currently with GeoBISL.

Issue 2: I see Brunswick on the site, https://www.vets.gov/facilities/facility/vha_557GE, so not an issue. I don't see Tifton (557GF).  @patrickvinograd do you see it in the data?

**Comment by patrickvinograd** [comment]
Re Issue 2: Tifton 557GF is one of the sites missing lat/long data.

**Comment by patrickvinograd** [comment]
Re Issue 4: The results are sorted by distance from the center of the map, as you page through the results you'll get further from the center. If you search for Tennessee, it puts the map at the center of the state. Some locations in KY, AL, etc are closer to the center of Tennessee than some locations in eastern/western Tennessee.

**Comment by patrickvinograd** [comment]
Issue 3: Yes, it's a bug in the VBA data, the same facility is listed under station number 757 and 757a.

**Comment by NatalieEMoore** [comment]
Issue 3:  Will be solved with the data refresh then!

**Comment by NatalieEMoore** [comment]
Issue Two:  Those lat/long refreshes only happen once a quarter so that site won't show until the refresh happens.  Trying to figure out when it will happen this quarter...

**Comment by NatalieEMoore** [comment]
For issue 4: so the results/distances are sorting by center of the map and not by zip code entered?

**Comment by patrickvinograd** [comment]
Well in this case they searched for 'Tennessee', not a zip code, so the map centers on the center of the state. In general they will be sorted by distance from center of the bounding box, whether that bounding box is centered on a zip code, a state, an address, etc. Whatever the search term is.

**Comment by jcmeloni** [comment]
@NatalieEMoore Is this a running open issue you want to keep open?

**Comment by NatalieEMoore** [comment]
yes please, I will close it out when it's done!

**Comment by ayaleloehr** [comment]
pinging @NatalieEMoore as the last comment was three months ago.
