### ISSUE TITLE
Website Data Issues

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#4037]
The website on this page is not correct.
https://www.vets.gov/facilities/facility/vha_623
 

It linked to our Vinita clinic and should be to our main page. Here is the correct link.
http://www.muskogee.va.gov/index.asp

**Comment by jcmeloni** [comment]
@NatalieEMoore Are you keeping this open because you can actually do something about it (I thought we were just beholden to whatever data comes our way), or just as a reminder?

**Comment by NatalieEMoore** [comment]
reminder for me to work with @jenny-h-l on websites that are wrong in the data.

**Comment by ayaleloehr** [comment]
pinging @NatalieEMoore here as well. next steps?

**Comment by NatalieEMoore** [comment]
No, this can stay open.  It's a reminder that the way we update facility websites on the FL details pages is not automated.  This is not a huge priority for FL because eventually the websites will be removed completely but not until we make some updates on our side.

**Comment by leannammiller** [comment]
closing, dupe
