### ISSUE TITLE
Remove white bar until we have login

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#4042]
Can we remove this white bar across the site? I know it's only temporary until we have login, but it looks strange as it is. 
<img width="432" alt="screen shot 2016-11-18 at 5 46 47 pm" src="https://cloud.githubusercontent.com/assets/1307774/20449413/255c47c6-adb7-11e6-8638-be69a9595493.png">

**Comment by crwallace** [comment]
I think this is probably related to #4028

**Comment by jcmeloni** [comment]
Removing identity label because this isn't about a user's identity.

**Comment by emilyville** [comment]
This can be closed because the white bar now has the login info in it instead of being empty. 🇺🇸
