### ISSUE TITLE
Create an Account button should open sign up pop-up instead of sign in

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#4044]
There are different pop ups for "sign in" / "create an account" but our two buttons go to the same "sign in" window. Can we change the create an account to open the account creation pop up?

<img width="411" alt="screen shot 2016-11-18 at 5 50 46 pm" src="https://cloud.githubusercontent.com/assets/1307774/20449495/bb0b23fa-adb7-11e6-8eff-04b532fb5175.png">

<img width="463" alt="screen shot 2016-11-18 at 5 52 16 pm" src="https://cloud.githubusercontent.com/assets/1307774/20449505/d078a03c-adb7-11e6-9ac1-6c9fb434ccc0.png">
<img width="456" alt="screen shot 2016-11-18 at 5 52 27 pm" src="https://cloud.githubusercontent.com/assets/1307774/20449507/d2451350-adb7-11e6-9038-d618c00c9933.png">

**Comment by jcmeloni** [comment]
This is a high-priority request; @staceylanger wants it in before full public launch.  Steve at ID.me is aware and they have to do work on their side to make this happen.  We are tracking this in our daily standups (nothing for Vanguard to do yet until ID.me provides two URLs, except to be ready when that drops).

**Comment by crwallace** [comment]
This mostly requires work on the API side with very little work from Vanguard. 

cc: @robbiethegeek // @omgitsbillryan

**Comment by omgitsbillryan** [comment]
@crwallace can confirm, unicorns will need to coordinate with ID.me before vanguard can consume.

**Comment by robbiethegeek** [comment]
@omgitsbillryan do you have an understanding of the level of effort that this will require?

**Comment by jcmeloni** [comment]
See above re: id.me coordination  @robbiethegeek @omgitsbillryan

**Comment by omgitsbillryan** [comment]
Tanel and I chatted and it looks to be as simple as adding a query param to the ID.me url in the form:

- `op=signin`
- `op=signup`

for sign in and sign up respectively.  I think the simplest soltion would be when the F/E calls `api.vets.gov/session/new` to get the login URL (e.g.):

```javascript
{"authenticate_via_get" : "https://api.idmelabs.com/saml/SingleSignOnService?SAMLRequest=fVLLbts..."}
```

the F/E, could conditionally add `&op=signin` or `&op=signup` for sign in and sign up respectively, depending on which button was pressed.

**Comment by omgitsbillryan** [comment]
Forgot to mention, in the above ^^^ solution, the level of effort for `vets-api` is a big fat :zero:.

**Comment by jcmeloni** [comment]
I will discuss this with ID.me on our 10am call and get a deploy date from Tanel.

**Comment by jcmeloni** [comment]
@crwallace Tanel says the two query parameters are in prod on their side, so add them whenever you're ready on our side!

**Comment by crwallace** [comment]
Thanks @jcmeloni! I will get on this right now.
