### ISSUE TITLE
Change how we refer to users in greeting

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#4047]
Currently when a user is logged into a verified account, we know their name, but we still say "hello email@address" in the header. Should we use the user's name when we know it instead to be more personal?  

Probably a question first for @emilyville but going to tag this with Vanguard as well so we can track with the other identity issues. 

<img width="1180" alt="screen shot 2016-11-18 at 8 20 12 pm" src="https://cloud.githubusercontent.com/assets/4719765/20451880/d8b55550-adcc-11e6-9a26-3b7cdef93f95.png">

**Comment by crwallace** [comment]
This is addressed by department-of-veterans-affairs/vets.gov-team#441
