### ISSUE TITLE
Users middle name shown as null when it doesn't exist

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#4048]
Right now vets.gov.user+264@gmail.com has a middle name of null as you can see below. This user does not have a middle name in ID.me or MVI.  I first created this issue in vets-api [here](https://github.com/department-of-veterans-affairs/vets-api/issues/523) but @omgitsbillryan thought this should be taken care of on the front end instead, so opening this issue now. 

![1bb7b30a-ab1d-11e6-82c3-25aabbcf951f](https://cloud.githubusercontent.com/assets/4719765/20452118/b9e9ebaa-add0-11e6-95ba-90fc2360dfef.png)

**Comment by crwallace** [comment]
this is addressed by department-of-veterans-affairs/vets.gov-team#441
