### ISSUE TITLE
failures for education-plain-language-update commits

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#4051]
@rroueche I need some help resolving commit failures for this PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/4000

I'm assuming I shouldn't make any more edits to these files until all the checks pass? I see two failures from commits submitted 26 days ago on this PR, then a long string of failures from a couple days ago. The last heroku link isn't showing the latest edits made.

**Comment by rroueche** [comment]
@bethpotts I think this is resolved, but want to get confirmation from you before I close this out. Thanks!

**Comment by jcmeloni** [comment]
@bethpotts @rroueche Can this be closed? The referenced PR is closed.

**Comment by rroueche** [comment]
@jcmeloni and @bethpotts I believe this is done, closing!
