### ISSUE TITLE
Reevaluate how we're handling close animations on expanding groups

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4056]
Close animations on expanding groups are to sensitive to vertical height and require manual adjustment via eyeballing to get correct. We went ahead and disabled them in PR #4026 to avoid weird jumpy behavior.

**Comment by jcmeloni** [comment]
@cweber Can this be closed? There is a PR referenced here that is merged.

**Comment by cweber** [comment]
Nope. This is an outstanding issue. We resolved it by turning something off because it was too clunky. This issue is open to remind us that we may need to write a better solution. The goal would be to re-enable close animations once we have a better solution built.

**Comment by rtluu** [comment]
there hasn't been any negative feedback as of late regarding collapsing groups. closing
