### ISSUE TITLE
Investigate shutting off date changes on scroll

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4061]
This is in Chrome and seems to be a browser default. So cool! ....not cool. Can we turn this off?

![date-scrolling](https://cloud.githubusercontent.com/assets/417657/20497420/0bd06890-aff7-11e6-8250-1147020a38be.gif)

**Comment by J-Quag** [comment]
Moving this out of ice box for after the pension form is released. Happens on more than just dates. the pension form has a large number of number fields.
