### ISSUE TITLE
Dates in review section are still throwing errors in first field

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4065]
Dates in the review section are still throwing errors prematurely. As soon as you select a month, the styling appears.

![screen shot 2016-11-21 at 3 35 43 pm](https://cloud.githubusercontent.com/assets/417657/20499632/42d2159c-b000-11e6-9df4-5e10e1631580.png)

It also has an error message based on military service dates, which is actually not even how we're referring to military service dates anymore.

**Comment by akainic** [comment]
Possibly reset all the `dirty` fields once you get to the review step.

**Comment by jbalboni** [comment]
@cweber I haven't been able to reproduce this (aside from the incorrect message text). Do you what steps you took to get this to happen?

**Comment by cweber** [comment]
Hmm. No, but I'll mess around and see if I can make it happen again.

**Comment by cweber** [comment]
Huh. I can't recreate. I'm going to close this. I'll open again if I see it again.
