### ISSUE TITLE
find verbiage for site security for call center

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4075]
More info: How secure is the site? There are many concerns about the secure of the Veteran’s PII on the vets.gov website as they do not have to establish a username and password to get to or fill out the application.

**Comment by cweber** [comment]
I think this might be better answered by @akainic or @koconnor719. I think she wants to be able to supply an answer to the Call Center that they can give to concerned veterans.

The full quote was:

"We received this question from the call center, and I wondered if you have standard verbiage to reply - How secure is the site? There are many concerns about the secure of the Veteran’s PII on the vets.gov website as they do not have to establish a username and password to get to or fill out the application."

**Comment by koconnor719** [comment]
is this a question from call center?  how's this for response:

The vets.gov account meets the highest security standards in both government and the private sectors:

•	NIST 800-63-2
•	OMB M-04-04
•	Executive Order 13681, Section 3  
•	National Strategy for Trusted Identities in Cyberspace (NSTIC)

In recent years, data breaches have compromised the personal data of hundreds of millions of Americans. The Anthem Health breach alone compromised the Name, Date of Birth, Address, Phone Number, and Social Security Numbers of 78.8 million Americans. The OPM breach compromised 22.1 million Americans. As a result, a new adaptive approach is required to protect the identities of Americans.

VA, and other government agencies, are required to meet new security standards for protecting Veteran information listed above.  The vets.gov account security capabilities are an industry leader in this area.

**Comment by ayaleloehr** [comment]
This question seems related to @jcmeloni 's comment here about teams taking things into their own hands, so just figured it was worth it to connect the two data points: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/453#issuecomment-262250990

**Comment by koconnor719** [comment]
i think the response above could be standard across teams as we get these questions if that works?  that was my goal:)

**Comment by leannammiller** [comment]
escalated, closing this from this channel
