### ISSUE TITLE
Consider disabling continue button if there are errors on the page

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#4086]
If there are errors on a form page, while you are prevented from continuing onto the next screen, the Continue button is not disabled. Consider disabling the button.

Should apply to both HCA and education benefits, as well as future forms.

Curious as to what @goldenmeanie and @cweber think of this suggestion.

**Comment by cweber** [comment]
The disabled button could cause frustration. I like that the current enabled button scrolls you up the page when there is an error present, but it would be more valuable if it could scroll you to the first error on the page.

**Comment by akainic** [comment]
Totally agree with that. I think we have a separate ticket for that: https://github.com/department-of-veterans-affairs/vets-website/issues/3330. Going to close this ticket then and keep the Continue button enabled but fix scrolling to the error.
