### ISSUE TITLE
Remove underline from pipe character Sign in | Register link

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4088]
The pipe character in Sign in | Register gets underlined on hover.

![screen shot 2016-11-22 at 5 01 04 pm](https://cloud.githubusercontent.com/assets/417657/20543925/ad713c72-b0d5-11e6-962a-d7bbfefbd741.png)

**Comment by crwallace** [comment]
This was resolved in #4117
