### ISSUE TITLE
Issues with modal

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#4092]
1. ~~Mobile styles seem broken (when resizing the desktop screen the content doesn't adjust).~~ *Update:* no longer an issue

2. Is the content correct in the modal? I thought for the left side (staying on vets.gov) we were going to say: "Servicemembers and Veterans applying for education benefits *for the first time*". 

3. The scrolling functionality of the sticky-action-box is broken now. Not sure if this was caused by this PR or another, but we should fix this.

4. How do you trigger the modal to be viewed? We'll probably want to update the links from `/education` to the landing page to be the modal link.

**Comment by goldenmeanie** [comment]
This work was done in https://github.com/department-of-veterans-affairs/vets-website/pull/4054

It is triggered by putting `#modal` on the end of the URL

**Comment by akainic** [comment]
@goldenmeanie I saw that PR, these issues were identified by testing on that branch.

**Comment by goldenmeanie** [comment]
Booo

**Comment by cweber** [comment]
I just pushed a padding change (effecting left, right, divider and min-width of the container) to edu-benefits-modal-fix

**Comment by alexose** [comment]
It looks like the sticky box broke in `cb06bcb`.  I'll get a fix up in a new PR.

**Comment by alexose** [comment]
Per our conversation in #vetsgov-edu_benefits, we're keeping the language as is.   Closing this issue for now, but feel free to reopen if it warrants further discussion.
