### ISSUE TITLE
Address build warning caused by MapBox

### ISSUE THREAD

**Issue by alexose** [department-of-veterans-affairs/vets-website#4094]
I've been seeing this warning pop up for a couple weeks now:

```
WARNING in ./~/mapbox/vendor/promise.js
Critical dependencies:
1:379-386 This seems to be a pre-built javascript file. Though this is possible
, it's not recommended. Try to require the original source to get better result
s.
 @ ./~/mapbox/vendor/promise.js 1:379-386
```

**Comment by ayaleloehr** [comment]
cc @bshyong as this is likely from facility locator

**Comment by bshyong** [comment]
Looking into it

**Comment by bshyong** [comment]
We can't fix this since the issue lies with Mapbox including a precompiled file in their library, but we can squelch the warning https://github.com/department-of-veterans-affairs/vets-website/pull/4099
