### ISSUE TITLE
Expired Heroku link for [WIP] Health care plain language update PR

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/vets-website#4105]
PR #3979
PR history shows that "va-bot deployed to vetsgov-pr-3979 6 days ago" successfully. However the heroku link seems now to be expired, and I'm unable to re-build it: https://vetsgov-pr-3979.herokuapp.com

I committed new test changes to see if a new commit would trigger it to rebuild, since the last commit was >5 days in the past, but that didn't work.

**Comment by bethpotts** [comment]
@dannychapman I need to send a preview link to SMEs on Friday, so let me know if you think you can resolve this Friday. Thanks!

**Comment by jcmeloni** [comment]
@bethpotts @rroueche Can this be closed?

**Comment by dannychapman** [comment]
@jcmeloni This is still in progress

**Comment by jcmeloni** [comment]
@dannychapman Ok. Since the issue was about a heroku link that was needed like a week ago, I figured it might have been abandoned.

**Comment by dannychapman** [comment]
@jcmeloni WIP content plain language edits are all current and should be kept open for now. Merging soon fingers crossed!

**Comment by rroueche** [comment]
Closing bc we reset the heroku link
