### ISSUE TITLE
Use HTML5 input types for all form inputs

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4110]
Currently when entering a phone number on  mobile, the default letters keyboard is displaying first. Switch to trigger numbers firsts or, ideally, the phone pad.

**Comment by leannammiller** [comment]
@cweber - is someone on this?

**Comment by cweber** [comment]
Not yet. It's in 1-current-sprint to get picked up by one of the FE devs sometime this week.
