### ISSUE TITLE
External link icon outside button?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#4111]
The Account Management section of the Profile page currently has the external link icon outside the Delete Your Account button (screenshot below, which you likely can't see on the VA network unfortunately).  Should this icon be inside the button? 

![screen shot 2016-11-28 at 11 03 38 am](https://cloud.githubusercontent.com/assets/4719765/20675499/87b0cc80-b55a-11e6-8a47-e10e8ce8c378.png)

**Comment by crwallace** [comment]
@ayaleloehr -- we have known this was a visual issue but I thought @cweber and @goldenmeanie were implementing something so we have been waiting because I didn't want to stop on their styles changes.

**Comment by cweber** [comment]
Ah! We did implement something, though we intentionally kept it tied to a class name so that it would propagate out ... too far. It did get pushed live though so it's ready to use. Unfortunately, we did not build a version for a red ghost button.

That all said, the bones are in place to build a red version of this and/or generalize the code a bit more so it captures all buttons that go to an external source.

You can see the new version in action here: https://www.vets.gov/education/apply-for-education-benefits/

**Comment by goldenmeanie** [comment]
![exit-icon-secondary-darkest](https://cloud.githubusercontent.com/assets/1969/20754808/ab304dee-b6da-11e6-8a72-db9597419359.png)

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="93px" height="90px" viewBox="0 0 93 90" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 41.2 (35397) - http://www.bohemiancoding.com/sketch -->
    <title>exit-icon-secondary-darkest</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="exit-icons" transform="translate(-19.000000, -456.000000)" fill="#981B1E">
            <path d="M87,495 L47,495 L47,505 L87,505 L87,516 L112,500 L87,484 L87,495 Z M97,462.009833 C97,458.693521 94.3177317,456 91.008986,456 L24.991014,456 C21.6849366,456 19,458.690694 19,462.009833 L19,539.990167 C19,543.306479 21.6822683,546 24.991014,546 L91.008986,546 C94.3150634,546 97,543.309306 97,539.990167 L97,529 L87,529 L87,537 L29,537 L29,466 L87,466 L87,474 L97,474 L97,462.009833 Z" id="exit-icon-secondary-darkest"></path>
        </g>
    </g>
</svg>
```

**Comment by jcmeloni** [comment]
Removing identity label because this isn't about a user's identity.

**Comment by ayaleloehr** [comment]
That was me. Sorry, I conflated identity and profile earlier this week when I shouldn't have!
