### ISSUE TITLE
Healthcare landing page 

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4113]
Here is the healthcare landing page design for launch!

Mobile view:
![healthcare mobile 3 cards](https://cloud.githubusercontent.com/assets/13420618/20686135/68805ab2-b585-11e6-818a-be6f2a3181e9.png)

Desktop view:
![healthcare 3 cards](https://cloud.githubusercontent.com/assets/13420618/20685071/d08c4efe-b580-11e6-887e-e417fd87ddc2.png)

Here is the content for this page:

## Health Care

With VA health care, you're covered for regular checkups with your primary care doctor and appointments with specialists (like cardiologists, gynecologists, and mental health providers). You also gain access to home health and elder care, plus medical equipment, prosthetics, and prescriptions.

### Apply for Health Care

Apply online so you can start getting medical exams, flu shots, and preventive health care.

### Refill Prescriptions

Refill prescriptions online, and track the status of your refills.

### Send a Message to Your Health Care Team

Send a secure, private note to your doctor or other members of your VA health care team.

@emilyville Are we still good to go with MVP as the 4th card? If so, could you assign this to Tiffany and Eugene?

Tagging both @U-DON and @webinista because it is for both Rx and SM
cc: @angel and @emilyville for awareness

**Comment by emilyville** [comment]
@gnakm the new version (w/o MVP) looks good to me!

**Comment by ayaleloehr** [comment]
@emilyville will there be a link to this page from the vets.gov homepage or how will someone get here?

**Comment by gnakm** [comment]
@ayaleloehr From the homepage, users can go here by clicking on the blue heath care card. Right now it lands directly on the HCA apply page but now this health care landing page will come before it. 

Eventually, if some of our health care features become highly used, we will add those in the popular section.
