### ISSUE TITLE
Keep validation error messages in sync with form language

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4114]
Validation errors are hard to keep in sync with form and review language while they're embedded. Consider pulling them out into a localization file?

**Comment by jcmeloni** [comment]
@cweber Do you mean a localization file?

**Comment by cweber** [comment]
haha. yes. I really don't think I typed legalization on purpose. I'll edit above.

**Comment by leannammiller** [comment]
to discuss in 12/12 sprint planning

**Comment by leannammiller** [comment]
this fits with improved form building
