### ISSUE TITLE
Build out initial FE of 1995

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4122]
Based on [this outline](https://github.com/department-of-veterans-affairs/edu-benefits-team/blob/master/1995/1995-outline.md), FE buildout can begin on the 1995. We'll continue discovery work on Edu Benefits, but based on our initial conversations, this is a solid place to start and having a working prototype up quickly will be useful to get usability testing underway.

The form is broken down into the same chapters as the 1990. Pages have not been indicated yet, but when possible, mirror 1990.

**Comment by leannammiller** [comment]
we will break this down into more tickets, will revisit w/o 12/19

**Comment by jbalboni** [comment]
Seems like we can close this? @leannammiller
