### ISSUE TITLE
Refactor va-cards pattern to use Flexbox

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4126]
- tinyliquid, the Liquid implementation we've chose to use with Metalsmith does not support modulo/ `%`
- `includes/main-navigation.html` relied on a conditional that used the modulo operator. 
- `includes/main-navigation.html` is now broken.
- This is probably fixable with Flexbox

**Comment by carlmjohnson** [comment]
What if we extend tinyliquid? How much work would it be to patch it?

**Comment by webinista** [comment]
Extending tinyliquid is probably as much work as using Flexbox for layout. We could also consider a new template engine, but I think this is solvable with CSS.

**Comment by webinista** [comment]
Nope, not solvable with CSS. I overestimated the abilities of Flexbox. Not a huge deal. This only gets weird if we have more 4 cards.
