### ISSUE TITLE
PL WIP education page: subhead in the blue box not rendering correctly

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#4150]
https://vetsgov-pr-4098.herokuapp.com/education/gi-bill/higher-learning/

Can you please help? This is the branch: content/wip/education-plain-language-update

**Comment by bethpotts** [comment]
@dannychapman Are you able to help me with this since Rachael is out?

**Comment by dannychapman** [comment]
@bethpotts Fixed. There was no line spacing between the blue box formatting and the content. Please leave a space in between in future to fix.

**Comment by bethpotts** [comment]
@dannychapman Thanks so much!

**Comment by ayaleloehr** [comment]
This says fixed, so i'm closing. someone reopen if you disagree.
