### ISSUE TITLE
Page header is wider than content at small screen sizes

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4155]
At small screen sizes the page header doesn't collapse enough and sticks at a certain width, while the page content keeps shrinking:

![screen shot 2016-11-30 at 9 01 16 am](https://cloud.githubusercontent.com/assets/634932/20755349/9ca5b3b6-b6dc-11e6-8e91-52c49c0e4d3d.png)

This is pretty minor, as it only shows up on sub-iPhone 5 size screens.

**Comment by jcmeloni** [comment]
Not moving over to vets.gov-team as open PR should close this one soon https://github.com/department-of-veterans-affairs/vets-website/pull/4602
