### ISSUE TITLE
Disclaimer / alert button overlaps text when viewport ≤ 375px

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4170]
Adding `width: 90%` to `.va-alert h5, .va-title` will fix it 99% of cases.

<img width="623" alt="screen shot 2016-11-30 at 2 26 04 pm" src="https://cloud.githubusercontent.com/assets/354277/20773975/1ad1195c-b709-11e6-8abf-1490462c1195.png">

**Comment by webinista** [comment]
Assigned it to you, Mel, in case you want to give more specific direction. If now, feel free to reassign it to me.

**Comment by melwoodard** [comment]
@webinista thanks - rather than setting a width, can you give .va-alert-body a `padding-right: 3.5rem` ?
