### ISSUE TITLE
Profile: Link to secure messaging

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#4172]
When I log in to my profile, I see the following links:

<img width="682" alt="screen shot 2016-11-30 at 5 47 48 pm" src="https://cloud.githubusercontent.com/assets/103496/20774793/ed3d303a-b725-11e6-9dc4-316c57ac7578.png">

Should there be a link to "Message your health care team" under "Your account will allow you to:"?

**Comment by crwallace** [comment]
@angel -- I can add this, it was never in any mockup so I think it just got over looked. Would love to just get a quick 👍 from @staceylanger to add it.

**Comment by crwallace** [comment]
Also @ayaleloehr, do we think this needs the `identity` tag? This doesn't really have anything to do with identity or login.

**Comment by ayaleloehr** [comment]
I had been associating profile page with identity tag. That is probably inaccurate though, so feel free to remove if it's incorrect!

**Comment by staceylanger** [comment]
I am good with adding Secure Messaging. Thanks!
