### ISSUE TITLE
Header clean up

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4175]
@melwoodard did an awesome job auditing headers all across our tools. We need to clean up the headers for Rx detail and glossary pages.

### Detail page
1. Aligned with top of Prescription name
2. Contact should be `h4` with border bottom.
<img width="622" alt="screen shot 2016-11-30 at 7 00 02 pm" src="https://cloud.githubusercontent.com/assets/13420618/20776598/972cec8a-b72f-11e6-9d64-84633841f415.png">

claims for reference:
<img width="1024" alt="63974bb2-b6db-11e6-87a6-2d4cef6e12d7-1" src="https://cloud.githubusercontent.com/assets/13420618/20776619/bdd5a9b2-b72f-11e6-969d-73ca564d2248.png">

@mel is the primary blue the color we are going with across vets.gov for border bottom?

3. Order History should be `h2`

### Glossary page
1. Glossary should be `h1`
2. Status headers `h2` with `border-bottom`
3. Definition headers `h3`

![glossary page](https://cloud.githubusercontent.com/assets/13420618/20776761/9af9a230-b730-11e6-9ba0-84038b7b6996.png)

**Comment by melwoodard** [comment]
Thanks @gnakm. Yes, let's go with the primary blue border bottom to standardize these header styles.

H4 underlined headings should be the `highlight` class, so we can create a corresponding H2 `highlight` class

**Comment by webinista** [comment]
Should be a matter of replacing `va-h-ruled` with `highlight`. 

@melwoodard can you clarify this?

> H4 underlined headings should be the highlight class, so we can create a corresponding H2 highlight class

**Comment by melwoodard** [comment]
@webinista was just a suggestion for naming consistency - there's already an `h4 highlight` class, so the H2 variant with border bottom could be `h2 highlight`

**Comment by webinista** [comment]
@melwoodard Another followup question: is this a site-wide change for all ruled headings? I made an issue a while ago about unifying heading styles (#3660) but don't want to assume that this should be a global change rather than an Rx change.

**Comment by melwoodard** [comment]
Yes! Absolutely should be global.

**Comment by webinista** [comment]
MOAR QUESTIONS! 

The glossary terms are a definition list, as they should be. Do we want them to be smaller in size? If so, what size?

**Comment by jcmeloni** [comment]
Not moving over to vets.gov-team as open PR should close this one soon  https://github.com/department-of-veterans-affairs/vets-website/pull/4606

**Comment by gnakm** [comment]
The update here is that core team is going to finalize something that will go across vets.gov. I'm in check with @melwoodard about this issue. reference: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/760
