### ISSUE TITLE
Displaying proper error when user doesn't have Rx or SM access

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#4195]
Alright, taking this from Github (https://github.com/department-of-veterans-affairs/kudos-team/issues/271). Will restate the problem here first:

- Currently a Veteran needs an MHV account to use Rx on vets.gov.  
- Right now, when a user without an MHV account goes to Rx, the error says "We couldn't retrieve your prescriptions. Please refresh this page or try again later." This error statement is false, as retrying later won't work either. 
- Instead, when a user goes to Rx, we should check their profile object to see if they have access to Rx.  If they do, we let them through normally, if they don't, we put up a message saying:

"To refill prescriptions, you need to be registered as a VA patient through MyHealtheVet.
To register, visit MyHealtheVet. If you're registered but you don't see your prescriptions here, please call the Vets.gov Help Desk at 1-855-574-7286, Monday‒Friday, 8:00 a.m.‒8:00 p.m. (ET)."

The "visit MyHealtheVet" section should link to: https://www.myhealth.va.gov/web/myhealthevet/user-registration

(note, all the above applies to SM as well, I'm just using Rx as the first example as I assume once we do it for Rx it will be trivial to add it for SM as well)

Jeff Balboni [3:13 PM]  
@ayaleloehr Yep. The RequiredLoginView component passes a prop down to its child component called `isDataAvailable` if a user fails the serviceRequired check.

[3:13]  
We handle that here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/disability-benefits/containers/DisabilityBenefitsApp.jsx

[3:14]  
It's a little odd because you have to make the child of RequiredLoginView a React component, not an element, and the prop is only passed when it's false.

**Comment by ayaleloehr** [comment]
Comment above updated with new copy from @AnitraAppa [here](https://github.com/department-of-veterans-affairs/kudos-team/issues/271#issuecomment-264284909)

**Comment by AnitraAppa** [comment]
@ayaleloehr Thanks!

**Comment by gnakm** [comment]
Tagging @melwoodard and @emilyville for awareness because today we talked about adding similar alert for users who haven't signed in LOA1 and for profile page.

**Comment by AnitraAppa** [comment]
For Secure Messaging:
"To use Secure Messaging, you need to be registered as a VA patient through MyHealtheVet.
To register, visit MyHealtheVet. If you're registered but you still can't access Secure Messaging, please call the Vets.gov Help Desk at 1-855-574-7286, Monday‒Friday, 8:00 a.m.‒8:00 p.m. (ET)."

Link "visit MyHealtheVet" to: https://www.myhealth.va.gov/web/myhealthevet/user-registration

**Comment by webinista** [comment]
I think what needs to happen is this:

1. Augment `apiRequest` to function more like [`makeAuthRequest`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/disability-benefits/utils/helpers.js).
    - At the very least, catch HTTP errors (status codes ≥ 400) and return an action that indicates that refreshing the page won't help. (Probably an `UNAUTHORIZED` action or some such.)
2. Handle the `UNAUTHORIZED` action in a reducer that updates state to return `available`, `authorized` props
3. Passed those props to`RequiredLoginView` and the subsequent `AppContent` component.

I'm sure I'm not explaining this well, but I think that's what needs to happen.

**Comment by U-DON** [comment]
^ I see you've already updated on your findings, but I think the minimum necessary change for this to work is to match Disability Claim's usage of the `isDataAvailable` prop.
