### ISSUE TITLE
Add Call center number for Rx error

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4204]
We need to add call center number to error below. 
![screen_shot_2016-11-30_at_9 27 52_am_720](https://cloud.githubusercontent.com/assets/13420618/20836306/c19372d0-b86c-11e6-8b28-1e3ea29ae257.png)

New copy:
We couldn't retrieve your prescriptions. Please refresh this page or try again later. If this problem persists, please call the Vets.gov Help Desk at 1-855-574-7286, Monday‒Friday, 8:00 a.m.‒8:00 p.m. (ET). 

cc: @U-DON ✈️ and @webinista 😷

**Comment by ayaleloehr** [comment]
@gnakm like so?

<img width="1077" alt="screen shot 2016-12-02 at 9 23 02 am" src="https://cloud.githubusercontent.com/assets/4719765/20837188/f825e4c8-b870-11e6-8e76-80d848cc4b03.png">

**Comment by ayaleloehr** [comment]
or this?

<img width="1061" alt="screen shot 2016-12-02 at 9 30 11 am" src="https://cloud.githubusercontent.com/assets/4719765/20837408/f405cfc4-b871-11e6-8b5c-626292783534.png">

Or neither?

**Comment by gnakm** [comment]
Could we have it so that the texts take up 2/3 of page width? This may cause 3rd line but that's okay

**Comment by gnakm** [comment]
How about 2nd like after "If this problem persists,"

![artboard 1](https://cloud.githubusercontent.com/assets/13420618/20838386/56bf4ce0-b876-11e6-9349-74535de357d6.png)
