### ISSUE TITLE
Button should not break to two lines

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#4217]
The `Get Started` button in the EDU Benefits form should not break to two lines. It’s behaving as if it were part of a side-by-side two-button layout. It should be as wide as its content requires to be on one line.

currently:
![](https://cloud.githubusercontent.com/assets/4106356/20844337/22df311c-b874-11e6-895b-b4bc3531b4df.png)

**Comment by ayaleloehr** [comment]
This looks resolved here: https://www.vets.gov/education/apply-for-education-benefits/application/1990/introduction

@goldenmeanie can you close if so?

**Comment by cvalarida** [comment]
I think I remember seeing it broken in IE on someone's screenshare...somewhere...but haven't gone about testing it thoroughly yet.

**Comment by J-Quag** [comment]
This happens in IE11 when you make the window super small. Is there even anything we can do about that in IE?
