### ISSUE TITLE
Date fields are wrapping to two lines on small screens

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#4223]
320px width is breaking the form. The dropdown treatment is making mm/dd fields too wide. Would suggest switching to number fields or smart text fields that can deal with jan/Jan/JAN/January/january/01/1/etc. But a short term solution would be nudging the mm/dd fields a little narrower.

Currently:
![](https://cloud.githubusercontent.com/assets/4106356/20845604/b4fa93f6-b87a-11e6-9eca-c5a5ad1b917e.png)

**Comment by leannammiller** [comment]
related to https://github.com/department-of-veterans-affairs/vets-website/issues/3080

**Comment by annekainicUSDS** [comment]
First look into changing date fields to be 3 text fields instead of 2 dropdowns and a text field. Original ticket here: https://github.com/department-of-veterans-affairs/vets-website/issues/3080

**Comment by rtluu** [comment]
the change that should be made is in ticket #3080 as Anne mentioned. closing
