### ISSUE TITLE
Ghost buttons should treated consistently

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#4224]
Ghost buttons have no background in Rx and have white background in EDU. Should be consistent.

Edu
![](https://cloud.githubusercontent.com/assets/4106356/20845827/adb95aea-b87b-11e6-837a-c2dbbf9e10d2.png)

Rx
![](https://cloud.githubusercontent.com/assets/4106356/20846038/9a07b1e4-b87c-11e6-977f-baabc3a2bc30.png)

**Comment by leannammiller** [comment]
are they using a different component?

**Comment by leannammiller** [comment]
there is an issue to update this globally, retest when global change is made

**Comment by goldenmeanie** [comment]
Global issue is #4332
