### ISSUE TITLE
Review page text treatment should use regular/bold instead of blue/grey

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#4226]
- [X] The review page lists the labels and values for all questions in the accordions. The label should change to regular weight text-grey and the values should be bold weight text-grey. 

- [ ] (While you are in there, consider a min-width for the value column so that unanswered question labels break the same way as answered.)

**Comment by cweber** [comment]
@goldenmeanie How much do you love tables? ....cause those tables need love. Min-width is the least of it.

![screen shot 2016-12-06 at 6 07 24 pm](https://cloud.githubusercontent.com/assets/417657/20947815/f29117d2-bbde-11e6-936c-0427045859ae.png)
