### ISSUE TITLE
Submit-message screen should use standard accordion styles

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#4227]
The panel currently expands into a fully grey panel. We should change it to the standard accordion treatment where the headline stays in a grey box but the body is in a grey-outlined transparent box. Also the +|- is too small right now.

Currently:
![](https://cloud.githubusercontent.com/assets/4106356/20848094/7b603b40-b885-11e6-9ec4-7ac9e9a71801.png)

Accordion style:
![](https://cloud.githubusercontent.com/assets/4106356/20848129/9804a268-b885-11e6-93e9-9080f0ca8d7c.png)

**Comment by cvalarida** [comment]
@J-Quag When we get the 1990 moved to rjsf, I don't think this will be a problem.

**Comment by rtluu** [comment]
@cvalarida does your statement above still hold true? can this ticket be closed?

**Comment by cvalarida** [comment]
@rtluu Yup. That box on the confirmation page currently looks like this in my local branch:

![image](https://user-images.githubusercontent.com/12970166/29676333-9ec71cfa-88ac-11e7-8872-e7e02ebeced7.png)

The content may have been updated in another branch. If not, I expect it should be. There's probably a ticket for that...

**Comment by rtluu** [comment]
@cvalarida sounds good, lets loop @peggygannon in to see what she thinks of this content and if she is ok with it I'll close

**Comment by cvalarida** [comment]
I'm guessing the above is vestigial, left over from where it was copied (probably the 1990N). The content should be what's currently in that box for the 1990 (or something pretty close), so if it's not up-to-date in `master`, that needs addressed, but as this ticket deals with the style, this one's good to be closed.

The content change should probably be tracked in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2821.

**Comment by rtluu** [comment]
sounds good, I'll close this one
