### ISSUE TITLE
Update Homepage links to reflect new applications

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#4228]
On the homepage:
- the card for healthcare currently points to the HCA landing page
- the "Popular on Vets.gov" links do not reflect our new apps

@melwoodard and @emilyville -- please advise on changes.

**Comment by emilyville** [comment]
Thanks @crwallace - will chase down the right new breakdown of homepage links today

**Comment by emilyville** [comment]
Chatted with @staceylanger and here are the proposed changes:

in **Popular on Vets.gov** section
- change "View education benefits by school" to "Apply for education benefits" and have it link to the form here: https://www.vets.gov/education/apply-for-education-benefits/

In the **Explore Services and Benefits** Blue Card section
- change the copy on the Health Care card to be as follows:

> Health Care
> Apply for and manage VA health care

And send the link to https://www.vets.gov/healthcare/

**Comment by akainic** [comment]
Education benefits submissions are going well, haven't had any issues in awhile. We are working through minor UI bugs, but nothing that prevents the user from submitting a form. I am comfortable with directing more traffic to it!

**Comment by emilyville** [comment]
Great! assigning back to @crwallace for moving forward with changes.
