### ISSUE TITLE
Remove jQuery from shared code

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4230]
jQuery is a pretty large dependency and so we should be careful where we use it. It would be nice if we could avoid it in common code that all the apps pull in, so that apps that do not need it don't have to add to their page weight (like edu benefits)

Currently, jQuery is used in some shared legacy code (src/js/legacy/menu.js and toggle-veterans-crisis-line.js) and for some ajax calls in src/js/login/containers/Main.jsx. It seems reasonable to convert the former to plain js and the latter to `fetch` calls, but might need some investigation.

Related to #4115.

**Comment by jbalboni** [comment]
@crwallace Are there any issues with converting the jquery ajax calls to fetch in src/js/login/containers/Main.jsx?

**Comment by webinista** [comment]
Also related to #2508

**Comment by webinista** [comment]
Pretty sure it's now safe to remove jQuery from shared code. It's still used on the GI Bill Comparison Tool. We'll need to add it there if it isn't there.

**Comment by ayaleloehr** [comment]
cc @typesend for awareness re GIBCT

**Comment by jbalboni** [comment]
@webinista I think jquery is still used in src/js/login/containers/Main.jsx?

**Comment by webinista** [comment]
@jbalboni I spoke too soon. Also added #4583 to track that as a task.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
