### ISSUE TITLE
Replace babel-polyfill with ES2015 only core-js polyfills

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4232]
We're importing babel-polyfill to polyfill ES2015 features for all browsers, but that polyfill includes polyfills for ES.next features (like observables) as well, which we don't need. It may also include ES5 and ES3 polyfills that the browsers we support do not need.

We should look into replacing babel-polyfill with the just the polyfills from core-js (which babel-polyfill uses under the hood) that we need and see if it reduces the size of app bundles notably.

Related to #4115.

**Comment by annekainicUSDS** [comment]
Change needed: investigate if ES6 polyfill can be used in place of the babel-polyfill. Work with the Core team on this as this would be a global change. Cc: @robbiethegeek-usds

**Comment by hzoo** [comment]
FYI you can use https://github.com/babel/babel-preset-env with the useBuiltIns option to only load polyfills required by the environments supported (and babel-preset-env in general for syntax) This would replace "es2015" or "latest". Let me know if you have questions or join http://slack.babeljs.io/

**Comment by jbalboni** [comment]
Thanks @hzoo! We'll check that out.
