### ISSUE TITLE
Strip down the CSS used by education benefits

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4233]
The size of the CSS file we're serving is pretty big. We should see if we can shrink it by ditching style.sass and just importing what we need.

Related to #4115

**Comment by webinista** [comment]
May be related to #3266.

**Comment by annekainicUSDS** [comment]
This will require more research, look into whether or not things are being included twice, using latest from USWDS, getting rid of Foundation, etc. (but many of these are related to what the Core team is working on).

Next steps: talk to Core team about what they're currently planning for these issues. @tiffanybbrown-va

**Comment by jcmeloni-usds** [comment]
@annekainicUSDS Howdy - w're doing a slow roll here on getting rid of Foundation and being 100% USWDS mostly because we're down to 1 F/E person.  So, no real target date per se -- @tiffanybbrown-va is working through things as carefully as she can.

**Comment by rtluu** [comment]
work is to pair down different file, issue in #3692. closing
