### ISSUE TITLE
Investigate code splitting for education benefits

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4234]
Everyone who comes to the education benefits form will start at the introduction page. This page needs very little code to render; just the common dependencies and ~25kb of application code. So, we might be able to improve the speed of the initial page load by defering loading some of the application code (and dependencies like moment.js) until the user starts the form.

Related to #4115

**Comment by leannammiller** [comment]
@jbalboni do you mind estimating effort here?

**Comment by jbalboni** [comment]
I'm going to close this, as it's not going to be useful now with the way we're writing forms.
