### ISSUE TITLE
Add dental service for Health detail pages

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4237]
We need to add dental services on health detail pages under services the way we have for mental and primary care. 

![](https://cloud.githubusercontent.com/assets/13420618/20798563/431c597c-b7ad-11e6-91a5-e19f64d556bd.png)

**Comment by bshyong** [comment]
@gnakm are dental services always available at all health facilities? If Dental care is listed in the data from the API, it should automatically show up

**Comment by NatalieEMoore** [comment]
Dental services are not available at all health facilities.  Geobisl is working on refreshing the VHA service data to include dental.  It's currently just at mental health and primary care.  @patrickvinograd has the refresh happened yet?

**Comment by patrickvinograd** [comment]
I don't see Dental Services in VHA data yet. All facilities are blank for the DentalServices attribute.

**Comment by patrickvinograd** [comment]
This query should start listing facilities when the data is populated.

https://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VHA_Facilities/FeatureServer/0/query?where=DentalServices%3D%27YES%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=StationName%2C+StationNumber%2C+DentalServices&returnGeometry=false&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=pjson&token=

**Comment by bshyong** [comment]
I now see that there are some facilities showing up in the ArcGIS link above. Are they supposed to automatically show up under services["health"] or do we need to add them to a whitelist?

For example Togus VA Medical Center shows up in the ArcGIS link but the facility object from vets-api does not have Dental Services

https://api.vets.gov/v0/facilities/va/vha_402

**Comment by patrickvinograd** [comment]
They are purposefully not showing up - we need to whitelist them. This was by request of @NatalieEMoore so she could coordinate with stakeholders before the data started showing up.

@NatalieEMoore let me know when we can flip the switch for dental.

**Comment by patrickvinograd** [comment]
Not sure where this ticket got lost along the way, but dental services are enabled for some time now, it was around the beginning of the year if I remember correctly.
