### ISSUE TITLE
Find all incorrectly spelt MyHealtheVet on Vets.gov

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4243]
Please list all the pages on Vets.gov that doesn't spell MyHeath _**e**_ Vet the correct way. Thank you 
Related to: https://github.com/department-of-veterans-affairs/kudos-team/issues/272#issuecomment-264897050

**Comment by gnakm** [comment]
@AnitraAppa and @melwoodard  for awareness

**Comment by crwallace** [comment]
@gnakm -- is this still a relevant issue?

**Comment by gnakm** [comment]
No I think we're good on this now. Closing.
