### ISSUE TITLE
"Signing in to vets.gov" pop up stays up indefinitely

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#4249]
Steps to reproduce:
- Go to https://www.vets.gov/profile/
- Click Sign in
- Click Google login (already logged into this google account in this browser, so nothing more needed). This takes you to the profile page logged in as LOA1.
- Click "verify your account"
- Click to allow pop up (blocked pop up tracked in #4247)
- Click Continue to send 2FA code. Enter 2FA code.
- Click to send 2FA code again (issue tracked in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/482)
- Enter 2FA code again. Pop up changes to saying "signing in to vets.gov" but does not disappear:

![screen shot 2016-12-05 at 2 48 01 pm](https://cloud.githubusercontent.com/assets/4719765/20900563/a94632de-bafc-11e6-9aca-607e34b3ae9a.png)

If after this happens, I close this pop up and refresh https://www.vets.gov/profile/, I _am_ successfully logged in at LOA3. 

This is on Chrome Version 54.0.2840.98 (64-bit) and has occurred both on and off the VA network.  

cc @jcmeloni to see if you can replicate as well.

**Comment by jcmeloni** [comment]
@ayaleloehr Did you enter the same, or the 2nd, 2fa code?

**Comment by ayaleloehr** [comment]
2nd code

**Comment by jcmeloni** [comment]
Cool.  Just removing one more variable. :)

**Comment by ayaleloehr** [comment]
Can't reproduce anymore. closing. Feel free to reopen if anyone reproduces.
