### ISSUE TITLE
"Sign in" link pops up quickly on profile page when logged in

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#4250]
When a user is already logged in (either LOA1 or LOA3) and they refresh the profile page, the "sign in" and "create account links" pop up briefly before the page automatically moves to the profile page.  

This likely won't happen locally when running the API locally as well, as I believe it's an artifact of a slow network connection. The easiest way I have found to replicate this is to throttle your network speeds to 2G or 3G. I can replicate both on and off the VA network by slowing the network connection down. 

SM has a similar issue and @U-DON did something to change the default state I believe so that this didn't happen anymore. I can't seem to find that PR right now though. @U-DON do you know where that PR is, in case a similar approach could happen here?

cc @crwallace as all things profile page end up your way eventually.

**Comment by jcmeloni** [comment]
I don't have to throttle my connection at home (it's Comcast...) to see it.  FWIW.

The sign in page also flashes briefly when going to any LOA3-gated application after already having been logged in.  Probably same root cause but leave that up to Courtney to decide/change title if warranted.

**Comment by ayaleloehr** [comment]
@jcmeloni it does this for SM today?

**Comment by jcmeloni** [comment]
Yes, I observed this at home this morning. I can try it here on my hotspot if you want (not va network, but still a latency-laden network)

**Comment by jcmeloni** [comment]
Reproduced here.  Click link to "message your provider" (or any of the other gated apps) and get: 
* loading your info spinner
* sign in to vets.gov
* lag
* appropriate message about not finding me w/ that info

devtools snippet attached if you can see anything from this, lag-wise

![lag](https://cloud.githubusercontent.com/assets/347178/20902036/4aa10cca-bb03-11e6-9ff7-a7cd3a60b840.JPG)

**Comment by ayaleloehr** [comment]
@U-DON any thoughts on how to fix this for Rx / SM?

**Comment by U-DON** [comment]
I haven't encountered this lately, so I don't have an idea of what's causing it yet.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
