### ISSUE TITLE
HCA notifications bar is way intense, could we make it consistent with edu form?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#4257]
Do you think we could treat this notification the same way on both pages? I know that HCA traffic is different - meaning we're sending folks here thinking they might find more and the alert NEEDS to be more prominent, but it's still kind of intense for what we need and I think the way we address is on the EDU form is better and likely just as effective.

Thoughts @melwoodard @staceylanger @akainic ?

<img width="1091" alt="screen shot 2016-12-05 at 5 24 10 pm" src="https://cloud.githubusercontent.com/assets/1307774/20904996/ffbd233a-bb0f-11e6-9942-adb32074594c.png">
<img width="1115" alt="screen shot 2016-12-05 at 5 24 15 pm" src="https://cloud.githubusercontent.com/assets/1307774/20904997/ffc88f68-bb0f-11e6-81c4-04fa22ed4cf9.png">

**Comment by akainic** [comment]
I'm fine with that!

**Comment by gnakm** [comment]
Chiming in per Mel's request. 
Yes, I agree that it should be like the HCA one. We made changes for Rx and SM as well. I think keeping that first line bold will help it prominent yet at the same time not so alarming. 

<img width="974" alt="screen shot 2016-12-05 at 5 55 39 pm" src="https://cloud.githubusercontent.com/assets/13420618/20905990/1350a5bc-bb14-11e6-9c1d-5530045a6c21.png">

**Comment by gnakm** [comment]
Okay final verdict on this banner. @melwoodard and I thought it would be even better if the banner is right above the apply button, so that users can read it before the call to action. 

![artboard](https://cloud.githubusercontent.com/assets/13420618/20937537/5addab2c-bbb5-11e6-81dc-daa8ad5cc224.png)

@akainic Assigning this to you! You can re-assign to whoever you think can best deliver this change.

**Comment by emilyville** [comment]
Awesome! 👍 and for fun also :taco: 

assigning to @akainic to reassign and prioritize.

**Comment by leannammiller** [comment]
@cagedcrown - can you confirm status?

**Comment by leannammiller** [comment]
@cagedcrown can you provide status please?

**Comment by annekainicUSDS** [comment]
PR is open, needs to be updated with the latest comment from Jeff.
