### ISSUE TITLE
Sign in link not visible when session expires

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/vets-website#4268]
When a user's session expires in Redis the 'Account' and 'Sign Out' links are still displayed but the 'Sign In' link is not.

Steps to reproduce:
1. Login
1. Navigate to /profile
1. Expire the session (in a terminal: `$ redis-cli`, `> DEL your_session_key` or `> FLUSHALL`)
1. The body of the page displays 'Sign in to your Vets.gov Account' but the header does not have a 'Sign In' link.

![screen shot 2016-12-06 at 9 31 58 am](https://cloud.githubusercontent.com/assets/283834/20936293/f3367562-bb96-11e6-86ef-efbe0faf6c93.png)

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
