### ISSUE TITLE
Remove all gray bars with Apply CTA from top

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#4274]
Closing this convo over here with the outcome:
https://github.com/department-of-veterans-affairs/vets-website/issues/4259

Remove all top instances of the button inside the gray bar, if it's NOT elsewhere on the page move it to be at the bottom of the page in the green ui element. (Often it's on both at this time, and thencan simply be removed)

**Comment by emilyville** [comment]
@robbiethegeek / @crwallace / @jcmeloni  
I'd love your help in prioritizing this ticket as login stuff has made this a UI problem. That might mean handing it off to individual project teams for implementation, or just having one person go through site wide. Thoughts?

**Comment by jcmeloni** [comment]
@crwallace @webinista Let's talk about this in sprint planning today 1/3

**Comment by jcmeloni** [comment]
Holding on this, @emilyville to write ticket for reverting design first.

**Comment by emilyville** [comment]
This should happen before #4564, so not totally clear on the delay for not having created this issue. Nonetheless, here is is!

https://github.com/department-of-veterans-affairs/vets-website/issues/4564

**Comment by jcmeloni** [comment]
Thanks! My comment on 3 Jan was based on what I thought I heard you say in our call at 11am that day. My bad.

**Comment by jcmeloni** [comment]
Intention is for Core Team to tackle in Sprint 17-2 unless people have bandwidth in 17-1.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
