### ISSUE TITLE
"visit va.gov" link in header needs white external link icon

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/vets-website#4278]
external link icon isn't showing up which makes it look like there's a big space before the period

![image](https://cloud.githubusercontent.com/assets/11219417/20941916/c772d2ce-bbc6-11e6-8cbe-bb921805f01a.png)

**Comment by crwallace** [comment]
This looks like it is happening as well in the footer.

CSS looks like this:
```
[href^="http://"]:not([href*="vets.gov"]),
[href^="https://"]:not([href*="vets.gov"]) {
  background-image: url(/img/icons/exit-icon.png);
...
}
```

I think we need to exclude va.gov as well.
