### ISSUE TITLE
Improve build times

### ISSUE THREAD

**Issue by aub** [department-of-veterans-affairs/vets-website#4279]
Build times for this project have gotten to be around 15 minutes, and it would be nice to try to speed that up. I've looked into it a little bit, but it would be nice if someone with more experience around JS tooling could take a crack at it. Some avenues I found that might be worth exploring:

* [Parallelize Nightwatch](#4282) 

* [Discovery of browser startup during E2E](#4283)

**Comment by alexose** [comment]
The biggest improvement we could make to the non-E2E part of the build would be to implement [this plugin](https://github.com/mzgoddard/hard-source-webpack-plugin), which I've discussed a bit in #2753.

Another thing I would advise is that anybody testing out the build process should **fork the repo to their personal account, and set up a (free!) Travis account under their own name**.  With long build times and a limited number of travis workers shared between all of DSVA, it can become downright impossible to test during peak hours.

**Comment by aub** [comment]
FYI, the static asset creation process is less than a third of the total time for a full build, with the E2E tests taking the longest chunk of time, followed by the 508 tests.

**Comment by alexose** [comment]
You beat me to it :)

Specific numbers:

| Task  | Time |
| -- | -- |
| Install Dependencies | ~80s |
| Build | 3m 22s |
| Unit | 40s |
| E2E | 4m 44s |
| 508 | 3m 1s |

**Comment by jcmeloni** [comment]
Not moving over to vets.gov-team as this is captured in master ticket over there and will close it when that closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/578
