### ISSUE TITLE
Implementation - Parallelize Nightwatch

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-website#4282]
Nightwatch supports running multiple tasks in parallel, however when I turned that on the tests started failing. I'm not sure what caused the failures, but it did seem to speed thing up a little.

**Comment by alexose** [comment]
I dug into this a little more-- There's only one test that [fails](https://travis-ci.org/department-of-veterans-affairs/vets-website/jobs/182083399#L1878), and even that one [doesn't fail all the time](https://travis-ci.org/department-of-veterans-affairs/vets-website/jobs/182083400):

`test/disability-benefits/e2e/01.claim-status.e2e.spec   ✖ Expected element <.five.last.step.section-current> to be present - element was not found  - expected "present" but got: "not present"`

My guess is that it's timing-related.  Will try to recreate locally.

**Comment by robbiethegeek** [comment]
- new config done
- still broken tests

**Comment by alexose** [comment]
^^^ That.

The failing tests are a bit tricky to debug, but I'm making progress.  Should be fixed EOD if I had to guess.

**Comment by alexose** [comment]
Sorry, forgot to post an update on this.

I ended up focusing on the [switch to Electron](https://github.com/department-of-veterans-affairs/vets-website/issues/4409) and making the tests less brittle overall.  Will return to this as soon as `e2e-electron` is merged.

**Comment by alexose** [comment]
This was completed in https://github.com/department-of-veterans-affairs/vets-website/pull/4481.
