### ISSUE TITLE
During e2e tests browser may be starting up for each test.

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-website#4283]
There's some logging during the test execution that made me think maybe the headless browser or the connection to it is being bootstrapped with each spec. If that's the case, hopefully we could make it only happen once.

**Comment by jcmeloni** [comment]
Not moving over to vets.gov-team as this is captured in master ticket over there and will close it when that closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/578
