### ISSUE TITLE
Field labels / data should be stacked on mobile

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4299]
Labels/data are too squeezed on mobile. They should be stacked on narrow screens.

This might require rebuilding as a definition list `<dl>`

![screen shot 2016-12-08 at 12 13 26 pm](https://cloud.githubusercontent.com/assets/417657/21019826/e9168982-bd3f-11e6-9645-10c12160e23a.png)

**Comment by J-Quag** [comment]
This looks to be the 1990, do we know if this happens with the new schema?

**Comment by jbalboni** [comment]
I just merged this on the rjsf forms, so I think we can close it.
