### ISSUE TITLE
Consider removing moment.js in favor of date-fns

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4314]
Related to #4115 

Moment.js is a pretty big dependency and we're not using most of it. We could consider using [date-fns](https://date-fns.org/), which lets you pull in just the date functions you need.

**Comment by webinista** [comment]
Secure messaging, and IIRC prescriptions also uses Moment.js. The SM date picker also has it as a dependency. Tagging @U-DON and @bshyong for awareness.

Will raise the date picker issue with the core team's designers.

**Comment by ayaleloehr** [comment]
Adding a kudos label, as the above comment makes it sound like this will need to be done on the kudos side as well.

**Comment by leannammiller** [comment]
@aub could you please estimate?

**Comment by leannammiller** [comment]
@aub pinging for status on this ticket.

**Comment by leannammiller** [comment]
Leanna will check in with @jbalboni re: this ticket

**Comment by timwright12** [comment]
Closing due to age and inactivity
