### ISSUE TITLE
what steps do you take when you add a question to a form?

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4317]
document these steps and try to minimize

**Comment by jbalboni** [comment]
1. Add the field to the veteran object in utils/veteran.js.
2. Add the field to the veteranToApplication function in veteran.js if necessary.
3. Add the field to the list of fields for its page in reducers/uiState.
4. Add the field to the component for its page and choose the correct common form element component and the correct validation.
5. Add the validation to utils/validations.js for the correct page.
6. Add the field to the review component for its page.
7. Write tests.

**Comment by jbalboni** [comment]
@akainic Did I miss anything?

**Comment by jbalboni** [comment]
I think this is done.
