### ISSUE TITLE
Warn devs if not using correct versions of node and npm

### ISSUE THREAD

**Issue by alexose** [department-of-veterans-affairs/vets-website#4326]
We're using slightly out-of-date versions of node and npm.  This is fine, but it's possible that devs will run into subtle compatibility issues.  

Given that `.nvmrc` doesn't handle npm, it might be helpful to do a quick version check as part of `npm run build` or `npm run watch`.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
