### ISSUE TITLE
Change outline button default background to transparent

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#4332]
Issue moved from https://github.com/department-of-veterans-affairs/sunsets-team/issues/265

Change the default background of `.usa-button-outline` from white to transparent.

From claim status issue above: 

<img width="685" alt="transparent_backgrounds_ _issue__265_ _department-of-veterans-affairs_sunsets-team" src="https://cloud.githubusercontent.com/assets/4106356/21109083/5a21b408-c04c-11e6-9fb2-163a00eb0042.png">

**Comment by melwoodard** [comment]
cc @jbalboni @suzchap to test claim status once this has been implemented.

cc @goldenmeanie @cweber @akainic we're making transparent button background a global change since all the apps are overriding the default white background, so you shouldn't need to make a styling change specific to Edu.

**Comment by webinista** [comment]
Healthcare has slightly different [outline button styles](https://www.vets.gov/healthcare/apply/application/veteran-information/birth-information). I'm going to assume that these should be brought in line with other buttons on the site. @melwoodard Please correct me if this is not the case.

![screen shot 2016-12-16 at 3 01 52 pm](https://cloud.githubusercontent.com/assets/354277/21281338/ace3a7e4-c3a0-11e6-8ce7-ad945d6505b6.png)

**Comment by melwoodard** [comment]
@webinista that's correct!
