### ISSUE TITLE
PLACEHOLDER: Backend Discovery

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4340]

**Comment by akainic** [comment]
Meeting already happened. Add notes here.

**Comment by akainic** [comment]
Meeting notes:
- 1995 is on the same system as the 1990 (same as other education benefits forms)
- Ultimate goal is to spit out a batch file like we did for the 1990
- Same spool for all forms
- Same Admin functionality for the other education forms as the 1990
- Reporting: ask Shay for how the reports should look
