### ISSUE TITLE
Change prescriptions modal title color?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4349]
In light of department-of-veterans-affairs/messaging-fe#197, should the prescription name change colors as well?

![screen shot 2016-12-12 at 4 29 49 pm](https://cloud.githubusercontent.com/assets/354277/21122654/69e8b508-c088-11e6-8644-3b79e52c1fbc.png)

If the answer is "no," it's safe to just close this issue.

**Comment by gnakm** [comment]
@webinista Yes could we change the color here as well? 

My rationale being that on mobile, a user might click on it by accident, losing place on the site and in general haven't seen the need to go to a detail page from this point. 

Could we make sure field text patterns follow this: https://github.com/department-of-veterans-affairs/vets-website/issues/4143
