### ISSUE TITLE
Add privacy agreement to HCA

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#4366]
We need to add a privacy agreement to the end of the form right before submit (at the bottom of the Review page). The following is needed:
- [x] We need to include a checkbox with language along the lines of "I have read and accept the privacy agreement" (final language still to be drafted).
- [x] Below the checkbox needs to be a link to the privacy policy, which also needs to be written and added to Vets.gov (tracking in #4368)
- [x] The checkbox needs to be a required field. This requirement needs to be reflected both in the front-end and back-end (json schema?) validations of the form. But the value of the checkbox does not need to be submitted to the VA back-end service.

**Comment by jcmeloni** [comment]
@akainic confirmed 👍 on staging!!
