### ISSUE TITLE
facility locator mapping St. Petersburg, FL to Manhattan

### ISSUE THREAD

**Issue by jenny-h-l** [department-of-veterans-affairs/vets-website#4398]
From Jenny Heiland-Luedtke:

When I type
 
St. Petersburg, FL
 
OR
 
Saint Petersburg, FL
 
In the “Enter Street, City, State or Zip” box on the locator, I get results in Manhattan. Verified on more than one browser and with a colleague in the office.

**Comment by bshyong** [comment]
This might be a little out of our control because we are using a 3rd party for the reverse geocoding—translating search strings into coordinates. It looks like `saint petersburg, florida`, `st. petersburg, florida`, `saint petersburg`, and `st petersburg` all work but including the abbreviation FL does not

**Comment by jenny-h-l** [comment]
@bshyong : are you saying that only FL for florida is broken or all 2 character state abbreviations are broken?

**Comment by patrickvinograd** [comment]
It's just FL, and just st. petersburg (or just certain cities). For example, Miami, FL works fine. I think our only recourse is to report a bug to mapbox. Ben, I think you'd be in the best position to do so given that you know how you are using their API.

**Comment by bshyong** [comment]
I will file an issue with the Mapbox team

**Comment by bshyong** [comment]
This issue has been resolved this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/4567

Mapbox was returning POI results which ranked higher in relevance for this particular Saint Petersburg query
https://www.yelp.com/biz/saint-petersburg-manhattan
