### ISSUE TITLE
Login related errors from Google Analytics

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4402]
We were looking in GA and found some errors that look login related coming up in the edu-benefits bundle: https://analytics.google.com/analytics/web/#report/content-event-events/a50123418w128717608p132469923/%3F_u.date00%3D20161215%26_u.date01%3D20161215%26_r.drilldown%3Danalytics.eventCategory%3AJavaScript%20Error%2Canalytics.eventAction%3Ahttps%3A%2F%2Fwww.vets.gov%2Fgenerated%2Fedu-benefits.entry.js%26explorer-table.plotKeys%3D%5B%5D/

Here's a screenshot:

![screen shot 2016-12-15 at 1 17 29 pm](https://cloud.githubusercontent.com/assets/634932/21236406/df8e44ac-c2c8-11e6-938d-fdbc44a688d5.png)

There's no line number information. They all appear to be from users on IE11.

We don't use the login view, so I think these would be coming from the widget in the top right?

**Comment by jbalboni** [comment]
FYI @crwallace

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
