### ISSUE TITLE
Standardize loading messages for Rx

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-website#4408]
Loading prescriptions (both in "Refill prescriptions" and "History"): "Loading your prescriptions..."

Loading prescription detail: "Loading your prescription..."

Submitting refill: "Submitting your refill request..."

**Comment by U-DON** [comment]
@gnakm Just wanted to confirm the actual wording on the loading messages. Let me know if the above are not what they should be.

Currently, there's an inconsistency where the loading of prescriptions are in the format of "is loading your prescription(s)...", and the refill submission is as written above, but the work for this issue will fix that.

**Comment by gnakm** [comment]
@U-DON Thanks for this. 

What you have is correct:
Loading prescriptions (both in "Refill prescriptions" and "History"): `Loading your prescriptions...`
Loading prescription detail: `Loading your prescription...`
Submitting refill: `Submitting your refill request...`

I filed an issue somewhere. May have gotten lost or closed about taking all of the `is` and making sure all the messages end with `...`

Can you confirm that these are the pages that have latency? The only other page is glossary but can't imagine there ever being a lag there.

**Comment by U-DON** [comment]
@gnakm Yup, these should be the only pages/actions that have latency. Glossary isn't loaded from the API, so it won't need a loader.
