### ISSUE TITLE
Use electron in place of phantomjs

### ISSUE THREAD

**Issue by alexose** [department-of-veterans-affairs/vets-website#4409]
Not only is PhantomJS not being super actively maintained, it is also [notably slower](https://github.com/segmentio/nightmare/issues/484) than Electron.

It should be pretty straightforward to swap PhantomJS with Electron without having to change the tests much.  However, due to subtle differences, we will have to repair some failing tests.

**Comment by alexose** [comment]
New implementation is up and being tested on the `e2e-electron` branch.

**Comment by alexose** [comment]
I've noticed two things that cause Electron to fail in places where Phantom didn't:

1) Click events require that the clicked element isn't overlapped by any other element.  This is good to fix anyway.

2) Our smooth scrolling plugin causes some timing issues.  I think this is because Electron is so much quicker to load pages.  Anyway, I've implemented a way to override smooth scrolling for our E2E tests.

**Comment by alexose** [comment]
All tests are passing locally but continue to have issues in the Travis environment.  The good news is that it's at least [25% faster](https://travis-ci.org/alexose/vets-website/jobs/184390855#L2290) with a lot more room for improvement.

**Comment by alexose** [comment]
Travis [appears](https://travis-ci.org/alexose/vets-website/jobs/184614274#L2360-L2497) to be tripping over selectors for certain form elements.  This isn't happening locally.  I'm going to try to debug this in docker.

**Comment by alexose** [comment]
Successfully replicated it in docker.   Definitely looks like some extra complexity introduced by `xvfb`.

**Comment by alexose** [comment]
Turns out that using .setValue doesn't trigger the `change` event, and it's not really possible to trigger `change` programmatically in React.

So, I wrote a snippet that uses the arrow keys instead of the mouse.  This works fine in xvfb, but not in OSX.  :facepalm:

There are still a couple of other issues I need to tackle, most importantly figuring out what is causing HCA not to validate: https://travis-ci.org/alexose/vets-website/jobs/185638483#L2492-L2524

**Comment by alexose** [comment]
Only one set of problems left at this point, which is the edit screen test in `est/hca/06-edit-submission.e2e.spec.js`.  It's almost certainly a timing issue.

**Comment by alexose** [comment]
Almost there, but I'm still seeing an issue with the accessbility tests.

**Comment by jcmeloni** [comment]
Not moving over to vets.gov-team as this is captured in master ticket over there and will close it when that closes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/578

**Comment by alexose-gov** [comment]
Done!

**Comment by jcmeloni-usds** [comment]
Yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaay!!!!! 🎉
