### ISSUE TITLE
Prescription list sorting for desktop and mobile

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4411]
After the prescriptions design/ux audit with the core team, we discussed the same issue you guys brought up in this [PR about rx list view](https://github.com/department-of-veterans-affairs/vets-website/pull/4391) of how the sort option is not consistent. Mobile is missing ascending/descending option. 

Changes: 
`Last submit date` --> `Submit date   `
`Last fill date` --> `Fill day`
Next to each dropdown, add links to view Newest to Oldest and Oldest to Newest
<img width="679" alt="screen shot 2016-12-15 at 8 19 10 pm" src="https://cloud.githubusercontent.com/assets/13420618/21248251/c3d60840-c303-11e6-8aef-45aa55d10594.png">

**Prescription refill page card view (desktop)**: Dropdown 
We are changing to dropdown because at most recent testing, users missed sort by links. 
- Prescription name (default)
- Facility name
- Submit date

<img width="1117" alt="screen shot 2016-12-15 at 8 17 49 pm" src="https://cloud.githubusercontent.com/assets/13420618/21248233/98a0cb06-c303-11e6-9f3b-6c88cfd93077.png">

**Prescription refill page list view (desktop)**: Embedded sort in table
- Prescription name (default)
- Facility name
- Submit date
<img width="750" alt="screen shot 2016-12-15 at 8 22 07 pm" src="https://cloud.githubusercontent.com/assets/13420618/21248310/32c405e0-c304-11e6-936b-b51a27b4d8d6.png">

**Prescription history page (desktop)**: Embedded sort in table
<img width="636" alt="screen shot 2016-12-15 at 8 23 20 pm" src="https://cloud.githubusercontent.com/assets/13420618/21248336/5b9f9cfe-c304-11e6-8361-dffa40ca43d5.png">
- Submit date (default)
- Prescription name
- Fill date
- Prescription status

**Prescription refill page (mobile)**: Dropdown 
<img width="301" alt="screen shot 2016-12-15 at 8 26 59 pm" src="https://cloud.githubusercontent.com/assets/13420618/21248412/ee2ee354-c304-11e6-97af-ffb6a4a837d4.png">
- Prescription name (default)
- Facility name
- Submit date

**Prescription history page (mobile)**: Dropdown 
<img width="300" alt="screen shot 2016-12-15 at 8 27 11 pm" src="https://cloud.githubusercontent.com/assets/13420618/21248425/fce101ac-c304-11e6-91d0-2439c27c3bed.png">
- Submit date (default)
- Prescription name
- Fill date
- Prescription status

I wanted to break it down by pages and device. Before breaking this down to smaller issues, wanted to give @U-DON and @bshyong a bigger picture context since it feels like a lot of the issues are intertwined.

**Comment by U-DON** [comment]
@gnakm I'm confused by what 'Newest to oldest' or 'Oldest to newest' are supposed to mean in the context of 'Prescription name' and 'Prescription status', which are text fields (not dates). And is the one that's selected of those links supposed to be bolded?

**Comment by gnakm** [comment]
@U-DON You bring up a good point. Here is my brain dump in the order of what I prefer most to least. Would love to hear your thoughts from a technical perspective!

**Option A**
Have all the ones with dates (submit, fill) show `Newest to Oldest` | `Oldest to Newest`
and ones with names (prescription name, facility, status) show `A-Z` | `Z-A`

I prefer this option because there is a way higher chance that users will always opt for Newest and Alphabetical order and the language is content specific. 

**Option B**
Show `Ascending` | `Descending` for all the choices with perhaps and up and down arrow next to each word. This unifies things but not crazy about the idea because the language is very vague and might not be meaningful to users. 

**Option C**
Drop down with all the options. 
6-8 options is not optimal but it is the least prone to confusion because it's straightfoward. I generally don't like the idea of giving users that many choices.

**Comment by gnakm** [comment]
Also, some of the mocks here say "Last submit... last fill." Please ignore those. Option A, B, and C all suggest that we now have the choice to see things in ascending and descending order, so take out anything that says last!

**Comment by bshyong** [comment]
@U-DON Let me know if you have any preference for any of the implementation options. I wanted to take a look at some Secure Messaging issues today to get more familiar with that app and will probably tackle this next.

**Comment by U-DON** [comment]
Option A sounds best in terms of usability.

**Comment by webinista** [comment]
Related to #4427.

**Comment by Drakenhart** [comment]
2 Questions: In regards to what is on the playbook - 
1) Would the RX cards look a lot like the definition lists, was this intentional (to be styled in a similar manner)?
2) Also, should this be what others do with similar kinds of data information?

I ask because it's a pattern I've noticed and couldn't find clarity anywhere else.
