### ISSUE TITLE
List view missing fill date

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4412]
<img width="738" alt="screen shot 2016-12-15 at 8 34 15 pm" src="https://cloud.githubusercontent.com/assets/13420618/21248570/e0ff39d0-c305-11e6-9a3b-d078a4ab067d.png">

We need to add a fill date column for Rx refill list view.

**Comment by U-DON** [comment]
The mock in #4411 has 'Last submit date' and 'Last fill date' rather than 'Submit date' and 'Fill date'. Which one should it be?

**Comment by gnakm** [comment]
This mock is accurate. We should take out `last`.
