### ISSUE TITLE
Simplify and reduce specificity of #rx-history selector

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4422]
These selectors can be simplified.

```
#rx-history table td:nth-child(3) a, 
#rx-history table td:nth-child(3) .edit-checkbox label, 
.edit-checkbox #rx-history table td:nth-child(3) label
```

**Comment by eli-lewis** [comment]
@tiffanybbrown-va is there an update on this?

**Comment by tiffanybbrown-va** [comment]
No. No update. If someone else wants to take it, great. If we want to close for the sake of clearing the queue, that's fine too.

**Comment by eli-lewis** [comment]
@ayaleloehr ^^^

**Comment by ayaleloehr** [comment]
Redirecting to @bshyong . If he thinks this is worth doing, we should do it. if not, we should close.

**Comment by ayaleloehr** [comment]
pinging @bshyong on this to close if he doesn't think it needs to be done.

**Comment by bshyong** [comment]
Closing this out for now
