### ISSUE TITLE
Hide list / card toggler on small screens [Was: Prescription list view needs labels]

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4427]
When toggling into list view, the table header labels disappear. Each cell loses its label.

![screen shot 2016-12-16 at 6 03 00 pm](https://cloud.githubusercontent.com/assets/354277/21283590/f016e2d8-c3b9-11e6-8676-91cfa322f8f6.png)

Related to #4411

**Comment by bshyong** [comment]
do we need to manually add labels on the left for mobile? I'm using the common sortable table component and it looks like it collapses to this type of card view on small screens. cc @gnakm

**Comment by bshyong** [comment]
Another option is to disable the list view altogether on mobile/smaller screens

**Comment by webinista** [comment]
I think disabling it on smaller screens is the way to go. It's basically the same as the card layout at that point. Otherwise, I think we can use `::before` to inject those labels.

**Comment by bshyong** [comment]
I agree with hiding it—on mobile, the only view option should be the default `card` view. However, I can't think of a way to have the component switch to `card` when it is resized to a smaller window unless we attach an onResize listener.

**Comment by gnakm** [comment]
Seeing this now guys. Let's disable it on small screen because it is literally the same information in the same order as cards and users had more trouble with the desktop view than mobile view.

**Comment by U-DON** [comment]
@bshyong Can this be done by only using CSS classes? Set a class for the view state, say `rx-refill-table-view`, `display: none` for the card section under that container (only on desktop), and `display: none` for the table section always. Just an initial thought, not sure if it works.
