### ISSUE TITLE
New card design 

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#4436]
Below is the new design for the cards on the homepage, if there's any copy that differs from what we already have, please go with what we have as I might have old copy. 

The cards on the homepage will include icons, but the cards in the interior pages won't. Here are the homepage cards:
![cards-with-icons](https://cloud.githubusercontent.com/assets/103496/21334185/3a2348a6-c60a-11e6-95f9-3120e69a2e8e.png)
Note that I increased the padding to 30px here. The gold top border is 4px tall. I kept the font sizes the same and used font awesome for 3/4 of the fonts:
- ![image](https://cloud.githubusercontent.com/assets/103496/21333731/d26fa874-c606-11e6-88f8-34be9519f1b3.png) fa-suitcase
- ![image](https://cloud.githubusercontent.com/assets/103496/21333734/e8304ad8-c606-11e6-8fb1-c410d2bc7d46.png) fa-graduation-cap
- ![image](https://cloud.githubusercontent.com/assets/103496/21333746/0c9838fe-c607-11e6-8318-6b819185dfb2.png) fa-user-md

We couldn't find one that fit Disability Benefits very well, so I modified a font awesome one:
![image](https://cloud.githubusercontent.com/assets/103496/21333786/57cc43b0-c607-11e6-8c4b-d81b631d3e9d.png)
I put the svg as a zip since GH doesn't allow svg for issues. Let me know if that doesn't work. 
[disability-benefits.svg.zip](https://github.com/department-of-veterans-affairs/vets-website/files/662483/disability-benefits.svg.zip)
Let me know if you need anything else to be able to use this icon. 

Here's what the card looks like for the interior pages without icons:
![cards-without-icons](https://cloud.githubusercontent.com/assets/103496/21334190/446d6576-c60a-11e6-9630-157402656448.png)

**Comment by emilyville** [comment]
Assigning to @jcmeloni for triage!

**Comment by jcmeloni** [comment]
@crwallace @webinista Let's talk about this in sprint planning today 1/3

**Comment by jcmeloni** [comment]
Intention is for Core Team to tackle in Sprint 17-2 unless people have bandwidth in 17-1.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
