### ISSUE TITLE
"fatal: No url found for submodule path 'schema' in .gitmodules" when running "git submodule init; git submodule update"

### ISSUE THREAD

**Issue by axle07** [department-of-veterans-affairs/vets-website#4463]
I just cloned the repo, as described [here](https://github.com/department-of-veterans-affairs/vets-website#i-want-to), and got the following error on step 3:

"fatal: No url found for submodule path 'schema' in .gitmodules"

**Comment by jcmeloni** [comment]
Sorry, can't reproduce this.  If you run into it again please create an issue and paste in the commands and responses leading up to the error. Thanks!
