### ISSUE TITLE
Create terms & conditions based on MHV's draft

### ISSUE THREAD

**Issue by AnitraAppa** [department-of-veterans-affairs/vets-website#4470]
Creating issue to track terms & conditions work, as discussed with @staceylanger last week. (Want to make sure I don't forget about this!)

Notes:
- Existing Vets.gov users accepted MHV terms
- Need to create combined T&C for new Vets.gov users who don't have an MHV account
- MHV has separate T&C for each of the products on their site right now. Working on combined version of all T&C's. 
- I'll take the MHV combined T&C draft I have from Stacey, take a pass on making it work for Vets.gov and generally cleaning it up. Will work with Nick from there as well.

**Comment by jcmeloni** [comment]
FWIW during our Privacy/ATO work last week, we created a Vets.gov privacy policy and got it in the site that included  any relevant info from MHV generally.  Again, just FWIW. If it changes, it has to go back through the VA Privacy Office. cc @staceylanger

**Comment by ayaleloehr** [comment]
@AnitraAppa are there next steps?

cc'ing @mikeusdsva here as well.

**Comment by AnitraAppa** [comment]
Thanks for following up --- need to check in on how the larger MHV conversations went while I was out. @mikeusdsva I'm still having trouble with Slack, want to connect over email? Can come by 1800G tomorrow morning too.

**Comment by mikeusdsva** [comment]
Let’s set some time tomorrow.

**Comment by AnitraAppa** [comment]
Sounds like this is still mostly on the back burner -- will connect with @NatalieEMoore to see if any of the work related to medical authorization affects this when she's back next week.

**Comment by NatalieEMoore** [comment]
I'm back if you still need to chat about this @AnitraAppa!

**Comment by ayaleloehr** [comment]
@NatalieEMoore I believe this is being tracked elsewhere. can this be closed?
