### ISSUE TITLE
Make TabNav a common component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4473]
- [ ] Copy `disability-benefits/components/TabNav.jsx` to `common/`.
- [ ] Augment it to support a `className` property to enable additional classes
- [ ] Update the following files to use common component
    - [ ] `rx/containers/Main.jsx`
    - [ ] `disbility-benefits/components/ClaimDetailLayout.jsx`
- [ ] Move `test/disability-benefits/components/TabNav.unit.spec` to a common test directory and update the path.

**Comment by webinista** [comment]
Need to determine whether these are dissimilar enough to justify multiple instances. Disability Benefits tab is fuller featured, so that's probably the one that should switch.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
