### ISSUE TITLE
Add monitoring/alerting for TIMS submissions

### ISSUE THREAD

**Issue by markolson** [department-of-veterans-affairs/vets-website#4506]
With the ops team, create an alert in prometheus that will let us or the on-call person know if the number of submissions falls below a reasonable number each night.

**Comment by leannammiller** [comment]
@markolson can you estimate this pls?

**Comment by lihanli** [comment]
i think this would work
http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=4w&g0.expr=sum(worker_education_benefits_claim_221990_307+%2B+worker_education_benefits_claim_221990_331+%2B+worker_education_benefits_claim_221990_351)+%3C+25&g0.tab=1

**Comment by jkassemi** [comment]
@lihanli - do you know where the "331" is coming from? From what I can see in https://github.com/department-of-veterans-affairs/vets-api/blob/b1ccfa995c738dcbf98458408ead1bc826d4f404/app/controllers/v0/education_benefits_claims_controller.rb we should expect `failure` and `success`. If you don't have any further info we can investigate a little further.

**Comment by jkassemi** [comment]
A minor suggestion for improving the metrics collection for this - we've had a clearer time writing the queries when we record total submissions and failures instead of successes and failures.

**Comment by lihanli** [comment]
the last 3 numbers are the region codes, we're collecting the data here
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/education_form/create_daily_spool_files.rb#L101

i don't think the `api.education_benefits_claim.221990.success` data will be used here since we want to know how many submissions are sent to TIMS and the other data only tells us how many submissions are sent to the API

**Comment by jkassemi** [comment]
@lihanli - awesome, ty. Makes sense.

The statsd tags support is a little wonky, that's why it's getting pushed into the metric name and not a separate label. https://github.com/department-of-veterans-affairs/vets-api/blob/49a5ace61929f26b5d5177ed32c79d2d8c77a93a/lib/statsd_middleware.rb#L18 provides a quick example of how to use it.

**Comment by jkassemi** [comment]
With that we can use a query like `sum(delta(worker_education_benefits_claim_transmissions{form:'22-1990'}[24h])) == 0` to alert when there aren't any submissions within a 24 hour period.

**Comment by markolson** [comment]
@jkassemi We have the data broken out across multiple files (the `rpo`) and would likely need to check if any of them have a delta of `0`. Which makes me think that a gauge isn't appropriate for this, because then it would trigger if the same counts actually did get sent two consecutive days.

**Comment by jkassemi** [comment]
@markolson - I think we'll end up with a gauge "per" with this implementation:

```
worker_education_benefits_claim_transmissions{form:'22-1990', rpo: 307}
worker_education_benefits_claim_transmissions{form:'22-1990', rpo: 331}
worker_education_benefits_claim_transmissions{form:'22-1990', rpo: 351 }
...
```

We can group by rpo `sum(delta(worker_education_benefits_claim_transmissions{form:'22-1990'}[24h])) by (rpo) == 0` to get an alert when any particular rpo has a delta of 0.

**Comment by jkassemi** [comment]
@markolson, given that https://github.com/department-of-veterans-affairs/vets-api/issues/662 wasn't the right approach, is there any reason to suspect that this process is not currently running properly? 

I expected to see metrics for `worker.education_benefits_claim.transmissions` based on the changes in https://github.com/department-of-veterans-affairs/vets-api/commit/040d65a7973b020c4ed2d28cc05cd0c4e8cdffec, but nothing's showing up in prometheus as of yet.

**Comment by markolson** [comment]
The change wasn't deployed until last night, and the job that generates the metrics is only run once at 3AM Eastern each day.  `worker.education_benefits_claim.transmissions` exists now.

**Comment by jkassemi** [comment]
@markolson is right about the gauge not necessarily changing, so the delta is in fact not a solution to this problem. 

Potential solutions include tracking a timestamp, log-based alarms, or triggering a PD exception from the rails application.
