### ISSUE TITLE
Remove Blog from vets.gov

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4521]
Vets.gov/experience looks like this right now: 

![screen shot 2016-12-28 at 3 39 41 pm](https://cloud.githubusercontent.com/assets/354277/21533860/e68cadde-cd13-11e6-949d-15ac6d784762.png)

Not sure how it's supposed to look. Are we still keeping the blog around?

**Comment by jcmeloni** [comment]
@koconnor719 @staceylanger @emilyville Is the blog something that's being kept around?

**Comment by ayaleloehr** [comment]
This document says no: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/4299ddb480469bdc6aa8591d64efaca80db14fa8/Decisons/management%20decisions.md

Relevant section:
```
Delete vets.gov blog

Date: 7/16
Description: leads team voted to decommision the vets.gov blog. martin t. notified and ok w/ this decision. need to make sure SEc Bob blog is still on site somewhere.
Rationale: lack of blogs, low frequency, doesn't align w/ mission of vets.gov.
Implications: need to make sure sec bob blog stays on site somewhere
Decision Approver: leads
```
That seems to not have been, however, so I do not know if we should reevaluate.

**Comment by webinista** [comment]
There's a post up from [last month](https://www.vets.gov/2016/11/11/help-us-improve-vets-gov/). Posts are also displayed _oldest_ first.

**Comment by jcmeloni** [comment]
@staceylanger Please advise if the blog is to remain? Thanks!

**Comment by koconnor719** [comment]
@jcmeloni the leads decided the blog should be deleted a few months ago:)  @emilyville

**Comment by webinista** [comment]
The blog is only linked from [Secretary Bob's message](https://www.vets.gov/2016/11/11/help-us-improve-vets-gov/). If you click the "Experience Link,"  however, you'll land on the old blog.

**Comment by emilyville** [comment]
Ok by me if we remove whenever! Just remember to also remove the footer link to Sec Bob's post and we should be in the clear.

**Comment by jcmeloni** [comment]
@emilyville Sounds good, and thanks everyone for comments.  @webinista I'll just change this issue to be "remove blog" :)

**Comment by jcmeloni** [comment]
Intention is for Core Team to tackle in Sprint 17-2 unless people have bandwidth in 17-1.

**Comment by koconnor719** [comment]
We need to keep sec Bob post pls



Sent with Good (www.good.com)


-----Original Message-----

**Comment by webinista** [comment]
We need more of a plan for this. Outstanding questions:

1. **Which Secretary Bob post are we retaining?**  I assume it's the [most recent one](https://www.vets.gov/2016/11/11/help-us-improve-vets-gov/) that's linked from the footer.
2. **Are we keeping it at that URL?**
      a. If so: We need to:
               - Remove the "Experience" link, so that the blog is no longer part of the site. 
               - Remove the footer / related posts links
               - (Should we also remove the background image, and move the text up?)
      b. If not: What should the new URL be?
               - Need to update the URL in the footer as well

**Comment by koconnor719** [comment]
Yes we should only have 1 sec Bob post up there. The most recent from 11/16



Sent with Good (www.good.com)


-----Original Message-----

**Comment by jcmeloni** [comment]
Since this isn't slated for this sprint, no need to focus on the questions now unless you want to (which is totally fine, just saying no one has to).  I will discuss with decision-maker folks in our next pre-planning meeting and get decisions that the team will need to appropriately complete the work in a future sprint.

**Comment by koconnor719** [comment]
Sounds good😀



Sent with Good (www.good.com)


-----Original Message-----

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
