### ISSUE TITLE
Build Front End 1995 pg. 2 - Benefit Information

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4542]
Are you getting, or do you expect to get any money (including, but not limited to, federal tuition assistance) from the Armed Forces or public health services for any part of your coursework or training? (Note about top-up?)
Do you expect to receive educational benefits under the Government Employee's Training Act (GETA) for the same course(s) you will receive VA education benefits? (answer only if you are a federal government employee)

**Comment by cweber** [comment]
These two are covered in different issues that I just updated. (Military history and School Selection)
