### ISSUE TITLE
build front end 1995 CH 3 - Military Service

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4543]
# Service Periods
Branch of service **[text]** 
Start of service period **[date]**
End of service period **[date]**

# Military History
Do you have any periods of service that began before 1978? **[radio]**

# Contributions
I am receiving benefits from the U.S. Government as a civilian employee during the same time as I am seeking benefits from VA. **[check]**

**Comment by annekainicUSDS** [comment]
Notes from meeting with Shay:

- Condense last 2 pages into a single page (military service pre 1978 and receiving benefits from USG)

**Comment by jbalboni** [comment]
Changes:

Change "receiving benefits" checkbox to a yes/no radio button
Consolidate periods of service and receiving benefits question into single page

**Comment by goldenmeanie** [comment]
Updated placement recommendation above
