### ISSUE TITLE
build front end 1995 CH 4 - School Selection

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4544]
# 4.1 NEW school, university, or training facility
_^ Title needs copy help_

In what type of education or training do you plan to enroll?

 - Type of education or training **[select]** 
 - Name of school, university, or training facility **[text]** 
 - Address **[standard address component]**
 - Education or career goal (for example, “Get a bachelor’s degree in criminal justice” or “Get an HVAC technician certificate” or “Become a police officer.”) **[textarea]**
 - Are you getting, or do you expect to get any money (including, but not limited to, federal tuition assistance) from the Armed Forces or public health services for any part of your coursework or training? **[check]** _ONLY IF on active duty_

# 4.2 OLD school, university, or training facility
_^ Title needs copy help_

 - Name of school, university, or training facility **[text]**
 - Address **[standard address component]**
 - When did you stop training? **[date]**
Why did you stop training? **[text]**

**Comment by akainic** [comment]
@cweber @goldenmeanie is the school information for NEW and OLD conditional based on anything? Are all these questions on the same page? I think a little clarity might be helpful here on exactly how this page should look (at least I'm confused :)).

**Comment by cweber** [comment]
I'm running through these and providing a bit more context for fields, as well as page breaks. Once I'm done with that, we can do a pass on what's conditional as well as what's required.

**Comment by annekainicUSDS** [comment]
Notes from meeting with Shay:

1. NEW school
- Can we make it so that the drop down options for "Type of education or training" reflect what is relevant based on benefit selected? (separate ticket for this already exists for 1990)
- "Type of education or training" and "name of school" should be required
- Address isn't needed for national test, tuition and cert, or top-up (make this conditional on answer to first question, selecting first 4 options would make it required) (but still not required)

2. OLD school
- Include examples for "Why did you stop taking classes" question (Shay to provide)

**Comment by jbalboni** [comment]
Pre-requisite for these changes is [#870](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/870), which I'm working on.

**Comment by goldenmeanie** [comment]
We should switch the order of "Type of training" and "Name of institution"

**Comment by annekainicUSDS** [comment]
@goldenmeanie Is this a new requirement, to switch the order? Perhaps we should create a separate ticket for that so it can be tracked.

**Comment by annekainicUSDS** [comment]
1. "Type of education or training" and "name of school" are already required (done)

**Comment by goldenmeanie** [comment]
@annekainicUSDS I could go either way. I think the conditional fields make more sense adjacent to the triggering field so I consider it conceptually part of the same effort. But I defer to whatever makes sense to you, but I would recommend not deploying one change without the other.

**Comment by annekainicUSDS** [comment]
I see what you mean. Seems like a low lift anyway to switch the fields so we might as well do it in the same PR.

**Comment by jbalboni** [comment]
@goldenmeanie @annekainicUSDS The address is already conditionally shown, so it sounds like we need a PR for swapping the order of education type and name of school?
