### ISSUE TITLE
update database to store the type of form that's being submitted

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4549]
currently defaults to 1990, will need to accommodate 1995

**Comment by leannammiller** [comment]
@lihanli pinging for status

**Comment by lihanli** [comment]
done

**Comment by leannammiller** [comment]
waiting for charter

**Comment by leannammiller** [comment]
@lihanli has this been reviewed? if not, @knkski could you please review it?

**Comment by leannammiller** [comment]
still blocked by charter

**Comment by leannammiller** [comment]
this can be merged @lihanli

**Comment by lihanli** [comment]
it's merged
