### ISSUE TITLE
Updating YTD report for any add'l biz requirements for the 1995

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4550]

**Comment by leannammiller** [comment]
@lihanli can you pls estimate?

**Comment by lihanli** [comment]
what are the additional business requirements? exact same fields added for 1995?

**Comment by markolson** [comment]
Does the original excel file we got have any non-1990 entries in it? If not, we probably need to ask Shay if she got multiple YTD reports.

**Comment by lihanli** [comment]
the original file had all the forms on it

**Comment by markolson** [comment]
Ok. I think take a look at #4549 first and think about any db migrations that need to take place to get the info needed for the more comprehensive report?

**Comment by lihanli** [comment]
done but not merged

**Comment by leannammiller** [comment]
@knkski can you review this one please?

**Comment by lihanli** [comment]
still not merged yet, can i merge it now that the charter is done @annekainicUSDS?

**Comment by annekainicUSDS** [comment]
I think we should still wait to merge until the charter is signed. It's with our stakeholders for review now, but not yet signed. Sorry :/

**Comment by annekainicUSDS** [comment]
This has been merged, closing.
