### ISSUE TITLE
make a 1995 schema

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4551]
approach TBD, need to schedule powwow between back end and FE - do we want to make an invisible field that says which kind of form it is?

**Comment by leannammiller** [comment]
@lihanli ping for status please!

**Comment by lihanli** [comment]
done

**Comment by leannammiller** [comment]
@markolson to review?

**Comment by leannammiller** [comment]
will need to be revalidated as a front end item by @jbalboni and @markolson
