### ISSUE TITLE
Reinstate header design

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#4564]
This issue created a slew of changes to the header that we need to revert back to the intended design. 

https://github.com/department-of-veterans-affairs/vets-website/issues/3771

Here is the original mockup, and this change went out for the 11/11 launch. 

![vets gov-homepage-11-11-updated-copy2](https://cloud.githubusercontent.com/assets/1307774/21628312/6123c7bc-d1d3-11e6-988e-d7014c4c0006.png)

Before that, we should address all the UI elements that cause banding and bring them into the body of the page. 

Dependencies:
https://github.com/department-of-veterans-affairs/vets-website/issues/4274#issuecomment-270162428
#4574

There were a few full-width alerts, but I believe they have all been removed ( @melwoodard ?)

**Comment by jcmeloni** [comment]
Intention is for Core Team to tackle in Sprint 17-2 unless people have bandwidth in 17-1.

**Comment by melwoodard** [comment]
We still need to address the full-width alert on the HCA apply landing page (should match the alert on the Edu apply landing page). I'll log a separate issue and tag as a dependency.

There were a couple changes made via #3771 that we should consider retaining here:
- Moving the profile links inside the blue nav bar - this removes one band from the navigation area and more strongly ties these links to global navigation
- Vertically stacking the crisis line and 'work in progress' text on mobile

@emilyville thoughts on keeping these parts?

<img width="400" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/21653192/c87fcfa0-d264-11e6-9f73-e51923867c2b.png">

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
