### ISSUE TITLE
wire up the submission

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4573]
port over JSON schema validation to finish submission controller so it uses new HCA submission service

**Comment by leannammiller** [comment]
@lihanli is this for @markolson to review?

**Comment by lihanli** [comment]
it's already merged, i didn't close it because anne mentioned in a meeting to not close issues?

**Comment by leannammiller** [comment]
leave in validate until testing, mark with work with Josh on ES team if needed
