### ISSUE TITLE
HCA alert banner design update

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#4574]
Moves the alert message below the intro paragraph https://www.vets.gov/healthcare/apply/

Alert message style should follow the modifications outlined in #4029

![alert-warning-hca-update](https://cloud.githubusercontent.com/assets/4106356/21653521/62b8ada2-d266-11e6-9cc3-4b6649ec1e4a.png)

Is a dependency of #4564 and #4274

**Comment by melwoodard** [comment]
@jcmeloni this is the last lurking full-width banner, which should ideally go in tandem with #4564 and #4274.

**Comment by jcmeloni** [comment]
thanks @melwoodard I'll throw it in the bucket with the others!

**Comment by jcmeloni** [comment]
Intention is for Core Team to tackle in Sprint 17-2 unless people have bandwidth in 17-1.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
