### ISSUE TITLE
discovery: set up alerts for error handling

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4575]
what kind of alerting do we want? 

set up meeting with rainbows to discuss
-anne
-mark
-lihan
-core team rep

**Comment by ayaleloehr** [comment]
@leannammiller should this be closed?

**Comment by leannammiller** [comment]
@ayaleloehr I'm not sure. That's really a question for @markolson

**Comment by annekainicUSDS** [comment]
Currently difficult to sort through Sentry errors and PagerDuty alerts to understand the severity of the error. 

Figure out how to prioritize errors and what alerting mechanism is best for each type of error (e.g., if we don't send a spool file one night, that seems like a PagerDuty alert; if one form isn't formatted correctly and doesn't enter the spool file, that might be a different type of alert).

Formalize these procedures and add documentation in vets-api for this.
