### ISSUE TITLE
Build Front End 1995 CH 1 - Veteran/Applicant Information

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4578]
# 1. Applicant Information

 - *First name **[text]**
 - Middle name **[text]**
 - *Last name **[text]**
 - Suffix **[select]** _Is there a strong argument for why our name component uses a dropdown list instead of  a text field? Caitlin_
 - *Social Security Number **[number]**
   - I don't have a Social Security Number **[check]**
   - VA file number **[number]** _Conditionally revealed based on checking box above._

**Comment by cweber** [comment]
Moved this here from edu-benefits-team

**Comment by leannammiller** [comment]
@jbalboni - is the work you're doing this week covering these? should we put all of these chapter tasks as in-progress?

**Comment by jbalboni** [comment]
@leannammiller Not intentionally, no. It does look like the PR I just put up covers most of this page, but that's the only one.

You can leave this one in progress, but the other chapters should not be in progress.

**Comment by jbalboni** [comment]
@cweber Are these fields required?

**Comment by cweber** [comment]
We haven't marked any fields as required yet. For now, assume the same required fields as the 1990. We have a call with stakeholders today and will nail down required fields soon.

**Comment by jbalboni** [comment]
@cweber Sounds good. Another question: do you have any file number expamples? Or is it just an integer?

**Comment by cweber** [comment]
You're too fast! We're also waiting on confirmation from that we can actually remove that field entirely.

We have a number of outstanding questions about field removal that need answered by the legal team. They'll be on the call today too. Hopefully we'll get most of the answers. I'll update after the call with changes and any outstanding questions we still have about each chapter.

**Comment by cweber** [comment]
@jbalboni We're keeping file number, but have not resolved whether it looks a certain way, has letters in it, etc. Should know by Monday, I think.

We'll also be in touch about how we want to implement it. Applicants only need to provide a SSN OR File Number.

**Comment by cweber** [comment]
@jbalboni Required fields indicated by an *

File number still in progress.

**Comment by cweber** [comment]
File number resolved and edited above.

Social: 9 digits
File number: C+8 digits. (VA does not care about receiving the C.)

cc @goldenmeanie

**Comment by mollyblake** [comment]
Please note:  the 'n' is lower case for SSN.  THANKS! 
*Social Security **n**umber 
I don't have a Social Security **n**umber 
And **yes** to the contraction for "I don't have ..."  that's perfect!

**Comment by annekainicUSDS** [comment]
Notes from meeting with Shay:

1. Intro Page:
- change language to: "Fill out this application if you are changing schools or programs to obtain a new COE"
- If changing school, type of training, or degree, they would use 1995
- At the bottom, where we list "22-1995", also list the name of the form
- At OMB number and respondent burden at the bottom perhaps

2. CH 1
- Help/error message text on File number field: "If you have a file number that starts with "C", please only include numbers that come after that" (make it more clear that the "C" is not necessary to include)

**Comment by mollyblake** [comment]
[1] Fill out this application to get a new Certificate of Eligibility (COE) if you are changing schools or programs. 

[2] Red error message: _If you have a file number that starts with C, you only need to give us the numbers that come after that._

[3] Please add after _Why did you stop taking classes?_  this content: (for example, “I moved to a different area” or “The program wasn't right for me.”)

[4] _Which benefit are you transferring to a new location?_  Did Shay make a comment on this?  @goldenmeanie 

[5] Change _I am receiving benefits from the U.S. Government as a civilian employee during the same time as I am seeking benefits from VA_ TO _Are you getting benefits from the U.S. Government as a civilian employee during the same time as you're seeking benefits from VA?_

Yes or no options
