### ISSUE TITLE
508 Testing- SM

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/vets-website#4592]
User was able to successfully log in to vets.gov, messaging.  When she navigated to "compose message" the screen reader did not recognize any content.  There were no alerts and focus was not taken to any of the fields.  The same happened with all the folders.  As a result the user was unable to compose, read, send, save messages.

**Comment by bshyong** [comment]
Was this on Internet Explorer and Windows?

**Comment by eli-lewis** [comment]
yes.  IE11

**Comment by bshyong** [comment]
@eli-lewis do you know the screen reader and operating system that was used for testing?

**Comment by eli-lewis** [comment]
Jaws was the screen reader, she was using a PC, not sure version.
