### ISSUE TITLE
Refactor site header to remove Foundation class names

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#4603]
For these class names, switch to element-specific media queries:

- `hide-for-small-only`
- `hide-for-medium-up`
- `hide-for-medium-up` 

Remove these class names:
- `small-9`
- `columns`
- `small-3`

These class names are used for the search form and fields. Can refactor this to take advantage of Flexbox.

For these class names, translate to USWDS grid:

- `medium-5` 
- `medium-offset-3`

Blocks department-of-veterans-affairs/vets.gov-team#549

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
