### ISSUE TITLE
Remaining form scaffolding work for 1995

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4608]
This is the remaining support work for the 1995 form, i.e. the work that needs to be done to support all the fields and our normal form UI flow.

I have a gist with prototype work for some of this [here](https://gist.github.com/jbalboni/52a9183490e1608f5881d7f72b03370c).

- [x] Object field
 - We need to create a flexible template for blocks in the form so that we can add descriptions when necessary (and fix some spacing issues)
- [x] Lazy load form and exclude routes for production
 - We don't want to add a lot of bloat to the 1990 form, so before we allow this to be usable on staging, we need to convert the edu benefits app to lazy loadable routes.
- [x] Date field
 - This is mostly done in the gist, but needs some style work and proper validation
- [x] Growable Table
 - This is maybe half done in the gist linked below. Mostly styling work left.
- [x] Redux set up
 - We need to store the form data and validation state in Redux so we can check them across all pages at the end before submitting
- [x] Review page
 - This is pretty big. We should be able to generate this page from the schema, but it'll take some work.
- [x] Add all 1995 fields/pages in config
- [x] Investigate performance issue
- [x] Confirmation page (in progress - Jeff)
  - This one is to build the confirmation page that we show after submitting a form. I think it’s the same as the 1990 one, but not sure yet. The important thing for that one is to put in place the common code so that after a successful submit it shows the confirmation page that’s set in the form config.
- [ ] Address field (in progress - Anne)
  - This needs to be a custom field to support the switching of the state/zip fields
- [ ] Conditional pages (in progress - Eugene)
  - This one is to add the functionality to skip a page in the form depending on form data. There’s a page in the form that should only be shown if a user has answered a particular question. What we did on the 1990 form was have a `depends` property on each page’s route that was either a function or an object that we could use with Lodash’s match function. It’d be a similar thing here, except in the form config object.
- [ ] Expandable fields (in progress - Jeff)
  - We have some fields that are only shown when you answer yes to a question above them (there’s an ExpandableFields component for this now on the 1990 form). We need to port that over somehow to this way of building forms.
- [ ] Conditional drop down options
  - This is something we need to do at some point, but may not be necessary for 1995 specifically. In some places we change the dropdown options for a field when form data changes. This would work similarly to the conditional validation
- [ ] Move more stuff to Redux state
  - We're probably using local component state too much, so find places to avoid that. The biggest one is the schema held in FormPage's state. This item is more tech debt that something that needs to happen for production. 

Before production:
- [ ] Figure out how to share schema between front and back end
- [ ] Better unit test coverage

**Comment by jbalboni** [comment]
FYI @leannammiller @akainic

**Comment by leannammiller** [comment]
in case you're interested @aub

**Comment by leannammiller** [comment]
@jbalboni is this list up to date?

**Comment by jbalboni** [comment]
@leannammiller It is now.

**Comment by jbalboni** [comment]
Closing since this was broken into separate issues.
