### ISSUE TITLE
[URGENT] Veterans Crisis Line links not working 

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/vets-website#4614]
Hi @bshyong and @webinista -- was just clicking around and noticed these links weren't working. Can one of you fix as soon as you can? Thanks!

![image](https://cloud.githubusercontent.com/assets/12674895/21723587/ff9771a0-d3fe-11e6-80f8-58c953c224e0.png)

**Comment by maryannbrody** [comment]
Edit to add -- I'm in Chrome Version 55.0.2883.95 (64-bit), checked with @crwallace as well and it wasn't working for her. 

Thanks!

**Comment by webinista** [comment]
Fixing it now. Also: _Call 1-800..._ and _Text to 838255_ were not originally supposed to be links on wide screens. Did that requirement change?

**Comment by maryannbrody** [comment]
Nope -- that is still accurate. The phone and text are not links on wide screens. Good question!
