### ISSUE TITLE
Build front end 1995 CH 2 : Benefit Selection

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4623]
# 2. Benefit Selection
- Select the benefit that is the best match for you **[check]**
  - _All options from 1990_
  - Add: Reserve Educational Assistance Program (REAP, Chapter 1607)
  - Add: Transfer of Entitlement Program (TOE)

**Comment by mollyblake** [comment]
@cweber 
Transfer of Entitlement Program (TOE) 
* please add the acronym

**Comment by goldenmeanie** [comment]
Thanks @mollyblake!

**Comment by annekainicUSDS** [comment]
Notes from meeting with Shay:
 
- Switch order to TOE, Post Vietnam, then REAP
