### ISSUE TITLE
Determine how to collect SS/File#/Payee#

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4637]
File number: What do File numbers look like? Do they have any characters other than numbers in them? Could you share a sample? (I think we asked this, but forgot because we thought we were removing it.) Does it look distinctly different than a SSN?
 
>File numbers often match the SSN exactly – XXX-XX-XXXX. In fact, I would either have a check box for file number is the same, or defauIt the file number field to the SSN and allow for changes. If they have a VA assigned file number it will be 8 digits instead of 9 – XX-XXX-XXX. They are sometimes preceded by a “C” – CXX-XXX-XXX, but we do NOT need the C. I t would make the field a number only, 8 or 9 characters. As we expand forms, we will need to add a payee number. This is used for Chapter 35. The dependent has the claim number of the vet followed by a payee number.

**Comment by cweber** [comment]
File number (Usually your SS#): 
[_______________________________]

**Comment by cweber** [comment]
Is this less stress for the average user than writing a more complex field?

Social Security Number:
[_______________________________]

File number:
[_______________________________]

**Comment by cweber** [comment]
Social Security Number (or your VA file number) (required):
[_______________________________]

**Comment by cweber** [comment]
Social Security Number (required):
[_______________________________]
 - [x] I don't have a Social Security Number
VA file number
[_______________________________]

**Comment by goldenmeanie** [comment]
I think that the label based solution is good !
