### ISSUE TITLE
Martin Taylor Email With Edits Needed on Vets.gov

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#4680]
Just got this email from Martin Taylor: 

Hello,
The Camp Lejeune Final Rule is set to be published by the federal register on January 13th. The final rule establishes that veterans, former reservists, and former National Guard members, who served at Camp Lejeune for no less than 30 days (consecutive or nonconsecutive) during this period, and who have been diagnosed with any of eight associated diseases, are presumed to have incurred or aggravated the disease in service for purposes of entitlement to VA benefits.
 
Members of VBA’s compensation service have reviewed the current Camp Lejeune language on vets.gov and recommend the following edits. Please let me know if you have any concerns. Thank you
 
Vets.gov:

     -Contaminated Drinking Water at Camp Lejeune
          oFirst paragraph, first sentence: remove “-or were assigned to-“
          oFirst paragraph, first sentence: remove “(toxic chemicals)”
          oFirst paragraph, second sentence: change to read “Scientific and medical evidence has shown an association between exposure to these contaminants during military service and later development of certain diseases.”
          oFirst paragraph, third sentence: this is not what presumptive service connection is.  Without further explanation of how service connection works, this sentence must be completely removed. Remove sentence
          oFirst paragraph, last sentence: presumptive service connection only applies to veterans, reservists, and national guard.  Given that this page is about disability benefits, no reference should be made to family members.  Please change to read “if you have qualifying service at Camp Lejeune and have a current diagnosis of a listed disability, you may be eligible for disability compensation.

     -Can I get disability benefits from VA?
         oFirst paragraph, first sentence: remove “under official orders or other official assignment”
         oSecond bullet: recommend changing this entirely to read “You have a diagnosis of one or more of the following conditions:” and then list the conditions as sub-bullets. 

     -Who’s covered?
         oSecond bullet: remove “servicemembers” entirely.  We only provide benefits for Veterans, former reservists and members of the National Guard.

     -What kind of disability benefits can I get?
          oThis seems confusing – this whole thread is under the guise of disability benefits, which is compensation.  Health care is provided by VHA, even if it is tied to service connection.  Additionally, given the separate health care benefits available to Lejeune vets, I would rename this to “What kind of benefits can I get?” Rename to “What kind of benefits can I get?”

     -How do I get these benefits?
          oFirst bullet: Please change the explanatory sentence to read “Be sure to note that you’re applying for one or more of the presumed Camp Lejeune illnesses, and attach evidence, or”

     -Can family members of Veterans also get help from VA?
          oRecommend revising this to note that certain Veterans are also eligible for health care benefits, since it covers different disabilities from the presumptive rulemaking.  It also covers different classes of veterans (does not include NG or Reserve service).  If you refer to the official comms plan, this section is just Camp Lejeune Healthcare and provides more accurate information about this benefit.

**Comment by rroueche** [comment]
@mollyblake @bethpotts per the work we've been doing today.

**Comment by koconnor719** [comment]
thx for making this happen @rroueche !

**Comment by bethpotts** [comment]
@rroueche @NatalieEMoore @koconnor719 Update on this: I've been working with Jennifer Rudisill on this vets.gov Camp Lejeune page today. I've incorporated the list of edits that came from her. I needed clarity on one of them, so we had some back and forth. Now I'm waiting for her approval on some text she wanted me to rewrite. I have communicated to her that in order to get this updated Camp Lejeune page live by 11:00 ET, I need any further edits from her by 9:00 or 9:15 Friday morning.

**Comment by rroueche** [comment]
@bethpotts thank you so much for the update. that sounds great - i'll be on standby in the morning when you get the green light.

**Comment by koconnor719** [comment]
We just got va approval on this via va email



Sent with Good (www.good.com)


-----Original Message-----

**Comment by bethpotts** [comment]
@koconnor719 We are pushing to production by 11:00 ET this morning. Here's the associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/4674

**Comment by koconnor719** [comment]
Yeah!! Thx



Sent with Good (www.good.com)


-----Original Message-----

**Comment by bethpotts** [comment]
Closing this since the new content is live!
