### ISSUE TITLE
content update to sign in page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#4681]
In our efforts to support the broadening scope of the Claim Status tool to encompass more than just disability claims, we'd like to make a small update to the text on the sign-in page. Specifically, we'd like to change the last sentence (just above the buttons) to appear as 3 bullets:

•    Refill a prescription.
•    Send a secure message to your healthcare provider.
•    Check the status of a disability, pension, or VR&E claim.

**Comment by bethpotts** [comment]
<img width="932" alt="sign in page" src="https://cloud.githubusercontent.com/assets/14881910/21907693/732b595e-d8c5-11e6-9378-27dec960b1f3.png">

**Comment by bethpotts** [comment]
There are also a couple proofreading fixes needed, please!:
1) We should capitalize "In" (because it's used adverbially) and "Your" in the header, like this: Sign In to Your Vets.gov Account
2)  Remove "the" before "VA" in the first line of text under the header, so it reads: Vets.gov is a new website from VA offering online services for Veterans.
3) Our site-wide style for buttons is to headline cap them, so: Create an Account

**Comment by rroueche** [comment]
Closing, relocated to Team repo: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/759
