### ISSUE TITLE
New page needed for disability section

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#4704]
@rroueche @bethpotts 
GWI in Afghanistan has its own set of info (and has far fewer relevant conditions). It should be its own page off of Contact With Hazardous Materials. All of the actual info is okay; it just needs to be separated. 

Here's the page, I'm referencing and that it will be similar to. https://vetsgov-pr-3324.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/gulf-war-illness/

[1] Action: create new page for Afghanistan GWI

[2] Action: create piano key on this page that links to new page: https://vetsgov-pr-3324.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/

**Comment by rroueche** [comment]
@mollyblake thanks! I will take care of those 2 things within the next couple of days.

**Comment by mollyblake** [comment]
https://vetsgov-pr-3324.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/gulf-war-illness/

@bethpotts can you look at this? It's the new content for the Gulf War Page.  Will add content into new Afghanistan page when it's stubbed out 

Thanks!

**Comment by rroueche** [comment]
@mollyblake where in the IA should the Afghanistan page go?

**Comment by mollyblake** [comment]
IMHO it should be a piano key on this page https://vetsgov-pr-3324.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/ and should be titled:  **Gulf War Illness from service in Afghanistan** but I think we should get opinions from @bethpotts on the name of the page ...

**Comment by bethpotts** [comment]
@mollyblake @rroueche 
Agree with Molly's placement in the IA.
Title: Gulf War Illness from Service in Afghanistan
Beth's next steps: Copyedit the page.

**Comment by bethpotts** [comment]
@mollyblake I've copyedited the Afghanistan page. It's waiting for you in pivotal.

**Comment by rroueche** [comment]
thank you!! i'll have this stubbed out for ya today.

**Comment by rroueche** [comment]
@mollyblake and @bethpotts we already have a piano key for the Gulf War Illness page on the Exposure page (https://vetsgov-pr-3324.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/), is it good practice to have another piano key called Gulf War Illness from Service in Afghanistan in that list of piano keys? Or should that info just be on the Gulf War Illness page?

**Comment by bethpotts** [comment]
@rroueche I think we're almost done with this. The only question I have is about the breadcrumbs/the Afghanistan location in the folders. The breadcrumbs currently show it at the same level as the Gulf War page, but it's actually a level down. Should that be reflected in the breadcrumbs?

**Comment by bethpotts** [comment]
Done.  Can't add the complete label because this issue wasn't created in the content repo.
