### ISSUE TITLE
address validation error street length over maximum

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-website#4711]
```
Form The property '#/veteranAddress/street' was not of a maximum string length of 50 in schema efb95931-f477-5756-8e16-ed95db359c86#
```
happened on Jan 11, 2017 1:05:29 AM UTC

**Comment by annekainicUSDS** [comment]
Double check validations to make sure we are validating the street address to not be blank.

**Comment by cagedcrown** [comment]
I am unable to replicate this error locally. There is also a character limit of 30 for the street address. 

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/common/components/questions/Address.jsx#L111

**Comment by leannammiller** [comment]
@jbalboni @annekainicUSDS - Mo is blocked on this?

**Comment by jbalboni** [comment]
@leannammiller I think we can close this. Mo and I can't reproduce it and we haven't seen any more.

**Comment by leannammiller** [comment]
ok
