### ISSUE TITLE
Combining two pages in Disability branch

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#4724]
@rroueche @bethpotts 
Per SME recommendations, we would like to combine the content from two pages into one page.  The pages are:

[1] Radiogenic Risk Activities
/disability-benefits/conditions/exposure-to-hazardous-materials/radiogenic-risk-activities/
AND
[2] Ionizing Radiation
/disability-benefits/conditions/exposure-to-hazardous-materials/ionizing-radiation/

The content is as follows: 

Radiation Exposure

Find out if you can get disability compensation or benefits for illnesses—including some cancers—believed to be caused by contact with radiation during military service.

Can I get disability benefits from VA?

You may be able to get disability benefits if you have an illness that’s on the list of those believed to be caused by radiation—or that doctors say may be caused by radiation—and if you had contact with ionizing radiation while serving in the military by:

- Being part of atmospheric nuclear weapons testing, or
- Serving in the postwar occupation of Hiroshima or Nagasaki, or
- Being a prisoner of war (POW) in Japan, or
- Working as an x-ray technician, in a reactor plant, or in nuclear medicine or radiography (while on active duty or during active or inactive duty for training in the Reserves), or
- Doing tasks like those of a Department of Energy (DOE) employee that make them a member of the Special Exposure Cohort (See 42 U.S.C. 7384L(14)), or 
- Part of underground nuclear weapons testing at Amchitka Island, Alaska, or
- Being assigned to a gaseous diffusion plant at Paducah, Kentucky, or
- Being assigned to a gaseous diffusion plant at Portsmouth, Ohio, or
- Being assigned to a gaseous diffusion plant at Area K-25 at Oak Ridge, Tennessee

To qualify for benefits, your illness must have appeared within a certain period of time. And you must have been discharged from the military under conditions other than dishonorable.

Who’s covered?
Veterans

What kind of disability benefits can I get?
Health care
Compensation (payments)

How do I get these benefits?
You’ll need to apply for benefits.

When you apply, we’ll ask the military branch that you served with (or the Defense Threat Reduction Agency) to give us a range of how much radiation they think you may have come into contact with. We’ll use the highest level of the range they report to decide on your benefits. [See 38 CFR 3.311(b)(5) for more information]( https://www.law.cornell.edu/cfr/text/38/3.311)

(Apply for benefits)[/disability-benefits/apply-for-benefits/]

**Comment by rroueche** [comment]
Reminder to me: before removing the obsolete page, I need to make sure I've checked the site for that URL and update it to the combined page URL. I'll also need to submit an issue for a redirect.

**Comment by bethpotts** [comment]
Note from Molly in the dup issue I just closed:
Here's the new page -- ready for Eagle Eyes @bethpotts to copy edit. FYI @rroueche
https://vetsgov-pr-3324.herokuapp.com/disability-benefits/conditions/exposure-to-hazardous-materials/radiogenic-risk-activities/

**Comment by bethpotts** [comment]
I created a new issue for the next step: copyediting.

**Comment by mollyblake** [comment]
Closing!

**Comment by rroueche** [comment]
@mollyblake I'm actually going to re-open bc I still need to:

1. Remove obsolete page from folder
2. Work w/tech team to redirect old obsolete page URL to the consolidated page URL.

**Comment by rroueche** [comment]
@mollyblake and @bethpotts do we want the piano key for this to be called "Radiation Exposure" and also the page URL to be "Radiation Exposure" ?

**Comment by mollyblake** [comment]
IMHO yes.  Defer to @bethpotts on final

**Comment by bethpotts** [comment]
@rroueche @mollyblake Yes! Let's rename both the piano key and the url: Radiation Exposure / radiation-exposure
Thanks for your help with this, Rachael!

**Comment by rroueche** [comment]
No problem! We should be all set, the changes are in staging, and James will set the redirects to go live at the same time that we merge this PR. Still scheduled for Feb 23.
