### ISSUE TITLE
menu link errors

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#478]
when i click on any of the breadcrumb items on this page https://www.vets.gov/disability-benefits/filing/active-duty/tools/ i get the error message page below ("the page you are looking for cannot be found").  is that the expected result?

![screen shot 2015-11-09 at 10 22 11 pm](https://cloud.githubusercontent.com/assets/13770771/11053592/584237b2-8730-11e5-947c-c669fc0a273e.png)

![screen shot 2015-11-09 at 10 22 36 pm](https://cloud.githubusercontent.com/assets/13770771/11053603/669addd2-8730-11e5-83a9-03d8bd855f59.png)

**Comment by koconnor719** [comment]
the first part of this error was fixed; the second part is still going to a page not found:


if i click on the breadcrumb item "Predischarge Filing Status" on this page https://www.vets.gov/disability-benefits/filing/active-duty/bdd/index.html, i get the following page:

https://www.vets.gov/disability-benefits/filing/active-duty/
![screen shot 2015-12-10 at 8 43 32 pm](https://cloud.githubusercontent.com/assets/13770771/11733754/cb205820-9f7e-11e5-9806-74a4704a40ba.png)

**Comment by bethpotts** [comment]
The link from the get (Apply) page goes to the correct predischarge page. The link from this page (https://www.vets.gov/disability-benefits/get/filing/faster/) goes to some old predischarge page that I'm guessing was supposed to have been killed. I can fix this problem. I'm not familiar with how to assign an issue to myself, or maybe Kelly needs to do that since she's the owner?? But I'll gladly take it on!

**Comment by dannychapman** [comment]
This has been fixed in production. Closing.

**Comment by bethpotts** [comment]
Kelly, I wanted to follow up to say that Danny has fixed all the breadcrumbs, so this page is good to go! The paths have changed, and thus the breadcrumbs have changed, so here's the new BDD page, with beautifully functioning breadcrumbs: https://staging.vets.gov/disability-benefits/claims-process/claim-types/predischarge-claim/bdd/index.html

**Comment by koconnor719** [comment]
Awesome!!



Sent with Good (www.good.com)


-----Original Message-----
