### ISSUE TITLE
SAML assertion vs sign-in click time gap

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets-website#4812]
It appears that the SAML assertion for identity is generated on page load. ID.me will consider a SAML assertion expired after 5m, so this may mean that a user must either register or sign in within 5 minutes of loading a page.

The SAML assertion should be generated in response to clicking the sign in or register links.

**Comment by jcmeloni-usds** [comment]
Moved to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1053
