### ISSUE TITLE
Add e2e screenshot/video artifacts to Jenkins

### ISSUE THREAD

**Issue by alexose-gov** [department-of-veterans-affairs/vets-website#4858]
Now that we use Jenkins, it would be great to produce some artifacts when a test fails.  A screenshot would be nice, but it's actually possible to [record video via xvfb](http://afterdesign.net/2016/02/07/recording-headless-selenium-tests-to-mp4.html) too.

**Comment by ayaleloehr** [comment]
@alexose can you put this in vets.gov-team instead?  And label it with `core`?

**Comment by alexose-gov** [comment]
Done!
