### ISSUE TITLE
" i " link not working on playbook product methodology page

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#486]
link does not work for the "i" link for "define project plan"  (note: it appears that none of the "i" links work on the other playbook product methodology pages.) suggest we just remove these for launch?

![screen shot 2015-11-09 at 10 43 51 pm](https://cloud.githubusercontent.com/assets/13770771/11053903/5c9fb5ca-8733-11e5-87af-f2886a52da16.png)
on playbook page https://www.vets.gov/playbook/product-methodology/definition/

**Comment by dannychapman** [comment]
This is ready for deployment.
