### ISSUE TITLE
Update health records content - Alerts

### ISSUE THREAD

**Issue by altangel** [department-of-veterans-affairs/vets-website#4964]
Update alerts on the download page with updated content:

**Successful update:**
![hr v4 download side by side](https://cloud.githubusercontent.com/assets/25392602/23374538/9555c586-fcd9-11e6-8ab1-9fd7312e892f.png)

**Errors with update:**
![hr download no table error 2](https://cloud.githubusercontent.com/assets/25392602/23374525/85123466-fcd9-11e6-98b5-c59d825e05e7.png)

**Not up-to-date:**
![hr download no table not up to date](https://cloud.githubusercontent.com/assets/25392602/23374526/85232c3a-fcd9-11e6-9780-4b8b2898c9ae.png)

/cc @AnitraAppa @mikeusdsva for awareness and in case I missed something.

**Comment by mikeusdsva** [comment]
Instead of "PDF File" can we just say "PDF"
