### ISSUE TITLE
Facility Locator - Bugs on IE10

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#5063]
Caught these during today's usability session. User is using IE10.

Arrow icon is floating under the header on main FL page. 
<img width="233" alt="screen shot 2017-03-10 at 11 22 15 am" src="https://cloud.githubusercontent.com/assets/13420618/23803387/59c3e4b8-0584-11e7-9cbb-3e84a91487fe.png">

All text should be centered aligned with dropdown icon.
![image](https://cloud.githubusercontent.com/assets/13420618/23803372/48aab7c4-0584-11e7-9866-a4e9e95bd10e.png)

**Comment by bshyong** [comment]
copied to vets.gov team repo https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1644
