### ISSUE TITLE
Capitalize 'i' in GI Bill breadcrumb

### ISSUE THREAD

**Issue by mollyblake** [department-of-veterans-affairs/vets-website#5082]
Would appreciate it if someone could help with this issue -- the **i** in the Gi Bill breadcrumb is lower case. It should be **GI** Bill.  Thanks! 

<img width="360" alt="screen shot 2017-03-14 at 12 39 38 pm" src="https://cloud.githubusercontent.com/assets/16196072/23917084/db0c907e-08b3-11e7-8670-cef5cb7f3cdf.png">

**Comment by saintsoup52** [comment]
Thank you... this is a personal pet peeve of mine :-)
