### ISSUE TITLE
Links to the accredited rep page now wrongly point to Disability App Process page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#5197]
Links to the accredited rep page used to point here: /disability-benefits/apply-for-benefits/help/
Now, for some reason, globally, they point here: /disability-benefits/apply/

Not sure why this global change happened, but we need to get all the "get help from a trained professional/get help from an accredited rep" links to point here once again: /disability-benefits/apply-for-benefits/help/ 

Some pages that have a link to what should be the accredited rep page (there are more than 3):
https://www.vets.gov/disability-benefits/apply/
https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/non-hodgkins/
https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/navy-coast-guard/

**Comment by rroueche** [comment]
This has been resolved!
