### ISSUE TITLE
GI Bill CT: Missing ® in header & breadcrumbs

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5206]
The version of the CT that is a WIP is missing the registered trademark symbol next to GI Bill.

The header and the bread crumbs should read "GI Bill® Comparison Tool" similar to the current version of the tool.

**Current Tool**
![image](https://cloud.githubusercontent.com/assets/4397508/24522599/0e6b5534-155e-11e7-9edd-942bab4c85a6.png)

**WIP Version**
![image](https://cloud.githubusercontent.com/assets/4397508/24522636/2e6568f2-155e-11e7-931e-2856eec46a82.png)

Here are the VA approved terms of use for GI Bill tradermark:
http://benefits.va.gov/GIBILL/Trademark_Terms_of_Use.asp

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
Lets do a string search for "GI Bill" and identify all the places that might need the trademark logo.
