### ISSUE TITLE
GI Bill CT: City/State not showing up properly in the search results

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5207]
When a US based school is displayed in the CT search results the description below the school name should say "[City], [State]."

Currently the WIP version of the showing City and Country (not state)

![image](https://cloud.githubusercontent.com/assets/4397508/24522802/b881feb0-155e-11e7-9176-ceeed5cb695a.png)

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
Seems like straight forward enough logic based on USA, then show state instead.
Can state ever be null? - if so maybe just show country anyway.

**Comment by saintsoup52** [comment]
State is NULL when it is not in the US... so the default now is to show state, but when NULL it shows country instead.
