### ISSUE TITLE
GI Bill CT: Calculator Questions In-State & Out-of State not appearing

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5208]
In the WIP version when a user selects a public school and says they are an out-of-state student the tuition/fees questions are not changing accordingly.

An out of state student should be asked two tuition questions not just one.

**Current production version:**
![image](https://cloud.githubusercontent.com/assets/4397508/24522927/35e7f080-155f-11e7-926c-c9e7da3631d4.png)

**WIP version:**
![image](https://cloud.githubusercontent.com/assets/4397508/24522971/69bd3ab4-155f-11e7-9b33-d0382e4459e3.png)

@mphprogrammer @saneshark

**Comment by U-DON** [comment]
I believe @melwoodard wanted to keep just one input for tuition and fees to encompass both. If the input for the radio button changes, it should update the number in the text input accordingly.

**Comment by melwoodard** [comment]
Correct - seeing both fields is confusing from a user perspective because only one of them applies to their situation, not both. 

However @U-DON it does look like the calculator logic isn't matching up for an out-of-state situation - in the live tool, the amount the GI Bill pays to the school is capped at the in-school tuition rate, but on dev it's showing that GI Bill will pay the full out-of-state tuition. @saintsoup52 can you confirm that the calculation in production is the correct logic?

**Comment by U-DON** [comment]
I think I mistakenly set the tuition fees cap to be the out-of-state tuition fees if the user selected "No" for the in-state radio input. If the cap should be the in-state tuition fees for any public schools, I can make that change.

**Comment by saintsoup52** [comment]
We need both questions to make the calculations work correctly.

The tuition benefit for a Post-9/11 GI Bill student attending a public school as an out of state student is the lesser of the following:
* Out of State tuition fees charged - scholarships (CH 33 is a payer of last resort)
* In-State Tuition rates for the same program (CH33 is capped at in-state tuition)

I appreciate the desire for simplicity but without two questions we cannot be displaying accurate benefit information.

On a related note... The data we are prepopulating for these two fields comes from ED's IPEDS system which means it is self reported data by the school and is the average tuition/fees charged for first-time, full-time students in the largest program on campus.  The data is also dated which means it is 1-2 years old... tuition rates increase on average 3%/year.

Many GI Bill students are neither first-time or full-time students so this number may not reflect their actual experience. And if they are looking at a particular school's website the tuition/fees published there will be more accurate then what we can provide.

That means while we are serving up  the best information available... it can be wrong more than half the time for GI Bill students.

Students using the tool need to be able to see and adjust any prepopulated fields that affect their benefits because otherwise they will not understand why what we are showing them makes any sense.

**Comment by saneshark** [comment]
@melwoodard Do you have any thoughts based on @saintsoup52 findings above?

**Comment by melwoodard** [comment]
Since we aren't able to guarantee the accuracy or even presence of tuition rates for every school, it sounds like we'll need to revert back to showing the two fields separately.
