### ISSUE TITLE
GI Bill CT: Buy-Up Program

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5209]
In the current WIP version a user should not be able to input a value higher than $600 for their buy-in. 

The typical buy-in is $600 but it could be less. If a user were to input a value above $600 into the tool they would be told they were eligible to receive wildly higher monthly benefits under MGIB.

In the production version we use a drop down menu to enforce that behavior.

**Current version**
![image](https://cloud.githubusercontent.com/assets/4397508/24523129/0116495a-1560-11e7-8bb7-557f13515a1d.png)

**WIP version**
![image](https://cloud.githubusercontent.com/assets/4397508/24523221/5336b44a-1560-11e7-8b02-e00af2b60af2.png)

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
explain via text that max should be 600, but allow the user to input values exceeding this, but the calculation will reflect 600 regardless of value exceeding 600.

**Comment by melwoodard** [comment]
Append the label for the buy-up amount field to be:

How much did you pay toward buy-up (up to $600)?
