### ISSUE TITLE
Redundant Page Titles

### ISSUE THREAD

**Issue by raineystraus** [department-of-veterans-affairs/vets-website#521]
I thought we'd eliminated page titles that were redundant to the breadcrumb. I'm seeing this throughout and I'm not sure if that approach changed with the content team somewhere along the way.

See example: https://www.vets.gov/disability-benefits/conditions/exposures-to-hazardous-materials/specific-environmental-hazards/

**Comment by dannychapman** [comment]
This example is actually an orphaned, old version of the page - fixed in the new version. Unable to find other good examples for now, so closing this one. Please reopen if you find specific examples though!
