### ISSUE TITLE
GI Bill CT: Outcome measures with nulls are showing up as 0% with blue on the graph

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5210]
This is probably a duplicate of another issue but this issue is also affecting how outcome measures are displaying.

Trying searching for "UNIVERSITY OF PHOENIX-ONLINE CAMPUS". Because UOP is a 4 year school VA has not released any grad data for veterans.

However, the WIP version is showing a 0.00% rate and is even showing a slight blue line on the graph bar.

![image](https://cloud.githubusercontent.com/assets/4397508/24523426/fc0bcc7c-1560-11e7-8de1-17b18a1dd926.png)

@mphprogrammer @saneshark

**Comment by mphprogrammer** [comment]
`graduation_rate_veteran` is showing `nil` in GIDS...

**Comment by saneshark** [comment]
@mphprogrammer are we supposed to maybe provide a default value on the front-end when null? please advise.

**Comment by mphprogrammer** [comment]
@saneshark It should say `No Data`
<img width="901" alt="screen shot 2017-03-31 at 3 13 46 pm" src="https://cloud.githubusercontent.com/assets/4104431/24565785/c07c7778-1624-11e7-836f-ff099881388b.png">

**Comment by mphprogrammer** [comment]
It should say `No Data` in the chart area, although the current tool shows 0% - that is wrong 
<img width="894" alt="screen shot 2017-03-31 at 3 16 14 pm" src="https://cloud.githubusercontent.com/assets/4104431/24565842/06906ec2-1625-11e7-8739-4dfa9e06a777.png">
