### ISSUE TITLE
GI Bill CT: Missing "learn more" links

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5212]
In the WIP version of the tool there are several learn more links that are missing that need to be added back to the tool.

**Cautionary Information**
* Student complaints
* All Campuses

**Current Version**
![image](https://cloud.githubusercontent.com/assets/4397508/24523689/e968cc04-1561-11e7-9045-58f3031216e4.png)

**Proposed Version**
![image](https://cloud.githubusercontent.com/assets/4397508/24523814/592fadc8-1562-11e7-8156-7b7e3751b5a5.png)

**Additional Information**
* Accredited
* Type of accreditation
* Single point of contact
* Credit for military training
* Historical Information

**Current Version**
![image](https://cloud.githubusercontent.com/assets/4397508/24523724/027244dc-1562-11e7-8ee9-5733a9db6f34.png)

**Proposed Version**
![image](https://cloud.githubusercontent.com/assets/4397508/24523770/331d46f4-1562-11e7-8e55-88d8b3e3fe97.png)

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
Might have just been missed in mockups -- compare to what is in production.
