### ISSUE TITLE
GI Bill CT: Missing links in additional information

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5213]
The following links are missing from WIP version of the GI Bill CT. Both of these links provide vital consumer information to uses using the tool that comes from ED.

* "See accreditors"
* "Link to Veterans Tuition Policy"

**Current Version**

![image](https://cloud.githubusercontent.com/assets/4397508/24523960/dbadbbfa-1562-11e7-9582-03d05b813413.png)

**WIP Version**

![image](https://cloud.githubusercontent.com/assets/4397508/24523975/f0adf290-1562-11e7-8bad-d7599af71170.png)

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
@U-DON to check and see if this is in production currently and copy from there if possible, otherwise escalate to me.

**Comment by U-DON** [comment]
The tuition policy link should appear if `vetTuitionPolicyUrl` is available. It doesn't appear to be in the attributes for an institution. @mphprogrammer: Would you be able to add it in there? Meanwhile, I can add the accreditors link.

**Comment by mphprogrammer** [comment]
Yup. It seems to be missing from the institution_profile_serializer. Will do that now...

**Comment by mphprogrammer** [comment]
@U-DON  I did some checking and found `vet_tuition_policy_url` returned in `links : { ... , vet_website_link: ‘... url ...’ }`
