### ISSUE TITLE
GI Bill CT: Resizing the screen makes data disappear

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5214]
When the screen shrinks to mobile size certain data disappears to include:
* Types of complaints
* Post-9/11 GI Bill # & $$ 

![image](https://cloud.githubusercontent.com/assets/4397508/24524038/3719397e-1563-11e7-8206-c2ff6a3b0270.png)

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
@bshyong to verify if this is incorrectly marked up or if it is just a design nuance that @saintsoup52 identified as an issue incorrectly.

**Comment by bshyong** [comment]
This is due to an error with the CSS breakpoints. There is a gap between 481 and 784px where nothing will show up.

**Comment by saintsoup52** [comment]
Sorry to revisit this issue... but I just checked the staging sit using my iphone (chrome) and I was not able to see the types of complaints.

![image](https://cloud.githubusercontent.com/assets/4397508/24794492/de69c32e-1b53-11e7-9a63-d32b9efd4ca3.png)

@bshyong @saneshark

**Comment by U-DON** [comment]
I think this is expected when there are 0 total complaints. It should only display the complaints that have a non-zero count. At least that's what the code is doing right now, so I thought that was as designed. @melwoodard Is that the expected behavior?

**Comment by saintsoup52** [comment]
Thank you for flagging that change... It does appear to work when I search for schools with no complaints. 

Nice new feature.

**Comment by melwoodard** [comment]
@U-DON that's correct
