### ISSUE TITLE
GI Bill CT: Caution flag reasons should not be cased incorrectly

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5215]
Reasons codes for Caution flags in the work in progress version of the tool are being cased incorrectly. 

It appears somewhere along the line the first letter of each word is being capitalized. When this happens it messes up key acronyms like ACICS and FTC.

![image](https://cloud.githubusercontent.com/assets/4397508/24524221/c8512afa-1563-11e7-86ba-977386b4d601.png)

@mphprogrammer @saneshark

**Comment by mphprogrammer** [comment]
@saintsoup52 Programmatically I have no way of knowing whether a word is an acronym. Perhaps we should go to all upper case?

**Comment by saintsoup52** [comment]
I completely agree... therefore however the caution flag is uploaded into the data service is how it should be displayed.

Currently based on the data we are uploading into the data service the caution flags should say "School operating under provisional accreditation (previously accredited by ACICS)"

Somewhere along the pipeline all the first letters of the words are being capitalized. We just need to stop doing that and let EDU decide how it should look in files they upload.

Hope that makes sense.

**Comment by mphprogrammer** [comment]
I'll get this, looks like spacing is wrong after comma in this instance too.

**Comment by saneshark** [comment]
@mphprogrammer is this being addressed as part of https://github.com/department-of-veterans-affairs/gibct-data-service/pull/239

**Comment by mphprogrammer** [comment]
@kam Yes

**Comment by leannammiller** [comment]
@mphprogrammer since #239 is merged should this be closed?
