### ISSUE TITLE
GI Bill CT: Filters are missing counts

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5216]
In the WIP version of the tool the new search page is missing counts next to each type of filter.

In the current version of the tool we provide very helpful tallies of the number approved programs that meets each of the various criteria.

**Current Version**
![image](https://cloud.githubusercontent.com/assets/4397508/24524319/1ba40376-1564-11e7-9645-a90f3b8a491f.png)

**WIP Version**
![image](https://cloud.githubusercontent.com/assets/4397508/24524349/31df75e4-1564-11e7-8459-8ac0207e5127.png)

@mphprogrammer @saneshark

**Comment by U-DON** [comment]
We've decided to remove them since the UX around them is unintuitive with the way they're provided ('All' would get the current count of results rather than the actual count of all results).

**Comment by saneshark** [comment]
@saintsoup52 this was a design decision we made. The filter counts didn't seem to provide much value particularly with UI redesign and are an added level of complexity to the interface. The count at the top for the search results should likely be sufficient.

This will also allow us to remove the group_by distinct database queries we use to retrieve the counts, which will likely improve search queries by 2-3 x current speed.

**Comment by leannammiller** [comment]
removing from our backlog.
