### ISSUE TITLE
propose solution to: Search results - eligibility questions can extend way below search results

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5221]
In the WIP version of the search results page when they are 5 or fewer search results a user cannot see how adjusting the answers to the eligibility questions affects their estimated benefits.

A user should be able to change their answers to the eligibility questions and see how the benefits change up and down (e.g., online, other GI Bill benefits).

There are several possible paths to making this happen:
* Filter questions should be collapsible (current feature and available in the mobile version) [preferred]
* Eligibility questions should be above filter questions in a closed drawer [not preferred]

Here is what the screen looks like with less than 5 results:
![image](https://cloud.githubusercontent.com/assets/4397508/24541333/01a95df2-15c5-11e7-9057-34467cfb5ea1.png)

One of the most important features of the GI Bill CT is that users can easily see how their answers to questions affect their benefits. For example taking classes online cut living allowance benefits in half.

DOD uses this exact feature when they are demonstrating the tool and how the different GI Bill benefit works to soon to be separating servicemembers.

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
This is not a launch blocker, will remain in backlog for now and we will look at this more closely later.

**Comment by leannammiller** [comment]
will review with @melwoodard

**Comment by phiden** [comment]
Duplicates #3865 -- closing that one and keeping this one, as it's more detailed
