### ISSUE TITLE
GI Bill CT: Historical information section is displaying incorrect year

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5223]
In both the production and WIP version of the tools the years are incorrect for the historical Post-9/11 GI Bill information.

We are currently display FY 2016 data not "FY'14" or "2014" data. Both versions should say "FY 2016".

 I understand that including "FY" is not very consumer friendly but there has been great deal of confusion on how the number of Post-9/11 GI Bill students could be more than total number of GI Bill students at a school. The number of all GI Bill students is counted on a calendar year basis while the Post-9/11 GI Bill students are counted on fiscal year basis. 

We have received a number of complaints from schools about this and that is why the current tool includes "FY"

**Current Tool**
![image](https://cloud.githubusercontent.com/assets/4397508/24542535/fbfc1552-15c9-11e7-8863-2409470e5eb6.png)

**WIP Version***
![image](https://cloud.githubusercontent.com/assets/4397508/24542446/a7ce6d22-15c9-11e7-9ce0-d4f55a128185.png)

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
Lets set this one to 2016 on the front end, but open a separate issue to track how to do this on a longer term basis as well (based on conversation with stakeholders and admins).

**Comment by U-DON** [comment]
@melwoodard Should the header be "Total paid (FY 2014)"?

**Comment by melwoodard** [comment]
@U-DON yes, except 2016 - "Total paid (FY 2016)"
