### ISSUE TITLE
Disability Benefits: Missing Card Navigation

### ISSUE THREAD

**Issue by raineystraus** [department-of-veterans-affairs/vets-website#526]
The landing page for disability benefits should include a card for "Application Process" or something like this. We'd want redundant access here, through the standard navigation and through the button/call-to-action.

**Comment by dannychapman** [comment]
@raineystraus would this be different from the green apply button we have now? Not sure I follow.

**Comment by emilyville** [comment]
I am closing, I agree with @dannychapman
