### ISSUE TITLE
SGLI Premium Rates Table 

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/vets-website#5263]
Hi @melwoodard, @rroueche . This is a table that needs to be designed and inserted into the Servicemembers' Group Life Insurance (SGLI) page: https://github.com/department-of-veterans-affairs/vets-website/blob/content/wip/life-insurance/content/pages/life-insurance/options-and-eligibility/sgli.md

You'll  see a note on the page where it needs to go. Table in word doc is attached. Please let me know if you have any questions. Thanks!

[SGLI Premium Rates Table.docx](https://github.com/department-of-veterans-affairs/vets-website/files/896492/SGLI.Premium.Rates.Table.docx)

**Comment by melwoodard** [comment]
I can tackle this.

**Comment by melwoodard** [comment]
@DanielleSoCompany you can take a look at the table here: https://vetsgov-pr-5240.herokuapp.com/life-insurance/options-and-eligibility/sgli/

If it looks good, feel free to go ahead and close this issue.

**Comment by DanielleSoCompany** [comment]
Thank you, @melwoodard !
