### ISSUE TITLE
Legacy Programs: Missing Navigation Descriptions

### ISSUE THREAD

**Issue by raineystraus** [department-of-veterans-affairs/vets-website#529]
We need a line of description for each of these programs so the users can ID which to investigate.

https://www.vets.gov/education/eligible-programs/

**Comment by dannychapman** [comment]
@rcarthur @ss0ss It would be great to knock these out for our current IA. Can we track this?

**Comment by emilyville** [comment]
these have a line description, so go us. closing issue.
