### ISSUE TITLE
GI Bill CT: Displaying incorrect OPE code

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5294]
The staging version of the tool is showing an incorrect OPE code in the "Additional information section".

The tool should be displaying the 8-digit OPE code, however it is currently showing a messed up version of the 6-digit OPE code. Unfortunately for all of us, many OPE codes start with zeros and those tend to be stripped somewhere along the data pipeline.

![image](https://cloud.githubusercontent.com/assets/4397508/24897443/eedc689a-1e66-11e7-8858-cc05822d6e42.png)

@mphprogrammer @saneshark @leannammiller

**Comment by saneshark** [comment]
@mphprogrammer I'm going to assign this one to you to look into as soon as you can. This will be a launch blocker. Hopefully a minor fix.

**Comment by mphprogrammer** [comment]
@saneshark These are 8-character strings in GIDS, would you know if the Client is converting them to numbers (there are a few with letters in them) and dropping the leading 0's? @U-DON

**Comment by mphprogrammer** [comment]
This is what GIDS returns:
```
"id":"28995","type":"institutions","attributes":{"name":"THE ART INSTITUTE OF ATLANTA","facility_code":"21000311","type":"FOR PROFIT","city":"ATLANTA","state":"GA","zip":"30328","country":"USA","bah":1458.0,"cross":"00138813","flight":false,"correspondence":false,"ope":"00927005","ope6":"09270" ...
```

**Comment by mphprogrammer** [comment]
Directly hitting the API on staging (https://staging.vets.gov/gids/v0/institutions/21000311)
`{"data":{"id":"28995","type":"institutions","attributes":{"name":"THE ART INSTITUTE OF ATLANTA","facility_code":"21000311","type":"FOR PROFIT","city":"ATLANTA","state":"GA","zip":"30328","country":"USA","bah":1458.0,"cross":"00138813","flight":false,"correspondence":false,"ope":"00927005","ope6":"09270"`, which I think is valid

**Comment by mphprogrammer** [comment]
@U-DON could you take a look and see? The GIBCT seems to be dropping the last 2 characters of the ope (`05`) and dropping the first 2 or converting to integer (`00`). Also, it looks like the cross (Ipeds) is being converted to an integer, the leading (`00`) are being dropped there too.

**Comment by U-DON** [comment]
Yeah, I think the front end code is dropping the leading zeros somewhere. Probably since we try to convert a lot of the data from strings to numbers.
