### ISSUE TITLE
Life insurance additional callout

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/vets-website#5309]
Hi Rachael. I've added the callouts for the Life Insurance section in a new branch titled [WIP] life-insurance-callouts. But there's one additional callout that I need help with. It should appear only on the Options and Eligibility page (but not its subpages) so I'm not sure how to code the {% if path contains} part of the code. Here's the rest of the code for the callout, if you're able to add this. Thanks!

<li>Want to know more about dividends? Some life insurance policies provide dividend options (cash payments made to policy holders when the company makes a profit).
<p><a href="http://www.benefits.va.gov/insurance/dividends_options.asp">Learn more about dividend options</a>.</p>
<p><a href="http://www.benefits.va.gov/insurance/dividends_special.asp">Learn the truth about dividend rumors</a>.</p>
<p><a href="https://insurance.va.gov/UnclaimedFunds/">Search for unclaimed funds</a>.</p>
</li>

**Comment by rroueche** [comment]
@DanielleSoCompany should that text appear in addition to the other /options-and-eligibility callout text, so total it'd be:

```<li>Want to know more about dividends? Some life insurance policies provide dividend options (cash payments made to policy holders when the company makes a profit).
<p><a href="http://www.benefits.va.gov/insurance/dividends_options.asp">Learn more about dividend options</a>.</p>
<p><a href="http://www.benefits.va.gov/insurance/dividends_special.asp">Learn the truth about dividend rumors</a>.</p>
<p><a href="https://insurance.va.gov/UnclaimedFunds/">Search for unclaimed funds</a>.</p>
</li>

 <li>Already have VA life insurance? <a href="/life-insurance/manage-your-policy/">Manage your policy online</a>.</li>
 <li>Need more information? <a href="http://www.benefits.va.gov/INSURANCE/ins_publications.asp">Read our insurance publications</a>.</li>```

**Comment by rroueche** [comment]
cancelling bc this is in progress here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2228
