### ISSUE TITLE
Adding accordions for age-based tables

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/vets-website#5315]
Hi @melwoodard . I've created the tables we discussed in the following 2 pages within Branch: content/wip/life-insurance:

vets-website/content/pages/life-insurance/options-and-eligibility/fsgli.md
vets-website/content/pages/life-insurance/options-and-eligibility/vgli.md	

There are notes for you re: where you'll need to create the accordions for the age ranges. Just let me know if you have any questions. Thanks!

@rroueche just keeping you in the loop on this - thanks!

**Comment by melwoodard** [comment]
Thanks Danielle! I'll start looking into the accordion implementation.
