### ISSUE TITLE
Need to find/fix error

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/vets-website#5316]
Hi @rroueche. There's an error that's causing deployment to fail in the Life Insurance branch. It looks like it started with this commit: https://github.com/department-of-veterans-affairs/vets-website/pull/5240/commits/528234c450be2746b4a822829e67f401a39945fa.

I found and fixed what I thought was the error (there was a link that read " [contact OSGLI](/life-insurance/contact or appropriate link based on http://benefits.va.gov/INSURANCE/resources-contact.asp)." because we'd had a question in the copydeck. But even after I fixed that, there's still an error somewhere.

We're hoping you can help us find/fix the error so Peggy can begin proofing in staging tomorrow. Thanks in advance for your help!

**Comment by bethpotts** [comment]
@rroueche Any chance you'll have time to take a look at this, so Peggy can proof LI?

**Comment by rroueche** [comment]
Fixed!
