### ISSUE TITLE
Military tuition assistance field appears on OJT profiles

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#5317]
@saintsoup52 - @U-DON noticed that OJT profiles show a field in the calculator for Military Tuition Assistance - which seems like something specific to school tuition and not on the job training. 

This exists in production as well as the new version we're building out - and the field doesn't seem to affect anything in the calculator results. Is this field supposed to be in OJT or can it be removed?

**Comment by saintsoup52** [comment]
Good catch... TA only affects the tuition/fees benefit and therefore that question should be hidden when an OJT program is selected.

**Comment by melwoodard** [comment]
Thanks, that makes sense!
