### ISSUE TITLE
GIBCT Calculator: Disparity in fourth term housing allowance

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-website#5318]
When a user selects "Active Duty" and "Post-9/11 (Ch 33)" in the eligibility form, there's a disclaimer that they aren't eligible for housing allowance. When that's the case, in the production tool, "Months 19-24" in the Housing Allowance row shows a non-zero amount. In the staging version, we have $0 for every term, which matches the disclaimer shown.

<img width="880" alt="screen shot 2017-04-12 at 7 17 48 pm" src="https://cloud.githubusercontent.com/assets/1067024/24983391/c7c0880a-1fb4-11e7-94f6-c64c6bfe72ba.png">

@saintsoup52: Can you confirm the correct behavior?

**Comment by saintsoup52** [comment]
Thanks for asking... the Months 19-24 should read $0 and not "NaN" like in the production tool.

I thought I remembered us asking another question of the users enrolled in OJT programs, something like how long will is your OJT program which would have truncated those results but I can't find it in my notes. So please disregard my ramblings.

**Comment by U-DON** [comment]
Closing since this was just to confirm, and the staging tool is following correct behavior.
