### ISSUE TITLE
Transfer Post 9/11 GI Bill: Page/Content layout

### ISSUE THREAD

**Issue by raineystraus** [department-of-veterans-affairs/vets-website#535]
This page doesn't quite feel like it's working yet consider:

- Process list for "What happens next"

And either, move learn more to the bottom of the page or put contact information in a "help side bar"

https://www.vets.gov/education/gi-bill/transfer/

**Comment by koconnor719** [comment]
@gnakm can you pls. review and see if this issue needs to be closed or requires further review by design team?

**Comment by gnakm** [comment]
@koconnor719 Thanks for pointing this out! I am working on something similar for Roadrunner to help simplify these heavy eligibility pages. Let's leave it open for because I think this particular page needs extra love and I will work on it.

**Comment by gnakm** [comment]
We are working on redesigning a template for pages just like in Roadrunner but it's on the lower end of the priority spectrum. It's been noted. Once it becomes of global decision, it will be changed.
