### ISSUE TITLE
Figure out a better way to handle array fields on schemaform review pages

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#5352]
We currently pull array fields out of their page when on the review screen and show them separately. This is complicated and creates edge cases, like when the array field has a minimum number of items and there's no warning about this to users.

We could get rid of the separation entirely or come up with ways of handling the required field edge case.

**Comment by jbalboni** [comment]
FYI @goldenmeanie @cvalarida

**Comment by goldenmeanie** [comment]
We might need a way to visually call out review chunks that need attention
