### ISSUE TITLE
GI Bill CT: Monthly living allowance rate for MGIB incorrect

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5388]
The benefits estimator is not correctly calculating the MGIB (CH 30) benefits when the user served less than 3 years. The correct rate for a 2 year enlistment under CH 30 is $1,509/month.

http://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100116.asp

**3 years**
![image](https://cloud.githubusercontent.com/assets/4397508/25280908/8ab666ca-2679-11e7-9386-f5578e07eab1.png)

**2 years**
![image](https://cloud.githubusercontent.com/assets/4397508/25281012/f1de0db2-2679-11e7-9c77-95dcc3b89b07.png)

**Comment by melwoodard** [comment]
@U-DON @bshyong can you look into this?
