### ISSUE TITLE
GI Bill CT: How many dependents question should be hidden

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5389]
If a user selects: 
1. VR&E and 
2. says they are eligible for the Post-9/11 GI Bill 

Then the question asking "How many dependents do you have" should be hidden.

![image](https://cloud.githubusercontent.com/assets/4397508/25281456/73abcfb8-267b-11e7-9f4b-9503a5b6b70a.png)

@leannammiller @mphprogrammer @saneshark

**Comment by melwoodard** [comment]
@saintsoup52 this matches the functionality of the current tool - should it not?

**Comment by saintsoup52** [comment]
Sorry... you are correct... I love finding issues one and half years later.

This is not critical for launch.

**Comment by melwoodard** [comment]
Thanks - so just to be clear, the desired functionality _should_ be what you stated above?

**Comment by saintsoup52** [comment]
Correct... it should be hidden when they are Post-9/11 eligible.
