### ISSUE TITLE
GI Bill CT: Clarify Estimated Benefits Results are by Year

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5390]
In the absence of the old benefits estimator it is not clear to the user that the estimated results are for an academic year.  Since the results can be very high, a user might think this for the life of the GI Bill

We should add "/yr" after "GI Bill pays to school" and "Book Stipend"

![image](https://cloud.githubusercontent.com/assets/4397508/25281700/238f1700-267c-11e7-8579-43587371cabd.png)

@leannammiller @mphprogrammer @saneshark

**Comment by leannammiller** [comment]
@melwoodard your call

**Comment by melwoodard** [comment]
We'll add, thanks.
