### ISSUE TITLE
GI Bill CT: Yellow Ribbon issues

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5391]
There are three issues here:
1) The question should be "Will you be a yellow ribbon recipient?" It doesn't matter if they are a **current** recipient.

2) The default answer to that question should be "No" as it is on the current tool. Most students will not receive YR benefits

3) The Yellow Ribbon results in the estimator should be below the tuition/fees benefits not below the book stipend. 

![image](https://cloud.githubusercontent.com/assets/4397508/25281993/2da3b4fc-267d-11e7-97ed-66ba1aed2626.png)

@leannammiller @saneshark @mphprogrammer

**Comment by melwoodard** [comment]
1. We will change this
2. The default answer is in fact "No" - no change here
3. We will change this
