### ISSUE TITLE
GI Bill CT: "See rates" link to Yellow Ribbon is using incorrect year

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5392]
The link to the Yellow Ribbon rates is linking to the incorrect year. 

It should be linking to "2016" not "2015."

![image](https://cloud.githubusercontent.com/assets/4397508/25282830/a7488da8-267f-11e7-879f-cb26c3f939f0.png)

**Current Link**
http://www.benefits.va.gov/gibill/yellow_ribbon/2015/states/RI.asp

**Correct Link**
http://www.benefits.va.gov/gibill/yellow_ribbon/2016/states/ri.asp

@leannammiller @saneshark @mphprogrammer

**Comment by leannammiller** [comment]
@bshyong @U-DON please fix at your earliest convenience
