### ISSUE TITLE
GI Bill CT: Confusing order of Additional Resources

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5393]
In the new "Additional Resources" under the video is says "Ready to Apply" but the resource link right below are for people who are not ready to apply.

![image](https://cloud.githubusercontent.com/assets/4397508/25283264/26bdbd64-2681-11e7-864e-cdb16abea474.png)

"Explore your career" links to Careerscope and is for people who have no idea what they want to do next.

I recommend either reordering the resources to make more sense or removing the "Ready to Apply" language.

Also to avoid confusion consider saying "Choose a school guide"

@leannammiller @saneshark @mphprogrammer

**Comment by leannammiller** [comment]
@melwoodard your call

**Comment by melwoodard** [comment]
Let's remove the "Ready to apply" heading and modify the second link per Patrick's suggestion above.
