### ISSUE TITLE
GI Bill CT: Calculator Results for OJT missing "/month"

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5403]
The calculator results for OJT programs is missing key descriptive information.

Unlike how school results are displayed the calculated results for OJT/Apprenticeship programs are not totaled per term but rather they keep displaying a per month benefit. We need to clarify that these are monthly benefits not total benefits.

Additionally the OJT programs don't have "Terms" like school programs so we should probably modify that language as well.

**Old Version (Production)**
![image](https://cloud.githubusercontent.com/assets/4397508/25330462/bf2766b2-28ad-11e7-8f08-72e331cf47a6.png)

**Staging Version**
![image](https://cloud.githubusercontent.com/assets/4397508/25330506/dea1fd86-28ad-11e7-8efc-df067bfdf80d.png)

@leannammiller @saneshark @mphprogrammer

**Comment by U-DON** [comment]
@melwoodard Any suggestions for the 'per term' language?

**Comment by melwoodard** [comment]
@U-DON @bshyong let's change that heading to "Estimated benefits per month" since it's outlining monthly amounts
