### ISSUE TITLE
GI Bill CT: Buy-up should revert back to $600

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5405]
This can be backlogged.

If a user inputs more than $600 in the buy-up input field the field should return to $600, the max value. Since the calculations limit the buy-up to $600 this is not critical for launch.

![image](https://cloud.githubusercontent.com/assets/4397508/25331050/b067f2de-28af-11e7-8c68-3729de799053.png)

@leannammiller @saneshark @mphprogrammer

**Comment by patrickvinograd** [comment]
Seems feasible, will leave it to somebody with more frontend experience to identify the right event/events on which to rest - guessing it's when this text field loses focus but there might be other cases.
