### ISSUE TITLE
GI Bill CT: Yellow Ribbon Results should disappear

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5408]
If a a user selects a cumulative service that results in a tier that is less than 100% the Yellow Ribbon results should not appear (similar to the yellow ribbon questions).

![image](https://cloud.githubusercontent.com/assets/4397508/25339377/867645a4-28d0-11e7-9f8f-4d8437cf73d7.png)

@leannammiller @saneshark @mphprogrammer

**Comment by melwoodard** [comment]
Confirmed bug - when 90% or less is selected, the YR field correctly disappears, but the YR results in the calculator do not.

<img width="966" alt="argosy_university-seattle_-_gi_bill _comparison_tool" src="https://cloud.githubusercontent.com/assets/4106356/25348218/5bed314c-28d2-11e7-85a4-0ad4f9532123.png">
