### ISSUE TITLE
Blue Box Overload: Multiple Pages

### ISSUE THREAD

**Issue by raineystraus** [department-of-veterans-affairs/vets-website#542]
https://www.vets.gov/disability-benefits/conditions/pow/
https://www.vets.gov/disability-benefits/claims-process/evidence/
https://www.vets.gov/education/gi-bill/montgomery-active-duty/
https://www.vets.gov/education/gi-bill/transfer/
https://www.vets.gov/education/survivors-dependent-assistance/

**Comment by MarinaMartin** [comment]
@raineystraus Is this fixed? @singletrackr referenced this in a recent commit but the links you have above still don't seem quite consistent with regard to blue boxes.

(Is there a style guide reference somewhere as to when we use a blue box? I can't find one.)

**Comment by singletrackr** [comment]
@raineystraus I updated the blue boxes on the pages listed in your comment above. Can this issue be marked as resolved and closed?

**Comment by dannychapman** [comment]
These are resolved. Closing!
