### ISSUE TITLE
GI Bill CT: Cautionary Information - Extra "0"

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5431]
In the newly launched comparison tool, if a user selects a school that has zero complaints an extra line appears.

https://www.vets.gov/gi-bill-comparison-tool/profile/11964125

![image](https://cloud.githubusercontent.com/assets/4397508/25424738/7b330052-2a37-11e7-8fab-22037c690eeb.png)

@leannammiller @melwoodard

**Comment by melwoodard** [comment]
Thanks @saintsoup52.

We'll need to look into what's causing this - the trailing 0 doesn't appear consistently: https://www.vets.gov/gi-bill-comparison-tool/profile/21115805

**Comment by U-DON** [comment]
The issue arose since there's inconsistency in the data when there are zero complaints in a category. Some schools have `null`, some have `0`, and some have a mix (such as in this case). Made a PR to generally account for falsy values.

Tagging @mphprogrammer / @patrickvinograd for awareness.
