### ISSUE TITLE
GI Bill CT: Not clear path from search results to school profile page

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5457]
Feedback from a stakeholder: "I'm not sure it's clear to visitors that they need to click on the school name in order to get the full picture.  So, you type in a school and you get a mini profile,  Then you need to click on the school name to get the full profile.  Maybe they could add something that says "Click here for full information""

The new version of the GI Bill CT it is not clear that a user can or should click on the school name to be taken to the school profile page. In fact, less than half of users last who landed on the search page clicked through to the school profile page.

![image](https://cloud.githubusercontent.com/assets/4397508/25579846/8823dd3e-2e49-11e7-9691-b5ece18fee60.png)

The Department of ED uses a similar design on the College Scorecard and they had the same issue. That is why they added a "VIEW MORE DETAILS>" button on the bottom of their search results.

![image](https://cloud.githubusercontent.com/assets/4397508/25579853/9c92ced8-2e49-11e7-8e61-1e4b06d6580a.png)

@leannammiller @melwoodard

**Comment by leannammiller** [comment]
@melwoodard i agree that we could do this. could you mock something up? our FE has capacity.

**Comment by saintsoup52** [comment]
Thank you... and if you need more incentive... ~95% of College Scorecard users make the jump from the search results page to the school profile page. 

Less than half of GI Bill CT users make the jump which means this is a very big user experience issue.

**Comment by melwoodard** [comment]
The lower left area of the card will be a good noticeable place for this - here's how I think it could look for desktop vs. mobile:

<img width="735" alt="20170509-gibct" src="https://cloud.githubusercontent.com/assets/4106356/25871123/459684b2-34bb-11e7-8310-06f8eb2844d6.png">

<img width="289" alt="20170509-gibct" src="https://cloud.githubusercontent.com/assets/4106356/25871146/531807f0-34bb-11e7-9c9b-cbcad7d22b48.png">

**Comment by leannammiller** [comment]
Will the ‘view details’ take them to the profile page? If so, I think it’s a great idea.
 
Stephanie

**Comment by saintsoup52** [comment]
Sorry to be commenting on a closed comment... But this change has not been pushed live yet and it was closed 12 days ago.

Is there an ETA for when this will be live?

@leannammiller @melwoodard

**Comment by jmcneal65** [comment]
Morning.  I believe, I am reading that this task has been closed but I don't see on the CT website the link "View Details" to direct our users to view the full profile of a school.  Please provide an update. Thanks!

John

**Comment by leannammiller** [comment]
Yes, this ticket reflects finding the solution. There are separate tickets to reflect the implementation that are in our private repo. It should be done this week or next. I'll keep you posted @jmcneal65

**Comment by jmcneal65** [comment]
Thanks. This small missing detail has caused some headaches for our users'... Emails coming in with comments:  "The Comparison Tool is broken, can't reach the school profiles after search results."  Sooner the better... @leannammiller .

**Comment by leannammiller** [comment]
@jmcneal65 could you please forward me any emails you get with this complaint? We need to understand the scope of the problem.

The fix will be implemented this sprint but we want to make sure we're interpreting numbers correctly.
