### ISSUE TITLE
Blue boxes inconsistent around Hazardous Exposures sections

### ISSUE THREAD

**Issue by dnesting** [department-of-veterans-affairs/vets-website#547]
Sometimes the blue boxes cover all of the sections in a page.  Sometimes individual blue boxes cover individual sections.  Sometimes sections lack a blue box.

https://www.vets.gov/disability-benefits/conditions/exposures-to-hazardous-materials/agent-orange/

![image](https://cloud.githubusercontent.com/assets/7342162/11073892/b83ef698-87ba-11e5-874a-554d11ec6497.png)

https://www.vets.gov/disability-benefits/conditions/exposures-to-hazardous-materials/birth-defects/

![image](https://cloud.githubusercontent.com/assets/7342162/11073920/d213691e-87ba-11e5-8794-d4bf2c2f0ebf.png)

https://www.vets.gov/disability-benefits/conditions/exposures-to-hazardous-materials/project112-SHAD/

![image](https://cloud.githubusercontent.com/assets/7342162/11073928/e9d84f06-87ba-11e5-878b-63867658f372.png)

**Comment by dannychapman** [comment]
@dnesting Good catch. Fixed!
