### ISSUE TITLE
GI Bill CT: Add learn more for VSOC

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5475]
Feedback from stakeholder: "Quick note, I get that VSOC isn’t available at most schools; would it be possible to hyperlink it to VSOC’s landing page anyway?  For those who don’t know what VSOC is, they’ll be like “Veterans don’t have success on this campus—pass”."

![image](https://cloud.githubusercontent.com/assets/4397508/25662115/4aa6bcb2-2fe1-11e7-886c-8faa9b3c4aed.png)

Since we already have approved text from the about this tool page we probably should add it to the CT as a learn more

Veteran Success on Campus (VSOC)

The VetSuccess on Campus (VSOC) program aims to help Veterans, Servicemembers, and their qualified dependents succeed and thrive through a coordinated delivery of on-campus benefits assistance and counseling, leading to completion of their education and preparing them to enter the labor market in viable careers. Read the VetSuccess on Campus (VSOC) fact sheet.
For more information visit: https://www.ebenefits.va.gov/ebenefits/vsoc  

http://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp

@leannammiller @melwoodard

**Comment by leannammiller** [comment]
We will put this in our backlog.
