### ISSUE TITLE
coding for smaller font size

### ISSUE THREAD

**Issue by k8reimann** [department-of-veterans-affairs/vets-website#5489]
Survivors Pension Rates page

https://github.com/department-of-veterans-affairs/vets-website/blob/content/wip/pensions/content/pages/pensions/survivors-pensions/rates.md

The following text, under bold header "Find your Maximum Annual Pension Rate (MAPR) amount" needs to be smaller:

Date of Cost-of-Living Increase: 12-01-2016
Increase Factor:  .3%
Standard Medicare Deduction: Actual amount will be determined by SSA based on individual income.

(also, I'm unable to designate a site wide label to this issue...)

**Comment by rroueche** [comment]
@k8reimann looks good to me now here too -- does it look good to you?
https://vetsgov-pr-5241.herokuapp.com/pension/survivors-pension/rates/

if this is good to go, you can close the issue!
