### ISSUE TITLE
Font size change needed

### ISSUE THREAD

**Issue by k8reimann** [department-of-veterans-affairs/vets-website#5490]
on Veterans Pensions Rates page
https://github.com/department-of-veterans-affairs/vets-website/blob/content/wip/pensions/content/pages/pensions/rates.md

text following bolded heading "Find your Maximum Annual Pension Rate (MAPR) amount" should be smaller font:

Date of Cost-of-Living Increase: 12-01-2016
Increase Factor:  .3%
Standard Medicare Deduction: Actual amount will be determined by SSA based on individual income.

(unable to designate this issue with sitewide label...)

**Comment by rroueche** [comment]
@peggygannon looks good when I check, not sure how it was fixed, but does it look right to you now? 

https://vetsgov-pr-5241.herokuapp.com/pension/rates/

**Comment by rroueche** [comment]
if so, you can go ahead and close this issue!

**Comment by leannammiller** [comment]
closing.
