### ISSUE TITLE
Urgent:  The following rows should be checked: Complaint File

### ISSUE THREAD

**Issue by jmcneal65** [department-of-veterans-affairs/vets-website#5494]
Uploading Complaint file produce errors:
          >>>Line 40 to Line 8193<<<<<
The following headers should be checked: 
•Level is a missing header
•Case owner is a missing header
•Submitted is a missing header 
•Closed is a missing header

Example of messages: 

![complaint](https://cloud.githubusercontent.com/assets/26603766/25803770/84fee3c4-33c6-11e7-9d96-5074ab0e31f9.png)

**Comment by ayaleloehr** [comment]
Tagging @mphprogrammer @leannammiller @saneshark for awareness.

**Comment by mphprogrammer** [comment]
Those are error messages produced when there is no facility code in a data row. In this case, the facility code is required to use the data in the Csv’s row. This is expected and normal. The Csvs have issues with missing data, so we warn on a row by row basis. In the case of the missing headers (columns), I would like to see the CSV in question to make sure those headers are missing

**Comment by mphprogrammer** [comment]
I need to see the CSV being used for the Header (column) issues. As far as I can tell after a quick glance:

(1) the missing header `Closed` should be named `Closed reason` - looks like the name changed in the CSV file, 
(2) the missing header `Level` looks like it can be taken out of GIDS (I am not sure why its there in the code)
(3) the missing header `Case owner` looks like it can be taken out of GIDS (I am not sure why its there in the code)
(4) the missing header `Submitted` looks like it can be taken out of GIDS (I am not sure why its there in the code)

**Comment by mphprogrammer** [comment]
The only real issue is the column name change from `closed reason` to `close`, this will affect complaint counts. If you, for the time being, rename the column `closed` to the name `closed reason` and rerun the upload, that particular missing header error should disappear, and the complaint counts should be fine.

**Comment by mphprogrammer** [comment]
See the comments that address this in issue #5495.

**Comment by leannammiller** [comment]
@mphprogrammer here is the list of errors that John wanted me to send along to you.

[05-11-17 Errors.docx](https://github.com/department-of-veterans-affairs/vets-website/files/993179/05-11-17.Errors.docx)

**Comment by mphprogrammer** [comment]
@jmcneal65 Could you check the Complaints Csv to see if there are blanks in the facility_codes corresponding to rows in the error message. 

Again, these Csvs often suffer from data integrity issues (the data is suitable for humans, but not suitable for machines). As an aside, an earlier complaints csv that I have has over 670 missing facility codes in the data. The new Data Service is simply alerting you to that. Tagging @leannammiller for awareness...

**Comment by mphprogrammer** [comment]
For illustration, a prior Complaint.csv, note the facility_code column and the total count (607 of 7902 records with blank facility_codes).

<img width="709" alt="screen shot 2017-05-11 at 1 23 00 pm" src="https://cloud.githubusercontent.com/assets/4104431/25962822/34d6e53e-364d-11e7-9448-b66680defeb9.png">

**Comment by mphprogrammer** [comment]
Closing this per last weeks meeting.
