### ISSUE TITLE
Urgent:  The following rows should be checked: WEAMS FILE

### ISSUE THREAD

**Issue by jmcneal65** [department-of-veterans-affairs/vets-website#5495]
when uploading the WEAMS file;  it not reading blanks in the institution field, see attachments

![weams](https://cloud.githubusercontent.com/assets/26603766/25803831/d3e1b156-33c6-11e7-8c8b-656716a2e597.png)

**Comment by ayaleloehr** [comment]
Tagging @mphprogrammer @leannammiller @saneshark for awareness

**Comment by mphprogrammer** [comment]
@jmcneal65 This is normal, and if you check the rows the institution names are probably blanks - these names are required. Normally, these CSVs contain errors (sometimes many). One of the rules we use is schools must have names and facility codes or they will not display in the GIBCT, nor would it be useful to do so.

**Comment by jmcneal65** [comment]
this is not normal, it wasn't happening prior to new updates...

**Comment by leannammiller** [comment]
Let's sync up and see if there are some process improvements we can make to smooth this out, @jmcneal65

**Comment by mphprogrammer** [comment]
@jmcneal65 can you look at rows 34068 and 34069 under the institution column and tell me what school names are there? Every new CSV file has its own "bad" data, and they would not have the same errors from update to update.

**Comment by mphprogrammer** [comment]
@jmcneal65 If you prefer, you can email the CSV to me, and I can take a look if you'd like.

**Comment by jmcneal65** [comment]
Will do.

**Comment by jmcneal65** [comment]
34068 and 69 rows has NULL in both rows

**Comment by mphprogrammer** [comment]
@jmcneal65 So in this case, it seems like the Weams CSV has some data integrity issues, which has been common in the past. Institution names cannot be null to work in the GI Bill Comparison Tool (it can't be searched on and would provide an unsatisfactory user experience). The old version of the Data Service (from last year) absorbed these errors and did not report non-validating rows. The new one lets you know that the data in the "bad" rows should be checked. Most often, these are data errors similar to what you have found. The use of the word "normal" our earlier conversation meant "this is how the data service should react". This does not mean that the entire Csv is bad, only the two rows highlighted.

**Comment by mphprogrammer** [comment]
Closing this per last weeks meeting...
