### ISSUE TITLE
"Ionizing Radiation" and "Radiogenic Risk Activities" are confusingly similar

### ISSUE THREAD

**Issue by dnesting** [department-of-veterans-affairs/vets-website#553]
These two sections under exposures-to-hazardous-materials are confusingly similar, providing similar bulleted lists for eligibility.  Should these be combined into one page?

https://www.vets.gov/disability-benefits/conditions/exposures-to-hazardous-materials/ionizing-radiation/
https://www.vets.gov/disability-benefits/conditions/exposures-to-hazardous-materials/radiogenic-risk-activities/

Also, FWIW, UV sun exposure is "ionizing radiation"; we might try to find a better term for that.

**Comment by rcarthur** [comment]
@mariana-almeida These are indeed confusing - it's very complicated because both involved radiation and, in some cases, overlap. They are, however, different programs, with different names and different eligibility lists.  These two topics cannot be combined.

**Comment by dnesting** [comment]
It sounds like you're saying we have two government programs that are confusingly similar, and we are choosing to expose that confusion to the user.  This seems like a missed opportunity.  I don't believe we are under any obligation to maintain a 1:1 correspondence to content on the site with the government program behind it, are we?  Let's focus on the user experience.

(That being said, I am completely open to responses that we can't find a way to combine these in a way that's less confusing to the user, or that none of this content is in the critical path to getting benefits, and so it really doesn't matter all that much.)

**Comment by mariana-almeida** [comment]
@dnesting Thanks for your feedback! I'm afraid we need to keep these program titles as is. They are distinct programs with specific criteria for eligibility - even though they are similarly named. As you mentioned, the call to action is clear for each program - apply! I appreciate your close reading of our site!
