### ISSUE TITLE
GI BILL CT: Change Public/Private/Foreign "Institution" to "School"

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5726]
@leannammiller  @melwoodard @jmcneal65

We need ensure the language describing schools on the GI Bill Comparison Tool is consistent between types of schools. 

In the header on the school profile page we should be saying Public /  Private / For Profit /Foreign "School" not institution.  Currently we only use the term school when a "For Profit" school is selected.

The consistency is important because it is unfair and confusing to call one a school and the other an institution. Additionally we are drafting the updates to the TAP curriculum and instructors use the GI Bill CT to teach the difference between types of schools and the feedback was that the word "institution" is confusing.

**Private School**
https://www.vets.gov/gi-bill-comparison-tool/profile/31000139

![image](https://user-images.githubusercontent.com/4397508/26973191-3a6bbc98-4ce3-11e7-984b-54c552952e1b.png)

**Public School**
https://www.vets.gov/gi-bill-comparison-tool/profile/11801605

**Foreign School**
https://www.vets.gov/gi-bill-comparison-tool/profile/31002871

**Comment by leannammiller** [comment]
Thanks for noting @saintsoup52 - we will put this in our backlog.

**Comment by leannammiller** [comment]
confirming with Stephanie Price this is desired
