### ISSUE TITLE
facility locator results not filtering?

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#577]
when i search any facility type (e.g., cemetery) by state (e.g., Virginia), i get facilities that are in many other states--not just Virginia?

![screen shot 2015-11-10 at 8 48 35 pm](https://cloud.githubusercontent.com/assets/13770771/11081649/733d6700-87ec-11e5-95b8-005f38a91bc1.png)

**Comment by dannychapman** [comment]
Unable to replicate. Seems to work when zooming out. Closing for now.
