### ISSUE TITLE
Different parts of the vets.gov website have different headers

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/vets-website#587]
**vets.gov**:
![screen shot 2015-11-11 at 1 15 39 pm](https://cloud.githubusercontent.com/assets/772/11098940/5e77dd0c-8876-11e5-8bb1-eabf52ad836a.png)

**GI Bill Comparison Tool**:
![screen shot 2015-11-11 at 1 15 46 pm](https://cloud.githubusercontent.com/assets/772/11098939/5e773b72-8876-11e5-9bc4-8c41ada9d89e.png)

**Facility Locator**:
![screen shot 2015-11-11 at 1 15 52 pm](https://cloud.githubusercontent.com/assets/772/11098938/5e775210-8876-11e5-97a9-f4f2f43f941f.png)

Specific differences:

- [ ] GI Bill Comparison Tool's header is a different color
- [ ] They all have different widths
- [ ] GI Bill Comparison Tool's "VA logo" has a different hover animation (it's instant as opposed to fade-in)
- [ ] `This site is a work in progress.` is in a different position in different position and fonts on each of them

**Comment by llimllib** [comment]
I fixed the differences between facility locator and the main vets.gov header in c49d5f3

**Comment by MarinaMartin** [comment]
@rickleegit Can you please update the GI Bill header, or assign to Marc? Thanks!

**Comment by rickleegit** [comment]
This will also resolve https://github.com/department-of-veterans-affairs/vets-website/issues/671

**Comment by koconnor719** [comment]
is this resolved since 671 is closed? if so can this issue be closed?
