### ISSUE TITLE
Server is sending 403s, instead of 404s for non-existant pages

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/vets-website#588]
```
~ $ http head https://www.vets.gov/definitely-not-real
HTTP/1.1 403 Forbidden
Connection: keep-alive
Date: Wed, 11 Nov 2015 18:27:57 GMT
Server: nginx/1.4.6 (Ubuntu)
x-amz-error-code: AccessDenied
x-amz-error-message: Access Denied
```

**Comment by joduinn** [comment]
Found in triage. 

$ curl https://www.vets.gov/definitely-not-real
...gives a correct 404 page. 

We've done a bunch of nginx config changes in last few months, which I think solved this. Closing as done, but if you still see problems, please reopen with details.
