### ISSUE TITLE
Posting Vets.gov to Facebook has no image

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#590]
![image](https://cloud.githubusercontent.com/assets/489465/11100524/bccf78f2-887f-11e5-9642-ff98db0b2416.png)

**Comment by MarinaMartin** [comment]
@dannychapman I am assigning this to you, as I think you said you have a PR to fix this. Please close when it's pushed to production. Thanks!

**Comment by dannychapman** [comment]
![screen shot 2015-11-19 at 1 33 15 pm](https://cloud.githubusercontent.com/assets/281709/11280093/1e644ed8-8ec2-11e5-9fe8-dc08bfa122c4.png)

Fixed! Closing.
