### ISSUE TITLE
UserVoice ideas look like they are coming from Marina

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#593]
Fine for now, ultimately strange and should be changed.

**Comment by rickleegit** [comment]
Kelly this looks like a design issue. But if not please assign @plusjeff

**Comment by koconnor719** [comment]
Emdash, do you know when we can change this?  if not for a while, can you (or marina) please provide a sentence that i can respond with??

**Comment by koconnor719** [comment]
test message; closed.

**Comment by MarinaMartin** [comment]
Why did we close this? This is an issue. The reason is UserVoice is using my Github account to post via Zapier. I need to change this, which is an open issue but not super high priority.

**Comment by MarinaMartin** [comment]
@rickleegit @koconnor719 If I assign myself an issue please don't re-assign to other people. This should probably apply across the board (e.g. if Emdash assigns herself an issue, there is probably a reason).

You can see who assigned who the issue in the little history notes above. Thanks!

**Comment by rickleegit** [comment]
Sorry. We used this as a test issue to show Kelly the features of GH.

**Comment by MarinaMartin** [comment]
This was fixed.
