### ISSUE TITLE
Suggestion: Linking to eBenefits for disability compensation.

### ISSUE THREAD

**Issue by edmullen** [department-of-veterans-affairs/vets-website#594]
On the [Disability Benefits page](https://www.vets.gov/disability-benefits/get/), the two main call to action buttons – "Go to eBenefits to apply" – link to the [eBenefits homepage](https://www.ebenefits.va.gov/ebenefits/homepage) where the user needs to find the right link for disability benefits. 

**Consider linking directly to the [disability compensation page](https://www.ebenefits.va.gov/ebenefits/about/feature?feature=disability-compensation)**. Its saves a step and confusion.

Further down in the Steps, the apply link does go directly to the disability compensation page on eBenefits, so the precedent exists.

**Comment by emilyville** [comment]
@mariana-almeida - If this makes sense to you assign to me or tiffany to change!

**Comment by rcarthur** [comment]
@mariana-almeida I concur with this user comment.  My guess is that there was some uncertainty about logins - but this doesn't seem to be a real problem.

**Comment by mariana-almeida** [comment]
@webinista Can you please update this link? It's the eBenefits button on Disability pages. Details in the original post. Thank you!!
