### ISSUE TITLE
Under what license is the site (and content) distributed?

### ISSUE THREAD

**Issue by benbalter** [department-of-veterans-affairs/vets-website#599]
It'd be awesome to add a LICENSE file, to make it explicit what license, if any, the site's code and content is distributed, and what license, if any, contributors grant if they submit a pull request. 

Since it's a government site, and contains both code and content, I'd suspect CC0 would be a natural choice (since it can be used for both and is congruent with government work being in the public domain).

**Comment by nsinai** [comment]
How about this (taken from analytics.usa.gov):

Public domain

This project is in the worldwide public domain. As stated in CONTRIBUTING:

This project is in the public domain within the United States, and copyright and related rights in the work worldwide are waived through the CC0 1.0 Universal public domain dedication.

All contributions to this project will be released under the CC0 dedication. By submitting a pull request, you are agreeing to comply with this waiver of copyright interest.

**Comment by emilyville** [comment]
@webinista @plusjeff this sounds good to me? if it looks good let's add a license file.

**Comment by webinista** [comment]
Please contribute to the LICENSE.md file in the [issue#599 branch](https://github.com/department-of-veterans-affairs/vets-website/tree/issue%23599).

**Comment by webinista** [comment]
@plusjeff I'm going to assign to you for some contributions in the what's public domain/what isn't public domain section. It's in the issue#599 branch.

**Comment by plusjeff** [comment]
PR #2548  for this assigned to @MarinaMartin

**Comment by plusjeff** [comment]
CC Zero 1.0 applied awhile ago. Closing.
