### ISSUE TITLE
Site does not load over HTTPS without www

### ISSUE THREAD

**Issue by benbalter** [department-of-veterans-affairs/vets-website#601]
Depending on whether you use HTTPs or HTTP, and www or the root domain, the site does not load (time out):

| &nbsp;  | HTTPS              | HTTP               |
|:--------|:-------------------|:-------------------|
| WWW     | :heavy_check_mark: | :heavy_check_mark: |
| non-www | :no_entry_sign:    | :heavy_check_mark: |

Specifically, http://vets.gov, http://www.vets.gov, and https://www.vets.gov all resolve, but https://vets.gov appears to refuse the connection (it should probably redirect to https://www.vets.gov, the canonical endpoint).

/cc @konklone because HTTPs + .gov :smile_cat:

**Comment by konklone** [comment]
Just saw this -- to connect the threads, my comment at https://github.com/department-of-veterans-affairs/vets-website/issues/589#issuecomment-156181743 requests that when `https://vets.gov` is configured, that an HTTP header be placed on it:

```
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

This is the header used by `https://whitehouse.gov`, `https://18f.gov`, and ~35 other `.gov` domains.

**Comment by emilyville** [comment]
@awong-dev - could you add some context here and re-assign or close appropriately?

**Comment by ayaleloehr** [comment]
This is working as of today. Both http and https, with and without www, all now redirect properly to https://www.vets.gov.

Also tested on many pages, not just the homepage. All works properly now.
