### ISSUE TITLE
UserVoice Idea: Improve the Search Engine

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#602]
The search engine must be improved. I searched for IHD and there was nothing returned. Then I searched for Ischemic Heart Disease and got one link returned. Acronyms and abbreviated terms are standard within the military and VA lexicon. The VA dot gov search engine is the worst ever. Please bring this one up to the level of Google, or at least close.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10678980-improve-the-search-engine

**Comment by koconnor719** [comment]
Eric,  here's my suggested response.  can you pls. modify as you think / or just validate and i'll post to the site.

"Thank you for your feedback.  The VA.gov search is not a part of vets.gov search.  Please check out our vets.gov search functionality and let us know your feedback."

**Comment by koconnor719** [comment]
posted and closed
