### ISSUE TITLE
No link to Github Repository?

### ISSUE THREAD

**Issue by OpenGlobe** [department-of-veterans-affairs/vets-website#604]
I might have missed it, but I didn't see any link to this Github repo from the pages - seems like off the "we're designing in the open" statement in top header might be one place to include something like that.

**Comment by nsinai** [comment]
Good point @OpenGlobe!  I also didn't see this repo anywhere on vets.gov, and only found it looking around github.

There are some great calls to action by Secretary Bob, but they aren't actionable with a link or explanation about how to contribute back.  Even the user voice icon is pretty subtle, and not connected to the Secretary Bob call to action.

**Comment by OpenGlobe** [comment]
Closed.
