### ISSUE TITLE
Download complete list for claims assistance issues

### ISSUE THREAD

**Issue by OpenGlobe** [department-of-veterans-affairs/vets-website#605]
The statement at the bottom of Sec. McDonald's message takes visitors to the following page to "download the complete list" of claims assistance providers:

http://www.va.gov/ogc/apps/accreditation/index.asp

But the download from that page appends .asp to each Excel document downloaded for one of the four categories selected.  Perhaps this isn't an issue for vets.gov as much as it is for va.gov - but seems like a PDF with those four categories combined might be a better temporary solution off the vets.gov page.   I'm guessing most users will otherwise struggle to do much of anything with the files.

**Comment by koconnor719** [comment]
this link is for the disclaimer (not the blog); i think we should relabel this to "Search Accredited Attorneys, Claims Agents, or Veterans Service Organizations (VSO) Representatives" to be more accurate.

**Comment by koconnor719** [comment]
action required to modify link text.

posted response
Thank you for your feedback. We've added your suggestion to our enhancements and will clarifying the label for that link. Great idea!

vets.gov

**Comment by emilyville** [comment]
@webinista could you could tackle this one?
