### ISSUE TITLE
UserVoice Idea: add feedback directions

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#608]
-

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10680045-add-feedback-directions

**Comment by koconnor719** [comment]
marina, are you adding these manually?  if so, i can do that.

**Comment by koconnor719** [comment]
this is a duplicate comment so i'm closing; comment to add some feedback instructions to the site already logged and routed to Emdash.
