### ISSUE TITLE
User voice - clearer call to action and feedback channel

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#609]
Clearer call to action and feedback channel

Why isn't there a clearer way to give feedback on this page on the introductory post from Sec. McDonald? Why is there a lightbulb icon instead of a call to action, like "Comment" or "Write to us" or "Share Your ideas? https://www.vets.gov/2015/11/11/why-we-are-designing-in-beta.html

3
votes
Vote

**Comment by koconnor719** [comment]
emily,

per our discussion, i think you wanted to take some action on this one--maybe call the lightbulb "website feedback" or something--and provide some brief instructions on the site.  

how's this for a response: 

Thank you for your feedback. We have added your request as an enhancement and will be updating the site in the coming weeks.  Thank you.

**Comment by koconnor719** [comment]
posted response; design team working on adding some descriptive text for feedback.

**Comment by koconnor719** [comment]
this is related to UserVoice Idea: Overview of feedback #684

**Comment by emilyville** [comment]
Perfect! Thanks @koconnor719

**Comment by emilyville** [comment]
Also, hoping the blog post will help in addressing this. Closing, and we will see if it's an issue in usability testing.
