### ISSUE TITLE
User Voice - English usage

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#610]
English usage

Use the English language correctly. Don't use "agnostic" when you mean "independent". That is an IT bad English word that should not be used here. "Agnostic" pertains to religion.

**Comment by koconnor719** [comment]
Shaun, i don't think any change is actually needed here? pls. confirm and i'll close this issue and respond.  how's this for a response:

Thank you for your feedback. Our team of writers will review all language comments and update the content on vets.gov accordingly.

**Comment by ss0ss** [comment]
This is a style comment. IMO, no changes needed. Although, I do want to highlight that its use (assuming HS-level english) is geared towards religion, and not only until you have a college-level, even graduate reading level does it become part of normal vocabulary. Good to note.

**Comment by koconnor719** [comment]
revised response posted and closed:

Thank you for your feedback. Our team of writers will review all language comments and update the content on vets.gov accordingly.  Our writers strive to make the language on  vets.gov clear and direct, yet its tone is warm and quiet. We respect Veterans’ time, so we get to the point. And we avoid bureaucratese. We distill and simplify. We’re not selling programs and benefits, but rather helping Veterans and their families understand whether a benefit is right for them so they can make informed choices about how to proceed. Our goal is to give Veterans and their families the information they need to make important decisions confidently, easily—and done.

vets.gov team
