### ISSUE TITLE
User voice - explain schedule of disabilities

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#611]
Explain schedule of disabilities

Explain how to interpret the schedule of disabilities

**Comment by koconnor719** [comment]
susan and shaun, i don't think we want to be writing any content describing disabilities--this links to 38 CFR http://www.benefits.va.gov/warms/bookc.asp#k which actually does provide some details that are helpful...i'm NOT going to label this as an enhancement..ok?  if response below ok w/ you i will close.

Thank you for your feedback. We link to source material for this information 38 CFR Book C, Schedule for Rating Disabilities.

**Comment by ss0ss** [comment]
Kelly - so we can close this, right?

**Comment by koconnor719** [comment]
yes.  as long as you guys are ok w/ my response--which i will post back to site.  i can close these when i post the response.

**Comment by koconnor719** [comment]
trying to make this easy for you guys:)  i'm happy to manage these issues start to finish--once i get your approval..if that works?

**Comment by ss0ss** [comment]
I'm fine with that. If you feel that you have the ammo to close out on your own - like something obvious, I say that's fine. @sjb912 ?

**Comment by sjb912** [comment]
Totally fine with that.

**Comment by koconnor719** [comment]
posted response and closed
