### ISSUE TITLE
User voice - Make Vets.gov "Process" header more clear

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#613]
Make Vets.gov "Process" header more clear

"Process" and "Playbook" aren't self-evident terms. Maybe "Behind the Scenes" or "How Vets.gov is Being Built" would be more accurate for "process"? Instead of "playbook", maybe "Vet.gov Playbook" or "Vets.gov plans" or "Plan for vets.gov"

2
votes
Vote

**Comment by koconnor719** [comment]
emily, i totally agree with this one.  1) i don't think it makes sense lumping the blog and playbook together, and 2) i don't think process is good label for either.  can you pls. advise on how you'd like to handle:)  thanks. then i can draft a sentence with response..

**Comment by sjb912** [comment]
Process as a header for Playbook works. Blog is badly placed there, though. 

Creating vets.gov would work as a header for both.

**Comment by koconnor719** [comment]
posted response:

Thank you for your feedback. Our team is thinking about a better label for these things, based on your feedback and other user feedback we have received. We will be modifying this to make it more clear to users!

vets.gov team

**Comment by emilyville** [comment]
created issue #724

**Comment by koconnor719** [comment]
posted updated response based on change:

Thank you for your feedback.  We received this feedback from other Veterans too--so we made the change!  Great idea.

vets.gov team
