### ISSUE TITLE
User voice - clarify UX

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#622]
Clarify UX

It's pretty hard to tell that the Yellow highlighted text is a title and not clickable, and that the lighter blue boxes below *are* links. Just the hover state isn't enough, there needs to be a better action callout here.

1
vote
Vote

**Comment by koconnor719** [comment]
emdash, pls. advise how you want to respond--and if you intend to you make this change?  in which case i'll mark as an enhancement.

**Comment by emilyville** [comment]
Created issue #722 to capture this feedback. Please respond that we are adding it to our roadmap!

**Comment by koconnor719** [comment]
posted and closed: 


Thank you for your feedback. We appreciate your comment, and we are working on this! We want to collect a little more feedback from Veterans before we make this particular change, but we've logged your comment, and it will be considered as we collect additional user feedback and brainstorm with our team about how to make the "How can we help?" text a better user experience.

vets.gov team
