### ISSUE TITLE
User voice - pin colors (facility locator)

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#624]
Pin Colors

Do the color of the pins on the Facility Locator Map have meaning? Purple = NCA, Brown = MC, ... ?

**Comment by koconnor719** [comment]
emily, 

should we add a legend to the facility locator page?  here are the color codes:
Red - Central Office
Blue - Benefits Office
Green - Intake Site
Purple - Cemetery
Orange - VISN (Veterans Integrated Service Networks) Office 
Yellow - Outpatient Clinics
Brown - Hospitals
Pink - Veteran Centers

**Comment by koconnor719** [comment]
how's this for response:

Thank you for your feedback.  We have added your change as an enhancement and will be modifying the site with the following color legend: 
Red - Central Office
Blue - Benefits Office
Green - Intake Site
Purple - Cemetery
Orange - VISN (Veterans Integrated Service Networks) Office 
Yellow - Outpatient Clinics
Brown - Hospitals
Pink - Veteran Centers

**Comment by llimllib** [comment]
I thought about a legend, but I didn't have a good idea for where to put it. Open to suggestions!

**Comment by koconnor719** [comment]
what about a link on top right of page (just above the text listing) to "color legend" that would open up one of those little info / help boxes we use  for " i ";

**Comment by koconnor719** [comment]
emily can you verify this link is ok to add?

**Comment by koconnor719** [comment]
posted response.

**Comment by emilyville** [comment]
Awesome. I will make a separate issue about usability of the map - and a legend, and we can incorporate with facility locator efforts.

**Comment by koconnor719** [comment]
ok to close this issue?  

proposed response:
Thank you for your feedback. Great idea--we're making your change!

vets.gov

**Comment by koconnor719** [comment]
posted response:
Thank you for your feedback. We have added your change as an enhancement and will be modifying the site with the following color legend: 
Red - Central Office
Blue - Benefits Office
Green - Intake Site
Purple - Cemetery
Orange - VISN (Veterans Integrated Service Networks) Office 
Yellow - Outpatient Clinics
Brown - Hospitals
Pink - Veteran Centers
