### ISSUE TITLE
User voice - UX clarity

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#627]
UX clarity

Clarify your hierarchy and color palette. The UX is fundamentally flawed, y'all. Clarify calls-to-action and user affordances.

**Comment by koconnor719** [comment]
emdash, how do you want to respond to this?

**Comment by emilyville** [comment]
Something like...

Thank you for your feedback! Clarity and UX hierarchy are important to us, and we want you to have a good experience on vets.gov. Please check back as we update and expand our design and incorporate more services.

**Comment by koconnor719** [comment]
posted and closed.

Thank you for your feedback. Clarity and UX hierarchy are important to us, and we want you to have a great experience on vets.gov! Please check back as we update and expand our design and incorporate more services. 

vets.gov team
