### ISSUE TITLE
User voice - disclaimer language

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#629]
Language on Blog unclear

Was reading the disclaimer on the blog. The last sentence (the link) really makes no sense. 'Download the complete list', it's not clear what the list is from the prior content.

**Comment by koconnor719** [comment]
emily and danny,

we actually have this enhancement in the backlog already --it was flagged during testing.  this has nothing to do w/ the blog--it's about the disclaimer content on every page...the link actually not be "download" but rather "search" given where this link take you:http://www.va.gov/ogc/apps/accreditation/index.asp


 i think the link should be, "search Accredited Attorneys, Claims Agents, or Veterans Service Organizations (VSO) Representatives" if you agree?

**Comment by koconnor719** [comment]
how's this for the response:

Thank you for your feedback. We've added your suggestion to our list of enhancements."

**Comment by koconnor719** [comment]
posted response; 

Thank you for your feedback. Our team is modifying the link. Great idea.

**Comment by dannychapman** [comment]
Bringing in @sjb912. Your thoughts @sjb912 ?

**Comment by sjb912** [comment]
Yeah -- it's a poor experience. The attorneys who helped us with the disclaimer wanted us to point to this page. Let's drop that "download" line and change the link language to:

Search for help near you. 

It would be great if that link could be the last sentence in the disclaimer paragraph, rather than hanging out all by itself.

**Comment by dannychapman** [comment]
@sjb912 Thanks! This is now ready for deployment.

**Comment by dannychapman** [comment]
All set!
