### ISSUE TITLE
User voice - apply for counseling eBenefits

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#631]
Apply for Counseling - refer to one-click in eBenefits

The "Apply for free counseling services" - there is an electronic one-click application process in eBenefits. It's okay to provide the form for some folks, but for others, the one-click option would be better and should be visible.

**Comment by koconnor719** [comment]
shaun, pls. advise on this one:)

**Comment by ss0ss** [comment]
I kind of get what they're going for, but they're pretty much asking for a function that currently resides within eBenefits, the one-click apply for counseling, to exist on vets.gov. Because as far as I know, we don't have any 'Apply For Counseling' yet, let alone the topic outside of PTSD. That will come with Mental Health.

**Comment by koconnor719** [comment]
posted response:

Thank you for your feedback. We are developing in the open and delivering iteratively, so we haven't built out healthcare information and services for vets.gov yet. We will review your feedback when we begin to design the healthcare portion of vets.gov, and we will make sure to provide Veterans with both the form and the one-click option for the application process. 

vets.gov team

**Comment by MarinaMartin** [comment]
Re-opening. The original poster is referring to the link on this page:
https://www.vets.gov/education/tools-programs/education-career-counseling/

which goes directly to a PDF. If there is a one-click option available today on eBenefits, we should link to that.

**Comment by ss0ss** [comment]
What's the quick-fix? Linking to eBenefits directly? I've been scrounging for that one-click option...but haven't found it yet. Will keep looking for it.

**Comment by MarinaMartin** [comment]
@ss0ss I think it's this:
http://www.benefits.va.gov/VOCREHAB/edu_voc_counseling.asp

**Comment by ss0ss** [comment]
Ah, ok. What the user was referring to was this (see larger snapshot below - this is taken from my personal eBenefits account). So, after you're logged in, you can navigate to the below page, w/in eBenefits and then you can click the 'Request Counseling' link, which takes you here:

![image](https://cloud.githubusercontent.com/assets/12176114/11174455/9469f502-8bf1-11e5-813a-bee62a9aabdd.png)

It's a one-click to fill out a request that sends you to a pii verification and then you are asked to submit. 

![image](https://cloud.githubusercontent.com/assets/12176114/11174423/312237de-8bf1-11e5-855c-07ab8ba608ba.png)

Any link on VA.gov is just going to take you to eBenefits and ask for credentials, every time.

I don't think we're there yet until we start integrating the eBenefits functionality into vets.gov.

Va.gov doesn't have a one-click functionality to apply for counseling.

**Comment by MarinaMartin** [comment]
@ss0ss Not to beat a dead horse, but can you try this experiment: log in to eBenefits. Right-click on that Request Counseling link and save it. Log out of eBenefits. Paste the link in your browser. Sign in. See if it takes you directly to the request counseling page? If it does, then we could at least link to it directly even if it forces sign-in in the middle.

**Comment by ss0ss** [comment]
@MarinaMartin 
1. The URL is: https://eauth.va.gov/wssweb/wss-common-webparts/mvc/ebn/verifyVRE8832Application
2. After log out, I get a redirect to: https://access.va.gov/accessva/

**Comment by MarinaMartin** [comment]
@ss0ss If you click that URL while logged-out, and then log in, does it take you to the right page?

**Comment by ss0ss** [comment]
@MarinaMartin tldr: yes.
- If I'm logged out and enter the url, the access.va.gov does not give me the "dummy proof" sign in button to eBenefits to log back in...continues below
![image](https://cloud.githubusercontent.com/assets/12176114/11199687/df36bf28-8c9d-11e5-994d-ba161a4df8ca.png)
- However, if I nav to find any DS Logon, like here:
![image](https://cloud.githubusercontent.com/assets/12176114/11199721/4274c8aa-8c9e-11e5-8dea-a871097ede09.png)
- I log on (although it's a generic DS, and not to eBenefits...because there isn't a logo to eBenefits), enter creds, and then add the url to the complete form from eBenefits, then I get my ready-to-submit to the VRE8832 application, with all of my pii ready to send.

**Comment by ss0ss** [comment]
@koconnor719 - Good here? I'm removing myself as assignee.

**Comment by koconnor719** [comment]
pls. clarify the resolution; reading the thread i am unclear on next step.

**Comment by koconnor719** [comment]
this last screenshot is VOA (the 10-10EZ form / online application).  the initial user comment was about a one-click option to apply for counseling (the 28-8832 form).  from the above string, i do not believe a one-click option exists for the 28-8832 form?  i will confirm w/ eBenefits. but i'd like to close this issue if it doesn't exist.

**Comment by koconnor719** [comment]
working w/ EVSS team to make this deep link happen; posted response:

Thank you for the clarification. We are working on adding a link to the online form.  It won't be a one-click option though because Veterans will need to sign in using DS Login in order to use the online version of the form, but we can certainly add a link to that login page to make it easier for Veterans. Once a Veteran is logged in, it will take him or her immediately to the online form. Thank you for this suggestion!

vets.gov team

**Comment by koconnor719** [comment]
notes:

This is the main DS Logon page: https://myaccess.dmdc.osd.mil/identitymanagement/authenticate.do?execution=e3s1
 
This is the main DS Logon Registration page: https://myaccess.dmdc.osd.mil/identitymanagement/registration.do?execution=e4s1 
 
I don’t have the deep link to the vocational/educational counseling form yet.  That is something that EVSS must provide so that we can use it on the vets.gov web page.

**Comment by koconnor719** [comment]
confirmed w/ VR&E business SMEs that NO "one-click"counseling feature exits.  a Veteran needs to be signed in to eBenefits, apply, get approved, and then can access services. closing this issue since EVSS team is not able to provide a "deep link" to this within eBenefits.   modified response above per this information.  there is no other action item for this comment.
