### ISSUE TITLE
UserVoice Idea: Eligibility Assessment

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#634]
The key thing that's missing is quickly determining eligibility. There are so many benefits but we often don't know about them, until we attend some random briefing one day. What would be great is to take an eligibility assessment and then know, what all benefits I'm entitled to. Right now, for example, on the education page, you've broke up the benefits, but one may not know where to start. I often meet vets who don't know which education benefit they are actually eligible for.  

If you break out disability and education (which makes sense), perhaps have, front and center, an eligibility workflow option. Otherwise, I'd rather see what I'm eligible for immediately and then provide links to all of those application processes. 

This would require a great deal of meta work to be done, but would drastically improve the workflow.  The whole process can easily stay anonymous, as well.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10682529-eligibility-assessment

**Comment by koconnor719** [comment]
this seems to be an information architecture comment.  proposed response below:

Thank you for your feedback. We will review your comment along with other feedback we get from Veterans about determining eligibility.

**Comment by sjb912** [comment]
We've dreamed of a widget that would allow folks to feed us simple demographic info that would allow us to match them up with services and programs most likely to fit their needs, so they wouldn't have to hunt through so much to find what might apply to them. That's a manual front end to something that should be a whole lot more sophisticated. One day, when we have the ability to ID specific visitors, we can do a lot of this by making some smart cuts on serving up content about programs that most likely apply to them. Were they in the service during a period that would qualify them for post 9-11 GI Bill but they haven't yet applied for those benefits? That could be a piece of content we'd serve up. (And they can let us know if that's interesting to them. If not, we don't have to keep pushing it their way. ) Are they of an age where they're likely to be buying a house? Again - there's stuff we can serve them. Are they an aging Veteran who might need P&F services? There are lots of ways to think of how to do this. My Eric invented "people who bought x also bought x" for Amazon -- you wouldn't believe how effective that is at helping people get into stuff that might interest them. A variation on that theme, judiciously applied, could serve us on vets.gov, too.

**Comment by koconnor719** [comment]
proposed response based on comment above:

Thank you for your feedback. In the coming months, vets.gov will have an account sign on capability that Veterans can use to create a secure account, access services, and sign up for updates based on specific user preferences. This functionality will take us some time to develop, so please check back on vets.gov in early 2016! 

vets.gov team

**Comment by koconnor719** [comment]
posted and closed.
