### ISSUE TITLE
UserVoice Idea: Tools, and financial planning

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#636]
This new website can / should do more for servicemembers before and during their transition out of the service and into Veteran status. Areas to focus on would include calculators for better determining pensions, since this information is critical to financial planning during transition; tools to understand, prepare for, and submit first claims disability with the VA, specifically tools to better link their understanding of their own medical records into the VASRD; and additional tools specifically for financial planning, that factor in variables such as CRSC - and that are tools that are usable, functioning, and of added value to Vets for their financial planning.

The website would also benefit from hosting from flipped learning opportunities, to include YouTube / videos demonstrating specific tasks associated with interacting with the VA. Our younger generation is wildly comfortable with learning this way; the VA needs to be as comfortable with this, too.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10682889-tools-and-financial-planning

**Comment by koconnor719** [comment]
response:

Thank you for your feedback. We are developing in the open and releasing new features and content iteratively.  We have not yet begun work on the financial planning tools and content for the site, but will keep your feedback for when we start that work.

**Comment by koconnor719** [comment]
posted and closed
