### ISSUE TITLE
UserVoice Idea: 3 bugs

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#638]
1) first line of the Secretary's message is missing the word "of" after "version"

2) This feedback form is titled "Post an Idea," which doesn't accurately describe what I'm trying to do, which is report a bug.

3) When I click the light bulb icon to leave this feedback, I am taken all the way to the bottom of the page (on iPad Safari), and at first I couldn't see where I was typing.

-- Chase Kimball

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10684329-3-bugs

**Comment by llimllib** [comment]
#1 does indeed seem like a typo, should I fix it?

**Comment by koconnor719** [comment]
yes  pls. add the "of" bill.  thanks.

**Comment by koconnor719** [comment]
here's the response:

Thank you for your feedback.  We made some of your suggestions (correcting typo in our blog)--thank you!  We will consider your other feedback for future enhancements.

**Comment by koconnor719** [comment]
posted and closed
