### ISSUE TITLE
UserVoice Idea: Accurate Vet Entrepreneurship resources

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#646]
Under veteran entrepreneurship, you direct vets to only SBDCs, instead they should be directed to SBA OVBD where all SBA partners are available (SBDCs are only one partner).  Also you list CVE with its old name, not its present name.  You also fail to include VA VR&e which is the only VA program with authority and program availability to support small business development by disabled veterans.  Please quit mis-directing vets to only SBDCs, they are only part of the many resources available to vet entrepreneurs.  Bill Elmore, OriginalVetInBiz@yahoo.com

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10690080-accurate-vet-entrepreneurship-resources

**Comment by koconnor719** [comment]
checking w/ content sme's on this suggestion.

**Comment by koconnor719** [comment]
closing this comment, as I am pretty sure this user is referencing the page on VA.gov (http://www.benefits.va.gov/GIBILL/docs/factsheets/Entrepreneurship_Training.pdf) . None of the information cited is on vets.gov.

**Comment by MarinaMartin** [comment]
Shouldn't we leave this open and add the content? @koconnor719

**Comment by koconnor719** [comment]
he�s referencing a VA.gov content page that has not yet been migrated over.  My assumption was that we�d catch this in the concurrence process when we QA and update the content prior to migration, but I can reopen.


Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436
