### ISSUE TITLE
UserVoice Idea: Less blank space between sections for less scrolling

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#649]
Maybe tightened up the blank space between sections so we don't have to scroll as much from a desktop view (not an issue on mobile view)?

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10690968-less-blank-space-between-sections-for-less-scrolli

**Comment by koconnor719** [comment]
proposed response:

Thank you for your feedback. Our design and writing team tried to break up dense pages of information, rewrite the information in plain language, and design pages that were easy for user to scan quickly. In our user testing, these content pages tested well with Veterans, including blind Veterans.

vets.gov team

**Comment by koconnor719** [comment]
posted and closed
