### ISSUE TITLE
UserVoice Idea: What's the goal of this site?

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#651]
This 'post an idea' is great. You should have a clear objectives for this new great site so that ideas can  be in the correct context. You will save yourself alot of trouble. The intention of the site is good to know. Kudos for this site and I hope it elvolves into good usefullness for our vets. An about or objective will give idea contributors a starting focus. I always have lots of ideas.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10691487-what-s-the-goal-of-this-site

**Comment by koconnor719** [comment]
Thank you for your feedback. We are working on additional instructions and context for the "post an idea" feature!

**Comment by sjb912** [comment]
This comment just made me smile. May this kind contributor always have a lot of ideas. :-)

**Comment by koconnor719** [comment]
posted and closed
