### ISSUE TITLE
UserVoice Idea: Community based links

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#652]
As VA encourages 'community' involvement (bravo!) it may be very prudent to e.g. link SAMHSAs' updated community based services locator: https://findtreatment.samhsa.gov/ 
and link other well vetted & appropriate local community based resources partnered with VA

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10691964-community-based-links

**Comment by koconnor719** [comment]
response: 
Thank you for your feedback. We are developing in the open and delivering information and services iteratively. As we begin to work on healthcare information and services for vets.gov in 2016, we will include this information and feedback. 

vets.gov

**Comment by koconnor719** [comment]
posted and closed.
