### ISSUE TITLE
UserVoice Idea: myHealtheVet

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#653]
Provide secure link to myHealthyVet too

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10691823-myhealthevet

**Comment by koconnor719** [comment]
response:

Thank you for your feedback. We are developing in the open and delivering features and content iteratively. We plan to deliver healthcare information and features (such as myHealtheVet) in the coming months.

**Comment by koconnor719** [comment]
posted and closed
