### ISSUE TITLE
UserVoice Idea: Online Self-Making Appointment like airline seating chart online, monthly calendar show instead of seating chart

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#654]
After we are told from the doctor we need to come back in 3/6/12months.  We need self-making appointment online, like we reserve airline-seating when we buy airline ticket online.  After we make an appointment online VA send email/text confirmation and if that date is not available VA give us new date/time.  Also the main important is VA have to reply in 24 hours after we request that appointment date, not just we have to follow up and follow up. And this appointment online should be able make in advance as far as 12 months or at least 6 months.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10691817-online-self-making-appointment-like-airline-seatin

**Comment by koconnor719** [comment]
response:

Thank you for your feedback. We are developing in the open and delivering information and features iteratively. We plan to have Veteran focused features, including the ability to make an appointment online, available on vets.gov in 2016.

**Comment by MarinaMartin** [comment]
@koconnor719 Sounds good

**Comment by koconnor719** [comment]
posted and closed
