### ISSUE TITLE
On GI Bill "Instituions" page "Refine my search" for institution type doesn't display status

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/vets-website#655]
URL: `https://www.vets.gov/gi-bill-comparison-tool/institutions/search?utf8=%E2%9C%93&page=1&num_results=9&source=search&military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&institution_search=Chicago&commit=Search+Schools&page=1&num_results=9&page=1&num_results=9&page=1&num_results=9&page=1&num_results=9&schools=true&state=il&page=1&num_results=9`

I have selected the `School` `Institution` option, but it still looks like:

<img width="1241" alt="screen shot 2015-11-13 at 11 46 15 am" src="https://cloud.githubusercontent.com/assets/772/11151633/35747a78-89fc-11e5-97a7-f60cdd73c35a.png">

**Comment by alex** [comment]
(I'm expecting `School` to show up as selected)

**Comment by rickleegit** [comment]
@mphprogrammer, pretty sure that this is a product of the bug fix yesterday. Mind having a look? If this will be resolved by the search rewrite, please just note a realistic eta for the deployment of a tested search rewrite. 

Thanks!

**Comment by mphprogrammer** [comment]
Its a product of having the double ids - having both the responsive and regular filters.

**Comment by rickleegit** [comment]
Ok. Let's figure this out Monday. Will the rewrite help?

**Comment by mphprogrammer** [comment]
Yup - the rewrite will have no ids in the controls, and incorporate a select box for school features.

**Comment by rickleegit** [comment]
Perfect! Thanks!!

**Comment by emilyville** [comment]
@rickleegit can we close this out? I'm guessing so because it's way old.
