### ISSUE TITLE
"Find Employment" Link Broken on Institution Pages

### ISSUE THREAD

**Issue by gmorgana-va** [department-of-veterans-affairs/vets-website#656]
On individual institution pages (example below), the "Find Employment" link under additional resources directs to a non-existent page.

https://www.vets.gov/gi-bill-comparison-tool/institutions/profile?military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&institution_search=10007837&source=home&page=1&num_results=9&facility_code=10007837

Other similar links point to this site instead:
https://www.ebenefits.va.gov/ebenefits/jobs

**Comment by MarinaMartin** [comment]
@rickleegit Can you please fix this link on GI Bill?

**Comment by rickleegit** [comment]
Fixed in cleanup1120-rick. Will be pushed to staging in next merge for anticipated push to prod tonight.

**Comment by dannychapman** [comment]
@rickleegit is this all set? Just wondering if we can close it out.

**Comment by koconnor719** [comment]
can this be closed? @dannychapman @rickleegit

**Comment by rickleegit** [comment]
Fixed
