### ISSUE TITLE
UserVoice Idea: clairification of website intentions

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#657]
1. Will my HealtheVet access be available as it is on ebenefits?  
2. Can a section be highlighted for Veterans to access the letters needed for proof of service, but more important make it easier to access the Veterans Preference Letter for Civil Service Preference.
3. If this combines as a single website, will information be available so that veterans seeking information on claims assistance be more readily available.  There seems to be a problem when veterans take their DBQ's to PCP's not wanting to compete them though there is a memo directing that this should be done.  Given it is meant to serve as an internal information, it would/could be useful to many veterans to know that it exist.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10693017-clairification-of-website-intentions

**Comment by koconnor719** [comment]
response:

Thank you for your feedback. We are developing in the open and delivering iteratively, so we plan to deploy claims-related and healthcare information and features (such as myHealtheVet and eBenefits) starting in 2016. We will include your feedback in our healthcare design work.

**Comment by MarinaMartin** [comment]
@koconnor719 Sounds good!

**Comment by koconnor719** [comment]
posted and closed
