### ISSUE TITLE
UserVoice Idea: Error in Facility Locator

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#658]
I can't help but notice that the Facility Locator does not display VA Hospitals in several states, even when the city of the VA hospital in entered into the search

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10693143-error-in-facility-locator

**Comment by llimllib** [comment]
Difficult for me to say anything without example cities. Shall I respond asking for some example missing locations?

**Comment by koconnor719** [comment]
response: 

Thank you for your feedback. Can you provide us with some specific example cities and states?

**Comment by llimllib** [comment]
@koconnor719: thanks!

**Comment by koconnor719** [comment]
posted and closed

**Comment by MarinaMartin** [comment]
We should leave this open as we await a response.

**Comment by koconnor719** [comment]
no response as of 11/16

**Comment by koconnor719** [comment]
i think we should close this if we don't get a response by end of this week.

**Comment by MarinaMartin** [comment]
If we don't get a response we should do our own due diligence and see if we can figure out what's missing. If we have an intern hanging around this would be a good task!

**Comment by koconnor719** [comment]
assigned to VE resource

**Comment by koconnor719** [comment]
we have completed tests on approx. 30 cities; there is a data question (see issue 726) we are looking into.

**Comment by koconnor719** [comment]
reassigning this to the Facility Locator product team to test and validate that this is in fact working.

**Comment by koconnor719** [comment]
related to #726

**Comment by koconnor719** [comment]
closed and posted:

Thank you for your feedback. Our team has conducted testing on this issue, and we are already working to update and enhance the Facility Locator data using VA Site Tracking (VAST), which should fix the issue you identified! Because we are "developing in the open" we are launching new features and enhancements to vets.gov on an ongoing basis based on Veteran feedback. Thanks for your feedback.

vets.gov team
