### ISSUE TITLE
UserVoice Idea: MHV

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#660]
Adding a link to MHV on this site would be helpful in accessing accounts from this location.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10694148-mhv

**Comment by koconnor719** [comment]
response: 

Thank you for your feedback. We are developing in the open and delivering iteratively. We plan to deploy healthcare information and features starting in 2016.

**Comment by MarinaMartin** [comment]
@koconnor719 Your response sounds good!

**Comment by koconnor719** [comment]
posted and closed
