### ISSUE TITLE
UserVoice Idea: When entering a term or terms into the search bar, allow for predictive text technology to be deployed.

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#662]
Launch predictive text when entering search terms in the search bar

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10695177-when-entering-a-term-or-terms-into-the-search-bar

**Comment by MarinaMartin** [comment]
We actually have this now. Try typing "gi bill" into the search bar.

**Comment by koconnor719** [comment]
posted and closed
