### ISSUE TITLE
Technical discovery for design system

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#6637]
I wanted to start compiling questions we had:

1. How do we want to integrate it with vets-website?
2. How will integrating React components work?
3. Can we use tooling to autodocument existing site? And make documentation for previous releases also available for those who haven't upgraded yet?
3. Can we use tooling to autogenerate Sketch files to keep them automatically in sync?
5. How will we be able to accommodate RJSF?
 
- How can we maintain and improve accessibility?
- note on crossbrowser to be addressed

**Comment by jbalboni** [comment]
For 1, there are two initial paths, I think:

1. Make the design system separate from vets-website. To keep things in sync, I think this implies that our shared patterns and components need to be pulled out of vets-website and the design system either depends on that new common repo or lives in it. This is more work than the option below, I think, and entails significant changes to how FE development works.

2. Put the design system inside vets-website. If we were just building this for the vets team, this is what I would want to do. It avoids a bunch of wiring and configuration issues. You can also pull it out later, if necessary. But if we know we're going to change that later, why even start here?

**Comment by ncksllvn** [comment]
Relevant issue opened to Fractal about React support - https://github.com/frctl/fractal/issues/21

**Comment by cehsu** [comment]
I've moved the accessibility question, as I had intended that as a more general planning topic, rather than a question for tool selection specifically. But please feel free to reorganize if the previous location makes more sense.

**Comment by rtluu** [comment]
Moved this ticket to be tracked in the vets.gov-team repo #5609
