### ISSUE TITLE
[WIP] Define design system requirements for React components and compare with Fractal capabilities 

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#6655]
Reference: https://github.com/frctl/fractal/issues/21

1. Component code is visible in the design system and an example of it renders

**Comment by jbalboni** [comment]
So far:

- Rendering React components in Fractal works with the limitation that it is just outputting html. Any JS-based interactivity doesn't work.
- Rendering React components with JS-interactivity is partially working, and I think I can get it to fully work, but it's a little slow and messy.
- Fractal only supports one template system at a type, so I've had to write a proxy adapter to choose between React and njk

I've also found that, if I wanted to document a library of React components, Fractal is not very well suited. If I were doing that, I would have the following main requirements:

1. React renders and runs in the browser
2. There's a way to document all of the props available on components
3. You can change those props and see events generated in the guide

Fractal can do 1 with a lot of effort, but not 2 or 3.

The goal of a design system is different from documenting a UI component library for developers, so I don't want to derail that for the same of just FE developers. But it would be good to make sure devs and designers both understand what the end result will be and how we would use it.

**Comment by rtluu** [comment]
Moved this issue to be tracked in vets.gov-team repo #5610

**Comment by ncksllvn** [comment]
@jbalboni so it doesn't sound like Fractal is going to play very nicely with React, unless there was a full-out fork of Fractal that did a lot of stuff to plug it in. Do you think Fractal is still the way to go and we just tone down how much our design system will do (or figure out a different way), or consider a different solution?
