### ISSUE TITLE
UserVoice Idea: Overview of feedback

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#684]
Wish I could see what ideas other people have posted.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10722843-overview-of-feedback

**Comment by sjb912** [comment]
Excellent point. Since we're not running a blog that folks can contribute to, we should capture comments and reflect back the kind of feedback we're getting on a page on the site. (This would, of course, traditionally be how a blog would be used...)

**Comment by koconnor719** [comment]
can we make the "feedback forum" a link somewhere in the footer, maybe below "blog"? presently i think you can only see the feedback forum when you enter your own comment?

**Comment by koconnor719** [comment]
this is related to issue #609 (User voice - clearer call to action and feedback channel #609).

**Comment by emilyville** [comment]
So, if I understand this right - we want to help them get to this link, to see all feedback from everyone:

https://veterans.uservoice.com/forums/330333-vets-gov

I think that makes sense. But now that I entered some test feedback, in the widget this link is exactly what comes up after your feedback, and it says "See the forum", so uh... maybe we should close this issue and kindly send the link over to this commenter. It doesn't stay up for as long as I'd like, but maybe that's a setting in uservoice (couldn't find it on first look though).

I hate cramming things into the footer, but if we did feel this was something super important we could add this:
![screen shot 2015-11-18 at 6 21 45 pm](https://cloud.githubusercontent.com/assets/1307774/11260571/597a905a-8e21-11e5-913e-c6c577184596.png)

I vote we close this issue and if we get more comments such as this we can revisit!

**Comment by koconnor719** [comment]
posted response and closed.  

Thank you for your feedback. Users can view all comments by clicking on the feedback lightbulb at the bottom of the page and entering your feedback.  Once you enter your comment you can view all the feedback. We've logged your feedback, and if we get additional comments requesting this feature we will add it to our enhancement roadmap!

vets.gov team
