### ISSUE TITLE
UserVoice Idea: View VA medical co-pay online

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#704]
I would like to be able to view my VA medical co-pay account online. I use "pay.gov" to make payments. If I could see my balance and get email alerts on new changes, snail-mail bills could be eliminated there by saving a lot of trees.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10742862-view-va-medical-co-pay-online

**Comment by koconnor719** [comment]
proposed response:

Thank you for your feedback.This beta release of Vets.gov is just a beginning. We’ve launched it with deep content in the two benefit categories that Veterans have told us mean the most to them: disability and education. There are many more features to come! We’ll be adding new information and tools on an ongoing basis. But we wanted to get vets.gov in front of you now, as we build it, so you can tell us what’s working for you and what isn’t. Our team will add your feedback to our enhancement list for 2016. Thank you for your suggestion.

**Comment by koconnor719** [comment]
posted and closed.
