### ISSUE TITLE
Assets are not gzipped

### ISSUE THREAD

**Issue by dannychapman** [department-of-veterans-affairs/vets-website#705]

**Comment by dannychapman** [comment]
@llimllib is this all set?

**Comment by llimllib** [comment]
the locations json file is now gzipped, but nothing else is

**Comment by carlmjohnson** [comment]
Is there a CDN in front of the site? A check of the headers shows Nginx but nothing else. Putting a CDN in front will probably let us kill two birds (latency, gzip) with one stone.

**Comment by joduinn** [comment]
@carlmjohnson There is not currently a CDN in front of the vets.gov site. Static content is on s3, and dynamic/programatic content is in auto-scaling-groups behind an ELB behind nginx.

Note: CDN like CloudFront is not natively provided in AWS govCloud. I did find this doc ( http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/setting-up-cloudfront.html ) on how to use commercial CloudFront with govCloud, but it would need careful reading, as well as questions about ITAR resolved before we could go too far down this path. 

Not trying to be a downer - just adding the (little) info I have to the thread.

**Comment by ShawnArnwine** [comment]
ITAR: As long as we are only serving up static content (e.g. static (not sensitive pages), images, etc.) using CloudFront, then there is no harm here.  In a simplistic sense, we are more or less doing this by jumping from GovCloud over to E/W to serve up the website...so no worries.

Also when using CloudFront (or perhaps any CDN) we should consider hashing the object names as AWS caches quite a bit and it can take some time for it to refresh across the network.

**Comment by jbalboni** [comment]
We're gzipping everything now with https://github.com/department-of-veterans-affairs/devops/pull/452, so I'm closing this.
