### ISSUE TITLE
UserVoice Idea: Get to claims process outline from disability-benefits page

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#708]
I can't get to https://www.vets.gov/disability-benefits/get/ from https://www.vets.gov/disability-benefits/

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10745697-get-to-claims-process-outline-from-disability-bene

**Comment by koconnor719** [comment]
i think this comment is asking to have the "apply for benefits" on the landing page of Disability Benefits--which it is at the bottom.  

response: Thank you for your feedback. If we are understanding your comment correctly, you are wanting to be able to get to the "apply" page from the "Disability Benefits" landing page.  (Please clarify if this is not your comment.)  You can get to the apply page at the bottom of that Disability Benefits landing page.

**Comment by koconnor719** [comment]
posted and closed
