### ISSUE TITLE
Confusing/missing data on VA Medical center page

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/vets-website#7130]
URL: https://www.vets.gov/facilities/facility/vha_688

![screen shot 2018-01-20 at 2 22 40 am](https://user-images.githubusercontent.com/772/35181051-cf11e0e2-fd88-11e7-84f4-a8d0e5ab3045.png)

Specifically, the first bullet point under "Specialty care". There appears to either be a missing label, or the 17 days should be applied to the "Specialty care" bullet.

**Comment by ayaleloehr** [comment]
cc @NatalieEMoore

**Comment by NatalieEMoore** [comment]
moving to a different repo, thanks @alex

**Comment by alex** [comment]
A public repo, or an internal repo?

**Comment by NatalieEMoore** [comment]
Our internal vets.gov-team repo where there are a bunch of other tickets like this one for the facility locator.
