### ISSUE TITLE
Add branding language to playbook

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#714]
add the following text for branding in the playbook:

The Department of Veterans Affairs (VA) announced in January, 2015, that VA will transition into a single VA website. Vets.gov has been designated as the website that all VA content will transfer to. The purpose of creating a single website is to create a unified web experience for Veterans and their families. Individual branding of VA websites and programs are contradictory to the intentions of this unified effort. Web content and programs that are transferred into Vets.gov will adopt the Vets.gov branding model and replace previous branding.

**Comment by emilyville** [comment]
in PR #719

**Comment by emilyville** [comment]
@ss0ss is working on copy - then we will revisit, @koconnor719 !

**Comment by sjb912** [comment]
shaun -- hope I haven't stepped on your toes. Knocked this out for you --
what do you think?

The Department of Veterans Affairs (VA) announced in January, 2015, that
VA would transition its many websites to a single site -- Vets.gov -- with
the goal of creating a unified web experience for Veterans and their
families. The Vets.gov branding model will replace previously existing
branding of VA Web content and programs when they become part of Vets.gov.

**Comment by koconnor719** [comment]
martin is ok with this language fyi.

**Comment by ss0ss** [comment]
@koconnor719 @emilyville - @sjb912, couldn't have said it better myself!

**Comment by emilyville** [comment]
Closing, and yay!
