### ISSUE TITLE
People try to click on the yellow "How can we help?" box

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#722]
I think this is a good place for a delightful interaction that shows this is built by humans. I think this is also probably able to be scoped solely to the homepage, making it a superfun design task.

From uservoice ticket #625

**Comment by sjb912** [comment]
Love that idea, Emily. What if it were a Googlesque tip of the day -- something that VA offers that folks might not know about that might be helpful to know? Our content team could create a bunch of these and you all could spring load them to serve up randomly.

**Comment by emilyville** [comment]
I'm closing this because it's been consolidated into https://github.com/department-of-veterans-affairs/vets-website/issues/1617
