### ISSUE TITLE
Facility Locator Map needs legend for pin colors

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#723]
here are the color codes:
Red - Central Office
Blue - Benefits Office
Green - Intake Site
Purple - Cemetery
Orange - VISN (Veterans Integrated Service Networks) Office 
Yellow - Outpatient Clinics
Brown - Hospitals
Pink - Veteran Centers

What it looks like now:
![screen shot 2015-11-18 at 6 58 18 pm](https://cloud.githubusercontent.com/assets/1307774/11261116/5c961390-8e26-11e5-9d17-fea96d740203.png)

inspired by uservoice ticket #624

**Comment by koconnor719** [comment]
Can we add a link w/ the color legend to the main Facility Locator landing page? i think that was the user comment.

**Comment by emilyville** [comment]
I think this is old and can be closed, right @ayaleloehr / @rickleegit ?

**Comment by ayaleloehr** [comment]
Closed 1/7 via commit d733a67d13c9dec0ca2f2693e26053c3ed8989e5
