### ISSUE TITLE
UserVoice Idea: Missing Site - Source Locator Suggested

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#726]
You are probably already aware that you are missing medical centers, aka hospitals, in MN, SD, ND and maybe elsewhere. You can find the complete listing at VA Site Tracking (VAST) located on the VSSC. 

You can info pull from authorized blurb - 
The Department of Veterans Affairs (VA) provides services to Veterans at 1,588 locations. That number includes 1,218 healthcare facilities. VA also operates 300 Vet Centers and 70 Mobile Vet Centers, which provide readjustment counseling to Veterans and their families. Veterans can access:
•	Outpatient care at 1,207 locations;
•	Acute Inpatient (hospital) care at 144 locations;
•	Community Living Centers (CLCs) at 134 locations; and
•	Residential Rehabilitation at 114 locations.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10779216-missing-site-source-locator-suggested

**Comment by koconnor719** [comment]
checking with VHA content SMEs

**Comment by koconnor719** [comment]
Posted this response; waiting on VHA validation:

Thank you for your feedback; we are checking on this data.

**Comment by koconnor719** [comment]
after some testing, there seems to be an issue w/ FL missing sites. specifically with red sites (Central office): when you click on "all facilities" you can clearly see that  there are more than 6 red sites:

<img width="1440" alt="screen shot 2015-12-03 at 6 04 55 pm" src="https://cloud.githubusercontent.com/assets/13770771/11576972/793cbfd0-99e8-11e5-8ff0-021f97453535.png">

but when i filter on "central office" (the red sites) only 6 sites appear:

<img width="1440" alt="screen shot 2015-12-03 at 6 06 03 pm" src="https://cloud.githubusercontent.com/assets/13770771/11576991/93ec01f6-99e8-11e5-8bb3-f193d8ad9572.png">

**Comment by llimllib** [comment]
Sites that have a category that's not in the filter list get red markers, so those do not represent missing facilities, just sites that have types I don't know what to do with

**Comment by llimllib** [comment]
> The Department of Veterans Affairs (VA) provides services to Veterans at 1,588 locations. 

We have 1,716 facilities listed in the facilities locator, so there's not some big bolus we're missing.

**Comment by llimllib** [comment]
For example, I do not believe we are missing any facilities in ND:

![find_locations_-_locations_and_facility_locator__vets_gov_and_ivy_-_import_your_playlists_into_spotify](https://cloud.githubusercontent.com/assets/7150/11593017/f4bcdaf0-9a6f-11e5-958b-7641f68c36ed.png)

**Comment by koconnor719** [comment]
Assigning this to the Facility Locator product team (Rick Lee and Eric Schles) to test this and provide a recommendation to our team for a legend of colors on the facility locator in the near term--and provide users a legend (based on user feedback) before we make any technical changes. trying to avoid rework--and work enhancements through the VA product team--and business owner.

**Comment by koconnor719** [comment]
Alex, i think you are working this?  can you let me know status when you have a minute--and is there potentially a quick fix we can do, so i can post an update to the web comments on the site since this is an older comment.

**Comment by ayaleloehr** [comment]
@koconnor719 We pushed some fixes to the facility locator this week.  The data source we use currently is: http://www.va.gov/webservices/fandl/documentation/fandl.cfm

As we write the new facility locator over the next couple months, we plan use the VAST dataset, as this user suggests.

**Comment by koconnor719** [comment]
closed and posted this issue and #658 :

Thank you for your feedback. Our team has conducted testing on this issue, and we are already working to update and enhance the Facility Locator data using VA Site Tracking (VAST)! Because we are "developing in the open" we are launching new features and enhancements to vets.gov on an ongoing basis based on Veteran feedback. Thanks for your feedback.

vets.gov team
