### ISSUE TITLE
Post-9/11 GI Bill OJT & Apprenticeship

### ISSUE THREAD

**Issue by jmcneal65** [department-of-veterans-affairs/vets-website#7342]
Education Service Leadership want to update the GI Bill Comparison Tool (CT) that will contain OJT/APP data.   EDU Business Analytics has the OJT/APP data and can provide.  How long can EDU have this request executed?

Thanks,
John

**Comment by saintsoup52** [comment]
Ideally this new data file would added as one of the inputs to the GI Bill CT Data Service that would be ultimately rolled into the data that runs the tool.

In the short term I will work with EDU on how to "hack" this process until the data service can be updated.
