### ISSUE TITLE
Missing vetnav-menu error on Playbook pages

### ISSUE THREAD

**Issue by chriseldredge-usds** [department-of-veterans-affairs/vets-website#7458]
[common/index.js](/department-of-veterans-affairs/vets-website/blob/master/src/js/common/index.js#L9) assumes all pages will have a `#vetnav-menu` element, but no such element is present on playbook views (e.g. https://www.vets.gov/playbook/). This results in an unhandled javascript error that prevents additional javascript from executing.

**Comment by ncksllvn** [comment]
Thanks @chriseldredge-usds! The Playbook is in need of some revisiting now that we've launched as VA.gov and there are still a couple console warnings on Dev, but now that we've migrated to a React-powered top navigation, the error defined in this ticket is no longer present.
