### ISSUE TITLE
Validate evidence type and each evidence type page

### ISSUE THREAD

**Issue by cehsu** [department-of-veterans-affairs/vets-website#7535]
In discussing the evidence summary page's depends logic, @goldenmeanie indicated that evidence should always be present. The evidence summary page should always be displayed for each disability increase, as evidence is required, with a minimum of 1 item provided for each evidence type selected.
This work includes ~providing validation logic for the evidence type page~, and for each of the document upload and record request pages, as well as displaying all evidence (treatment center names, and/or uploaded document information) on the evidence summary page.

### Acceptance Criteria:
- [ ] uploaded docs are listed in the evidence summary page
- [ ] if treatment centers have been identified where records can be retrieved, list those treatment centers in evidence summary
- [ ] evidence is required on its respective page, if selected on the evidence type page

**Comment by markgreenburg** [comment]
I think we can simplify this by just making sure that each step in the evidence process is `required`, so that it's not possible to continue past an evidence page without actually uploading said evidence.
