### ISSUE TITLE
Add "Feedback Forum" link 

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#765]
in order to increase the user feedback we are getting, can we add a link to the feedback forum so users can access the feedback without having to actually enter a comment first?  we are only getting 1-2 user comments every few days; of ~35 user comments we've had 2 user requests for this.  i don't think users are easily finding the feedback mechanism.

**Comment by emilyville** [comment]
Good idea. I propose this (I am happy to add it). 
  
![screen shot 2015-11-18 at 6 21 45 pm](https://cloud.githubusercontent.com/assets/1307774/11521050/a5cf21fa-985d-11e5-89f8-77d0ffa0b33e.png)

Thoughts @dannychapman ?

**Comment by koconnor719** [comment]
love it!  should we have the word "feedback" in there instead of public?..."see the feedback forum".  am thinking public is kind of implied?

**Comment by dannychapman** [comment]
Maybe “Join our feedback forum”


Danny Chapman

------------------------------------------------
Owner / Designer
www.ducstudio.com

**Comment by koconnor719** [comment]
Perfect!!

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by emilyville** [comment]
I think saying "join" implies membership status - kind of like "sign
up".... Maybe it should just say "feedback forum" or "vets.gov feedback
forum"?

**Comment by dannychapman** [comment]
Great point. 

Feedback forum works for me.


Danny Chapman

------------------------------------------------
Owner / Designer
www.ducstudio.com

**Comment by koconnor719** [comment]
more perfect "feedback forum"  :)

**Comment by emilyville** [comment]
I like Susan's suggestion of "Read Comments and add your own." instead of "Feedback Forum".

Since the earlier change is ready to go out, simply repopening this issue and will readress before next deploy.

**Comment by sjb912** [comment]
And -- sorry to have sent this with an improper cap -- no capital C on
comments. Thanks!

Read comments and add your own.

**Comment by koconnor719** [comment]
@emilyville can this be closed now? we've got other issues to test feedback forum for placement and language.
