### ISSUE TITLE
Yellow ribbon unsorted list stye issue

### ISSUE THREAD

**Issue by ss0ss** [department-of-veterans-affairs/vets-website#795]
https://www.vets.gov/education/gi-bill/yellow-ribbon/

Unsorted bullet li font size is smaller than p text.

@dannychapman not going to tear through the css, escalating to you.

**Comment by dannychapman** [comment]
@ss0ss I think this is fixed yes?

**Comment by ss0ss** [comment]
@dannychapman Yes.

**Comment by bethpotts** [comment]
Sorry, I thought the issue was still there, but I was on the live site rather than staging. Looks good.
