### ISSUE TITLE
UserVoice Idea: White text on blue?

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#798]
It's a sleek look, but I'm not crazy about the white text on blue.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10849986-white-text-on-blue

**Comment by koconnor719** [comment]
proposed response for approval:

Thank you for your feedback. The vets.gov design aspires to be honest, transparent, respectful, and accessible to all visitors. Everything we build for the vets.gov platform is created with these basic principles in mind, including the selection of our color palette. We tested colors with Veterans and selected those colors based on that data.  

vets.gov team

**Comment by emilyville** [comment]
:+1: on that response, @koconnor719 !

Assigning back to you for you to close once the response is sent.

**Comment by koconnor719** [comment]
posted and closed
