### ISSUE TITLE
UserVoice Idea: Automatic Travel Pay Algorithm

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#813]
The VA knows our appointment dates and locations. VA even sends out mail and phone reminders. Kiosks confirm appointment check-ins and appointments are viewable by the patient in MyHealthEvet.  Take it a step further and allow patients to simply affirm attendance online and have an algorithm calculate their allowable travel payment and issue a check based on electronic signature that the travel was performed!

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10893597-automatic-travel-pay-algorithm

**Comment by koconnor719** [comment]
closed and posted response:

Thank you for your feedback. This beta release of Vets.gov is just a beginning. We’ve launched it with deep content in the two benefit categories that Veterans have told us mean the most to them: disability and education. There are many more to come--including Healthcare and MyHealtheVet! We’ll be adding new information and tools on an ongoing basis. But we wanted to get vets.gov in front of you now, as we build it, so you can tell us what’s working for you and what isn’t. Our team will add your feedback on MyHealtheVet as we develop the healthcare section of vets.gov in 2016.  Thank you for your suggestion.
vets.gov team
