### ISSUE TITLE
GIBILLCT Not Showing Some Approved Schools

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#8182]
Schools that have alpha-numeric facility codes are not showing up in the search for approved schools.

For example the following schools do not appear.

**facility_code | institution**
1007A105 | SAN DIEGO COUNTY SHERIFFS DEPARTMENT
1008A105 | LIVERMORE POLICE DEPARTMENT
10A00101 | ALABAMA DEPARTMENT OF PUBLIC SAFETY-BIRMINGHAM POST
10A00110 | ESCAMBIA COUNTY SHERIFF'S OFFICE
10A00201 | ALABAMA DEPARTMENT OF PUBLIC SAFETY-HAMILTON POST
10A00210 | CAPE CORAL FIRE DEPARTMENT
10A00301 | ALABAMA DEPARTMENT OF PUBLIC SAFETY-HUNTSVILLE POST
10A00310 | SEBRING POLICE DEPARTMENT
10A00311 | VALDOSTA POLICE DEPARTMENT
10A00401 | ALABAMA DEPARTMENT OF PUBLIC SAFETY, ALEX CITY FIELD OFFICE
10A00410 | FEDERAL CORRECTIONAL INSTITUTION BOP - MIAMI
10A00411 | FORSYTH COUNTY SHERIFF'S OFFICE
10A00501 | ALABAMA DEPARTMENT OF PUBLIC SAFETY-MOBILE POST
10A00510 | MELBOURNE POLICE DEPARTMENT
10A00601 | ALABAMA DEPARTMENT OF PUBLIC SAFETY-EVERGREEN POST
10A00610 | SPESSARD HOLLAND GOLF COURSE BREVARD COUNTY
10A00701 | ALABAMA DEPARTMENT OF PUBLIC SAFETY-DECATUR POST

**Comment by saintsoup52** [comment]
Tagging @briangryth @jkassemi @saneshark

**Comment by jkassemi** [comment]
@briangryth I'm having trouble finding the associated vets.gov-team ticket for this issue. If you have one, can you link? 

@saintsoup52 I'm relatively sure we explicitly addressed this, and I'm no longer able to replicate the problem, so closing. Please reopen or reach out to @briangryth if problems persist.
