### ISSUE TITLE
® Font/Script Issues

### ISSUE THREAD

**Issue by ss0ss** [department-of-veterans-affairs/vets-website#831]
VBA has requested that all ® be normal script and not superscript across all GIBILL®

ie. they like the one on the right, not the left:

![image](https://cloud.githubusercontent.com/assets/12176114/11545335/af57c1d4-98fb-11e5-8994-f05d7c211a9c.png)

**Comment by koconnor719** [comment]
i think we just say no to this.  as long as the one on the left isn't wrong.

**Comment by dannychapman** [comment]
This has been tackled by a subsequent PR. Closing.
