### ISSUE TITLE
Playbook: Need consistent usage of Vets.gov vs. vets.gov

### ISSUE THREAD

**Issue by ShawnArnwine** [department-of-veterans-affairs/vets-website#837]
https://www.vets.gov/playbook/

Within the boxes (e.g. Human Centered Design, Platform, etc), in some places we use "Vets.gov" and others we use "vets.gov"

Should all be Vets.gov (is my understanding).

**Comment by sjb912** [comment]
Hey, Shawn -- I appreciate your eagle eye. Actually, it's vets.gov in text. The only place the v is capped is in the logo and at the beginning of a sentence. Please lob editorial style questions like this to me (susanjanebenson.va@gmail.com) or Beth Potts,  vets.gov's copy chief beth@stortechnologies.com
