### ISSUE TITLE
Facility Locator Location defaults and driving directions are random

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#845]
the default facility locator page opens for all users (i think) to NE; should it open to a location based on where a user is (assuming his/her location service is enabled):

<img width="1440" alt="screen shot 2015-12-03 at 6 08 09 pm" src="https://cloud.githubusercontent.com/assets/13770771/11577035/dd413e48-99e8-11e5-8016-4f17b0da348b.png">

also, what should the default "start" be for driving directions; it seems random; same comment as above, should the start default from your current location (assuming your location service is enabled).

<img width="1440" alt="screen shot 2015-12-03 at 6 09 14 pm" src="https://cloud.githubusercontent.com/assets/13770771/11577071/0a3378e4-99e9-11e5-8da8-d6425ca3be1f.png">

**Comment by llimllib** [comment]
> the default facility locator page opens for all users (i think) to NE

the geographic center of the US is in Lebanon, Kansas; the page loads centered on the center of the US

>  it open to a location based on where a user is (assuming his/her location service is enabled):

it does. You have location service disabled, and you clicked on the first 'driving directions'. In that case, the map routes the user from the current location (the geographic center of the US) to the selected site

**Comment by llimllib** [comment]
I think that this issue is really about the behavior of the map when the user loads it with location service disabled or unavailable. I've talked a bit about this with @EricSchles; when the map loads it should:

1. Not display all pins
2. Not display any sites

Then, once the user searches for a location *or* zooms in far enough, the map should begin displaying sites and pins.

Does that seem reasonable?

**Comment by llimllib** [comment]
I think this should probably become a new issue with the above^^^ ?

**Comment by koconnor719** [comment]
yes Bill. sounds good. what do you want me to do w/ this issue?  close it and open a new one w/ your description above?
