### ISSUE TITLE
Create list for React Apps that have Left Rail Navigation.

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/vets-website#8452]
We need a list of apps that include the Left Rail Nav. @mnorthuis mentioned that some need them and some don't. Here is the list of React Apps we have in our website. Once this is done we can implement them on the pages you need them on.

- va-gov/pages/burials-memorials/pre-need-eligibility/apply-for-pre-need-form-40-10007.md
- va-gov/pages/burials-memorials/veterans-burial-allowance/apply-for-burial-allowance-form-21p-530.md
- va-gov/pages/dashboard/index.md
- va-gov/pages/disability/file-for-increase-form-21-526ez.md
- va-gov/pages/discharge-upgrade-instructions/index.md
- va-gov/pages/download-va-letters/letters.md
- va-gov/pages/education/apply-for-gi-bill-form-1990.md
- va-gov/pages/education/change-gi-bill-benefits/dependent-request-change-form-22-5495.md
- va-gov/pages/education/change-gi-bill-benefits/request-change-form-22-1995.md
- va-gov/pages/education/check-post-9-11-gi-bill-benefit-status.md
- va-gov/pages/education/complaint-tool/form.md
- va-gov/pages/education/gi-bill-school-comparison-tool/index.md
- va-gov/pages/education/information-sharing-opt-out/opt-out-form-0993.md
- va-gov/pages/education/other-va-education-benefits/national-call-to-service-program/apply-for-benefits-under-ncs-form-1990n.md
- va-gov/pages/education/submit-school-feedback.md
- va-gov/pages/education/survivor-dependent-benefits/apply-for-dependent-benefits-form-22-5490.md
- va-gov/pages/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e.md
- va-gov/pages/employment/vocational-rehab-and-employment/application/chapter31.md
- va-gov/pages/employment/vocational-rehab-and-employment/application/chapter36.md
- va-gov/pages/facilities/index.md
- va-gov/pages/gi-bill-comparison-tool/index.md
- va-gov/pages/health-beta/index.md
- va-gov/pages/health-care/apply-for-health-care-form-10-10ez.md
- va-gov/pages/health-care/health-records/index.md
- va-gov/pages/health-care/medical-information-terms-conditions.md
- va-gov/pages/id-card-beta/index.md
- va-gov/pages/pension/application/527EZ.md
- va-gov/pages/profile/index.md
- va-gov/pages/track-claims/index.md
- va-gov/pages/verify.md
- va-gov/pages/veteran-id-card/apply.md
- va-gov/pages/veteran-id-card/index.md
- va-gov/pages/veteran-representative/index.md

**Comment by mnorthuis** [comment]
@accbjt I think this issue is created in the wrong repository.  Can you move to vets.gov-team?

**Comment by accbjt** [comment]
Transffered this ticket to vets-gov-team repo.

**Comment by donnabsaunders** [comment]
The 22-5495 form will soon be sunsetted
