### ISSUE TITLE
legal requirement - footer link inspector general

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#871]
vets.gov is legally required to have a footer link to "Inspector General" (see VA.gov homepage footer) on vets.gov.  pls. add this link to the following page:  http://www.va.gov/oig/

**Comment by koconnor719** [comment]
team is currently in process of adding this link in the next week or s. clarification on comment above: presently we are not legally required to have this link on vets.gov--but in the future when vets.gov is the homepage for Veterans in later 2016 this will be required.  therefore we are adding the link now, in advance of that to ensure we are in full compliance with this requirement.

**Comment by emilyville** [comment]
Here is my best hope at where / how this could go. It occurs to me - do people visiting our site know/care about the va oig? 

Any ideas on how we can plain language this link @dannychapman @sjb912 beyond "inspector general"?

![screen shot 2015-12-16 at 12 53 40 pm](https://cloud.githubusercontent.com/assets/1307774/11853676/31cb9c64-a3f4-11e5-941b-a7f6fcec7b34.png)

It also crossed my mind we could sneak it in to the white section above the footer - where we have other legal-type content about plain language.

**Comment by koconnor719** [comment]
I like it. But defer to you and danny.

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by dannychapman** [comment]
@emilyville That placement makes sense to me. I think that's probably what we should ship for now, then adjust later if we can.

**Comment by Drakenhart** [comment]
I am working on a project that has similar strict requirements. 

There is a document that lists the required links in the footer. If you look va.gov you will see them. Any sites that are under the umbrella of the VA, need to have a link back to the va.

A good example of this can be found on eBenefits.gov and explore.va.gov as well. I hope this helps?

**Comment by koconnor719** [comment]
there is a legal requirement for this link in footer. Veterans need to be able to contact the OIG hotline to file a complaint from our homepage; we cannot use any different plain language the link in footer--it needs to be "Inspector General" per the legal requirement--the same way it is on VA.gov. can we pls. post this in next production release?

**Comment by koconnor719** [comment]
@emilyville @dannychapman team, just checking on status of adding OIG link in footer so i can close this:)

**Comment by dannychapman** [comment]
@koconnor719 PR posted, @emilyville will review!
