### ISSUE TITLE
Deliver IE 8 and below a minimal, single column layout style sheet

### ISSUE THREAD

**Issue by dannychapman** [department-of-veterans-affairs/vets-website#881]
Consider keeping basic design elements consistent, but without the grid and other more complex UI elements.

**Comment by emilyville** [comment]
@webinista - do you think we could incorporate this into the future of roadrunner?

**Comment by webinista** [comment]
@emilyville Sure. We should probably think about what that will look like though.

**Comment by koconnor719** [comment]
IE9 is standard; message on IE8; assign to vanguard per stacey.

**Comment by jcmeloni** [comment]
Closing; there is a message when viewed in IE8: "Your browser is out of date. To use this website, please update your browser or use a different device. "
