### ISSUE TITLE
Playbook Editorial Reference Guide

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#893]
Add content to Playbook for editorial reference for language (e.g., Servicemembers) and style (e.g. "V" for Veterans)

**Comment by koconnor719** [comment]
assigning mariana:)

**Comment by emilyville** [comment]
this will be covered in playbook 2.0/roadrunner content! @maryannbrody or @mariana-almeida - feel free to close if it's already covered there, or wait until that is the case.

**Comment by mariana-almeida** [comment]
These two items are in the style guide we've been using. When it's time to put it on the Playbook site, we're ready. I'll close this one since this work timing is TBD.

**Comment by mariana-almeida** [comment]
Closing, per rationale above.
