### ISSUE TITLE
UserVoice Idea: In the crisis line area, link to the text and chat options

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#903]
Right now, in the footer the Veterans Crisis Line is just a phone number. This resource has a website (https://www.veteranscrisisline.net/) that also provides text and online chat options, which some people may prefer. It could be helpful to link to this website from that spot.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11066301-in-the-crisis-line-area-link-to-the-text-and-chat

**Comment by koconnor719** [comment]
we should make "Veterans Crisis Line" clickable and go to the website (as it does on VA.gov):  https://www.veteranscrisisline.net.

posted response: 

Thank you for your feedback.  Great idea--we are making this change! 

vets.gov team

**Comment by koconnor719** [comment]
team, any update on when this link can be added to the crisis line text at the bottom of page?  @emilyville @dannychapman

**Comment by dannychapman** [comment]
I've put together a pull request that addresses this. My approach is to have the phone link be clickable for mobile devices, and the website link for everyone else.

**Comment by koconnor719** [comment]
perfect!  thx

**Comment by koconnor719** [comment]
posted and closed:

Thank you for your feedback. Great idea--we made your change!

vets.gov team
