### ISSUE TITLE
Readme / Setup Instructions missing vagov-content clone

### ISSUE THREAD

**Issue by ATeal** [department-of-veterans-affairs/vets-website#9111]
Recently the default local development commands (`npm run watch` and `npm run build`) have been updated to include `vagov-content` yet cloning that repo as a sibling to this project isn't in the readme.

Wanted to get thoughts / opinions on adding that to the readme before I went down that route.

**Comment by patrickvinograd** [comment]
It's worth adding.

**Comment by ncksllvn** [comment]
Excellent point - added here, https://github.com/department-of-veterans-affairs/vets-website/pull/9175!
