### ISSUE TITLE
Templates made into downloadable files.

### ISSUE THREAD

**Issue by Drakenhart** [department-of-veterans-affairs/vets-website#920]
**Issue**
Templates on the site's playbook are not download able. It is not easy to locate such files.

**suggestion**
A selection of graphic files (Photoshop, svg, illustrator, sketch, etc) that duplicate the suggested templates would improve speed and efficiency of redesign work some teams may wish to consider in their current projects.

For ease of use for those who are currently looking into having their projects absorbed by vets.gov, having such files and having them linked on the playbook would improve designer/developer find-ability.

**Comment by goldenmeanie** [comment]
We've been working on a more comprehensive sketch based vetsdotgov toolkit that would help with this.

**Comment by Drakenhart** [comment]
What of those who do not use Sketch? Or those who do not use Macs? Not all designers use Macs.

There are those out there that are either not familiar with Sketch, or are forced, by security reasons, to use other programs like Adobe's Suite, only have access to Windows (since Sketch is a MAC product), or have to use other open source programs like, Inkscape. 

Will Sketch be the first with other sets coming later?

**Comment by goldenmeanie** [comment]
We're starting by reusing tools from our own workflow. But we should definitely pay attention to what would be most useful to others. Thanks for the feedback!

**Comment by Drakenhart** [comment]
I think that would work well. It's not quite as editable as say a Photoshop or Illustrator file with layers, but it would help quite a bit. :) It might even help keep upkeep to a minimum as well. :)

Thanks!

**Comment by koconnor719** [comment]
need to have process to engage on public comments.

**Comment by koconnor719** [comment]
Thank you for your feedback!
