### ISSUE TITLE
consistency with quotation marks and apostrophes

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#922]
Can we get all the quotation marks and apostrophes to be curly rather than straight? Right now we have a mix of both.

**Comment by dannychapman** [comment]
@bethpotts This should happen automatically with markdown. Can you add a list of specific examples that need fixing here? Feel free to assign this issue to me at that point too.

**Comment by bethpotts** [comment]
I think there would be many dozens of examples, but I could comb the site if that's what's needed. Here are two pages that feature both on the same page:

Contaminated C-123 page (the third blue box has a straight apostrophe in the word "children's" and the fourth blue box has a curly apostrophe in the word "children's"):
https://staging.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/c-123/

VEAP page (orange stripe has a straight apostrophe and the header immediately under that has a curly one):
https://staging.vets.gov/education/legacy-programs/veap/
