### ISSUE TITLE
File names don't always translate well into breadcrumbs

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#923]
1) Breadcrumbs will not always match the actual click-through path that was taken to land where you are. For instance, because the file naming for BDD is this: 
https://staging.vets.gov/disability-benefits/filing/active-duty/bdd/index.html
... the breadcrumbs are 
Disability Benefits > Filing > Active Duty > Benefits Delivery at Discharge (BDD) 
... but we don't have a page called Filling, nor one called Active Duty.
The actual path to get to BDD is 
Disability Benefits > Claims Process > Claim Types > Predischarge > Benefits Delivery at Discharge (BDD) 

2) Since I'm using BDD as an example, here's the second issue with the switch to using file names to populate breadcrumbs: apostrophes, quotation marks, hyphens, and capitalization will be wrong in some cases. Every word is capitalized for the breadcrumbs (even ones that shouldn't be, like "the"); we don't use possessive apostrophes in file names, so they will be absent from the breadcrumbs (Survivors' and Dependents' Assistance); in the above example, the file name has "pre-discharge," which will become "Pre-discharge" for the breadcrumbs. But there shouldn't be a hyphen in this word, so the breadcrumbs will not be consistent with the way that word is styled on our site.
https://staging.vets.gov/disability-benefits/claims-process/claim-types/pre-discharge/.

**Comment by dannychapman** [comment]
Fixed with new IA updates. Closing.
