### ISSUE TITLE
Coming soon message

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#925]
On this page: How do I file for a disability benefit?
https://staging.vets.gov/disability-benefits/get/filing/

Danny--was this page created to address the breadcrumb issue? Is Ric aware that this page needs language added?

**Comment by dannychapman** [comment]
This page was created to match what we have in the breadcrumb, URL structure. We probably should add content to fit this spot, or rework the IA. Thoughts @rcarthur ?

**Comment by dannychapman** [comment]
This has been fixed with the new IA updates. Closing.
