### ISSUE TITLE
UserVoice Idea: Expand Post 9/11 GI Bill for Medical Careers

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#931]
Encourage veterans to pursue medical career options by expanding the length of time the post 9/11 GI Bill covers for those fields.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11175309-expand-post-9-11-gi-bill-for-medical-careers

**Comment by koconnor719** [comment]
closed and posted response:

Thank you for your feedback. This feedback forum is only for vets.gov website comments and questions. All questions regarding GI Bill benefits should be directed to the “Ask a Question” section the VA.gov website at https://gibill.custhelp.com/app/utils/login_form/redirect/ask .  

vets.gov team
