### ISSUE TITLE
UserVoice Idea: Having the ebenefits site default to the "in progress"vets.gov site is not good customer service.

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#932]
Currently I am trying to simply log into ebenefits via www.va.gov and I am automatically getting redirected to www.vets.gov.  Once there the interface is different and I am now wasting time trying to get to the ebenefits login page.  Ebenefits is a bad enough application but having users blindly redirected to a "in progress" vets.gov site is poor customer service.  It seems like the rush to implement vets.gov is potentially making it harder to apply for benefits, check statuses, etc.  Please don’t screw up MyHealtheVet by having it default to Vets.gov.
If you are going to change the path to an existing application that Veterans use leave the old path in place so people can quickly do what they need to do without having to navigate a completed new site (in this case a work in progress site).  Do better outreach and education and get actual Veterans/regular users of these systems to be part of any UAT.  
Give us (Veterans) a voice and let us be part of the process, it won’t help your project’s timeline but it will make a better product in the end.  A product that is delivered on time and budget that doesn’t get used or make the customer’s experience  better is only a success for the PM not the end user.  
-	from a disabled Veteran, VA Employee with experience in VHA, VBA, OI&T, etc.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11176905-having-the-ebenefits-site-default-to-the-in-progr

**Comment by ss0ss** [comment]
This is interesting, would love to know the exactly where the this "redirect" comes from exactly...

Also - is there a way for non Vets.gov, VA employees, can participate beyond Uservoice?

**Comment by MarinaMartin** [comment]
The Veterans Employment Center link on eBenefits goes directly to Vets.gov as of yesterday - but you wouldn't go there to log in to eBenefits or check a claim, so I'm a little confused.

I also just checked Google Analytics and 100% of the traffic from VA.gov is coming from GI Bill pages. All of the referrers from eBenefits are clicking Employment Center.

We should respond to this user with an invite to one of our UAT sessions!

**Comment by koconnor719** [comment]
Posted response:

Thank you for your feedback.  This should not happen. We certainly don't want to redirect Veterans trying to login to eBenefits to vets.gov.  When our team tested the eBenefits login link, it still goes to the existing page: https://myaccess.dmdc.osd.mil/identitymanagement/authenticate.do;jsessionid=DnHNNTmStDWxa98l2xQTc0gwMfexTyvTA3xrjF97ePiQbTlSxbUC!-1899913949?execution=e1s1 . 

If you can send us a little more information (like the page or url from which you are being redirected to vets.gov), then our team can do more testing to make sure we fix any problem.

We welcome your participation in our user testing activities for vets.gov!  We talk to Veterans every week to get their feedback on the site and do usability testing.  Please contact us at vavetsgov-feedback@va.gov to participate.  We are designing vets.gov based on Veteran feedback like yours, so thank you again for taking the time to give us your ideas.

vets.gov team

**Comment by maryannbrody** [comment]
Thanks, @koconnor719 -- appreciate you responding and inviting him to participate in usability testing. :)

**Comment by koconnor719** [comment]
closing this issue since we cannot replicate the issue and I don't believe this is an error; invited this user to participate in user testing.
