### ISSUE TITLE
When breadcrumbs don't act like breadcrumbs to show you how you got to a page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#935]
This is sort of a broad question about the purpose of breadcrumbs. There are at least a handful of pages that don't have a single linear path. Accredited Representatives (AR) and the disability get (Apply) pages are both examples of this. We link to both from many different pages. So breadcrumbs are sort of irrelevant for these two pages, and just show what our filing system is. I don't think they help, and they may even confuse.

**Comment by MarinaMartin** [comment]
We have this challenge on the Employer Commitments page in the Employment Center too... all other pages are either for Job Seekers or Employers, but that page is for both.

**Comment by Drakenhart** [comment]
There is a type of breadcrumb navigation style called "path". The idea is that the site tracks the user's path through the site and displays their location based on how they got there.

This may be something to consider.

Other types are:
* Location (ai / file structure)
* Attribute (ecommerce like)

**Comment by emilyville** [comment]
thinking we can close this @webinista ?

**Comment by webinista** [comment]
I think so. This feels like an IA question that's being addressed by other issues. (And if it isn't being addressed, we can reopen it.)
