### ISSUE TITLE
All-claims addressUI usage doesn’t account for international zip codes

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/vets-website#9367]
Several pages in https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/disability-benefits/all-claims/pages are using https://github.com/department-of-veterans-affairs/vets-website/blob/18b9d24fcc44815f4decf6501ea1eb74841ad3c1/src/platform/forms/definitions/address.js#L131 but with a field called `zipCode` instead of `postalCode`.  This will cause issues with validating international zip codes, however this is done because the of how `address` is defined at https://github.com/department-of-veterans-affairs/vets-json-schema/blob/2b77b41de3f0bcb998b73281f8dd8dc67ff0dd99/dist/21-526EZ-ALLCLAIMS-schema.json#L68

**Comment by jbalboni** [comment]
FYI @cvalarida
