### ISSUE TITLE
UserVoice Idea: Linked in profile not populating resume?

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#940]
When I am asked to use my linkedin profile., I sign into linked in and choose to populate the resume and it doesn't work? Please help. 

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11218422-linked-in-profile-not-populating-resume

**Comment by koconnor719** [comment]
alex, can you pls. test this and confirm it's not a but?  not sure if this is a bug or user error.  (if user error i can respond with directions.)

**Comment by MarinaMartin** [comment]
I tested this and it works for me - but perhaps this user has something unique about their profile that is causing it to not import. Can you respond and ask them what happened specifically (did they get an error, or did they get returned to VEC with a blank page?) and then have them email us with their name/email so we can troubleshoot?

**Comment by koconnor719** [comment]
posted response:

Thank you for your feedback. Sorry you are having trouble using this feature. Our team has tested this functionality, and it seems to be working as it should. Can you contact us with some more details so we can get this issue fixed for you?  Please email our team at vavetsgov-team@va.gov and tell us what's happening when you try to do this--does it give you an error message, or a blank page?  We want to get this working for you right away!

vets.gov team

**Comment by koconnor719** [comment]
closing this issue; no response response received from user and email contact posted for further info.
