### ISSUE TITLE
Consume the "outages" property of the user data

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/vets-website#9407]
The `/v0/user` route, which is used by the FE to create the user/profile object in app state, now provides an `outages` property, which is used to indicate to the FE when a service is unexpectedly unavailable. We should begin consuming this somewhere in the FE.

One idea for this is to plug the `outages` data into DowntimeNotifications by mapping the `outages` data structures to match that of `maintenace_window` and using it to populate the DowntimeNotification Redux store.

API route - https://github.com/department-of-veterans-affairs/vets-api/pull/2738

**Comment by jbalboni** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #23](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23) via [**ZenHub**](https://www.zenhub.com/)
