### ISSUE TITLE
Suggested Templates and their representitive Pages do not match.

### ISSUE THREAD

**Issue by Drakenhart** [department-of-veterans-affairs/vets-website#943]
I crafted a quick and dirty set of balsamiq files based on your playbook's suggested templates. As I was going between the pages that were examples, i realized they didn't quite match. I'm still curious what the small gray button-like box is in the template.

I realize these may just be basic guidelines. 

Perhaps multiple links to other similar-sample pages on the site would be helpful?

**Comment by webinista** [comment]
Follow #2089 and related tasks.
