### ISSUE TITLE
Decide on style guide for markdown content

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#952]
Should HTML tags in markdown content be indented?  If not, it's really _really_ hard to visually match unbalanced tags.

The stuff I'm setting up for #949 will catch things at the automated tool level, but it's still hard to read....

See

https://raw.githubusercontent.com/department-of-veterans-affairs/vets-website/da93d1f25f3c4419415804280a1bc22601d4c3e5/_education/process.md

for an example.  There's an unbalanced `</li>` on line 99. I give nearly 0 chance of catching this on reading the code...

**Comment by plusjeff** [comment]
@webinista Has done some work on this I believe. Assigning to Vanguard team.

**Comment by webinista** [comment]
See #2416. Needs more content, and possibly some updates but the beginnings are there.

**Comment by plusjeff** [comment]
Closed the PR since it was from a super old branch #2416 . However, left a comment for @webinista in it.

**Comment by jcmeloni** [comment]
Closing; if we need to return to this issue past the beginnings that were started in #3039, we'll open a new ticket.
