### ISSUE TITLE
Settle on one ruby version for dev/ci/staging/deploy

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#961]
Codeship uses Ruby-2.2  Ruby stable is 2.3. Most macs seem to be running Ruby 2.1 by default.

Let's pick one and stabilize.

Assigning to @plusjeff for triage.

**Comment by plusjeff** [comment]
Ruby 2.3.x is the current decision. roadrunner-rails has a .ruby-version with 2.3.
