### ISSUE TITLE
I can has puma for web serving?

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#962]
unicorns always sound good until you see them.
Webrick seems, well, not often used.
Heroku standardized on puma and from my research, it seems architecturally the most modern (read: sane) of the ruby web servers.

See https://github.com/18F/college-choice/issues/597#issuecomment-138723666 and nesting's followup common for details.

I think this is as simple as adding puma to the gemfile, but we'd want to test this with our deployment/monitoring/ci infrastructure before just pushing the code change.

**Comment by awong-dev** [comment]
@plusjeff for triage.

**Comment by ayaleloehr** [comment]
@awong-dev for what it's worth, it looks like VEC and GI Bill tool are currently using Passenger.

https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/3a185439f7740123a413f18d847183c8f7ed8bf6/Capfile#L24

**Comment by plusjeff** [comment]
Puma has been decided upon.
