### ISSUE TITLE
UserVoice Idea: Ability to delete a profile

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#963]
Ability to delete a profile

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11262018-ability-to-delete-a-profile

**Comment by koconnor719** [comment]
@MarinaMartin is there any way to get a test user account so we can see this functionality in the VEC (ability to delete a user profile); i can't test this in order to provide detailed feedback.

**Comment by MarinaMartin** [comment]
Not right now - you have to be a Veteran.

**Comment by koconnor719** [comment]
checking w/ VEC SMEs (john thompson) whether this is possible.

**Comment by MarinaMartin** [comment]
There is not a delete button - we would have to add it. @ayaleloehr

**Comment by koconnor719** [comment]
@cfeeney-va @ayaleloehr is this an accurate response:

Thank you for your feedback. Users can delete their profiles on VEC.  Job seekers can edit his/her profile and remove all of their information from the profile at any time. Users will still have an account with VEC if they have registered that they can return to anytime. Our team is going to add a "delete" feature to VEC to make it easier to delete a profile.  Thanks for the suggestion!

vets.gov team

**Comment by koconnor719** [comment]
@cfeeney-va can you pls. verify the above response is accurate, or mod as needed, so i can post. thx

**Comment by koconnor719** [comment]
related to #165 in VEC repo

**Comment by koconnor719** [comment]
@cfeeney-va  can you pls. post a comment here w/ status on this issue?  i need to post a response on the site.

**Comment by koconnor719** [comment]
@cfeeney-va can  you pls. post status.

**Comment by cfeeney-va** [comment]
functionality exists; follow-up ticket in veterans-employment-center, task #216
