### ISSUE TITLE
UserVoice Idea: A more simple process for employers to access system and view resumes

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#985]
I registered about a week and a half ago.  I still do not have access to view resumes.  Can their be established a faster way of registering a business.  Employers should have a contact number to ensure they get access so that they are able to fulfill their commitment.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11314473-a-more-simple-process-for-employers-to-access-syst

**Comment by koconnor719** [comment]
posted response:

Thank you for your feedback.  Our team has fixed this issue, so you should be able to view resumes now!   

vets.gov team
