### ISSUE TITLE
UserVoice Idea: Help

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#990]
There should be some sort of help center to address submission errors.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11316897-help

**Comment by koconnor719** [comment]
Thank you for your feedback.  Can you provide some additional information about what type of "submission" error you are getting on vets.gov?  If you are having difficulties with VA.gov, you can go to this page for assistance:  https://iris.custhelp.com/app/ask/session/L2F2LzEvdGltZS8xNDUyMTkxMzk5L3NpZC96ZVBHTFhGbQ%3D%3D

**Comment by koconnor719** [comment]
closing this response b/c no additional info has been provided; if additional info is posted a new user voice issue will be opened.
